### ISSUE TITLE
Typedef redefinition with different types

### ISSUE THREAD

**Issue by loveFromLeo** [gpac/gpac#2208] opened 2022-06-22 07:34 UTC
Error compiling on OSX system
in maths.h line 117:
typedef Float Fixed;
error:Typedef redefinition with different types ('Float' (aka 'float') vs 'SInt32' (aka 'int'))
SInt32 is OSX typedef

in setup.h
#ifndef Bool
/*! boolean value*/
typedef enum {
	GF_FALSE = 0,
	GF_TRUE
} Bool;
#endif
error:Typedef redefinition with different types ('enum Bool' vs 'int')

**Comment by jeanlf** [comment] 2022-06-22 09:29
what is your configure command line and OSX version ?

**Comment by jeanlf** [comment] 2022-06-22 15:44
same config here, no issue building from xcode (UI or through command line)

do you have the same issue building from command line with configure & make ?

**Comment by jeanlf** [comment] 2022-06-22 15:45
are you on M1 or x86 ?

**Comment by jeanlf** [comment] 2022-09-28 17:02
closing, cannot reproduce. Will reopen if you give more details to reproduce

**Closed by jeanlf** 2022-09-28 17:02 UTC
