### ISSUE TITLE
mp4box crashes

### ISSUE THREAD

**Issue by urmelostsee** [gpac/gpac#354] opened 2015-12-18 09:31 UTC
Hello!
First of all: I am new to this subject, pls be patient :)
I want to use mp4box inside cut assistant. cut assistant works fine with AVI-files so far. For mp4-files, I had to install ffdshow and "Haali Media Splitter" as well as mp4box. The path mp4box is set in cut asistant. So, when cutting a video, everything seems to work well first. At a time, processing breaks an a box apears "mp4box.exe funktioniert nicht mehr" (=mp4box does not work anymore) --> the programm crashed.
Can anybody help me?
Thank you says urmel

The log is:
Adjusting chunk start time to previous random access at 27.96 sec
Extracting chunk Hugh_Laurie__Live_on_the_Queen_Mary_27_122.mp4 - duration 94.67s (27.96s->122.63s)
                                                        
IsoMedia import Hugh_Laurie__Live_on_the_Queen_Mary_27_122.mp4 - track ID 1 - Video (size 720 x 576)
IsoMedia import Hugh_Laurie__Live_on_the_Queen_Mary_27_122.mp4 - track ID 2 - Audio (SR 48000 - 2 channels)
Importing ISO File: |=================== | (99/100)
Fehler. Die letzte gestartete Kommandozeile war:
 -cat "V:\0Musik\Hugh_Laurie__Live_on_the_Queen_Mary_27_122.mp4" "V:\0Musik\Hugh_Laurie__Live_on_the_Queen_Mary.cut.mp4"

**Comment by wouterx** [comment] 2016-02-10 15:16
Just wanted to let you know that i have the same problem (i think).  

I have used MP4BOX via cut assistant (which is an awesome frontend) for several years.   Some new MP4 files seem to elicit a crash, while older files continue to work

this is the MP4BOX output window before the crash:
IsoMedia import file.mp4 - track ID 1 - Video (size 1280 x 720)
IsoMedia import file.mp4 - track ID 2 - Audio (SR 44100 - 2 channels)
Appending file D:\nieuwsgroepen\uitgepakt\anew\file.mp4
No suitable destination track found - creating new one (type vide)

I have recently updated to win10, and I installed the newest mp4box (1183),haali, ffdshow, and cut assistant.

**Comment by jeanlf** [comment] 2016-02-10 16:38
Could you upload some test sequences ?

**Comment by wouterx** [comment] 2016-02-11 14:29
after some more testing i am thinking that the problem is on our end........ maybe caused by the move to a fresh windows 10 install?

Strange thing is:  Files that have been previously edited by MP4Box (via cut assistant),  CAN be edited again. No errors, i tried over 10 different mp4 files with various properties, all of them work fine.

 Files that have NOT been previously edited by MP4BOX  ALL crash mp4box in the same manner.... no matter what the properties.  

Maybe file permissions related? (even though SYSTEM, and users have full acces to the new files...)

**Comment by rbouqueau** [comment] 2016-02-11 14:56
Anyway MP4Box should never crash. If you find a way to reproduce we'd be highly interested!

I close the issue for now. Re-open if we can help any further.

**Closed by rbouqueau** 2016-02-11 14:56 UTC

**Comment by wouterx** [comment] 2016-02-12 15:11
I tried a fresh win7 install (in a VM), Downloaded and installed cut assistant,mp4box, haali and FFDSHOW fresh. Tried cutting.... and exactly the same behaviour.   Previously uncut files still crash MP4BOX.

The smallest crashing file I have is a TV recording by BATV,  (Toy.Story-That.Time.Forgot.2014.HDTV.x264-BATV.mp4).  I could send it your way,

**Comment by rbouqueau** [comment] 2016-02-12 17:01
Thanks for the feedback. Please share a file if you wish us to fix the crash.

**Comment by rbouqueau** [comment] 2016-02-12 17:02
We have a dropbox if it can help: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by wouterx** [comment] 2016-02-13 10:42
After some more testing it seems that is is a compatibility issue between Cut Assitant (which is no longer maintained) and one of the files in the recent GPAC packages.   I previously only tried changing the mp4box.exe to older versions, now i change the entire folder/package.

-I have tried testing which revision causes the incompatibility/crash, but results are mixed.  
0.5.0 always works. 
0.5.2 rev 998 works
0.5.2 rev 1049  fails 
0.5.2 rev 1170 works only sometimes, when previously opened by another rev?
0.5.2 rev 1172 fails 
0.5.2.rev 1189 fails 

I understand that this may not be your problem (It is probably Cut Assistant that screws something up), it is still a very weird issue though.  please let me know what more i can do.  I will upload my file for testing. 

Thank you for your patience and help! 

(Also: if anyone has an alternative to Cut Assitant that would be great.  It is the only frontend i know of that can make multiple edits/cuts, and then automatically join them in a new file. It was unfortunately abandoned in 2013......)
