### ISSUE TITLE
Is there something like Multiple Object Tracking Features

### ISSUE THREAD

**Issue by a23232390** [gpac/gpac#1628] opened 2020-10-26 12:40 UTC
I want to track people in the HEVC TILES video
![image](https://user-images.githubusercontent.com/68137277/97173263-3c283500-17cb-11eb-99cb-5a92ec760c91.png)

**Comment by jeanlf** [comment] 2020-10-27 08:42
duplicate of #1629

**Closed by jeanlf** 2020-10-27 08:42 UTC
