### ISSUE TITLE
Compositor osize not scaling with the viewport

### ISSUE THREAD

**Issue by RodolpheFouquet** [gpac/gpac#2099] opened 2022-02-07 02:23 UTC
Command run:

`gpac --lowlat=no  --buffer=8000 -i out/live.mpd#VR @ compositor:fsize=true:sz=true:tvtd=partial  @ vout @1 aout`

The test data used is [here](https://www.mediafire.com/file/2r7s1i0tst06ane/out.zip/file)

What happens:

The vout opens a small window, with a content resolution corresponding to the size of the window.

When the window size is increased, the content inside stays low res.

As a workaround, I currently output to the maximum height of screen using a batch command like this:

```
@ECHO OFF

setlocal ENABLEDELAYEDEXPANSION
setlocal ENABLEEXTENSIONS
set wmicheight="wmic desktopmonitor get screenheight /format:value"
:height
for /f "tokens=2 delims==" %%a in ('%wmicheight%') do (
    If %%a LEQ 1 (
        rem skip if height is not bigger than 1
    ) Else (
        rem take the first height value larger than 1
        rem then skip to width
        Set /a "height=%%a"
    )
)
gpac --lowlat=no --buffer=8000 -i out/live.mpd#VR @ compositor:fsize=true:sz=true:osize=%height%x%height%:tvtd=partial  @ vout @1 aout
```

Tested with version 7535448f4acd2deaf0400922202f78fc0ae7fb6c on both ubuntu 20.04 (compiled manually) and Windows 11 (installer).

----
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment] 2022-06-09 11:12
Note that in your command, options `fsize` and `sz` are both useless.

I can't reproduce with head but there's been some playback improvements for compositor used as standalone filter.
Closing, please re-open / continue posting if you can reproduce.

**Closed by jeanlf** 2022-06-09 11:12 UTC
