### ISSUE TITLE
Osmozilla Browser Plugin Download and Install?

### ISSUE THREAD

**Issue by huangsherry** [gpac/gpac#627] opened 2016-09-06 11:06 UTC
I read from a paper that a plugin can be installed in Firefox:

"To support the DASH process on the client, then the client browser must be done to support the installation of a browser plug-in that can perform H.265 video play out at the client. In this case use Osmozilla plug-in version 1.0.1.0 which is the product of the GPAC. " 

Anyone knows how it works?

https://gpac.wp.mines-telecom.fr/player/browser-integration/

https://github.com/gpac/gpac/issues/371 
The two articles seem not working.

**Comment by rbouqueau** [comment] 2016-09-13 08:02
duplicate of #371, please post these

**Closed by rbouqueau** 2016-09-13 08:02 UTC
Labels: duplicate, player (mp4client/osmo), question
