### ISSUE TITLE
Last error 3 on mp4box 1.0.0

### ISSUE THREAD

**Issue by kenichi512** [gpac/gpac#1557] opened 2020-07-27 13:22 UTC
The current mp4box 1.0.0 seems to have a problem that did not have the previous versions when reading output paths on batch files with FOR IN DO to create many files. Instead show the output path, the prompt show error message saying `Cannot create directory "": last error 3`. The "" is because I use directories with spaces, so I don't understand why such error. But despite everything, the files are generated, so this error does not make sense when before that did not happen on version 0.8.0

My batch file is more or less like this:

```
@echo off
set "mp4box=D:\folder w spaces\MP4Box\mp4box.exe"
set inputV=D:\folder w spaces\Encode\H264
set output=D:\folder w spaces\Encode\Remux
FOR %%V IN ("%inputV%\*.h264") DO "%mp4box%" -add "%%V#1:fps=23.976" "%output%\%%~nV.mp4"
PAUSE>NUL
EXIT
```

**Comment by jeanlf** [comment] 2020-07-27 17:52
hmm I cannot reproduce here, whether the target dir exists or not. Do you have the same behavior running without batch but still with absolute paths ?

**Comment by kenichi512** [comment] 2020-07-27 19:34
If I only use constant names each file there is no such problem, but mp4box 1.0.0 does not show the output path as mp4box 0.8.0 does.

Mux with mp4box 1.0.0

```
mp4box -add "D:\folder w spaces\Encode\H264\EP 07.h264#1:fps=23.976" "D:\folder w spaces\Encode\Remux\EP 07.mp4"
Track Importing MPEG-4 AVC - Width 640 Height 480 FPS 23975/1000 SAR 0/0
AVC|H264 Import results: 35444 samples (35448 NALUs) - Slices: 572 I 6891 P 27982 B - 1 SEI - 420 IDR
AVC|H264 Stream uses forward prediction - stream CTS offset: 5 frames
0.500 secs Interleaving
```

The same file but with mp4box 0.8.0

```
mp4box -add "D:\folder w spaces\Encode\H264\EP 07.h264#1:fps=23.976" "D:\folder w spaces\Encode\Remux\EP 07.mp4"
AVC-H264 import - frame size 640 x 480 at 23.976 FPS
AVC Import results: 35444 samples (35447 NALUs) - Slices: 571 I 6891 P 27982 B - 1 SEI - 420 IDR
Stream uses forward prediction - stream CTS offset: 2 frames
Saving to D:\folder w spaces\Encode\Remux\EP 07.mp4: 0.500 secs Interleaving
```

**Comment by jeanlf** [comment] 2020-07-28 07:56
could you post the output of your batch without `@echo off` ?

**Comment by kenichi512** [comment] 2020-07-28 15:11
```
D:\folder w spaces\Encode>set mp4box=mp4box.exe

D:\folder w spaces\Encode>set inputV=D:\folder w spaces\Encode\H264

D:\folder w spaces\Encode>set output=D:\folder w spaces\Encode\Remux

D:\folder w spaces\Encode>FOR %V in ("D:\folder w spaces\Encode\H264\*.h264") DO "mp4box.exe" -add "%V#1:fps=23.976" "D:\folder w spaces\Encode\Remux\%~nV.mp4"

D:\folder w spaces\Encode>"mp4box.exe" -add "D:\folder w spaces\Encode\H264\EP 07.h264#1:fps=23.976" "D:\folder w spaces\Encode\Remux\EP 07.mp4"
Track Importing MPEG-4 AVC - Width 640 Height 480 FPS 23975/1000 SAR 0/0
AVC|H264 Import results: 35444 samples (35448 NALUs) - Slices: 572 I 6891 P 27982 B - 1 SEI - 420 IDR
AVC|H264 Stream uses forward prediction - stream CTS offset: 5 frames
0.500 secs Interleaving
Cannot create directory "": last error 3

D:\folder w spaces\Encode>"mp4box.exe" -add "D:\folder w spaces\Encode\H264\EP 08.h264#1:fps=23.976" "D:\folder w spaces\Encode\Remux\EP 08.mp4"
Track Importing MPEG-4 AVC - Width 640 Height 480 FPS 23975/1000 SAR 0/0
AVC|H264 Import results: 35444 samples (35448 NALUs) - Slices: 579 I 7036 P 27830 B - 1 SEI - 433 IDR
AVC|H264 Stream uses forward prediction - stream CTS offset: 5 frames
0.500 secs Interleaving
Cannot create directory "": last error 3

D:\folder w spaces\Encode>"mp4box.exe" -add "D:\folder w spaces\Encode\H264\EP 09.h264#1:fps=23.976" "D:\folder w spaces\Encode\Remux\EP 09.mp4"
Track Importing MPEG-4 AVC - Width 640 Height 480 FPS 23975/1000 SAR 0/0
AVC|H264 Import results: 35444 samples (35448 NALUs) - Slices: 665 I 7286 P 27494 B - 1 SEI - 439 IDR
AVC|H264 Stream uses forward prediction - stream CTS offset: 5 frames
0.500 secs Interleaving
Cannot create directory "": last error 3

D:\folder w spaces\Encode>"mp4box.exe" -add "D:\folder w spaces\Encode\H264\EP 10.h264#1:fps=23.976" "D:\folder w spaces\Encode\Remux\EP 10.mp4"
Track Importing MPEG-4 AVC - Width 640 Height 480 FPS 23975/1000 SAR 0/0
AVC|H264 Import results: 35444 samples (35448 NALUs) - Slices: 795 I 7217 P 27433 B - 1 SEI - 532 IDR
AVC|H264 Stream uses forward prediction - stream CTS offset: 5 frames
0.500 secs Interleaving
Cannot create directory "": last error 3

D:\folder w spaces\Encode>"mp4box.exe" -add "D:\folder w spaces\Encode\H264\EP 11.h264#1:fps=23.976" "D:\folder w spaces\Encode\Remux\EP 11.mp4"
Track Importing MPEG-4 AVC - Width 640 Height 480 FPS 23975/1000 SAR 0/0
AVC|H264 Import results: 35444 samples (35448 NALUs) - Slices: 625 I 7036 P 27784 B - 1 SEI - 432 IDR
AVC|H264 Stream uses forward prediction - stream CTS offset: 5 frames
0.500 secs Interleaving
Cannot create directory "": last error 3

D:\folder w spaces\Encode>"mp4box.exe" -add "D:\folder w spaces\Encode\H264\EP 12.h264#1:fps=23.976" "D:\folder w spaces\Encode\Remux\EP 12.mp4"
Track Importing MPEG-4 AVC - Width 640 Height 480 FPS 23975/1000 SAR 0/0
AVC|H264 Import results: 35444 samples (35448 NALUs) - Slices: 945 I 7579 P 26921 B - 1 SEI - 482 IDR
AVC|H264 Stream uses forward prediction - stream CTS offset: 5 frames
0.500 secs Interleaving
Cannot create directory "": last error 3

D:\folder w spaces\Encode>ECHO Press any key to exit. . .
Press any key to exit. . .

D:\folder w spaces\Encode>PAUSE1>NUL

```

I want to mention that I added mp4box to environment variables to avoid bin path lines.

I don't understand how that can say "Cannot create directory" when folders exist and mp4box 1.0.0 can generate the new files. If the directory did not exist, simply mp4box 1.0.0 would not run and prompt would say that there is no such directory. I suppose this is related to rewrite code on 1.0.0 compared to the previous versions. Also, why does mp4box 1.0.0 now generate an empty folder called "Storage" the first time it is run?

**Comment by aureliendavid** [comment] 2020-07-28 16:27
hello, 

I can't reproduce it either:

```
D:\folder with spaces\Encode>mp4box
Not enough arguments - check usage with -h
MP4Box - GPAC version 1.0.0-rev166-gd1cf75ee-master
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io

D:\folder with spaces\Encode>type 1557.bat
@echo on
set mp4box=mp4box.exe
set inputV=D:\folder with spaces\Encode\H264
set output=D:\folder with spaces\Encode\Remux
FOR %%V IN ("%inputV%\*.h264") DO "%mp4box%" -add "%%V#1:fps=23.976" "%output%\%%~nV.mp4"
pause

D:\folder with spaces\Encode>1557.bat

D:\folder with spaces\Encode>set mp4box=mp4box.exe

D:\folder with spaces\Encode>set inputV=D:\folder with spaces\Encode\H264

D:\folder with spaces\Encode>set output=D:\folder with spaces\Encode\Remux

D:\folder with spaces\Encode>FOR %V IN ("D:\folder with spaces\Encode\H264\*.h264") DO "mp4box.exe" -add "%V#1:fps=23.976" "D:\folder with spaces\Encode\Remux\%~nV.mp4"

D:\folder with spaces\Encode>"mp4box.exe" -add "D:\folder with spaces\Encode\H264\EP 07.h264#1:fps=23.976" "D:\folder with spaces\Encode\Remux\EP 07.mp4"
Track Importing MPEG-4 AVC - Width 128 Height 128 FPS 23976/1000 SAR 0/0
AVC|H264 Import results: 4 samples (7 NALUs) - Slices: 2 I 3 P 0 B - 0 SEI - 1 IDR
AVC|H264 Max NALU size is 119 - stream could be optimized by setting nal_length=1
0.500 secs Interleaving

D:\folder with spaces\Encode>"mp4box.exe" -add "D:\folder with spaces\Encode\H264\EP 08.h264#1:fps=23.976" "D:\folder with spaces\Encode\Remux\EP 08.mp4"
Track Importing MPEG-4 AVC - Width 128 Height 128 FPS 23976/1000 SAR 0/0
AVC|H264 Import results: 4 samples (7 NALUs) - Slices: 2 I 3 P 0 B - 0 SEI - 1 IDR
AVC|H264 Max NALU size is 119 - stream could be optimized by setting nal_length=1
0.500 secs Interleaving

D:\folder with spaces\Encode>"mp4box.exe" -add "D:\folder with spaces\Encode\H264\EP 09.h264#1:fps=23.976" "D:\folder with spaces\Encode\Remux\EP 09.mp4"
Track Importing MPEG-4 AVC - Width 128 Height 128 FPS 23976/1000 SAR 0/0
AVC|H264 Import results: 4 samples (7 NALUs) - Slices: 2 I 3 P 0 B - 0 SEI - 1 IDR
AVC|H264 Max NALU size is 119 - stream could be optimized by setting nal_length=1
0.500 secs Interleaving

D:\folder with spaces\Encode>pause
Press any key to continue . . .
```

what's your exact version of mp4box? (you can get it by running mp4box without arguments) 

did you build it yourself or installed it from our installers?

**Comment by kenichi512** [comment] 2020-07-28 17:54
I have used both the official build and my own builds (one of them make with Media Auto Build Suite) and in both cases it has the same error.

Official Build (installer):
```
MP4Box - GPAC version 1.0.0-rev0-ga99c032b-master
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io
GPAC Configuration: (static configuration file)
Features: GPAC_CONFIG_WIN32 GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_MINIMAL_ODF GPAC_HAS_QJS GPAC_HAS_FAAD GPAC_HAS_MAD GPAC_HAS_LIBA52 GPAC_HAS_JPEG GPAC_HAS_PNG GPAC_HAS_FFMPEG GPAC_HAS_OPENSVC GPAC_HAS_JP2 GPAC_HAS_OPENHEVC GPAC_HAS_THEORA GPAC_HAS_VORBIS GPAC_HAS_XVID GPAC_HAS_GLU
```
Build with MABS
```
MP4Box - GPAC version 1.0.0-rev156-gbcbdbdbf4-ab-suite
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io
GPAC Configuration: --prefix=/local32 --disable-shared --enable-static --static-mp4box
Features: GPAC_CONFIG_WIN32 GPAC_MINIMAL_ODF GPAC_HAS_QJS  GPAC_DISABLE_3D
```
Build with MSYS-MinGW
```
MP4Box - GPAC version 1.0.0-rev112-g09fb485a7-master
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io
GPAC Configuration: --static-mp4box --use-zlib=no --disable-lzma --prefix=tmpbuild
Features: GPAC_CONFIG_WIN32 GPAC_MINIMAL_ODF GPAC_HAS_QJS  GPAC_DISABLE_3D GPAC_DISABLE_SWF_IMPORT
```
Build with MVS2015
```
MP4Box - GPAC version 1.0.0-rev32-g3c72d002e-master
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io
GPAC Configuration: (static configuration file)
Features: GPAC_MINIMAL_ODF  GPAC_DISABLE_SWF_IMPORT
```

I didn't mention it before but my computer have Windows 10 64bit although that should not be the problem because as I said with previous versions of mp4box I don't have that error.

**Comment by jeanlf** [comment] 2020-07-29 07:38
still no luck reproducing with your rev or latest git. Coult you try adding `-log core@debug -strict-error` to your MP4Box command and post the last lines of one execution (last 10-20 should be enough) ?

**Comment by rbouqueau** [comment] 2020-07-29 07:47
Which shell do you guys use? cmd or another one?

**Comment by jeanlf** [comment] 2020-07-29 08:00
I tested with cmd, powershell and launching the bat from explorer, same ...

**Comment by kenichi512** [comment] 2020-07-30 03:54
When I add `-log core@debug -strict-error` prompt says `Error - 2 input names specified, please check usage` and neither generate a log.

**Comment by jeanlf** [comment] 2020-07-30 07:55
sorry, `-logs` not `-log` (I'll check why the arg is not reported as unknown)

**Comment by kenichi512** [comment] 2020-07-30 13:57
Ok it seems that I discovered what happens after testing with the other commands. In another batch script with longer paths, the drive letters were replaced by the modifier `%~d1`. Apparently mp4box 1.0.0 does not correctly interpret the parameter and it will show that error always if I don't specify drive letters.

**Comment by kenichi512** [comment] 2020-08-02 02:37
A few minutes ago I did a new build with MABS and this is the mp4box version.

```
Not enough arguments - check usage with -h
MP4Box - GPAC version 1.0.0-rev188-g2aa266dfa-ab-suite
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io
```

But it doesn't seem like there were any changes and still the same errors mentioned on my last post.

**Comment by jeanlf** [comment] 2020-09-04 12:49
1. for `%d1` , could you try patching the macro GF_MAIN_FUNC (include/gpac/main.h) to print to stderr the result of each arg before and after wide to multi-byte conversion (gf_utf8_wcstombs)  and see if you see something strange ?


2. The automatic name assignment in the handler is not a bug, it is by design, use `:name=`(empty) to avoid it

**Comment by jeanlf** [comment] 2020-09-10 15:45
Closing and attaching to long path support in windows - cf #1589

**Closed by jeanlf** 2020-09-10 15:45 UTC
