### ISSUE TITLE
How to fetch the log file

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#841] opened 2017-06-06 23:53 UTC
Hello there,
I am running DashCast on the server side for VoD streaming, and the bitrates are done via a config file.
I want to do further evaluation but I want to get the size (bitrate) of each frame once the segmentation is occur.
Is there any way I can extract all frames or segments' information?

Thanks
Irrz

**Comment by aureliendavid** [comment] 2017-06-19 08:22
duplicate of #846

**Closed by aureliendavid** 2017-06-19 08:22 UTC
