### ISSUE TITLE
Video and audio playback problems on iPod

### ISSUE THREAD

**Issue by forthrin** [gpac/gpac#1295] opened 2019-08-06 05:44 UTC
I'm posting as a new user on what seems to be a well maintained project and issue tracker.

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC.
- [X] I give enough information for contributors to reproduce my issue

Using the latest nightly build on macOS 10.14.6.

```
$ /Applications/GPAC.app/Contents/MacOS/MP4Box -version 
MP4Box - GPAC version 0.8.0-rev47-gbafe4cd3-master
(c) Telecom ParisTech 2000-2018 - Licence LGPL v2
GPAC Configuration: --extra-cflags=-Wno-deprecated
Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG 
```

I am experiencing issues with *some* (and always the same) videos on an iPod Nano:

**Problem 1**. Specifically around 12 or 45 minutes into the video, the built-in video player either:

- exits back to the video list
- runs amok playing video at several minutes per second

**Problem 2**. White noise artifacts, usually the left channel, in the same places per video.

What I'm doing (using latest FFmpeg):

`ffmpeg -i original.mp4 -ar 44100 -ac 2 -b:a 128k -profile:v baseline -level 3.0 -pix_fmt yuv420p ffmpeg.mov`

Then:

`MP4Box -add ffmpeg.mov ipod.mov` resolves problem 1, but then there is no audio on the iPod (though there is audio with ffplay, vlc, etc.)

`MP4Box -ipod ffmpeg.mov ipod.mov` brings back the audio, but alas also the original problem 1.

Workaround for problem 1: Convert video to AVI and back to MP4 (using FFmpeg). The problem may thus revolve around container metadata retained during mp4-mp4 operations.

However, doing diffs on `ffprobe -show_streams` or `MP4Box -info` before and after the AVI workaround reveals no relevant change in metadata.

For problem 2, I have found no workaround. I assume MP4 videos must have AAC audio. I've tried both standard aac and libfdk (the latter may produce slightly less noise).

If there is interest in resolving the problem, I can share small example files and any other required information. Maybe someone on the dev team as an iPod Nano to test this on?

FYI: Targeting iPod, ie. `ffmpeg ... -f ipod ... ffmpeg.m4v`, has no effect on the problem.

**Comment by forthrin** [comment] 2019-08-24 11:05
This issue was posted three weeks ago. Was it missed by the staff? Are iPods no longer supported?

**Comment by rbouqueau** [comment] 2019-08-24 15:43
Hi, I can't help you. I assume the people able to help you are just on vacation :) Ping again here if you still don't get an answer within a few weeks.

**Comment by forthrin** [comment] 2019-08-25 15:15
Thanks for the friendly update. J'ai oublié que les Européens font des vacances plus tard dans l'été :) I will retain my impression that the project is well run and the issue will be seen to in due time.

**Comment by aureliendavid** [comment] 2019-08-26 07:28
well this is a strange one

to be honest I don't have a device on which to test, and I have no idea where to get one

maybe someone can dig up one but I can't guarantee it 

in the meantime you can still upload samples with/without the issue at https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95 and maybe we can spot some issue in the files

**Comment by forthrin** [comment] 2019-08-27 10:29
I'll do my best to upload some sample files. I assume you guys know the MP4 format so well and have diagnostic tools so you should be able to spot any abnormalities in the metadata.

If no-one on the dev team has an iPod nano, they're easy to get, and maybe you can find a really damaged (but functioning) one practically free.

https://www.leboncoin.fr/image_son/1663618473.htm/

**Comment by forthrin** [comment] 2019-08-28 07:15
Files uploaded. See what you can figure out from this, and we'll take it from there.

Problem 1: `video.mov`: At 11:20, the built-in iPod video player prematurely exits playback of a 12 minute long video. Note that the video intentionally contains just black content.

Problem 2: - `speaker.m4a` - A microphone recording of what the short audio clip `audio.m4a` sounds like when played on an iPod (note the short, loud click).

**Comment by forthrin** [comment] 2019-09-08 08:35
What did you find when analysing the files?

**Comment by aureliendavid** [comment] 2019-09-09 07:39
sorry but I wasn't able to find anything useful, I don't think I can be of further help on this ; but we can keep the issue opened in case someone else has an idea

**Comment by forthrin** [comment] 2019-09-09 13:59
So there is nothing in the structure or metadata of the file that is incorrect, invalid or would suggest that a video player would suddenly freak out?

**Comment by aureliendavid** [comment] 2019-09-09 14:33
none that I could find, no

**Comment by forthrin** [comment] 2019-09-10 10:57
Check out the new file just uploaded ("video.m4v.gz"). It is the previously uploaded file "video.mov" that has been converted to AVI and back to MP4. Now the iPod player does *not* run amok or exit!

This workaround works for ALL videos that have the problem. (It is also the ONLY workaround I have found, and it's not a desirable one since it takes a lot of extra encoding time.)

Can you check the difference between "video.mov" and "video.m4v" in terms of structure or metadata that can explain why the iPod player is flipping out?

**Comment by forthrin** [comment] 2019-09-18 06:41
What did you find when comparing the two video files?

**Comment by forthrin** [comment] 2019-10-08 15:11
Did you find a significant difference between the .mov and .m4v file that explains why the iPod video player would bail around 11:20?

**Comment by forthrin** [comment] 2019-10-18 18:48
I've waited five weeks for a response. I would really like to find the root of this problem. When can I expect to hear back?

**Comment by rbouqueau** [comment] 2019-10-19 10:49
I've had a look at the video.m4v file: nothing special. The stopping on playback at 11:20 may be due to something in the h264 video instead of the MP4 container? I don't know which iPod Nano generation you are testing to find the medi specifications (e.g. https://support.apple.com/kb/SP497?locale=en_US).

I've had a look at the video.mov file: nothing special.

Both files are slightly different in their structures, but the main difference is that the audio is not compressed in the .mov.

Note that since you have opened your issue, MP4Box has gained support to .mov generation.

**Comment by forthrin** [comment] 2019-10-20 09:24
Thanks for your kind and insightful response. I really, really wonder what causes this. I will try the new version with .mov support and let you know how this goes. Thanks again!

PS! The iPod I'm using is an iPod nano 3rd generation with the latest software update. Every specimen I've tried has had the same problem. I have not tried other iPods.

PPS! If I didn't mention it earlier, QuickTime on a recent version of macOS actually had problems (halting playback) with the same video files as the iPod. I'll include details on this later if possible.

**Comment by forthrin** [comment] 2019-10-20 12:13
How do I get an updated version with `.mov` support?

Using latest Git version (`a7548b8a97f8a4ad200c2858ac65b6a11e4bffde`), I did `./configure --static-mp4box` and `make -j4`, but I just get a lot of compilation errors, starting with:

```
isomedia/box_code_apple.c:530:7: error: no member named
      'frames_per_counter_tick' in 'GF_TimeCodeSampleEntryBox'
        ptr->frames_per_counter_tick = gf_bs_read_u8(bs);
```

Homebrew version says "(c) 2018", thus very outdated. No `.mov` in `MP4Box -h format` there.

```
$ MP4Box -version
MP4Box - GPAC version 0.8.0-revrelease
(c) Telecom ParisTech 2000-2018 - Licence LGPL v2
```

**Comment by rbouqueau** [comment] 2019-10-20 15:25
> Using latest Git version (a7548b8a97f8a4ad200c2858ac65b6a11e4bffde)

I confirm this is the latest.

> isomedia/box_code_apple.c:530:7: error: no member named

I think you need to 'make uninstall' before rebuilding.

> How do I get an updated version with .mov support?

Yours have it, just create a .mov file. Note that creating .m4a or .m4v should create iPod files.

**Comment by forthrin** [comment] 2019-10-29 04:09
Worked with `make uninstall`.

I found a new file (45 minutes long) that makes the iPod player exit around 35 minutes.

The problem persists when running the file through the latest version of MP4Box.

```
MP4Box -ipod -add foo.m4v foo+.m4v -- PLAYER EXITS MIDWAY
MP4Box -add foo.m4v foo+.mov -- PLAYS ENTIRE FILE, BUT NO SOUND
AVI workaround -- WORKS
```

```
$ MP4Box -ipod -add foo.m4v foo+.m4v 
[iso file] Unknown box type uuid in parent avc1
[iso file] Unknown box type uuid in parent avc1
IsoMedia import foo.m4v - track ID 1 - Video (size 320 x 240)
[iso file] Unknown box type uuid in parent avc1           
IsoMedia import foo.m4v - track ID 2 - Audio (SR 44100 - 2 channels)
Setting up iTunes/iPod file...                            
Saving to foo+.m4v: 0.500 secs Interleaving
```

**Comment by forthrin** [comment] 2019-10-29 16:38
I did a very interesting find just now. I found an audio file that provokes the same behaviour as the (some, anyway) video files.

An M4A file of around 70 minutes, when played in the iPod audio player, when it gets to exactly 14 minutes, the playback progress bar races to the end of the file in like two seconds, after which the audio player exits back to the list of tracks.

The same thing happens even if I do a lossy audio compression with FFmpeg, or if I run MP4Box on it. Maybe this file will be easier to analyse? Can I use the same link to upload the file?

**Comment by rbouqueau** [comment] 2019-10-29 16:56
> Can I use the same link to upload the file?

Absolutely. It appears as a folder for us, so please give the file an explicit name (e.g. issue1295_audioxxx...).

Thanks

**Comment by forthrin** [comment] 2019-10-29 18:17
Uploaded. Note that there is no audible content. It's just 70 minutes of silence, but the problem happens anyway.

**Comment by forthrin** [comment] 2019-11-08 14:46
What did you find when investigating the audio file?

**Comment by rbouqueau** [comment] 2019-11-08 16:46
I didn't find anything wrong. I'm still hoping someone else can jump in the conversation to help.

**Comment by forthrin** [comment] 2019-11-12 09:42
Seems like we'll be waiting forever, but I'll try to be optimistic :) Do you think the problem comes from the metadata or the actual content data?

**Comment by forthrin** [comment] 2020-01-16 20:33
Found another .m4a file that around the 14 minute mark speeds up like crazy and rushes to the end. Could you look for clues by possible similarities between this file and the earlier .m4a file?

File uploaded using the initial upload link as "foo.m4a.gz".

**Comment by forthrin** [comment] 2020-01-19 08:40
Had a new variant today: A h264/aac file converted with FFmpeg to h264/aac with loss video and non-loss audio did NOT work, whereas the same with loss audio DID work, and non-loss audio in an audio file only (.m4a) DID work. The whole thing is just bizarre.

**Comment by forthrin** [comment] 2020-02-01 11:43
I found yet a new issue (possibly a different issue altogether). Out of a set of 7 minute videos, about 1/3 of them exhibit the following deviant behaviour:

- iTunes (12.9.5.5): Video identifies as ~21 minutes in video list and progress bar. Plays in slow motion.
- iPod (Nano 3): Video identifies as ~21 minutes in video list and progress bar. Plays at normal speed. Player quits when the 7 minute mark is reached (eg. around 1/3 of the progress bar).
- VLC (3.0.7.1): 7 minutes. Plays normally. No evidence of problems.
- QuickTime (10.5): Same as VLC

When removing audio and re-recording the entire video with zero brightness, the problem persists. Such a video has been uploaded for your investigation.

**Comment by jeanlf** [comment] 2020-11-22 17:28
Honestly I have no clue what causes that, the video files are OK to me, I suspect a decoding issue with the device.

For the audio, there is an issue in files `foo.m4a` and `Issue 1295 - iPod.m4a` where the sample duration is not constant (it must be 1024 for AAC), maybe that is one cause...

My hints would be:
- try removing edits to see if they are the cause of these wrong interpretation of the duration (use `MP4Box -add $SRC:noedit`)
- try remuxing the files from raw (`MP4Box -raw N $SRC`and `MP4Box -add`)

The fact that only a few videos cause the issues let me believe that the problem is related with the devices, not with GPAC.

I'm closing this as there isn't much we can do, but feel free to post any updates/files, we'll reopen if there is a patch we can add to solve this (but again, I doubt that)

**Closed by jeanlf** 2020-11-22 17:28 UTC

**Comment by forthrin** [comment] 2021-02-18 12:57
I managed to get hold of iPod Nano 4th and 5th generation. For what it's worth, these devices exhibit the exact same issues with crackling audio and videos exiting prematurely as reported for the 3rd generation.

I support the sentiment that there are probably errors in Apple's players, however, there must be something specific in the data that trigger these errors. I assume we'll never know.
