### ISSUE TITLE
Can't compile: audio_decoder.c:276:48: error: ‘AVFrame’ has no member named ‘channels’

### ISSUE THREAD

**Issue by osztrovszky** [gpac/gpac#438] opened 2016-03-03 13:25 UTC
Hello Guys,
I'd like to copile, however the make gives an error:

```
 CC audio_decoder.c
audio_decoder.c: In function ‘dc_audio_decoder_read’:
audio_decoder.c:276:48: error: ‘AVFrame’ has no member named ‘channels’
     int num_channels = audio_input_data->aframe->channels;
                                                ^
../../config.mak:147: recipe for target 'audio_decoder.o' failed
```

Please fix it.

Thanks,
Zsolt

**Comment by jeanlf** [comment] 2016-03-03 15:37
I cannot reproduce with latest GPAC or ffmpeg git, which versions are you using?

**Comment by rbouqueau** [comment] 2016-05-13 12:54
duplicate of #513

**Closed by rbouqueau** 2016-05-13 12:54 UTC
Labels: dashcast
