### ISSUE TITLE
wrong tfhd value and duplicate subtitle

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#57] opened 2015-03-06 07:52 UTC
According to https://github.com/Dash-Industry-Forum/dash.js/pull/451#issuecomment-77375968 we have a bug when packaging TTML in MP4 in some cases.

**Comment by rbouqueau** [comment] 2015-03-06 08:17
Ok, I'll fix it later today.

**Comment by rbouqueau** [comment] 2015-03-06 21:47
Context:
```
<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns="http://www.w3.org/ns/ttml" space="default" p:timeBase="media" lang="en" p:cellResolution="50 30" xmlns:p="http://www.w3.org/ns/ttml#parameter" xmlns:s="http://www.w3.org/ns/ttml#styling" xmlns:m="http://www.w3.org/ns/ttml#metadata" xmlns:ebuttm="urn:ebu:tt:metadata" xmlns:ebutts="urn:ebu:tt:style">
    <head>
        <metadata>
            <ebuttm:documentMetadata>
                <ebuttm:conformsToStandard>urn:ebu:tt:distribution:2014-01</ebuttm:conformsToStandard>
            </ebuttm:documentMetadata>
        </metadata>
        <styling>
            <style xml:id="defaultStyle" s:fontSize="80%" s:lineHeight="125%" s:textAlign="left" s:color="##FF00FF" s:backgroundColor="##660033" s:fontStyle="normal" s:fontWeight="normal" s:textDecoration="none" s:fontFamily="monospaceSansSerif"/>
        </styling>
        <layout>
            <region xml:id="defaultRegion" s:extent="80% 80%" s:origin="10% 10%" s:padding="0%" s:displayAlign="after" s:writingMode="lrtb"/>
        </layout>
    </head>
    <body>
        <div xml:id="SGN0">
            <p begin="00:00:00.000" end="00:00:10.000" style="defaultStyle" region="defaultRegion" xml:id="sub1">Hello, I am a EBU-TT-D subtitle 1</p>
            <p begin="00:00:10.000" end="00:00:30.000" style="defaultStyle" region="defaultRegion" xml:id="sub2">Hello, I am a EBU-TT-D subtitle 2</p>
        </div>
    </body>
</tt>
```

DASHing by 10s. Segment 1 is:
```
<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns="http://www.w3.org/ns/ttml" space="default" p:timeBase="media" lang="en" p:cellResolution="50 30" xmlns:p="http://www.w3.org/ns/ttml#parameter" xmlns:s="http://www.w3.org/ns/ttml#styling" xmlns:m="http://www.w3.org/ns/ttml#metadata" xmlns:ebuttm="urn:ebu:tt:metadata" xmlns:ebutts="urn:ebu:tt:style">
    <head>
        <metadata>
            <ebuttm:documentMetadata>
                <ebuttm:conformsToStandard>urn:ebu:tt:distribution:2014-01</ebuttm:conformsToStandard>
            </ebuttm:documentMetadata>
        </metadata>
        <styling>
            <style xml:id="defaultStyle" s:fontSize="80%" s:lineHeight="125%" s:textAlign="left" s:color="##FF00FF" s:backgroundColor="##660033" s:fontStyle="normal" s:fontWeight="normal" s:textDecoration="none" s:fontFamily="monospaceSansSerif"/>
        </styling>
        <layout>
            <region xml:id="defaultRegion" s:extent="80% 80%" s:origin="10% 10%" s:padding="0%" s:displayAlign="after" s:writingMode="lrtb"/>
        </layout>
    </head>
    <body>
        <div xml:id="SGN0">
            <p begin="00:00:00.000" end="00:00:10.000" style="defaultStyle" region="defaultRegion" xml:id="sub1">Hello, I am a EBU-TT-D subtitle 1</p>
        </div>
    </body>
</tt>
```

Segment 2 and 3 are identical:
```
<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns="http://www.w3.org/ns/ttml" space="default" p:timeBase="media" lang="en" p:cellResolution="50 30" xmlns:p="http://www.w3.org/ns/ttml#parameter" xmlns:s="http://www.w3.org/ns/ttml#styling" xmlns:m="http://www.w3.org/ns/ttml#metadata" xmlns:ebuttm="urn:ebu:tt:metadata" xmlns:ebutts="urn:ebu:tt:style">
    <head>
        <metadata>
            <ebuttm:documentMetadata>
                <ebuttm:conformsToStandard>urn:ebu:tt:distribution:2014-01</ebuttm:conformsToStandard>
            </ebuttm:documentMetadata>
        </metadata>
        <styling>
            <style xml:id="defaultStyle" s:fontSize="80%" s:lineHeight="125%" s:textAlign="left" s:color="##FF00FF" s:backgroundColor="##660033" s:fontStyle="normal" s:fontWeight="normal" s:textDecoration="none" s:fontFamily="monospaceSansSerif"/>
        </styling>
        <layout>
            <region xml:id="defaultRegion" s:extent="80% 80%" s:origin="10% 10%" s:padding="0%" s:displayAlign="after" s:writingMode="lrtb"/>
        </layout>
    </head>
    <body>
        <div xml:id="SGN0">
            <p begin="00:00:10.000" end="00:00:30.000" style="defaultStyle" region="defaultRegion" xml:id="sub2">Hello, I am a EBU-TT-D subtitle 2</p>
        </div>
    </body>
</tt>
```

@cconcolato 1) I don't see the tfhd error in the original post, can you help me point it out?
2) The duplicated ttml sample is something we actually discussed when it was coded. The only missing thing would be to mark the sample as duplicate. What do you think? (CC @jeanlf )

**Comment by SoleneBuet** [comment] 2015-03-10 06:15
@rbouqueau thank you for having a look at that. May I ask how you visualize the segments after their segmentation?
On the issue 451, they say "It is recommended to clamp the TTML begin and end value to fit the sample timing values", so this is probably the handling of start and end values during playback, not a bug on your side?

**Comment by rbouqueau** [comment] 2015-03-11 08:34
@cconcolato I just answered on the 'trun' zeroed values: there are made optional by the standard.

@SoleneBuet I used 'MP4Box -diso file.mp4'. It creates a XML dump file in the same directory.

> On the issue 451, they say "It is recommended to clamp the TTML begin and end value to fit the sample timing values", so this is probably the handling of start and end values during playback, not a bug on your side?

You are right. The issue is that it requires to modify the TTML content, i.e. re-encoding it, while DASH-ing it.

Actually we mark the samples as 'redundant' when the repeat data that waere already sent. It seems that the players ignore it.

Please let me know what you think.

**Comment by aleal-envivio** [comment] 2015-03-11 09:15
@cconcolato I agree that TRUN values are optional, if soTFHD default values must be used. In that case, when TTML packed with profile Live or onDemand, TFHD size and duration defaults are 0 and TRUN is empty so there is no way for the player to know the sample size and sample duration

With profile "dashavc264:live", "dashavc264:onDemand", TFHD are correctly filled.

**Comment by aleal-envivio** [comment] 2015-03-11 09:15
![trun](https://cloud.githubusercontent.com/assets/11294830/6593285/9513f270-c7d7-11e4-8795-7427c1cd195b.png)
![tfhd](https://cloud.githubusercontent.com/assets/11294830/6593288/97700716-c7d7-11e4-95a6-fa01f49dacec.png)

**Comment by aleal-envivio** [comment] 2015-03-11 09:21
For TTML begin and end values : Here is what you can find in  "Information technology — Coding of audio-visual objects — Part 30: Timed text and other visual overlays in ISO base media file format":
"The duration of the TTML document carried in a sample may be less than the sample duration, but should not be greater." It means that is it recommended to clamp end and begin value between  the sample timestamp and sample timestamp+duration

Now, as  nigelmegitt said, it is "should" and "not shall". So, it is up to you.

**Comment by rbouqueau** [comment] 2015-03-11 09:47
For the 'trun'/'tfhd' issue, I know understand. I'll investigate and let you know here.

For TTML, if the content is not prepared for DASHing, the constraint on the duration requires the DASHer to rewrite the TTML samples to modify the 'begin'/'end' values. In the principle the DASHer does not re-encode the content (e.g. it does not re-encode video when the RAP are not aligned). @cconcolato opinion on this?

@aleal-envivio Is my explanation clear about what we do with the 'redundant' flag?

**Comment by nigelmegitt** [comment] 2015-03-11 10:27
@rbouqueau I don't agree that the duration constraint requires the DASHer to modify the begin/end values. The sample period defines the active period for any individual TTML document and the implementation can temporally clip the content at runtime. There's no need to modify the TTML document content in this way. 

In fact, because it's a _should_ not a _shall_ as referenced above, that means that implementations must have a way to deal with content that isn't clipped/clamped (whatever term you prefer) anyhow.

**Comment by rbouqueau** [comment] 2015-03-11 11:13
@nigelmegitt Yes it is a 'should' and that's why we don't do it. We repeat the samples and mark them as 'redundant'. The current issue seems to be that the demuxers ignore this file and send the sample multiple times. Does it make sense to you?

**Comment by rbouqueau** [comment] 2015-03-11 11:19
@aleal-envivio For the 'trun'/'tfhd' issue, several things:
0) Thanks for the precise report.
1) The construction seems legal although it probably hides a bug in MP4Box (we set the optional defaults, but there values are zero). Investigating.
2) There is a 'sidx' box in the file. It may give the opportunity to know the sample sizes and durations. Do you consider it?
3) We probably need to make a pass on the 'sidx written' values as well to check it is complete.

What do you think?

**Comment by nigelmegitt** [comment] 2015-03-11 11:42
@rbouqueau I'm not sure what mechanism you're using to mark samples as redundant - it's not an approach described in EBU Tech3381 for example.

Regardless, there's a general case that is not be covered by that approach, when the sample boundaries and the subtitle times aren't aligned, e.g. because you want a fixed sample duration:

Sample n, time 00:00:10 -> 00:00:15:
```
...
<p begin="00:00:12" end="00:00:18">Subtitle 1</p>
...
```

Sample n+1, time 00:00:15 -> 00:00:20:
```
...
<p begin="00:00:12" end="00:00:18">Subtitle 1</p>
<p begin="00:00:16" end="00:00:21">Subtitle 2</p>
...
```

etc.

(by the way, temporally overlapping subtitles are permitted as in sample n+1, but that's not really important here - Subtitle 2 could begin at 00:00:18 with no change to the argument)

If you mark sample n+1 as redundant then you omit subtitle 2 incorrectly.

The way that I envisaged this working is that the implementation would resolve that between 00:00:10 and 00:00:15 sample n _only_ would be active. From 00:00:15 to 00:00:20 sample n+1 _only_ would be active, so all the content that may overlap from sample n into sample n+1's period is irrelevant because that sample has been deactivated/dropped and doesn't generate any visible rendered output.

A clever implementation might be able to spot that the Subtitle 1 `<p>`s are the same and make some optimisations on that basis: that's beyond what the specs say, but certainly permitted if it can be done reliably.

**Comment by rbouqueau** [comment] 2015-03-11 12:33
> I'm not sure what mechanism you're using to mark samples as redundant

ISOBMF 4th Edition 8.6.4.3: ```'sample_has_redundancy' = 1 //there is redundant coding in this sample```

**Comment by rbouqueau** [comment] 2015-03-11 12:33
> Sample n, time 00:00:10 -> 00:00:15:
> ```
> ...
> <p begin="00:00:12" end="00:00:18">Subtitle 1</p>
> ...
> ```

Correct.


> Sample n+1, time 00:00:15 -> 00:00:20:
> ```
> ...
> <p begin="00:00:12" end="00:00:18">Subtitle 1</p>
> <p begin="00:00:16" end="00:00:21">Subtitle 2</p>
> ...
> ```

Not correct. Let's remove the overlapping that is not supported in our EBU-TTD import. MP4Box will create 2 samples:

Sample n+1, time 00:00:15 -> 00:00:18, **marked as redundant** (because it contains the same information as Sample n):
```
...
<p begin="00:00:12" end="00:00:18">Subtitle 1</p>
...
```
Sample n+2, time 00:00:18 -> 00:00:20:
```
...
<p begin="00:00:18" end="00:00:21">Subtitle 2</p>
...
```

Both samples n+1 and n+2 may be part of the same MPEG-DASH segment.

Overlapping may require this kind of algorithms: http://concolato.wp.mines-telecom.fr/files/2012/09/webvtt-overlapping-cues-rewritten.png
Explained at http://concolato.wp.mines-telecom.fr/2012/09/12/webvtt-streaming/

**Comment by rbouqueau** [comment] 2015-03-11 12:34
> it's not an approach described in EBU Tech3381 for example

Indeed. In https://tech.ebu.ch/docs/tech/tech3381.pdf, section 6, is written:
```
The begin and end of an EBU-TT-D document may not be coincident with the begin and end of the
sample. All subtitle content that falls partially or wholly within the duration of the sample shall be
present in the EBU-TT-D document and shall be displayed. Subtitle content that falls entirely
outside the duration of the sample shall be omitted [...]
Any timed content that falls partially outside of the sample boundaries may be used for error
recovery
```
So IMHO EBU Tech3381 neither recommends nor invalidates the use of 'sample_has_redundancy'.

**Comment by aleal-envivio** [comment] 2015-03-11 12:57
For the 'trun'/'tfhd' issue, :
-> the construction is legal but values are wrong ( ttml sample size is not 0 and sample duration is not 0)
-> for sidx box, it was my first implementation, but  i saw streams with multple TTML sample by moof (one subtitle per sample, it is stupid but it looks legal)

**Comment by nigelmegitt** [comment] 2015-03-11 14:21
@rbouqueau wrote:
> Not correct. Let's remove the overlapping that is not supported in our EBU-TTD import. MP4Box will create 2 samples:

If your EBU-TT-D import doesn't support it then it has a problem: if you don't support arbitrary and constant (sample/)segment durations then you need a lookup table in the MPD to obtain the the URLs for fetching each sample/segment. This is particularly tricky for live cases. A constant duration model allows the client to construct the URLs - in that case you must expect overlapping content within adjacent samples.

There's no real need to have more than one sample per segment in the case of subtitles - all the samples are going to be in time order anyhow and the segment duration can be quite short. By creating lots of minimally sized samples based on the TTML timings in the content you're most likely to increase the data rate for no benefit.

> Both samples n+1 and n+2 may be part of the same MPEG-DASH segment.

By the same token, they may be part of different segments.

> So IMHO EBU Tech3381 neither recommends nor invalidates the use of 'sample_has_redundancy'.

Agreed. But it isn't necessary to use `sample_has_redundancy`. IMHO it is a special case when adjacent samples do _not_ have some degree of overlap. I don't see the value in setting that attribute to true on most samples since it doesn't help player implementations, which aren't required to take any notice of it anyway, and it's not clear what they should do with the information because it's not specified anywhere.

**Comment by jeanlf** [comment] 2015-03-11 18:57
Regarding trun / tfhd, size/duration are likely set as default values in the trex of the track in the init segment. The behaviour is different for dash-if profiles since they require not using default flags of trex. Hope this helps

**Comment by cconcolato** [comment] 2015-03-12 09:49
@aleal-envivio The MP4Reader snapshots are misleading. They indicate a size and duration of 0 when the fields are actually not present. Also, the snapshot of the trex box to be able to determine if there is a bug. I don't think MP4Box has a bug here. Let me explain.

There are flags in the 'trun' box (sample-duration-present and sample-size-present) that indicate if the duration and size fields are present. If set to 0, the defaults values for duration and size are used but these defaults may be either in the 'tfhd' if the flags (default-sample-duration-present and default-sample-size-present) at the 'tfhd' level are also set, but if they are not set, you have to look at the 'trex' box. 

I understand that in your ttml-in-mp4 parser code you don't parse the 'trex' box, so you indeed require profiles, as @jeanlf said, that force the default-sample-duration-present and default-sample-size-present flags to be set like dash264avc (http://dashif.org/w/2013/08/DASH-AVC-264-v2.00-hd-mca.pdf, p. 11, line 6-7): 
"Default parameters and flags are stored in movie fragments (‘tfhd’ or ‘trun’ box) and not track headers (‘trex’ box)". 

In MP4Box, that means using -profile dashavc264:live or -profile dashavc264:onDemand.

**Comment by aleal-envivio** [comment] 2015-03-12 09:50
For me it is ok.

**Comment by cconcolato** [comment] 2015-03-12 10:08
@nigelmegitt Just to clarify another point, the purpose of the 'redundant' signaling is to help players optimize the processing. 

Consider the following example (the example is stupid but is useful for explaining the concept). A document has only one paragraph which has a duration of 1 minute:
```
<p begin="00:00:00" end="00:01:00">Subtitle</p>
```
This document is stored in only one MP4 sample that has a CTS of 0 and a duration of 1 min. Let's assume that you want to fragment this file with 30 sec fragments. In MP4Box, we will create two samples: Sample 1 (CTS=0, dur=30s) and Sample 2 (CTS=30s, dur=30s) with exactly the same content. From a player perspective, when you play the second sample, you may be interested in knowing that the 2nd sample content is exactly the same as the previous one, so that you don't reload a new document (restarting animations with possible gaps ...). The redundant flag says:
For streams that are not audio,video, a sample that is RAP and that has "sample_has_redundancy=1 can be discarded, and its duration added to the duration of the preceding one, to maintain the timing of subsequent samples."

I hope that clarifies that part. However, for the rest of the discussion, as it is an optimization, we can ignore it.

**Comment by rbouqueau** [comment] 2015-03-12 10:28
@nigelmegitt In our current implementation we create one sample per paragraph because it was what our users asked for. We can still update our approach (especially since it will create many segments and overhead when we introduce overlaps).

I'm not sure I understood your approach. I would be really happy to have your view on the subject.

**Comment by cconcolato** [comment] 2015-03-12 10:53
@SoleneBuet For the record, as explained privately, in MP4Box, we have two phases for the processing of TTML (or any other media) for fragmentation, segmentation or DASH. 

The first phase is *importing* the media (i.e. the TTML document) and creating tracks and sample(s). This phase is media-aware, meaning that we can look into the media data to determine things like how many tracks are needed, how many samples, what the timestamps are. 

The second phase is *dashing* (fragmenting and segmenting). This phase is media-unaware, meaning that we don't look/touch at the sample content to create fragments or segments. We only look at the type (audio, video, text ...) and at some other properties. 

The question is then how to create samples from a TTML document. (see next response).

**Comment by cconcolato** [comment] 2015-03-12 10:55
@nigelmegitt I think we are in agreement. To make sure, consider the following example: a TTML file corresponds to an entire 1-hour long movie, with many paragraphs. 

One approach to store it into an MP4 file is to create only one sample out of this document. Now, assuming that you want segments of 1 min, since we don't want to modify the sample content (see previous answer), we have no choice but create 60 samples, all with the same content, but with different sample times. That's simple, but not very efficient from a storage point of view. From a player's perspective, the player has to load many identical large documents (or use the redundant signaling).  

The other approach is to create many samples during import to enable more compact storage and better dashing. From a player's perspective, it has to load many small documents. The difficulty here is how many samples to create. 

MP4Box supports both approaches:
- you can create samples directly without having MP4Box look at or alter the TTML content, using NHML. See http://concolato.wp.mines-telecom.fr/2014/01/27/first-attempt-at-storing-ttml-in-mp4/. That approach can be used by TTML authors who made sure that their TTML documents are ready for DASHing (i.e. have the right duration). We could probably improve the usability of this approach when there is only one TTML document to import (merge with the approach below).

- you can let MP4Box create the samples for you as documented in http://gpac.wp.mines-telecom.fr/2014/08/23/ebu-ttd-support-in-gpac/. That second option is probably too strict as it tries to create as many samples as possible and fails if paragraphs overlap (we thought initially that EBU-TT-D forbade that). I'm thinking of adding a parameter to add a target sample duration so that fewer samples would be created.

HTH,
Cyril

**Comment by SoleneBuet** [comment] 2015-03-18 12:58
Hello,

Following this, I'd like to share my testings, hoping this could help: https://github.com/SoleneBuet/dash-subtitling_testings with subtitling, MP4Box and Dash.js.
I tested different scenarios and you can find the results in tests.xlsx.
The EBU-TT-D subtitles are in `Sources´.

I would be happy to have your feedback on it.

Thanks.

**Comment by rbouqueau** [comment] 2015-03-18 13:48
@SoleneBuet Thank you for the test. I'll have a look when I find time.

Putting big binary files on 'git' is not a good idea. As a distributed versioning system, 'git' stores all his history on the local computer. If you update a 100MB file 10 times, people will have to checkout 1GB. Your checkout repo is already 3GB!

Now the question: why did you checkout if you don't have timeN I wanted to see the results which are stored in a .xlsx file. If you store it in a .pdf, Github is able to display them directly (since yesterday :) https://github.com/blog/1974-pdf-viewing). Otherwise we have to clone the repo.

Good to see that the dashavc264 profile seems to work fine in browsers.

About the duplicated samples, wouldn't it be related to https://github.com/gpac/gpac/issues/57#issuecomment-78254237? Is the number of repetition compatible with this scenario?

**Comment by SoleneBuet** [comment] 2015-03-18 14:03
I'll remove the files, it's not necessary since the command lines are stored in test.xlsx. I will only let the sources.
I'll convert my test.xlsx in pdf so it's easily viewable. 

Thanks a lot for the advice.

>About the duplicated samples, wouldn't it be related to #57 (comment)? Is the number of repetition compatible with this scenario?

I guess it is highly related. I think it may be the handling from Dash.js of the segments and fragments. 
I'd like to investigate a little bit more. I haven't find the pattern for the number of repetition yet.

Is there a place where I can find the differences implemented by MP4Box from a profile to another?

Is there any other tools than -info and -diso to display the ISOBMFF structure so it's easier to inspect it?
Or resources on how to read the -diso xml file (values I mean, as elements and attributes are part of ISOBMFF spec, and the spec is not really specific about the values)?

I realize fragmenting here is not really relevant, could you explain me why?

In any case, if you spot anything that rings a bell, feel free.

Next tests are going to be the handling of A/C size != from subtitle document (I might some difficulties here) and the absence of subtitles during the period.

**Comment by rbouqueau** [comment] 2015-03-18 14:15
> I'll remove the files

They are in the history of the repo. So even if you remove them from the checkout, people will keep downloading them. That's how 'git' works.

Otherwise that's very good!

> Is there a place where I can find the differences implemented by MP4Box from a profile to another?

It is in the code: https://github.com/gpac/gpac/blob/master/src/media_tools/dash_segmenter.c#L4856
I hope it helps.

> Is there any other tools than -info and -diso to display the ISOBMFF structure so it's easier to inspect it?

I use 'MP4Box -diso'. It is probably not the most user-friendly, but it is very powerful. XML files are now well handled by web-browsers. It is textual so you can compare easily two files with the 'diff' command.

> Or resources on how to read the -diso xml file (values I mean, as elements and attributes are part of ISOBMFF spec, and the spec is not really specific about the values)?

I understand it can be hard to grasp. As you mention the key is the ISOBMF spec. If you need an explanation about a specific value, please post here. We'll try to help you.

> I realize fragmenting here is not really relevant, could you explain me why?

I don't understand the question.

> > About the duplicated samples, wouldn't it be related to #57 (comment)? Is the number of repetition compatible with this scenario?

> I guess it is highly related. I think it may be the handling from Dash.js of the segments and fragments. 
I'd like to investigate a little bit more. I haven't find the pattern for the number of repetition yet.

Is the pattern of the repetition related to https://github.com/gpac/gpac/issues/57#issuecomment-78254237?

To make your life easier, you can open the mp4 files/segment directly in a text editor to watch the TTML parts. If a TTML sample is repeated 'n' times across segments, is it displayed 'n' times?

**Comment by SoleneBuet** [comment] 2015-03-18 14:29
>They are in the history of the repo. So even if you remove them from the checkout, people will keep downloading them. That's how 'git' works.

Oups. I'll try to look at how to fix that! If need be I'll make another repo.
Sorry I'm not very much used to git...

Thanks otherwise for your answer.

> I realize fragmenting here is not really relevant, could you explain me why?

Only dashing with MP4Box -dash seems resulting the same as dashing and fragmenting -dash -frag, at least in browser (in the case where -dash dur -frag dur, not when -dash dur -frag dur' ). I was wandering why, as the ISOBMFF should be quite different.

 you can open the mp4 files/segment directly in a text editor to watch the TTML parts.

This is now my turn not understanding properly. Which mp4 file should I open? Opening the subtitles-10m-random-length_dashinit.mp4 (for example) in a text editor results only in a sequence of numbers.
The only case I get to have the segments separated is in the case of "simple" profile by the way.

**Comment by SoleneBuet** [comment] 2015-03-19 07:17
@rbouqueau Should be all good now with the git! There is also the pdf.

**Comment by rbouqueau** [comment] 2015-03-19 08:39
@SoleneBuet Thank you! I'll review it later.

About segment/fragment, did you have the opportunity to read http://gpac.io/2011/02/02/mp4box-fragmentation-segmentation-splitting-and-interleaving/ ?

**Comment by SoleneBuet** [comment] 2015-03-19 08:43
@rbouqueau Yes I did, several times ;-)

>Fragmentation (-frag) is an optional process applicable to the MP4 file format. By default, MP4 files generated with MP4Box are not fragmented. This process consists in using Movie Fragments (moof). Movie Fragments is a tool introduced in the ISO spec to improve recording of long-running sequences and that is now used for HTTP streaming.

For reference I also found this article quite usefull: https://arashafiei.wordpress.com/2012/12/11/visualization-of-some-options-in-mp4box-dash-h/

Yes you are using moof boxes, the question is maybe more about how Dash.js is parsing the ISOBMFF.

**Comment by rbouqueau** [comment] 2015-03-19 08:50
> the question is maybe more about how Dash.js is parsing the ISOBMFF

I don't expect them to parse it. They should push the full ISOBMF segment thru HTML5/MSE. If they need to extract data from ISOBMF, I would advise them to use https://github.com/gpac/mp4box.js :)

**Comment by SoleneBuet** [comment] 2015-03-19 08:51
They actually do it like this now: https://github.com/Dash-Industry-Forum/dash.js/pull/451/commits
You can have a look to the modifs in FragmentExtensions.js.

**Comment by rbouqueau** [comment] 2015-03-19 10:30
>>>About the duplicated samples, wouldn't it be related to https://github.com/gpac/gpac/issues/57#issuecomment-78254237? Is the number of repetition compatible with this scenario?

>> I guess it is highly related. I think it may be the handling from Dash.js of the segments and fragments. 
>> I'd like to investigate a little bit more. I haven't find the pattern for the number of repetition yet.

> Is the pattern of the repetition related to https://github.com/gpac/gpac/issues/57#issuecomment-78254237?

I confirm it is (for the two first categories of your tests). Can you read the comment again? If the pattern is not clear, send me a PM.

**Comment by nigelmegitt** [comment] 2015-03-19 10:45
Sorry for the delay in responding.

@rbouqueau I think of the set of times when something changes in the subtitles as being a separate and unrelated list to the set of segment or sample times. Note that a `<p>` in TTML is not necessarily the same as a subtitle, and multiple `<p>`s in the same document are permitted with exactly the same, or overlapping, or non-overlapping timings. As @cconcolato pointed out, EBU-TT-D does permit overlapping paragraphs.

@cconcolato In your example of one sample for an hour long programme but segments of 1 minute, I wasn't aware that this is possible in DASH. Segments may contain one or more samples, right? Are you suggesting that the samples are duplicated across multiple segments? Or that the URL for the sample in each segment is in fact the same URL? I did not envisage that anyone would want to do that, and I don't see why they would - there's no reason not to create a single 1 hour segment for the subtitle Representation is there?

When it comes to setting a redundant flag, I can see how your example would work @cconcolato but only if the sample content is identical. I got the impression before that @rbouqueau was thinking of setting it if some part of the two samples is the same even if some other parts are not.

Maybe it helps to work with an example:

##### Input document

We start with an EBU-TT-D document that contains:

```xml
<p begin="00:00:00" end="00:01:00">Subtitle 1</p>
<p begin="00:00:30" end="00:01:30">Subtitle 2</p>
<p begin="00:01:00" end="00:01:30">Subtitle 3</p>
```

Let's say we want, for the sake of example, 5x18s samples. My assumption is that the parts of the document that overlap with each sample period would be extracted, without further editing, which gives:

##### Sample 1 [0-18)s

```xml
<p begin="00:00:00" end="00:01:00">Subtitle 1</p>
```

##### Sample 2 [18-36)s

```xml
<p begin="00:00:00" end="00:01:00">Subtitle 1</p>
<p begin="00:00:30" end="00:01:30">Subtitle 2</p>
```

##### Sample 3 [36-54)s

```xml
<p begin="00:00:00" end="00:01:00">Subtitle 1</p>
<p begin="00:00:30" end="00:01:30">Subtitle 2</p>
```

##### Sample 4 [54-72)s

```xml
<p begin="00:00:00" end="00:01:00">Subtitle 1</p>
<p begin="00:00:30" end="00:01:30">Subtitle 2</p>
<p begin="00:01:00" end="00:01:30">Subtitle 3</p>
```

##### Sample 5 [72-90)s

```xml
<p begin="00:00:30" end="00:01:30">Subtitle 2</p>
<p begin="00:01:00" end="00:01:30">Subtitle 3</p>
```

As you can see, samples 2 and 3 do end up being the same, so I guess that 3 could be marked as redundant by @cconcolato's logic above. However each consecutive sample does contain one or more `<p>`s that's in an adjacent sample too, but in general the samples are not redundant.

By the way, the presentation behaviour for those 5 samples should by the specification be indistinguishable from that when the EBU-TT-D processing also modifies the begin and end times to match the sample times, for example sample 2 could become:

```xml
<p begin="00:00:18" end="00:00:36">Subtitle 1</p>
<p begin="00:00:30" end="00:00:36">Subtitle 2</p>
```

and sample 3 could become:

```xml
<p begin="00:00:36" end="00:00:54">Subtitle 1</p>
<p begin="00:00:36" end="00:00:54">Subtitle 2</p>
```

Presumably if you did that then you could not use the redundant flag for sample 3?

**Comment by SoleneBuet** [comment] 2015-03-20 07:51
@rbouqueau The thing is, in none of my examples the subtitles are overlapping on each other, they're all exclusive in terms of timeline.
So absolutely no situation like Nigel's example:
```
<p begin="00:00:00" end="00:01:00">Subtitle 1</p>
<p begin="00:00:30" end="00:01:30">Subtitle 2</p>
```
 However it may overlap on segments/fragments, which is I guess where the problem comes from, it is repeated on the next segments. Does it makes sense?

**Comment by rbouqueau** [comment] 2015-03-20 08:40
@SoleneBuet You're right. Samples are repeated on the next segments, but the demuxer ignores the flag saying it is repeated. So it send it multiple times to the decoder. Is it clearer?

**Comment by SoleneBuet** [comment] 2015-03-20 08:55
Yes a little more clearer, thanks a lot! I also realized when comparing segments a difference if there is redundancy or not:

Context:
First segment (10s dashed file of 10min):

```
<MediaDataBox dataSize="1145">
        <BoxInfo Size="1153" Type="mdat"/>
    </MediaDataBox>
    <MovieFragmentBox TrackFragments="1">
        <BoxInfo Size="104" Type="moof"/>
        <MovieFragmentHeaderBox FragmentSequenceNumber="2">
            <BoxInfo Size="16" Type="mfhd"/>
            <FullBoxInfo Version="0" Flags="0x0"/>
        </MovieFragmentHeaderBox>
        <TrackFragmentBox>
            <BoxInfo Size="80" Type="traf"/>
            <TrackFragmentHeaderBox TrackID="1" BaseDataOffset="moof" SamplePadding="0" Sync="1" DegradationPriority="0" IsLeading="0" DependsOn="2" IsDependedOn="0" HasRedundancy="1">
                <BoxInfo Size="20" Type="tfhd"/>
                <FullBoxInfo Version="0" Flags="0x20020"/>
            </TrackFragmentHeaderBox>
            <TrackFragmentBaseMediaDecodeTimeBox baseMediaDecodeTime="10000">
                <BoxInfo Size="16" Type="tfdt"/>
                <FullBoxInfo Version="0" Flags="0x0"/>
            </TrackFragmentBaseMediaDecodeTimeBox>
            <TrackRunBox SampleCount="2" DataOffset="112">
                <BoxInfo Size="36" Type="trun"/>
                <FullBoxInfo Version="0" Flags="0x301"/>
                <TrackRunEntry Duration="2000" Size="1145"/>
                <TrackRunEntry Duration="8000" Size="1149"/>
            </TrackRunBox>
        </TrackFragmentBox>
    </MovieFragmentBox>
```
Second segment looks the same.

Third segment:
```
<MediaDataBox dataSize="2293">
        <BoxInfo Size="2301" Type="mdat"/>
    </MediaDataBox>
    <MovieFragmentBox TrackFragments="1">
        <BoxInfo Size="96" Type="moof"/>
        <MovieFragmentHeaderBox FragmentSequenceNumber="4">
            <BoxInfo Size="16" Type="mfhd"/>
            <FullBoxInfo Version="0" Flags="0x0"/>
        </MovieFragmentHeaderBox>
        <TrackFragmentBox>
            <BoxInfo Size="72" Type="traf"/>
            <TrackFragmentHeaderBox TrackID="1" BaseDataOffset="moof" SampleDuration="10000" SampleSize="1145" SamplePadding="0" Sync="1" DegradationPriority="0" IsLeading="0" DependsOn="2" IsDependedOn="0" HasRedundancy="0">
                <BoxInfo Size="28" Type="tfhd"/>
                <FullBoxInfo Version="0" Flags="0x20038"/>
            </TrackFragmentHeaderBox>
            <TrackFragmentBaseMediaDecodeTimeBox baseMediaDecodeTime="30000">
                <BoxInfo Size="16" Type="tfdt"/>
                <FullBoxInfo Version="0" Flags="0x0"/>
            </TrackFragmentBaseMediaDecodeTimeBox>
            <TrackRunBox SampleCount="1" DataOffset="104">
                <BoxInfo Size="20" Type="trun"/>
                <FullBoxInfo Version="0" Flags="0x1"/><!-- all default values used -->
            </TrackRunBox>
        </TrackFragmentBox>
    </MovieFragmentBox>
```

In 'trun', it appears there are TrackRunEntry duration=number. I guess it has to have with HasRedundancy and SampleCount, but what the link?
A little help on interpreting these segments?

Thanks.

**Comment by SoleneBuet** [comment] 2015-03-23 11:01
Ok so I resolved my problem by correctly using DTS and duration information in Dash.js. 
You can close :-) 
Thanks again.

**Closed** 2015-03-23 11:41 UTC
Labels: invalid
