### ISSUE TITLE
DashCast transcode a live stream in multiple qualities on windows7 64bit，and played these stream in the DASH.js.

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#262] opened 2015-09-25 09:02 UTC
Hello,

Who can give me a guideline about the title.

Because the segments that pruduct by Dashcast with the -live options, can not played by the dash.js player.
Thanks so much.

JamesXu

**Comment by rbouqueau** [comment] 2015-09-25 09:06
Duplicate of #216 and/or #251. Please don't double post.

**Closed by rbouqueau** 2015-09-25 09:06 UTC
Labels: duplicate

**Comment by adetheprince** [comment] 2015-11-19 05:51
DashCast: command not found

**Comment by jeanlf** [comment] 2015-11-19 08:16
which platform are you using? which version of the installer?

**Comment by adetheprince** [comment] 2015-11-19 08:26
Hi there
I am using Ubuntu Server 14.04.3 LTS 

I also try to use the tutorial but lots of error and directory missing...
