### ISSUE TITLE
Android APK Problem for OSMO4

### ISSUE THREAD

**Issue by JamesXu20150314** [gpac/gpac#1056] opened 2018-05-15 12:29 UTC
Hello, 

Who knows why the APK(https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/) cannot work well on any Android devices?

I have tried many Android devices (Google Pixel XL && Huawei Honor) and APK versions.

When I open an URL (DASH MPD file) after installing these APK, it will crash always.

Why?

To produce a new APK, I also have compiled the source code (master) by myself. However, it also will crash. I cannot play any profiles.

Yours Sincerely,
James Xu.

**Comment by Nikirand** [comment] 2018-05-20 05:43
I encountered the same problem as you. Besides, the iOS project can not work either, it shows black
screen every time we open it.

**Comment by ARSekkat** [comment] 2018-05-23 14:10
Hello James,

I can't reproduce this bug. Would it be possible for you to share your link of your MPD file or upload the file somewhere so I can test it?

Rida

**Comment by JamesXu20150314** [comment] 2018-05-25 03:16
Hello @ARSekkat, here is my MPD file ([http://www.xuzhimin.cc/Segments/Source-ERP-2304x1152.mpd](http://www.xuzhimin.cc/Segments/Source-ERP-2304x1152.mpd))

Here are my tiles ([http://www.xuzhimin.cc/Segments/](http://www.xuzhimin.cc/Segments/))

I also want to know the version of your GPAC and your devices.

Thanks.

**Comment by ARSekkat** [comment] 2018-05-28 09:04
Hello @JamesXu20150314 , I still can't reproduce your bug. I can read your MPD file using the latest version of the APK in the gpac nightly builds link. I tested it on Samsung Galaxy S7.

**Comment by aureliendavid** [comment] 2018-05-30 08:28
I managed to play it on my phone (LG G6, android 8), but only by using the player own UI: 

![1056](https://user-images.githubusercontent.com/7168263/40708581-1513df7e-63f4-11e8-9ea9-4f4b85e148e1.png)

If I use the "open URL" from the hamburger menu, it crashes every time.

**Comment by ARSekkat** [comment] 2018-06-08 11:36
For me this branch works for both GUI and the hamburger menu, can you test it too in your devices ? 
https://github.com/ARSekkat/gpac/tree/android_tmp

**Comment by jeanlf** [comment] 2019-06-29 12:53
No news closing

**Closed** 2019-06-29 12:58 UTC
