### ISSUE TITLE
Repeated ttml code when encapsulating inside fMP4

### ISSUE THREAD

**Issue by Canta** [gpac/gpac#2778] opened 2024-03-11 21:40 UTC
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue 

I'm trying to encapsulate a TTML chunk into an fMP4 container.
Related: #2730 

Back then, when trying to do the same with WebVTT, I was finally succesful thanks to your guidance.
So I tried the same command but using TTML input, and the output seems to have some problem.

This is an example input:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" xml:lang="en" >
  <head>
    <metadata>
      <ttm:title/>
      <ttm:desc/>
      <ttm:copyright/>
    </metadata>
    <styling>
      <style xml:id="style0" tts:textAlign="center" />
    </styling>
    <layout>
      <region xml:id="region01" tts:extent="100% 14%" tts:fontFamily="proportionalSansSerif" tts:fontSize="24px" tts:origin="0% 79%" />
    </layout>
  </head>
  <body>
    <div>
      <p style="style0" end="06:48:23.888" region="region01" begin="06:48:20.051" xml:id="caption0152" >Abrazándose. No robándose las perlas<br/>de la abuela Fine.</p>
    </div>
  </body>
</tt>
```

Then I run this gpac command:
```
# gpac -i input.ttml -o output.mpd:dmode=static:segdur=6.4:dur=6.4:noinit=false:segext=m4s:initext=mp4:timescale=1000:force_flush=true:moovts=1000:subs_sidx=0:store=fstart:mediats=1000
```

And this is what the output contains:
```
$ cat input_dash1.m4s
stypmsdhmsdhmsixlmsg,sidx��u�P�hmoofmfhdPtraftfhd&tfdt$trunpu�PTmdat<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" xml:lang="en" >
  <head>
    <metadata>
      <ttm:title/>
      <ttm:desc/>
      <ttm:copyright/>
    </metadata>
    <styling>
      <style xml:id="style0" tts:textAlign="center" />
    </styling>
    <layout>
      <region xml:id="region01" tts:extent="100% 14%" tts:fontFamily="proportionalSansSerif" tts:fontSize="24px" tts:origin="0% 79%" />
    </layout>
  </head>
  <body>
    <div>
      <p style="style0" end="06:48:23.888" region="region01" begin="06:48:20.051" xml:id="caption0152" >Abrazándose. No robándose las perlas<br/>de la abuela Fine.</p>
    </div>
  </body>
</tt><?xml version="1.0" encoding="UTF-8"?>
<tt xmlns="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" xml:lang="en" >
  <head>
    <metadata>
      <ttm:title/>
      <ttm:desc/>
      <ttm:copyright/>
    </metadata>
    <styling>
      <style xml:id="style0" tts:textAlign="center" />
    </styling>
    <layout>
      <region xml:id="region01" tts:extent="100% 14%" tts:fontFamily="proportionalSansSerif" tts:fontSize="24px" tts:origin="0% 79%" />
    </layout>
  </head>
  <body>
    <div>
      <p style="style0" end="06:48:23.888" region="region01" begin="06:48:20.051" xml:id="caption0152" >Abrazándose. No robándose las perlas<br/>de la abuela Fine.</p>
    </div>
  </body>
</tt>
```

As you can see, the xml content is duplicated inside the fMP4 container.
I didn't get playback on players, and that's how I end up checking inside the file. Didn't found a workaround with my known gpac commands, and this seems like some kind of error, so I create this issue here.

Tested with a mainline build minutes ago:
```
# gpac --asdasd
Nothing to do, check usage "gpac -h"
gpac - GPAC command line filter engine - version 2.3-DEV-rev922-g96b474ec5-master
(c) 2000-2023 Telecom Paris distributed under LGPL v2.1+ - https://gpac.io

Please cite our work in your research:
	GPAC Filters: https://doi.org/10.1145/3339825.3394929
	GPAC: https://doi.org/10.1145/1291233.1291452
```

Thanks.

**Comment by rbouqueau** [comment] 2024-03-13 15:29
The duplicated content is normal. That's how 14496-30 works with segmentation.  The content needs to be pre-segmented.

> I didn't get playback on players,

Which players? Would you have a complete test set that would allow to reproduce your issue?

**Comment by rbouqueau** [comment] 2024-03-13 18:36
@nigelmegitt You're right.

@Canta Do you confirm that input.ttml is supposed to be pre-segmented?

The actual command-line ends with an error message. How did you come to use this list of arguments, and why?
```
$ gpac -i input.ttml -o output.mpd:dmode=static:segdur=6.4:dur=6.4:noinit=false:segext=m4s:initext=mp4:timescale=1000:force_flush=true:moovts=1000:subs_sidx=0:store=fstart:mediats=1000
[FileOut] output file handle is not opened, discarding 805 bytes
```

**Comment by Canta** [comment] 2024-03-13 20:52
Thank you guys for taking a look at it.

@rbouqueau 
`How did you come to use this list of arguments, and why?`
This issue is a "spinoff" from https://github.com/gpac/gpac/issues/2730.
In that previous issue, I asked how to encapsulate webvtt inside fMP4.
Eventually had to also encapsulate ttml, so just tried the same command that got from there but with different input file.

Logically, I've also tried turning "on" and "off" several parameters, and took a look at the filters wiki in order to find something useful regarding TTML. Had no luck, so I just reported the original command.

I don't need that specific command to work, but just to encapsulate my input TTML file in fMP4. Whatever other gpac command you may consider is fine.


`Do you confirm that input.ttml is supposed to be pre-segmented?`
I'm not sure what you mean by "pre-segmented", but my use case is simple: I have raw (plain text) subtitle chunks for LIVE streaming (not VOD, but continuous streams), and I need to deploy those chunks inside fMP4 containers for some players to work. So, I guess the input is indeed "pre-segmented", as it's always a fragment of a longer live stream.

This is not a prototypical gpac use case. I'm using gpac as part of another software pipeline, and not as standalone encoding/packaging tool. But I was successful using it for #2730, so I guess the TTML thing is some kind of bug.

`Which players?`
This is for MPEG-DASH, so I mostly test with Dashif and Shaka Player on web browsers. However, other players with propietary customizations (and not under my control) may be also involved, and not just web but also Android and other devices (smart tvs, set top boxes, etc).
Dashif, for example, plays nicely my raw ttml subtitles (confirming that the syntax and the cues are fine). But Shaka Player doesn't, and that's a case where I need to implement fMP4 in order for it to play them.



Let me know if I can help understanding this.
Thanks.

**Comment by jeanlf** [comment] 2024-03-26 17:08
The warning was coming from specifying `initext` which was triggering a rawsub option, reopeningthe output - now fixed on master.

Regarding your command line, you specify `force_flush` which will force flushing the input media; in the case of timed text, this will send the last packet of the source (split to match the desired segment duration) plus the remaining of the media (same packet as it is a split, but with duration IN_DUR-seg_dur), hence the duplication.

Not using `force_flush` results in single TTML sample in each segment, but a bunch of files since the TTML duration is 06:48:23.888.

One way to avoid this is to set the CTS of the TTML to the earliest non-zero start time in the doc using `-i src.ttml:ttml_cts=-2`

**Closed by jeanlf** 2024-03-26 17:08 UTC
