### ISSUE TITLE
creating a tiled DASH video using MP4Box

### ISSUE THREAD

**Issue by Iman-sm** [gpac/gpac#660] opened 2016-10-13 20:21 UTC
Hi,
I was interested to know the corresponding command to create a tiled video. I have already created a normal DASH sequence with various qualities using MP4Box (which generates the *.mpd file), yet I don't know how to tell MP4Box that i want to create a tiled video that contains a different sequence in each tile. I've seen the demos like "tears of steel", yet i couldn't find any tutorial on how to create a tiled video and what command or commands to use to tell MP4Box that the videos that are provided to it need to be put together as tiles (or which sequence needs to be played in which tile). 
Thanks in advance

**Comment by rbouqueau** [comment] 2016-10-14 07:06
It seems like a duplicate of #595. I'm closing but your input is highly welcome there #595  :)

**Closed by rbouqueau** 2016-10-14 07:06 UTC
Labels: duplicate, question
