### ISSUE TITLE
Text relocation error for Android+x86 architecture

### ISSUE THREAD

**Issue by Duna** [gpac/gpac#1691] opened 2021-02-25 14:11 UTC
I am trying to compile the .so libs for an android project, unsuccessful because Text Relocation issue on newer android sdk
It seems this it needs to be fixed in x86 libs

**Comment by rbouqueau** [comment] 2021-02-25 14:57
It is difficult to answer without any detail, could you provide more?

Usually these errors are solved by using -fPIC.

**Comment by Duna** [comment] 2021-02-25 16:20
> It is difficult to answer without any detail, could you provide more?
> 
> Usually these errors are solved by using -fPIC.

No, it didn't work. disable-asm  worked, but I am wondering if the code still working

**Comment by rbouqueau** [comment] 2021-02-25 16:56
> disable-asm worked

GPAC has no such option. Would you please provide us with the log to understand more about the error?

**Comment by ATiwari1987** [comment] 2021-02-26 11:42
2021-02-25 14:43:27.414 20619-20619/com.enst.mp4box I/System.out: Loading library avcodec...
2021-02-25 14:43:27.415 20619-20619/com.enst.mp4box I/System.out: dlopen failed: "/data/app/~~ZmEO3tVu7m6NJGkYR6wdNQ==/com.enst.mp4box-E4Luw3FTCH87NiWcgTfBdg==/lib/x86/libavcodec.so" is 64-bit instead of 32-bit

**Comment by ATiwari1987** [comment] 2021-02-26 11:47
2021-02-25 13:43:45.907 26423-26423/com.enst.mp4box I/System.out: Loading library avcodec...
2021-02-25 13:43:45.907 26423-26423/com.enst.mp4box E/linker: "/data/app/~~BXk9ztSoipkJMdbtaI3cfw==/com.enst.mp4box-SvfB-NjbdSVdQ1kn6aJM8A==/lib/x86/libavcodec.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)

Getting this error when loading avcodec library in gpac project. However this  issue is only on x86 and not arm architecture, and gets resolvedby using --disable-asm flag (not with -fPic though)

**Comment by rbouqueau** [comment] 2021-02-26 13:29
> I am trying to compile the .so libs for an android project, unsuccessful because Text Relocation issue on newer android sdk

Compile error.

> 2021-02-25 13:43:45.907 26423-26423/com.enst.mp4box I/System.out: Loading library avcodec...

Runtime error. This is not a compile error.

Could you please provide way more context about what you did? Imagine that I'd like to help you and reproduce your issue: what do I need to do?

By the way is /lib/x86/libavcodec.so the extra that you built following the GPAC Android build instructions?

If the issue is with libavcodec from FFmpeg, could you please rebuild it with -fPIC?

> We dont want

Are you and @Duna working on the same issue?

**Comment by Duna** [comment] 2021-02-26 13:43
Yes we are in the same team Aakanksha will give you additional details

**Comment by ATiwari1987** [comment] 2021-02-26 14:02
Please note the following:-

There is no compile error. I was able to compile everything successfully.

I built the dependencies for gpac first by following the GPAC Android build instructions

2. Using same instruction I was able to build the gpac and its libraries. I just added x86 architecture also to build the x86 so files there along with armeabi ones.

3. Now we tried using the libraries in an android application targeting API version 30, it worked fine for arm architecture 

4. However when using the so files for x86, it gives error that I gave you above regarding txt relocation

5. Now to resolve this error I rebuild the ffmpeg dependencies i.e. avcodec and other libraries by adding --disable-asm flag, that was also built successfully. And after that I built the gpac libraries also with new x86 ffmpeg libraries ( The ffmpeg avcodec library built now didn't had txt relocation , I checked it using command)

6. Now I am able to load the x86 library in the android project fine in x86 also without any error.

Just wanted to check if above is the right way to use it according to you @Duna If you have any othet thing to add you can

**Comment by rbouqueau** [comment] 2021-02-26 14:39
2 ) could you detail your modifications?

 4 ) how do you start the x86 build? In a simulator? What are the OS characteristics?

Now while we are gathering the information:
- Could you please provide us with the full log of the runtime error please?
- Do you confirm that /lib/x86/libavcodec.so is the extra that you built following the GPAC Android build instructions?

PS: by googling the issue I've found some links about how Google address that issue for Chrome:
- https://bugs.chromium.org/p/chromium/issues/detail?id=911658#c19
- https://chromium.googlesource.com/chromium/third_party/ffmpeg/+/refs/heads/master/BUILD.gn

**Comment by ATiwari1987** [comment] 2021-02-26 15:43
In Application.mk first line i.e. 
APP_ABI := armeabi armeabi-v7a 
added x86 also , so that makes it as follows:-
APP_ABI := armeabi armeabi-v7a x86

I built it in Ubuntu 20.04.x64 OS.

Yes I have built the library using Android build instructions and modifying it as above.

In the sample application built over android studio with target API 30, mp4box.java sample file given in the project was used attached below:-

[MainActivity.zip](https://github.com/gpac/gpac/files/6050645/MainActivity.zip)

When the libraries are being loaded status and exceptions are being printed using  System.out.println. It shows success for arm based processor, however it gives exception when loading avcodec library as text revocations are not allowed after API 23 I think, I have already provided that output detail to you above. (Please check the java file you will see that it threw exception in system.loadflibrary while loading avcodec which i gave earlier). 

Also please note that this gets resolved after making changes in ffmpeg compile script and adding the --disable-asm flag to build the avcodec and other ffmpeg so files which are required by gpac library.

If still something not clear feel free to ask me.

I was able to get success for all libraries after recompiling the dependencies

**Comment by rbouqueau** [comment] 2021-02-26 16:24
> APP_ABI := armeabi armeabi-v7a x86

Thanks.

> Yes I have built the library using Android build instructions and modifying it as above.

That's not the answer to my question. It seems weird to me to have a manually built library inside the /lib/x86/ folder ; could you check this library is indeed the one you built?

> Also please note that this gets resolved after making changes in ffmpeg compile script and adding the --disable-asm flag to build the avcodec and other ffmpeg so files which are required by gpac library.

When you read the Google links, they explain where the error comes from, why FFmpeg won't fix it, and how they fix it. Have you tried what they do for Google Chrome?

NB: exact fix commit: https://chromium.googlesource.com/chromium/third_party/ffmpeg/+/3742b53c65dd653e7d877b9a97e47443f07cd2ac%5E%21/#F0

**Comment by ATiwari1987** [comment] 2021-02-27 02:12
@rbouqueau Yes the library is indeed the one that is built and generated inside the lib/x86 folder.

The link provided by you seems helpful and we can try out the suggestions in the link if we face issue in the x86 library which is loading for now. Thanks for all your help and suggestions, I really appreciate

**Comment by rbouqueau** [comment] 2021-02-27 14:29
Great, let us know. If you struggle too much I'll try to duplicate the setup as well.

**Comment by ATiwari1987** [comment] 2021-03-04 15:34
@rbouqueau we have been able to successfully compile the libraries and able to use them on osmo4 project. However we are facing issue using the mp4box command and have opened another issue for that https://github.com/gpac/gpac/issues/1693 . Waiting for someone to respond on that so that we have some example of how to use the mp4box command on android. Is it possible for you to link these issues and help us on that?

**Comment by rbouqueau** [comment] 2021-03-04 15:56
Ok. It seems like this issue can now be closed when we confirm the build is sane (#1693)

**Closed** 2021-03-04 17:09 UTC

**Comment by aureliendavid** [comment] 2021-03-11 13:53
@ATiwari1987 @Duna :

can you provide a bit more details on how you were able to build mp4box.so with the ndk?

did you have to make changes to `build/android/jni/` and/or to `applications/mp4box/` ?

thanks

**Comment by Duna** [comment] 2021-03-11 14:20
@ATiwari1987 is the expert here, but he worked a lot to make this compile. I also paid him.

**Comment by ATiwari1987** [comment] 2021-03-11 15:31
@aureliendavid you can add mp4box in the mk folder under the jni folder to build the mp4box.so file, hope that helps, however if still there is any issue you can let me know

**Comment by aureliendavid** [comment] 2021-03-11 15:37
> you can add mp4box in the mk folder under the jni folder to build the mp4box.so

yes, but I wanted to know if you had to make other changes to make it work or if just enabling it was enough?

**Comment by ATiwari1987** [comment] 2021-03-12 02:01
There were not any major changes but might be some small changes may be required for ex JniLogv in one place was modified to resolve an issue while compiling. Apart from this I don’t recall exactly what all changes were done, if you are getting any issue while camping you can let me know I will be able to recall if anything was done for that

**Comment by rbouqueau** [comment] 2021-03-12 10:23
Would it be possible to share your code so that we make a diff? If that's private you can upload the content using https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95. Let us know here.

Thanks for contributing back.

**Comment by ATiwari1987** [comment] 2021-03-16 15:03
@rbouqueau sorry for the late response, I was not available for last few days so not able to respond. It’s good to see that the script has been updated now and the issue resolved
