### ISSUE TITLE
pause_at_first_frame doesn't have effect on decoding

### ISSUE THREAD

**Issue by gorinje** [gpac/gpac#1612] opened 2020-10-08 23:09 UTC
Terminal seems not binge able to display still image or the first picture of a video, since there is no specific event to stop the player at the first displayed image and the argurment pause_at_first_frame arguments of this function : 
void gf_term_connect_from_time(GF_Terminal * term, const char *URL, u64 startTime, u32 pause_at_first_frame);

keeps the decoder performing the full decoding of the current input file.

Still images appear and then goes black. Videos keep playing or stay black when the event GF_EVENT_CONNECT is triggered.

May be a specific event triggered at the first displayed image could help to pause the gf_term_process_step loop ?

**Comment by jeanlf** [comment] 2020-10-09 10:34
what source are you using ? 
```
MP4Client -pause file.mp4
```
works fine here.

**Comment by gorinje** [comment] 2020-10-09 11:48
The function has been tested on jpeg and ogv files (ogg + theora). 

The function is used in a similar manner than main.c file in the folder gpac/applications/testapps/player_api. Though it is monothreaded, so the play_pause_seek_gettime is modified as follow : 

gf_term_connect_from_time(ctx->term, ctx->fio_url, 0, 1);
    while (!connected){
        gf_term_process_step(ctx->term);
        emscripten_sleep(1);
}

and expect that decoder would stop at the first frame displayed on the layer.

**Comment by jeanlf** [comment] 2020-10-09 12:13
I cannot reproduce this on osx nor windows (haven't tested on linux) - can you check if your vanilla MP4Client has the issue on your system ?

**Comment by gorinje** [comment] 2020-10-09 12:43
The following command tested with OSx (10.15.7) on this [ogv file](https://upload.wikimedia.org/wikipedia/commons/b/b3/Big_Buck_Bunny_Trailer_400p.ogv) :
./MP4Client -pause Big_Buck_Bunny_Trailer_400p.ogv

give me the same results -- the player keeps decoding without pausing at first frame --.

However, indeed an [mp4 files](https://pi4.informatik.uni-mannheim.de/~kiess/test_sequences/download/sequences/mp4/big_buck_bunny_scene.mp4) doesn't produce the same effect.

As well as a [jpeg file](https://ensiwiki.ensimag.fr/images/4/44/IRL_Segmentation_Lenna.jpg) on the same system :
./MP4Client -pause IRL_Segmentation_Lenna.jpg 

They both work with the pause argument.

May be it's related to a different behavior in the ogg demuxer ?

**Comment by jeanlf** [comment] 2020-10-09 13:19
indeed a few demuxers were not setting (or incorrectly) the playback mode property, now fixed on git. Can you cross-check ?

**Comment by gorinje** [comment] 2020-10-09 15:36
It works like a charm on ogv :) 

However, in view of my specific functioning -- monothreaded with the use of gf_term_process_step to trigger the pipeline process). Is there any flag to gf_term_* to check in order to suspend the decoding once this first frame is obtained?
```C
    ctx->term = gf_term_new(&ctx->user);
    if (!ctx->term)
    {
        fprintf(stderr, "\nInit error - check you have at least one video out and one rasterizer...\nFound modules:\n");
        gf_sys_close();
        return 1;
    }
    gf_term_connect_from_time(ctx->term, ctx->fio_url, 0, 1);
    
    while (!connected){
       gf_term_process_step(ctx->term);
        emscripten_sleep(1);
    }
    
    gf_term_play_from_time(ctx->term, 0, 1);
    while (!progress){
       gf_term_process_step(ctx->term);
        emscripten_sleep(1);
    }
return 0;
```

where my variables _progess_ and _connected_ are set as follow :
```C
Bool GPAC_EventProc(void *ptr, GF_Event *evt)
{
    switch (evt->type)
    {
    case GF_EVENT_CONNECT:
        connected = GF_TRUE;
        break;
    case GF_EVENT_PROGRESS:
        progress = GF_TRUE;
        break;
    default:
        break;
    }
    return GF_FALSE;
}
```

**Comment by jeanlf** [comment] 2020-10-09 16:29
As indicated in the doc, gf_term_process_step returns GF_TRUE if a frame was drawn, so if you pause at first frame, loop until you get GF_FALSE from gf_term_process

**Closed by jeanlf** 2020-10-09 16:29 UTC

**Comment by gorinje** [comment] 2020-10-21 11:23
My original code to get the first frame was indeed this : 
```
    gf_term_connect_from_time(ctx->term, ctx->fio_url, 0, 1);
    
    while (gf_term_process_step(ctx->term) == GF_FALSE){
        emscripten_sleep(1);
    }
```

However, eventhough the compositor declare a produced frame (frame_was_produced), depending on the decoder used, I have differents behaviors : 

-  for jpeg images , the image would quickly appears and then disappeared
- for theora video, the first frame draw is black and the display layer isn't resized

This behavior can be reproduced by setting a breakpoint on gf_fs_run_step(term->fsess) in terminal.c, line 1323 with the same terminal command and the same file give as above : 
./MP4Client -pause Big_Buck_Bunny_Trailer_400p.ogv

The first gf_fs_run_step call  gives a frame_was_produced at GF_TRUE, though nothing is displayed, the second call will also give a frame_was_produced at GF_TRUE and the first frame is correctly displayed.
