### ISSUE TITLE
MP4Box  dash  aac failed

### ISSUE THREAD

**Issue by LeoKingLong** [gpac/gpac#1467] opened 2020-04-16 07:19 UTC
1. I downloaded the latest filters branch code , and follow the 
"GPAC Build Guide for Linux  ---> MP4Box only "   ,and install the MP4Box successfully.
 
OS: Centos 6

2.  Dash command:
MP4Box -dash 1000 -frag 1000 -rap -frag-rap -profile live -segment-name my   /home/my.aac -out /home/my.mpd

3. Command result:
![image](https://user-images.githubusercontent.com/26246461/79426022-230d2300-7ff5-11ea-8bb8-6db16f9d973a.png)
......
[DASH] Cannot open file /home/my.aac for dashing: Feature Not Supported
DASH Setup Error: Feature Not Supported

4. But I can dash some MP4 file successfully,  why does dash aac failed？  Thanks

**Comment by jeanlf** [comment] 2020-04-16 07:28
I cannot reproduce, could you share your aac file?

**Comment by LeoKingLong** [comment] 2020-04-16 07:37
[8K.zip](https://github.com/gpac/gpac/files/4485547/8K.zip)
here it is

**Comment by LeoKingLong** [comment] 2020-04-16 11:55
![image](https://user-images.githubusercontent.com/26246461/79453159-dd178580-801b-11ea-818a-b9a477b02b85.png)
![image](https://user-images.githubusercontent.com/26246461/79453221-f1f41900-801b-11ea-80ed-f89fde63c080.png)

And it's master branch ,not filter branch.....

**Comment by jeanlf** [comment] 2020-04-16 12:30
you need 0.9.0 (filter branch) for that - you still have the old master installed on your system

**Comment by LeoKingLong** [comment] 2020-04-17 01:06
![image](https://user-images.githubusercontent.com/26246461/79520766-20104200-808a-11ea-8dd2-97c990c0dc54.png)
![image](https://user-images.githubusercontent.com/26246461/79520822-4930d280-808a-11ea-9c69-66a89ca11e86.png)

And new error:

![image](https://user-images.githubusercontent.com/26246461/79520898-69609180-808a-11ea-885c-180372c2a201.png)
......
![image](https://user-images.githubusercontent.com/26246461/79520921-767d8080-808a-11ea-9ce0-996572726e5a.png)
.....
![image](https://user-images.githubusercontent.com/26246461/79520937-8006e880-808a-11ea-976e-1c4403ec90ce.png)
.......
![image](https://user-images.githubusercontent.com/26246461/79521013-b9d7ef00-808a-11ea-872a-d52a1da4503f.png)

**Comment by jeanlf** [comment] 2020-04-17 08:14
Please don't use images post your logs as text.
Here's my output:
```
% MP4Box -dash 1000 -profile live -out temp/live.mpd 8K.aac
[Dasher] No template assigned, using $File$_dash$DS$$Number$
[Dasher] No bitrate property assigned to PID 8K.aac, defaulting to 1Mbps
	Try specifying bitrate property after your source, e.g. -i source.raw:#Bitrate=VAL
[MPD] Generating MPD at time 2020-04-17T08:12:28.874Z97s 99 %%
[Dasher] End of Period 
[Dasher] End of MPD (no more active streams)
```

I guess something is wrong in your command line syntax

**Comment by LeoKingLong** [comment] 2020-04-17 08:33
I use the same command provided by you ,and got the same faile result.

Because My test environment  has some safe policy，so copy txt is disabled,  sorry for that...

I had try compile  MP4Box only  (lastest filter branch and branch filter release ) on centos6 and centos7，and got the same fail result.
Maybe MP4Box has bug on centos7 ?

**Comment by jeanlf** [comment] 2020-04-21 09:45
on centos7 and centos8:
```
MP4Box -dash 1000 -frag 1000 -rap -frag-rap -profile live -segment-name my media/auxiliary_files/enst_audio.aac -out temp/my.mpd
```

works just fine. Are you sure you don't have a bad character somewhere in your command line?

**Comment by jeanlf** [comment] 2020-06-09 08:48
no news and cannot reproduce, closing

**Closed by jeanlf** 2020-06-09 08:48 UTC
