### ISSUE TITLE
mp4box incorrectly marks subtitle streams as video/mp4 when generating DASH

### ISSUE THREAD

**Issue by sandersaares** [gpac/gpac#271] opened 2015-10-07 07:56 UTC
The expected mimeType value for text streams is `application/mp4`.

For detailed rationale, see discussion in https://github.com/google/ExoPlayer/issues/689

**Comment by cconcolato** [comment] 2015-10-07 08:12
I agree with you. The [RFC](https://tools.ietf.org/html/rfc4337#page-3) is clear: `video/mp4` if the file contains video, `audio/mp4` if it does not contain video but contains audio, and `application/mp4` for all other files. It would have been better to use `text/mp4` for subtitle or text tracks but that's unfortunately not specified.

**Comment by jeanlf** [comment] 2015-10-07 08:33
indeed, now fixed thanks for the report

**Closed by jeanlf** 2015-10-07 08:33 UTC
Labels: bug, mp4box, subtitle

**Comment by rbouqueau** [comment] 2015-10-07 08:38
I understand it makes things easier, but we previously came to a different conclusion: https://github.com/gpac/gpac/issues/48#issuecomment-72638816

Opinions?

**Comment by sandersaares** [comment] 2015-10-07 08:46
[DASH-IF IOP](http://dashif.org/wp-content/uploads/2015/10/DASH-IF-IOP-v3.1.pdf) table 18 lists `application/mp4` as the correct MIME type for encapsulated TTML. I would say that is the most authoritative source on the topic.

**Comment by cconcolato** [comment] 2015-10-07 08:58
OK, it looks like I'm contradicting myself :( The problem is that subtitles are visual data but not video data, and the RFC uses both terms. Now if everyone agrees on `application/mp4`, the RFC should be updated. We'll bring the comment to MPEG for discussion.
