### ISSUE TITLE
force same number of segments for audio and video

### ISSUE THREAD

**Issue by evangeline123** [gpac/gpac#774] opened 2017-03-08 10:13 UTC
I am using ffmpeg and mp4box to create my dash videos. the segments that are created for audio and video are not the same in number, so it causes interrupts in playback. how can i force the same number of segments for audio and video?

here is my MP4Box command:

`MP4Box -dash 4000 -rap -dash-profile dashavc264:live -bs-switching no -url-template -segment-name %s_ -out dash/manifest.mpd 1000.mp4 2000.mp4 audio.mp4`

my ffmpeg command for video:

`ffmpeg -i video.mp4 -movflags faststart -r 24 -vcodec libx264 -preset medium -tune zerolatency -tune fastdecode -b:v 2000k -maxrate 2000k -bufsize 2000k -g 96 -an -s 1280*720 -ss 00:00:00 -t 00:02:00 2000.mp4`

ffmpeg command for audio:

`ffmpeg -i video.mp4 -movflags faststart -acodec libfdk_aac -b:a 128k -vn -ss 00:00:00 -t 00:02:00 audio.mp4`

with this command I have 31 audio segments and 41 video segments for a 2 minute video.

my gpac version is:
MP4Box - GPAC version 0.6.1-revrelease

**Comment by rbouqueau** [comment] 2017-03-08 10:49
Isn't this a duplicate of #771 which is already answered?

**Comment by evangeline123** [comment] 2017-03-08 10:54
i did that :duration but it didn't solve the problem and the video and audio length is the same

**Comment by rbouqueau** [comment] 2017-03-08 10:56
Can you please provide all the files and command-lines so that I can reproduce your issue?

**Comment by rbouqueau** [comment] 2017-03-08 10:57
PS: I mean the command-lines where you constraint the duration.

**Comment by evangeline123** [comment] 2017-03-08 11:03
command:
`MP4Box -dash 4000 -rap -dash-profile dashavc264:live -bs-switching no -url-template -segment-name %s_ -out dash/manifest.mpd 1000.mp4 2000.mp4 audio.mp4:duration=4`

and here is a sample video:

https://ufile.io/071a6

**Comment by evangeline123** [comment] 2017-03-08 13:28
I have tried the mp4box command with multiple videos and they all have this problem. video stops but audio keeps playing for a few seconds.

**Comment by rbouqueau** [comment] 2017-03-08 15:19
Your video encoding is not appropriate for your command-line. Please read http://gpac.io/2015/11/02/check-key-frame-alignment-with-mp4box/ and encode according to the blog articles mentioned there.

**Comment by rbouqueau** [comment] 2017-03-08 15:20
NB: log of RAP indices:
```
<SyncSampleEntry sampleNumber="1"/>
<SyncSampleEntry sampleNumber="97"/>
<SyncSampleEntry sampleNumber="193"/>
<SyncSampleEntry sampleNumber="263"/>
...
```

**Closed by rbouqueau** 2017-03-08 15:19 UTC
Labels: dash, duplicate, question

**Comment by evangeline123** [comment] 2017-03-08 15:34
I don't need to separate audio and video to create the dash in mp4box?

**Comment by rbouqueau** [comment] 2017-03-08 15:57
You do but there are also other constraints as well. Please read the documents mentioned above.

**Comment by evangeline123** [comment] 2017-03-09 07:36
the new command is:

`ffmpeg -i big.mp4 -movflags faststart -an -c:v libx264 -x264opts 'keyint=24:min-keyint=96:no-scenecut' -tune zerolatency -tune fastdecode -b:v 1000k -maxrate 1000k -bufsize 1000k -vf "scale=1280:720" output.mp4`

and the mp4box command is the same.

**Comment by rbouqueau** [comment] 2017-03-09 07:46
> ```-x264opts 'keyint=24:min-keyint=96:no-scenecut'```

This is the faulty part. We are willing to help but when we ask to follow some steps, please don't feel free to modify them along the way.

**Comment by evangeline123** [comment] 2017-03-09 07:50
you mean the keyint has to be 24?
