### ISSUE TITLE
Is it possible to mux longer m4a files with MP4Box that will play with low-spec SanDisk.

### ISSUE THREAD

**Issue by bat999** [gpac/gpac#598] opened 2016-07-27 15:36 UTC
Hi
I have a Sansa Clip Jam player that doesn't handle m4a files very well.
If I mux the aac files to m4a with FFmpeg it won't play them at all.
If I mux the aac files to m4a with mp4creator 1.6.1e-pre it will play them, but only if they are not more than 30 minutes duration.
If I mux the aac files to m4a with MP4Box it will play them, but only if they are not more than 11 minutes duration.
I have uploaded to MediaFire a 30 minute m4a file muxed with mp4creator that plays OK with the SandDisk "tester.m4a".
Is there a setting for MP4Box that will allow me to play longer files with the SanDisk?

**Comment by rbouqueau** [comment] 2016-07-27 16:25
Weird. Would you mind uploading the source instead?

The file you uploaded is perfectly fine.

**Comment by bat999** [comment] 2016-07-27 16:53
"The file you uploaded is perfectly fine."
Yes the "tester.m4a" file plays OK with the Sansa, it was muxed with mp4creator 1.6.1e-pre.

I've uploaded the 30 minute aac file "source.aac".

I've also uploaded the 30 minute m4a file muxed with MP4Box
aac@GPAC0.6.2-DEV-rev678-gd5bdf74-master 

"tester2.m4a".
The "tester2.m4a" file muxed with MP4Box won't play with the Sansa.

MP4Box -add source.aac -new tester2.m4a

**Comment by rbouqueau** [comment] 2016-07-27 17:13
All files seem sane. If mux it directly with GPAC, there are difference but nothing that could explain a special behaviour at 11mn or 30mn. Can the bug be reproduced aside from your Sansa player?

**Comment by bat999** [comment] 2016-07-27 17:25
There isn't a bug.
It's the crummy Sansa player that is badly designed.
It will play the 30 minute m4a file muxed by the old primitive mp4creator program.
It won't play the 30 minute m4a file muxed by the new sophisticated MP4Box program.

**Comment by rbouqueau** [comment] 2016-07-27 17:45
You could try to play with these options (one at a time):
```
	        " -flat                stores file with all media data first, non-interleaved\n"
	        " -no-sys              removes all MPEG-4 Systems info except IOD (profiles)\n"
	        "                       * Note: Set by default whith '-add' and '-cat'\n"
	        " -no-iod              removes InitialObjectDescriptor from file\n"
	        " -isma                rewrites the file as an ISMA 1.0 AV file\n"
	        " -ismax               same as \'-isma\' and removes all clock references\n"
	        " -3gp                 rewrites as 3GPP(2) file (no more MPEG-4 Systems Info)\n"
	        "                       * Note 1: some tracks may be removed in the process\n"
	        "                       * Note 2: always on for *.3gp *.3g2 *.3gpp\n"
	        " -ipod                rewrites the file for iPod\n"
	        " -psp                 rewrites the file for PSP devices\n"
```

**Comment by bat999** [comment] 2016-07-27 18:16
MP4Box -flat -add source.aac -new 1trial.m4a; \
MP4Box -no-sys -add source.aac -new 2trial.m4a; \
MP4Box -no-iod -add source.aac -new 3trial.m4a; \
MP4Box -isma -add source.aac -new 4trial.m4a; \
MP4Box -ismax -add source.aac -new 5trial.m4a; \
MP4Box -3gp -add source.aac -new 6trial.m4a; \
MP4Box -ipod -add source.aac -new 7trial.m4a; \
MP4Box -psp -add source.aac -new 8trial.m4a

No, none of these will play. :-(

I've uploaded...
1trial.m4a
2trial.m4a
3trial.m4a
4trial.m4a
5trial.m4a
6trial.m4a
7trial.m4a
8trial.m4a

**Comment by rbouqueau** [comment] 2016-10-10 10:43
We couldn't reproduce so likely won't fix... :/

**Closed by rbouqueau** 2016-10-10 10:43 UTC
Labels: help wanted, mp4box, wontfix
