### ISSUE TITLE
the movie freezed after a while in mp4client using mp4box -dash-live

### ISSUE THREAD

**Issue by reallxl** [gpac/gpac#379] opened 2016-01-19 07:16 UTC
hi,

I'm testing DASH live streaming under windows 7 64bit using
> gpac-0.5.2-DEV-rev1110-g9f2bf6e-master-x64

first I use mp4box with command line:
> mp4box -dash-live 10000 -mpd-refresh 6 -out {dir}\test.mpd -bs-switching no track1.mp4

then I use mp4client with command line:
> mp4client {dir}\test.mpd

I can see the movie playing, but after a little while, it would start to stutter, then simply freeze afterwards...
from console I see log like:
> [IsoMedia] Error opening new segment URL {dir}/track1_dash37.m4s at UTC 1453187376867: Requested URL is not valie or cannot be found
> [IsoMedia] Error opening new segment URL {dir}/track1_dash38.m4s at UTC 1453187376867: Requested URL is not valie or cannot be found
> [IsoMedia] Error opening new segment URL {dir}/track1_dash39.m4s at UTC 1453187376871: Requested URL is not valie or cannot be found

I thought my use case is basic and nothing special, but still met lots of problems to deal with...
help needed please...

**Comment by nguyen-viet-thanh-trung** [comment] 2016-01-19 10:50
Hi reallxl,
Could you please upload your file to our dropbox https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95 ?

**Comment by reallxl** [comment] 2016-01-19 11:00
hi nguyen-viet-thanh-trung,

i just uploaded 2 mp4 files, one is recorded by our own device,
the other one is simply downloaded from the website here: http://dash-mse-test.appspot.com/media.html

**Comment by nguyen-viet-thanh-trung** [comment] 2016-01-21 16:38
Hi reallxl,
You required DASH-ing with segment duration is 10 seconds (-dash-live 10000) while your GOP duration is 6 seconds. Consider reconfiguring your segment duration.

**Comment by rbouqueau** [comment] 2016-01-21 16:55
I even wrote a blog article to check this: https://gpac.io/2015/11/02/check-key-frame-alignment-with-mp4box/ in case it can help.

**Comment by reallxl** [comment] 2016-01-22 02:04
hi nguyen-viet-thanh-trung and romain,

thank you guys so much for the help, now the movie plays well with command line:
>mp4box -dash-live 6000 -mpd-refresh 6 -out {dir}\test.mpd -bs-switching no track1.mp4

but I still got console log like below sometimes
> [IsoMedia] Error opening new segment URL {dir}/track1_dash37.m4s at UTC 1453187376867: Requested URL is not valie or cannot be found

and the playback speed is quite weird, it acts like
accelerating for couple of frames, then freezing at one, then restart accelerating, freezing...loop
is it because some content (sample table boxes maybe?) in my mp4 file is incorrect?

**Comment by reallxl** [comment] 2016-01-22 02:14
ahh...the movie still got frozen in about 3~5 minutes

one another thing:
when I tried to play the content with dash.js, SEGMENTS_UNAVAILABLE_ERROR_CODE would be notified because it would come up with a range whose end is less than the start in its calcSegmentAvailabilityRange function

I can't really distinguish it might be a bug in dash.js or it's caused by some invalid information provided in the manifest...

**Comment by nguyen-viet-thanh-trung** [comment] 2016-01-25 10:47
Hi reallxl,
You simulated a live session by looping a mp4 file, but your input file is not aligned with segment duration. Therfore, your last segment have only 4.66 sec, but in MPD it's said that this segment have 6 sec. It wasted about 1.33 sec at the end of each loop which made a freezing. For time to time, you are more and more delayed and in the worst case, when client ask for the new segment, it was deleted from server, which caused the "Requested URL is not valie or cannot be found" error. Please try with a input aproximately 42 sec (7 segments) if it's better.

**Comment by rbouqueau** [comment] 2016-01-25 12:05
There is a ```:dur=VALUE``` in GPAC that can force the duration of the last segment for looping. Not all the players support it though.

**Comment by reallxl** [comment] 2016-01-26 01:57
hi nguyen-viet-thanh-trung and romain,
really thank you guys for pointing out the blind spot,
I believe that would set everything steady.
would give a try later and report back if this really saves the day
thank you again for your kind help

**Comment by reallxl** [comment] 2016-01-27 06:17
hi nguyen-viet-thanh-trung and romain,
now I use a source file consisted of 8 complete GOPs for DASH with command line:
>mp4box -dash-live 3000 -mpd-refresh 12 -out {dir}\test.mpd -bs-switching no live-12_track1.mp4

and mp4client would play smoothly!
but still, when I tried to play the content with dash.js,
SEGMENTS_UNAVAILABLE_ERROR_CODE would be notified.
and I noticed that it would come up with a range whose end is less than the start in its calcSegmentAvailabilityRange function

**Comment by reallxl** [comment] 2016-01-27 06:39
hi nguyen-viet-thanh-trung and romain,

after playing for a period, the movie would still get stuck...
>[IsoMedia] Error opening new segment URL {dir}/track1_dash37.m4s at UTC 1453187376867: Requested URL is not valie or cannot be found

my source file is as attached (it's definitely an mp4 file, modified to .txt just for uploading here)
[live-12_track1.txt](https://github.com/gpac/gpac/files/106148/live-12_track1.txt)
its fps is 20, GOPL is 60, and it has 480 frames in total, to my understanding, it should be well aligned.
so now I got quite confused :(

**Comment by nguyen-viet-thanh-trung** [comment] 2016-01-27 09:45
hi reallxl,
I could not reproduce your error. Could you please send me your log files in case of freezing.
for MP4Box: mp4box -dash-live 3000 -mpd-refresh 12 -out {dir}\test.mpd -bs-switching no live-12_track1.mp4 -logs dash@debug -lf mp4box.txt
for MP4Client: mp4client {dir}\test.mpd -logs dash:codec:sync@debug -lf mp4client.txt

**Comment by reallxl** [comment] 2016-01-27 10:47
hi nguyen-viet-thanh-trung,

here are the log files,
since it took a while before freezing (about a half), the file size just got quite crazy...
therefore I manually split it to upload here

[mp4box.txt](https://github.com/gpac/gpac/files/106411/mp4box.txt)
[mp4client_pt1.txt](https://github.com/gpac/gpac/files/106421/mp4client_pt1.txt)
[mp4client_pt2.txt](https://github.com/gpac/gpac/files/106418/mp4client_pt2.txt)
[mp4client_pt3.txt](https://github.com/gpac/gpac/files/106417/mp4client_pt3.txt)
[mp4client_pt4.txt](https://github.com/gpac/gpac/files/106419/mp4client_pt4.txt)
[mp4client_pt5.txt](https://github.com/gpac/gpac/files/106420/mp4client_pt5.txt)
[mp4client_pt6.txt](https://github.com/gpac/gpac/files/106422/mp4client_pt6.txt)
[mp4client_pt7_since404.txt](https://github.com/gpac/gpac/files/106423/mp4client_pt7_since404.txt)

**Comment by nguyen-viet-thanh-trung** [comment] 2016-01-27 15:08
hi reallxl,

Your problem is due to MP4Box rather than MP4Client: in your mp4box log you can see that before the generating of segment 529 you have: [DASH] Generating segments and MPD 83.696 seconds too late.
Of course, your client cannot get the segment in time. 
Unfortunally, I cannot reproduce this error here.  Did you reproduce it systematically ? Could you give us some informations (your OS, GPAC version, destination dashing folder capacity ...)
P.S: is your attached file same as your test file, because in your log input file 's name is live-12.mp4.

**Comment by reallxl** [comment] 2016-01-28 05:41
hi nguyen-viet-thanh-trung,

I also cannot reproduce the error today in exactly the same environment (win7 64bit, gpac-0.5.2-DEV-rev1110-g9f2bf6e-master-x64, "D:/nginx-1.8.0/html" with 37.7GB free space),
have no idea what's really going on out there...
sorry for the mis-used file in last reproductive trial... but I'm sure I did get the same error in my previous tries using live-12_track1.mp4

but still, there's noway to play the content in dash.js, the only thing came up is log messages like:
(I just manually add these console logs in the code)
>[calcPresTime] wall=2016-1-28 13:36:44 start=2016-1-28 13:4:44 shift=-4.248
>[calcSegAbleRange] check=1927.189 now=1915.473
>[calcSegAbleRange] start=1915.473=max(1915.473,0)
>[calcSegAbleRange] end=1912.4716777777778=(1915.473-3.001322222222222) periodEnd=1927.189 timeAnchor=1915.473
>notify ENAME_DATA_UPDATE_COMPLETED 2 [e.error.code === SEGMENTS_UNAVAILABLE_ERROR_CODE]
>notify SEGMENTS_UNAVAILABLE_ERROR_CODE end=1912.4716777777778 start=1915.473 calculate=undefined

**Comment by reallxl** [comment] 2016-01-29 09:57
hi nguyen-viet-thanh-trung,

after playing for about 2 days, finally the movie got frozen again...
I uploaded the logs to the sendspace here:
https://www.sendspace.com/filegroup/BZc54TKGXaxx02UXF50lAg

**Comment by rbouqueau** [comment] 2016-01-29 18:32
'MP4Box -dash-live' runs an explicit context that can be saved ('-dash-ctx'). You can also run the same as '-dash-live' without waiting for real-time with the '-ddbg-live' option (would replace '-dash-live').

If we have your source and context at the moment you encounter the issue, we can reproduce. If we can reproduce then we can solve.

These option would probably help a lot to debug these long run issues. Thanks.

**Comment by nguyen-viet-thanh-trung** [comment] 2016-02-01 12:44
Hi reallxl,

It should be fixed now. Could you please retry your test ?

**Comment by nguyen-viet-thanh-trung** [comment] 2016-02-04 09:19
Does it work well now ? I close this issue, re-open it if you need more

**Closed by nguyen-viet-thanh-trung** 2016-02-04 09:19 UTC
