### ISSUE TITLE
"gmem://%d@%p" is a way get data from memory or not

### ISSUE THREAD

**Issue by sfzy** [gpac/gpac#496] opened 2016-04-21 08:16 UTC
I want to put a h265 stream which made from a program I named it prog1, into mp4 file.
The prog1 produce the h265 stream and save it to file.
I want to put the h265 stream to mp4box and produce a mp4 file then save it.
But I found mp4box reads a file that had saved in storage device, if I can use mp4box reads the stream not from a file but from memory.
I found "gmem://%d@%p" in source code. Whether "gmem://%d@%p" means mp4box can get data from a memory address.
If "gmem://%d@%p" means mp4box can get data from a memory address, then gf_fopen(fileName, "rb"), now assumption fileName=gmem://100@AABB, gf_fopen while load  fopen(file_name, mode), and whether fopen will return NULL.
If the above , I takes a wrong way, how can I use mp4box not read data from a file but from another program produced data.

**Comment by rbouqueau** [comment] 2016-04-21 11:43
2 possibilities:
1) Either have input pipes #175 
2) Or write a programme that reads from memory. We have an example at https://github.com/gpac/gpac/blob/master/applications/testapps/fmp4demux/main.c

What do you think?

**Comment by sfzy** [comment] 2016-04-21 14:10
Thank you.
I think #175 is same to my condition.
I will read fmp4demux first try to understand it will take me a long time.

**Comment by rbouqueau** [comment] 2016-10-10 10:59
Ok. consider as a duplicate of #175 to avoid having too many issues open.

**Closed by rbouqueau** 2016-10-10 10:59 UTC
Labels: duplicate, mp4box, question
