### ISSUE TITLE
MP4box is unable to import the enhancement layer of an SHVC coded bitstream

### ISSUE THREAD

**Issue by amit89infotech** [gpac/gpac#448] opened 2016-03-07 21:37 UTC
I have an SHVC coded bitstream produced from SHM 7.0. When I use MP4box to import this stream, Only the base layer spatial resolution is imported. The enhancement layer spatial resolution is not imported. There is no error thrown during the command. However when the converted mp4 content is DASHed, The MPD has only the the base layer resolution as the maximum available resolution , though there are two representations. To make things clearer, I will outline the steps to reproduce the problem

1. Encode a standard test sequence using SHM7.0

2. Import it into MP4box using the following command
 

MP4Box -new -add path\PeopleOnStreet-2x7.bin:FMT=SHVC:fps=30:svcmode=splitnox path\POS73.mp4

result:
HEVC import - frame size 960 x 540 at 30.000 FPS
SHVC detected - 0 x 0 at 30.000 FPS
HEVC Import results: 150 samples (606 NALUs) - Slices: 10 I 0 P 290 B - 300 SEI - 1 IDR
Stream uses forward prediction - stream CTS offset: 3 frames
OpenGOP detected - adjusting file brand
Saving path\POS73.mp4: 0.500 secs Interleaving

3.  DASH the generated MP4 using
MP4Box -dash 4 -segment-name path\pos7  path\POS73.mp4

I dont encounter this problem when I have encoded a sequence using SHM4.1. This is the result of importing a SHM4.1 encoded stream into mp4box

HEVC import - frame size 1280 x 800 at 30.000 FPS
SHVC detected - 2560 x 1600 at 30.000 FPS
HEVC Import results: 8 samples (37 NALUs) - Slices: 2 I 0 P 14 B - 16 SEI - 1 IDR
Stream uses forward prediction - stream CTS offset: 2 frames
Saving C:\Amit\K2_SPDY\mp4BoxTest\POS41.mp4: 0.500 secs Interleaving

Thanks in Advance,
Regards,
Amit

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [yes ] I looked for a similar issue and couldn't find any.
- [ yes] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [yes ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by nguyen-viet-thanh-trung** [comment] 2016-03-08 19:09
Hi,
For SHM6 (or plus), please checkout our dev branch 'shm6'. Could you please give us your feedback so that we can improve it and merge to master

**Comment by amit89infotech** [comment] 2016-03-09 19:07
I still have the same problem. but I Think it maybe an issue with the
representation. When I DASH the content, I am able to view segments of
different sizes, which makes me believe that there are representations from
both the spatial resolution. However, when encoding using  SHM 8.0 and
above, MP4 box throws an exception "assertion failed in line 5851 in media
import.c".

I would like to get clarified on these things

1. Is the SHM6 from the dev branch is from this link
https://hevc.hhi.fraunhofer.de/svn/svn_SHVCSoftware/branches/SHM-6-dev/
2. Which version of SHM does MP4 box work best with

**Comment by nguyen-viet-thanh-trung** [comment] 2016-03-10 09:19
Sorry for this  ambiguity. I mean the SHM6 dev branch of GPAC: https://github.com/gpac/gpac/tree/shm6.
Could you please retry it ? BTw, can you share your file with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95. We will take an investigating.

 

> 1.

 Is the SHM6 from the dev branch is from this link

**Comment by mraulet** [comment] 2016-03-10 09:55
SHM latest developments are quite stable. It would be good to merge the branch in the trunk anyway.

Mickael

Sent by my iPhone

**Comment by amit89infotech** [comment] 2016-03-10 18:30
Hi,

I reproduced the same scenario on this dev branch of GPAC. However, I get
the same result. I have attached an image of my command prompt.
I have the following queries

1. Does Mp4 box support an AVC coded base layer in an SHVC stream?. When I
tried it, This resulted in an unhandled exception: read access violation.

2. For SHM 8.0 and above, there is an assertion failure "assertion failed
in line 5851 in media import.c".

**Comment by nguyen-viet-thanh-trung** [comment] 2016-03-10 18:55
Hi,

For my test, your uploaded file has one sample which contains only base layer (layer_id=0 temporal_id=0 size=286528). Is this correct ? Could you please upload a longer file ?

> 2. For SHM 8.0 and above, there is an assertion failure "assertion failed in line 5851 in media import.c".
In GitHub, line 5851 in media import.c is: 
if (max_temporal_id[layer_id] < temporal_id)
			max_temporal_id[layer_id] = temporal_id;
There is no assert !? Which version did you checkout ? Or have you got some modifications ?

**Comment by amit89infotech** [comment] 2016-03-10 19:14
These are the lines I am talking about

/*if we get twice the same SPS put it in the bitstream and set
array_completeness to 0 ...*/
else if (hevc.sps[idx].state & AVC_SPS_DECLARED) {
if (hevc.sps[idx].crc != gf_crc_32(buffer, nal_size)) {
copy_size = nal_size;
has_vcl_nal = GF_TRUE;
assert(spss);
spss->array_completeness = 0;
}
}
I have checked out the version from the link you have given me in this mail
https://github.com/gpac/gpac/tree/shm6.
media_import.c is the name of the file and it is in the media tools folder.
I have also attached the SHM 8.0 encoded stream.

The attached file has both base and enhancement layers and it has 150
frames encoded.
Please try to import the two uploaded streams in Mp4box and let me know
what you observe

Thanks,
Amit

**Comment by amit89infotech** [comment] 2016-03-10 19:44
This is the screenshot of the command prompt attached.

**Comment by nguyen-viet-thanh-trung** [comment] 2016-03-11 09:35
Hi,

I could import your stream without error. The output file has 2 tracks, 150 samples per track (see attached image). Please verify you use a good branch: git branch should point to shm6 rather than master.
For Dashing I confirmed there was an error, we'll fix it and tell you asap.
![mp4box1](https://cloud.githubusercontent.com/assets/10617871/13698541/ee7b16a0-e774-11e5-93d9-ccfea4f7abb0.PNG)
![mp4box2](https://cloud.githubusercontent.com/assets/10617871/13698542/ee8d8eac-e774-11e5-98e5-68a506d3ca0d.PNG)

**Comment by nguyen-viet-thanh-trung** [comment] 2016-03-11 13:04
It should be fixed now, could you please retry ?
FYI, I can generate a DASH stream, the mpd looks like this:
`<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M5.000S" maxSegmentDuration="PT0H0M0.033S" profiles="urn:mpeg:dash:profile:full:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>POS73_dash.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M5.000S">
  <AdaptationSet segmentAlignment="true" bitstreamSwitching="true" maxWidth="1920" maxHeight="1080" maxFrameRate="30" par="16:9" lang="und">
   <SegmentList>
    <Initialization sourceURL="POS73_dash_init.mp4"/>
   </SegmentList>
   <Representation id="1" mimeType="video/mp4" codecs="hev1.1.6.L150.0" width="960" height="540" frameRate="30" sar="1:1" startWithSAP="0" bandwidth="4067344">
    <SegmentList timescale="30000" duration="120">
     <SegmentURL media="dash/pos7_track1_1.m4s"/>
		...
     <SegmentURL media="dash/pos7_track1_150.m4s"/>
    </SegmentList>
   </Representation>
   <Representation id="1_2" mimeType="video/mp4" codecs="lhv1.0.0.L0.0" width="1920" height="1080" frameRate="30" sar="1:1" startWithSAP="0" bandwidth="8133667" dependencyId="1">
    <SegmentList timescale="30000" duration="120">
     <SegmentURL media="dash/pos7_track2_1.m4s"/>
		....
	 <SegmentURL media="dash/pos7_track2_150.m4s"/>
    </SegmentList>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>`

**Comment by nguyen-viet-thanh-trung** [comment] 2016-03-11 13:08
It should be fixed now, could you please retry it ?
FYI, I can generate a DASH stream, the MPD looks like it: (I renamed it to .txt for attaching)
[POS73_dash.txt](https://github.com/gpac/gpac/files/169094/POS73_dash.txt)

**Comment by amit89infotech** [comment] 2016-03-11 15:31
Thanks for the quick response. I wonder why I wasn't able to reproduce
this. Can you give me the link to the branch again, I ll make sure that I
have downloaded the right version..

Thanks,
Amit

**Comment by nguyen-viet-thanh-trung** [comment] 2016-03-11 15:47
HI,
1. First, make sure that you use the correct MP4Box: MP4Box -version should be sth like: MP4Box - GPAC version 0.6.2-DEV-rev59-gd4f06ad-shm6 (the last one is your current branch, it should be shm6 rather than master). If not, check your path to MP4Box.
2. Link to the branch: https://github.com/gpac/gpac/tree/shm6, click download zip to get archived file.
You can also clone from GitHub: git clone https://github.com/gpac/gpac.git then checkout this branch: git checkout shm6

Hope that it'll help you !

**Comment by amit89infotech** [comment] 2016-03-11 19:16
I was able to replicate the operations in the attached screen shots.
However, when I try to stream the segmented files using Mp4 client, I get a
stream setup failure in Osmo4

**Comment by nguyen-viet-thanh-trung** [comment] 2016-03-14 13:43
I think that you mix between 2 branchs: did you  use'shm6' for DASHing but 'master' for playback ?

**Comment by amit89infotech** [comment] 2016-03-14 16:30
Yes, I think I may have done that. Will make sure, I have shm6 for both.
Thank you.

**Comment by nguyen-viet-thanh-trung** [comment] 2016-03-15 10:13
Can we close this issue ?

**Closed** 2016-03-15 10:22 UTC
Labels: mp4box

**Comment by amit89infotech** [comment] 2016-03-15 14:35
Yea we can close it. Thanks
