### ISSUE TITLE
Windows 10 long path support

### ISSUE THREAD

**Issue by stax76** [gpac/gpac#1589] opened 2020-09-05 10:29 UTC
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I would like to request long path support in Windows 10. Currently, long paths don't work with long path prefix `\\?\` but only using 8.3 names. I would like to request native long path support that don't need a prefix or short name.

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#short-vs-long-names

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later

This is frequently requested by staxrip users:

https://github.com/staxrip/staxrip/wiki/Windows-10-long-path-support

**Comment by stax76** [comment] 2020-09-17 07:12
I would like to find out if a generic manifests is possible, as far as I know it is. I want to know in order to suggest it to other projects. Maybe you can try following as is without modification:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3" >
  <assemblyIdentity version="0.0.0.0" name="undefined"/>
  <description>WindowsExecutable</description>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
      <ws2:longPathAware>true</ws2:longPathAware>
    </windowsSettings>
  </application>
</assembly>
```

staxrip:
https://raw.githubusercontent.com/staxrip/staxrip/master/My%20Project/app.manifest

mkvtoolnix:
https://gitlab.com/mbunkus/mkvtoolnix/-/raw/main/src/extract/manifest.xml.erb

mpv:
https://raw.githubusercontent.com/mpv-player/mpv/master/osdep/mpv.exe.manifest

mpv.net:
https://raw.githubusercontent.com/stax76/mpv.net/master/mpv.net/app.manifest

**Comment by stax76** [comment] 2020-09-20 10:31
More info:

https://github.com/staxrip/staxrip/wiki/Windows-10-long-path-support

**Comment by aureliendavid** [comment] 2020-09-29 16:45
Hi, 

Thanks for the wiki page, it was very useful. 

I think I have something that works. I haven't done a ton of tests with long paths (mostly focused on non-regression), but something like this (with paths around 1300 chars long) seems to work now:

```sh
MP4Box -add "C:\Users\adavid\dev\gpac\filters\tests\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\counter_30s_audio.aac" -new "C:\Users\adavid\dev\gpac\filters\tests\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\longout.mp4"
```


Note that inside gpac, a lot of path objects are defined with a GF_MAX_PATH (=1024) limit so some operations might hit that limit before the windows limit.

**Comment by aureliendavid** [comment] 2020-10-01 11:44
@stax76 can you check it it's working for you (and close this issue if it's all ok)

thanks

**Comment by stax76** [comment] 2020-10-04 19:00
I usually don't make builds but wait for builds made by Patman.

**Comment by jeanlf** [comment] 2021-01-05 18:18
closing, reopen if needed

**Comment by stax76** [comment] 2021-01-05 19:56
I don't have permission to reopen it apparently.

I checked the executable with Resource Hacker, it's missing a necessary manifest flag, without this flag Win32 APIs you call will not support long path, you'll have to add a manifest with that flag.

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
    <assemblyIdentity type="win32" name="MP4Box" version="1.0.0.0"/>
    <application xmlns="urn:schemas-microsoft-com:asm.v3">
        <windowsSettings>
            <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>
        </windowsSettings>
    </application>
</assembly>
```

**Comment by stax76** [comment] 2021-01-05 21:10
Please reopen, I don't have permission to do so.

It still produces and error:

MP4Box 1.1.0-DEV-rev384-gf9e004333-x64-gcc10.2.0 Patman

D:\Projekte\VB\staxrip\bin\Apps\Support\MP4Box\MP4Box.exe -add "C:\Users\frank\long path video samples\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\fitness_temp\ID1 9ms German.aac:name= " -new "C:\Users\frank\long path video samples\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\fitness_temp\ID1 9ms German.m4a"

Cannot create directory "": last error 3
[Core] system failure for file opening of "\gpac_280_00006517_2" in mode "w+b": 0x00000005
Cannot open destination file C:\Users\frank\long path video samples\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\fitness_temp\ID1 9ms German.m4a: I/O Error

Please note that it has to be tested on Windows, I checked the manifest using Resource Hacker, and it's missing the long path flag, this much likely means that any Win32 API you call will not support long path. Manifest is necessary:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
    <assemblyIdentity type="win32" name="MP4Box" version="1.0.0.0"/>
    <application xmlns="urn:schemas-microsoft-com:asm.v3">
        <windowsSettings>
            <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>
        </windowsSettings>
    </application>
</assembly>
```

**Comment by jeanlf** [comment] 2021-01-06 08:45
@aureliendavid can you take a look ?

**Comment by aureliendavid** [comment] 2021-01-08 13:29
Hi @stax76 

The problem is that the changes I made only applies to the visual studio build and the official binaries. 

If I open mp4box.exe from https://download.tsi.telecom-paristech.fr/gpac/new_builds/win64/gpac-1.1.0-DEV-rev423-g37508607-master-x64.exe in Resource Hacker I do get this: 

![mp4boxmanifeset](https://user-images.githubusercontent.com/7168263/104020033-d25ddb80-51bc-11eb-936e-112a247b9886.png)

I would have to see how "Patman builds" are made (do you have a link?) but from the filename your mentioned I guess it is using mingw. I will look into how to enable long path support in our Makefile with mingw.

**Comment by stax76** [comment] 2021-01-08 13:52
Hello aureliendavid,

AFAIK @Patman86 is using mabs:

https://github.com/m-ab-s/media-autobuild_suite

@1480c1
@wiiaboo

**Comment by Patman86** [comment] 2021-01-08 14:06
I'm using mingw right!

**Comment by aureliendavid** [comment] 2021-01-08 14:09
Thanks I'll look into this. 

It looks like there are stuff about manifests that can be done with windres on mingw. 

If someone has a good doc about all that I'll take it but I'll try some things.

**Comment by aureliendavid** [comment] 2021-01-13 13:13
Ok I think 39a078f should solve this for mingw. 

It works for my tests, @stax76 I'll let you check your use cases and report back.

**Comment by aureliendavid** [comment] 2021-01-14 12:38
oops there was a typo in the previous commit, please use at least af9bc87 to test this feature

**Comment by stax76** [comment] 2021-01-14 20:09
Great news, thanks.

I'll test it as soon as @Patman86 makes a new build.

**Comment by stax76** [comment] 2021-01-16 14:38
It's causing a hang/freeze due to this code:

```
proc.Process.StartInfo.EnvironmentVariables("TEMP") = proj.TempDir
proc.Process.StartInfo.EnvironmentVariables("TMP") = proj.TempDir
```

Not sure if Windows, .NET Framework or MP4Box is responsible for the hang, happens only when the path exceeds 260 characters.

**Comment by stax76** [comment] 2021-01-16 18:25
@aureliendavid 

The problem with the temp folder is caused by MP4Box according to a test I made. So far I tested audio demux and mux and confirm that long paths are working now except when changing the temp folder. So it's almost done, thank you for working on it.

**Comment by jeanlf** [comment] 2021-01-17 09:14
Good news - could you detail the faulty test?

**Comment by stax76** [comment] 2021-01-17 09:42
If the env var TEMP and TMP on Windows have been changed to a path longer than 260 characters then MP4Box does not start processing and the process don't exit, it hangs.

To verify that MP4Box and not Windows or .NET is causing it, I changed TEMP and TMP for mkvmerge and here it worked correctly.

TEMP and TMP were changed in early days because MP4Box wrote large temp files to the system temp folder without deleting them afterwards, but maybe that has been fixed, in that case I could just remove the code.

**Comment by aureliendavid** [comment] 2021-01-18 15:35
well this is interesting.. 

it looks like the windows API function `GetTempPath()` hangs when both these conditions are true:
 1. the long path feature is enabled by manifest
 2. the TMP environmnent variable is longer that MAX_PATH (260)

the `GetEnvironmentVariable()` works under any of these conditions. 

this simple program hangs when 1 & 2 are true: 

```c
#include "windows.h"
int main()
{
    wchar_t tmp1[1024];
    GetEnvironmentVariable(L"TMP", tmp1, 1024); // this works ok 
    GetTempPath(1024, tmp1);                    // this hangs
}
```
(it also hangs without unicode and wide chars)

I haven't seen it mentioned anywhere from quickly googling (where can we even report bugs to microsoft?). 

I think we'll have to code our own `gf_get_temp_path()` using `GetEnvironmentVariable()`. [MSDN](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppatha) explains: 

> The GetTempPath function checks for the existence of environment variables in the following order and uses the first path found:
> 
>     The path specified by the TMP environment variable.
>     The path specified by the TEMP environment variable.
>     The path specified by the USERPROFILE environment variable.
>     The Windows directory.

**Comment by aureliendavid** [comment] 2021-01-18 17:12
hm I think this might be hitting some more fundamental limit of windows processes

If I run this in cmd.exe: 

```
> set TMP=C:\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
> calc
```

it hangs (and so does any other executable).

It looks like I can make it work within the visual studio debugger (although tmpfile() also hangs and would need to be replaced) but I can't run anything in a console so I don't even know how to test it for mingw for example.

**Comment by stax76** [comment] 2021-01-18 17:29
I guess long path is not supported everywhere in Windows.

I'll investigate if MP4Box still leaves large files in the temp folder.

Thank you for long path support, temp is not so important, issue can be closed.

**Comment by aureliendavid** [comment] 2021-01-18 17:36
> TEMP and TMP were changed in early days because MP4Box wrote large temp files to the system temp folder without deleting them afterwards, but maybe that has been fixed, in that case I could just remove the code.

@stax76 can you check that again? I think the cleanup is done properly in recent versions (if not can you detail your test?)

If you can do without the big TMP variable I'd happily mark this out of scope and a windows problem since it looks a pain to solve..

**Comment by aureliendavid** [comment] 2021-01-18 17:36
(sorry for the cross-post)

**Comment by aureliendavid** [comment] 2021-01-18 17:41
> Thank you for long path support, temp is not so important, issue can be closed.

feel free to open another issue if there are problems with temp files

**Closed by aureliendavid** 2021-01-18 17:41 UTC

**Comment by stax76** [comment] 2021-01-18 20:35
OK, I've removed the temp code now and hope it's fine, otherwise I will report it. Thanks again.
