### ISSUE TITLE
mpeg-dash video segments fail to load

### ISSUE THREAD

**Issue by evangeline123** [gpac/gpac#770] opened 2017-03-05 14:21 UTC
I have created my mpeg-dash file using this code:

`MP4Box -dash 4000 -rap -profile live -segment-name %s_ -frag-rap -out dash2/manifest.mpd 1500.mp4 700.mp4 audio.mp4`

and it is working fine until I seek in the video and then it starts to fail loading the segments.

any ideas why this is happening??

here is a live demo:
http://79.175.133.185/static/videos/main_dash/ondemand.html

**Comment by evangeline123** [comment] 2017-03-06 05:27
it seems like it is creating the segments only for half of the video. why is this happening?

**Comment by rbouqueau** [comment] 2017-03-06 08:33
This issue will be marked as invalid if you don't provide all the requested information. Thank you.

**Comment by jeanlf** [comment] 2017-07-17 15:30
closing since no details available to reproduce

**Closed by jeanlf** 2017-07-17 15:30 UTC
