### ISSUE TITLE
[MP4Box] [DASH] [iOS] Wrong playback speed and the broken media player timeline.

### ISSUE THREAD

**Issue by vladimir-kazakov** [gpac/gpac#234] opened 2015-09-08 12:21 UTC
Hi!

While creating DASH on-demand media using MP4Box (GPAC version 0.5.2-DEV-rev575-geedd2f0-master) for some iOS media player, I noticed following issues:

* The video playback speed is wrong. Depending on media, it may be either too fast or too slow. At the same time, the audio plays (sounds) at its normal speed.
* The timeline of the media player is broken. The media player shows it like there's a lot of content. So, when the media ends, there's still a lot of space to the right.

What's interesting, Google's eDash packager (https://github.com/google/edash-packager) produces DASH media that plays correctly. This points to the fact that MP4Box is doing something wrong. I've tried to find out what may cause such issues, and I noticed following issues in MP4Box. Test media with logs can be found here: http://1drv.ms/1JPg0t8. (I also use mp4dump for inspecting media, which comes from Bento4.)

1. After dashing the media, durations of the movie ('moov/mvhd') and the track ('moov/trak/tkhd') are being reset to 0. You may see it in /MP4Box/mp4box.info.video.txt and /MP4Box/mp4dump.video.txt. The media player that I use uses this information, and because of that is not able to display the timeline correctly. In the /Source folder, you may see logs that show that before dashing in MP4Box, durations are present.

1. "MP4Box -info" with eDash media, looses durations mentioned in (1). You can see it by looking at /eDash/mp4box.info.video.txt. This seems like another bug in MP4Box, because the /eDash/mp4dump.video.txt shows that durations are there. So, it's just MP4Box shows them as zeroes.

**Comment by rbouqueau** [comment] 2015-09-08 15:02
Thanks for reporting.

First, both content play well with the GPAC MP4Client player.

I am not at the office, so I couldn't submit the content to the conformance checker at http://www.dashif.org/conformance.html. Did you have the opportunity to test the content?

The content seems fine with both packager.

What is the player you try to play with? How can we reproduce your bug?

**Comment by vladimir-kazakov** [comment] 2015-09-09 07:17
Unfortunately, I can't share any information about the player. But let's forget about it for a moment - you still can reproduce the issue by using MP4Box only. Here are steps to reproduce the issue:

1. Take the info of the original file produced by FFmpeg (or see the `/Source/mp4box.info.video.txt`): `mp4box -info /Source/360p-400k.mp4`. You can see that durations in the "movie info" and the "track info" are present: `Timescale 1000 - Duration 00:00:52.209`, `Track # 1 Info - TrackID 1 - TimeScale 12288 - Media Duration 00:00:52.208`, etc.

2. Create DASH on-demand version using MP4Box: `mp4box -dash 2000 -rap -profile "dashavc264:onDemand" -bs-switching no /Source/360p-400k.mp4 /Source/audio-128k.m4a -out /MP4Box/sintel.mpd`. Take the info of the video file the same way as in the step 1 (or see the `/MP4Box/mp4box.info.video.txt`). As you can see, durations are set to 0, which seems wrong: `Timescale 1000 - Duration 00:00:00.000`, `Track # 1 Info - TrackID 1 - TimeScale 12288 - Media Duration 00:00:00.000`, etc.

3. In the step 2, durations are 0 not only in the info that MP4Box shows, but also in the media itself (see the `/MP4Box/mp4dump.video.txt`). Seems like everything is correct. But if we will take info of the eDash media, then MP4Box will show zero durations as well (see the `/eDash/mp4box.info.video.txt`). But that's wrong, since media has durations set (see the `/eDash/mp4dump.video.txt`).

Speaking of the step 2, you may say that it's okay, since other media players are able to play such media, but it seems wrong to kill such information, even if it may not be used by some players.

Speaking of the DASH-IF validator, it shows that the check of the representation 1 fails (see the `/MP4Box/dash-if.validator.txt`). Although it doesn't seem like a related issue. Anyway, I doubt that this validator validates media thoroughly.

**Comment by rbouqueau** [comment] 2015-09-09 16:33
Thanks for the detailed report.

Durations at '0' are expected for fragmented files. DASHed files from any other muxer will have the same characteristics. However you'll see that MP4Box also gives you the sum of the duration of the fragments:
```
MP4Box -info MP4Box/360p-400k_dashinit.mp4
* Movie Info *
        Timescale 1000 - Duration 00:00:00.000
        1 track(s)
        Fragmented File: yes - duration 00:00:52.209
27 fragments - 1 SegmentIndexes
        File suitable for progressive download (moov before mdat)
        File Brand iso5 - version 1
        Created: UNKNOWN DATE   Modified: UNKNOWN DATE
File has no MPEG4 IOD/OD

iTunes Info:
        Encoder Software: Lavf57.0.100
1 UDTA types: meta (1)

Track # 1 Info - TrackID 1 - TimeScale 12288 - Media Duration 00:00:00.000
Track has 1 edit lists: track duration is 00:00:00.000
Media Info: Language "und (und)" - Type "vide:avc1" - 0 samples
Fragmented track: 1253 samples - Media Duration 00:00:52.208
```

> Anyway, I doubt that this validator validates media thoroughly.

The DASH-IF validates the media files too, at least at the file format level.

We need to reproduce your issue to go further. Can't you reproduce it with any other player?

**Comment by vladimir-kazakov** [comment] 2015-09-10 11:38
> Durations at '0' are expected for fragmented files. DASHed files from any other muxer will have the same characteristics.

Is such behavior a requirement? Could you point me to the spec that describes which values should be used? I've tried looking at ISO/IEC 14496-12 (2012), but I don't see any descriptions of this logic there.

> DASHed files from any other muxer will have the same characteristics.

Well, as we can see, eDash doesn't reset anything to 0. Moreover, it updates the movie timescale, and sets it to the same value as the track timescale. My experiments show that when the timescale is synchronized, this solves the issue of the wrong playback speed in this particular player.

So, I was thinking that maybe MP4Box could also do something like this, assuming that there's no any requirements in the spec that would prohibit such behavior.

> Can't you reproduce it with any other player?

Unfortunately, no :( Seems like only this particular player relies on some data from media that is missing while using MP4Box. When I produce DASH media using eDash, everything works fine. So, I was thinking that maybe something could be done to make the behavior of MP4Box more similar to the behavior of eDash (unless it really violates some spec). Using eDash is a bit problematic, since it works only on Linux. It would be nice if MP4Box could produce DASH media that would work in this particular player as well.

**Comment by rbouqueau** [comment] 2015-09-10 12:51
> Is such behavior a requirement? Could you point me to the spec that describes which values should be used?

That in MPEG DASH (ISO/IEC 23009-1 2nd edition, 6.2.2): ```The Initialization Segment shall not contain any media data with an assigned presentation time.```

So the tables from the ```moov``` are all set to zero.

Recently, we added the computation of the total fragments (```moof```) for MP4Box. That's the duration you see with ```MP4Box -info``` :)

> Well, as we can see, eDash doesn't reset anything to 0.

It seems it does:
```
E:\Users\rbouqueau\Documents\Works\gpac\234>MP4Box -info eDash\360p-400k_dashinit.mp4
* Movie Info *
        Timescale 12288 - Duration 00:00:00.000
        1 track(s)
        Fragmented File: yes - duration 00:00:52.208
27 fragments - 1 SegmentIndexes
        File suitable for progressive download (moov before mdat)
        File Brand dash - version 0
        Created: GMT Tue Sep 08 11:00:56 2015
        Modified: GMT Tue Sep 08 11:00:56 2015

File has no MPEG4 IOD/OD

Track # 1 Info - TrackID 1 - TimeScale 12288 - Media Duration 00:00:00.000
Media Info: Language "und (und)" - Type "vide:avc1" - 0 samples
Fragmented track: 1253 samples - Media Duration 00:00:52.208
Visual Track layout: x=0 y=0 width=640 height=360
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 640 x 360
        AVC Info: 1 SPS - 1 PPS - Profile High @ Level 3
        NAL Unit length bits: 32
        Pixel Aspect Ratio 1:1 - Indicated track size 640 x 360
        SPS#1 hash: 4CB56C454FE3B93E30D7D2B6425805D02E55BD2D
        PPS#1 hash: F84447EBF61570BBEE3F9F184A7A189EAA14289D
Self-synchronized
        RFC6381 Codec Parameters: avc1.64001e
        No sync sample found
```

> My experiments show that when the timescale is synchronized, this solves the issue of the wrong playback speed in this particular player.

Ok that's a clue. You can try to use a different timescale with MP4Box:
``` -timescale VAL       sets movie timescale to VAL ticks per second (default is 600).```
or attached to the imported file if you want to modify a specific track:
```:timescale=TS     sets import timescale to TS```

Let me know if it helps.

> Unfortunately, no :( Seems like only this particular player relies on some data from media that is missing while using MP4Box. When I produce DASH media using eDash, everything works fine. So, I was thinking that maybe something could be done to make the behavior of MP4Box more similar to the behavior of eDash (unless it really violates some spec). Using eDash is a bit problematic, since it works only on Linux. It would be nice if MP4Box could produce DASH media that would work in this particular player as well.

We are really committed to solve your bug and we appreciate you keep on experimenting with MP4Box. At this stage it looks like we are looking for a workaround for your player.

**Comment by vladimir-kazakov** [comment] 2015-09-11 07:46
>> Well, as we can see, eDash doesn't reset anything to 0.

> It seems it does

No, it does not. Yes, MP4Box shows zero durations, but this is not true. This is what I was talking about in the step 3. The eDash media contains this information:

```javascript
{
    "name":"mvhd",
    "header_size":12,
    "size":108,
    "timescale":12288,
    "duration":641536,
    "duration(ms)":52208
}
```

```javascript
{
    "name":"tkhd",
    "header_size":12,
    "size":92,
    "enabled":1,
    "id":1,
    "duration":641536,
    "width":640.000000,
    "height":360.000000
}
```
So, durations are there, but MP4Box shows zeroes.

> You can try to use a different timescale with MP4Box

Interesting. I've tried using `-timescale` with different values (10000000 and 122880000), but it seems that nothing is changing in the output of `mp4box -info`. It doesn't matter what I specify, I still see that the movie timescale is 1000, and the track timescale is 12288. I expected that both had to be changed to a value that I specify.

> That in MPEG DASH (ISO/IEC 23009-1 2nd edition, 6.2.2): The Initialization Segment shall not contain any media data with an assigned presentation time.

But we're talking about the on-demand DASH media, which doesn't have an initialization segment. According to descriptions of segment types in 6.2, and the usage of `SegmentBase@indexRange` in MPD, this part should be called the "index segment". And in 6.2.4 I don't see any requirements to remove the movie and the track metadata.

Even if I'm wrong, 6.2.2 mentions "media data", which is stored in "mdat" boxes. But it doesn't make any sense for on-demand media, where all the data and metadata is in the one file. This is another pointer to the fact that this thing can't be called as "initialization segment".

> At this stage it looks like we are looking for a workaround for your player.

Well, I'm not a fan of workarounds for specific players, too. But currently it still seems to me that MP4Box is doing something wrong. Hopefully, with your help, we'll find out the truth :)

**Comment by rbouqueau** [comment] 2015-09-11 20:27
> No, it does not. Yes, MP4Box shows zero durations, but this is not true.

You're right, I didn't get your remark at first.

That's a difference between both files.

> But we're talking about the on-demand DASH media, which doesn't have an initialization segment. 

Actually it has an initialization segment, but in this case all the segments are part of a single-file. I think that's where there is an interpretation: I assume GPAC doesn't write the duration in this case to be aligned with the multiple-segment scheme. The notion of files for segments is arbitrary since you can equally split your onDemand content into multiple segments and keep it DASH-compliant. So what should the 'mvhd' or 'tkhd' duration be in the case we split into multiple files? What happens if we remove some segments (e.g. should we keep a wrong duration in the 'moov')?

I don't have the answer and it seems like a legitimate question. I note that putting zero by interpreting the initialization data solves all these questions. Does it make sense to you?

I didn't write it myself so I am going to ask the contributor.

We could generate a file with the correct duration for a test if we need to try this hypothesis.

**Comment by vladimir-kazakov** [comment] 2015-09-14 06:54
> So what should the 'mvhd' or 'tkhd' duration be in the case we split into multiple files?

Since both provide metadata for the movie and the track respectively, I see no reason to treat the "single file" and the "multiple files" cases differently. In all cases, metadata must be set to a proper value.

I don't see any requirement in ISO/IEC 14496-12 (2012) and ISO/IEC 23009-1 (2014) that durations in these boxes must be reset to 0 and are not important at all.

> What happens if we remove some segments (e.g. should we keep a wrong duration in the 'moov')?

Removing or adding segments changes media. Metadata that describes this media must be updated accordingly. This is what I would expect, and I don't see anything in specs that says that it shouldn't be like that.

> I note that putting zero by interpreting the initialization data solves all these questions. Does it make sense to you?

No, it does not. I don't understand why 0 is used with this special meaning. According to ISO/IEC 14496-12 (2012), 8.2.2.3 (duration of the movie):

`duration is an integer that declares length of the presentation (in the indicated timescale). This property is derived from the presentation's tracks: the value of this field corresponds to the duration of the longest track in the presentation. If the duration cannot be determined then duration is set to all 1s.`

So, my interpretation of this is:

* If the duration is unknown, the value is all 1s.
* Otherwise, the value is the duration of the longest track in the movie.
* 0 doesn't have any special meaning, so 0 means 0 (which sound weird that there's a movie with a 0 duration).
* The value is derived from the longest track in the movie, which means that if we change the duration of the longest track (by removing or adding segments), the duration of the movie must be updated.

Then, in 8.3.2.3 (duration of the track):

`duration is an integer that indicates the duration of this track (in the timescale indicated in the Movie Header Box). The value of this field is equal to the sum of the durations of all of the track’s edits. If there is no edit list, then the duration is the sum of the sample durations, converted into the timescale in the Movie Header Box. If the duration of this track cannot be determined then duration is set to all 1s.`

And again, unknown duration is all 1s, not 0. And 0 doesn't have any special meaning. 0 is 0, not something like "go and find this info somewhere else".

What's interesting, MP4Box already sets the duration of the fragmented movie in the `moov/mvex/mehd`, which doesn't follow your previous assumption that:

> That in MPEG DASH (ISO/IEC 23009-1 2nd edition, 6.2.2): `The Initialization Segment shall not contain any media data with an assigned presentation time.` So the tables from the moov are all set to zero.

Which additionally points to the fact that MP4Box has different behaviors in different places that actually must be treated the same way.

Also, speaking of your question about removing segments, in this case, `mehd` won't be updated as well. But, of course, resetting it to 0 is not an option, because 0 is 0.  And 6.2.2 in ISO/IEC 23009-1 actually doesn't say anything about metadata. It mentions "media data", and 6.3.3 further clarifies what does it mean:

`The tracks in the "moov" box shall contain no samples (i.e. the entry_count in the "stts", "stsc", and "stco" boxes shall be set to 0), and the "moov" box is thus small.`

MP4Box already does it, so no problems here. But MP4Box must not do the same for metadata of the movie and the track.

Moreover, the same chapter in the DASH spec says:

`The "mvex" box shall be contained in the "moov" box to indicate that the client has to expect movie fragments. The "mvex" box also sets default values for the tracks and samples of the following movie fragments.`

Okay, yes, MP4Box does it already, but I guess there's another issue exists: the default sample duration in the `moov/mvex/trex` is set to 0, which seems also wrong. This info is also metadata, and must match the same value as defined in the `moov/traf/tfhd`.

**Comment by cconcolato** [comment] 2015-09-14 10:05
I think you missed an important sentence in the ISOBMFF spec (Track Header Box definition 8.3.2.1):
> The duration field here does not include the duration of following movie fragments, if any, but only of the media in the enclosing Movie Box. The Movie Extends Header box may be used to document the duration including movie fragments, when desired and possible.

So what MP4Box does is perfectly valid according to the spec. You should file a bug with eDASH as what they are doing is not valid. You should also fix the player to look for the information in the duration information in the `mehd` box.

Regarding:
>the default sample duration in the moov/mvex/trex is set to 0, which seems also wrong

That information is superseded by the information in the `tfhd`, so having 0 may not be a problem. Anyway we do set them, unless the Smooth Streaming compatible mode is asked, see:
https://github.com/gpac/gpac/blob/236c5f8122d2cda5ff506fafd12bc53713d7038c/src/media_tools/dash_segmenter.c#L1040-L1047

Regarding:
>Interesting. I've tried using -timescale with different values (10000000 and 122880000), but it seems that nothing is changing in the output of mp4box -info. It doesn't matter what I specify, I still see that the movie timescale is 1000, and the track timescale is 12288. I expected that both had to be changed to a value that I specify.

I cannot reproduce the problem. I tried: 
```
 MP4Box -timescale 50000 360p-400k.mp4 -out a.mp4
```
and the timescale was changed from 1000 to 50000. Can you provide more information?

**Comment by vladimir-kazakov** [comment] 2015-09-15 13:26
> I cannot reproduce the problem. I tried: `MP4Box -timescale 50000 360p-400k.mp4 -out a.mp4` and the timescale was changed from 1000 to 50000. Can you provide more information?

Example command showed me that I was using it incorrectly. I was using it while dashing the media, expecting that the dashed media will use the new timescale. But when I do it like in your example, it works. Although I have more questions related to this feature:

* I noticed that the timescale changes only in the "moov". Is it correct behavior? I was expecting it to be updated everywhere.
* It seems that there's a precision issue. My test media - Sintel trailer - consists of 1253 frames. There are 24 frames per second. So, let's say, I want to use the 12288 timescale. It means that the duration of the media is 1253 / 24 = 52.2083(3), and in the target timescale it is 52.2083(3) * 12288 = 641436. But MP4Box sets it to 641544. And when I produce DASH media with such video, the playback speed is still broken in the iOS player that I use, although now it's not smooth, but the picture is "jumping" (switches between far frames), freezing, etc. When I force the timescale in FFmpeg, then it fixes the playback speed and the video is playing without any glitches.

> I think you missed an important sentence in the ISOBMFF spec (Track Header Box definition 8.3.2.1)

I can't find this quote in the ISOBMFF spec. Which version do you have? I'm using the 4th edition (2012-07-15).

> That information is superseded by the information in the tfhd, so having 0 may not be a problem. Anyway we do set them, unless the Smooth Streaming compatible mode is asked

I was using the following command: `mp4box.exe -dash 2000 -rap -profile "dashavc264:onDemand" -bs-switching no 360p-400k.mp4 audio-128k.m4a -out sintel.mpd`, and it is set to 0, as you may see if you'll take a look at the media that I provided. As far as I understand, since the command doesn't have anything related to Smooth Streaming compatibility, this mode is not used, right? Then why there's 0?

And then again, we're talking about 0 as being some magic number that means "go and find the real value somewhere else", but I still don't see anything in the specs that would explicitly give such a definition to the 0 value.

**Comment by cconcolato** [comment] 2015-09-15 15:26
>I noticed that the timescale changes only in the "moov". Is it correct behavior? I was expecting it to be updated everywhere.

This is the correct behavior. `-timescale` changes the movie timescale (updating the movie duration, the track duration values expressed in this timescale, the edit list entries). If you want change the track timescale (aka media timescale), you have to do it during the import such as:
```
MP4Box -add input.mp4:timescale=1000 -timescale 1000 input.mp4
```
This will import the input file, make a track whose timescale is 1000 and set as well the movie timescale to 1000.

>It seems that there's a precision issue.

Indeed, changing the timescale of a track shouldn't affect its duration in seconds (or marginally given the precision). I've created a separate issue #247 to track that bug.

> I can't find this quote in the ISOBMFF spec. Which version do you have?

The text I quoted is part of the first corrigendum: 14496-12:2012/Cor.1:2013. Available here: http://www.iso.org/iso/home/store/catalogue_tc/catalogue_detail.htm?csnumber=63525
Note that there are 3 other corrigenda and 3 additional amendments: 
http://www.iso.org/iso/home/store/catalogue_tc/catalogue_detail.htm?csnumber=61988
A new 5th edition is about to be released.

> Then why there's 0?

If I run your command line, and then do `MP4Box -diso 360p-400k_dashinit.mp4`, you can see the following two lines:
```
...
<TrackExtendsBox SampleDescriptionIndex="1" SampleDuration="0" SampleSize="0" TrackID="1">
...
<TrackFragmentHeaderBox BaseDataOffset="moof" SampleDuration="512" TrackID="1">
...
```
The value 0 in the TraxkExtendsBox ('trex') is superseded by the local value 512 in the TrackFragmentHeaderBox ('tfhd'). So the value 0 is not wrong.
If you look at the [DASHIF guidelines](http://dashif.org/wp-content/uploads/2015/04/DASH-IF-IOP-v3.0.pdf), it says (p.8 l21):
> Default parameters and flags shall be stored in movie fragments (‘tfhd’ or ‘trun’ box) and not track headers (‘trex’ box) 

MP4Box follows that. We could possibly use the values in both places (tfhd and trex), this wouldn't hurt but would not be strictly compliant to the DASHIF guidelines.

I believe we can close this bug.

**Comment by Uragawa** [comment] 2015-09-15 16:04
Hello @vladimir-kazakov, I'm also having issues on iOS (and I have reason to suspect we're talking about the same player) with content processed by MP4Box. As far as I'm concerned, the problem to boils down to two separate issues:
* the client MP4 parser ignores ```trex```, where it should get default sample durations from;
* the client MP4 parser assumes that the timescale in ```mvhd``` is usable everywhere, which is not true as ```mdhd``` has per-track timescales (if it really is the same player, you'll have to implement ```mdhd```).

Check that either isn't your case.

@cconcolato That's interesting about ```tfhd```, because my content has no sample durations in ```trun```, no defaults in ```tfhd``` and as I mentioned the client-side parser's ignoring ```trex```, where the defaults really were, was a key part of the problem. According to a colleague who is more closely involved with content processing, ```MP4Box -version``` outputs:
```MP4Box - GPAC version 0.5.2-DEV-rev31-g8804e05-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: (static configuration file)
Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG```

**Comment by cconcolato** [comment] 2015-09-16 20:44
@Uragawa It makes sense that you have a problem if your content and player behavior is as you describe. I don't understand if you want MP4Box to do anything different and why the version of MP4Box matters here. Can you clarify?

**Comment by Uragawa** [comment] 2015-09-16 21:13
@cconcolato Sorry, just reporting a behaviour that seemed different from what MP4 should be doing, though I re-read your post and Smooth Streaming compatibility mode may have something to do with my content's being like that (I don't have access to the script with the exact command line but it's highly likely to be enabled).

**Comment by cconcolato** [comment] 2015-09-17 07:28
Thanks. I'm closing this issue, as I don't think there is any problem with MP4Box. If this is the case, open a new issue describing the bug or the feature-request.

**Closed by cconcolato** 2015-09-17 07:28 UTC
Labels: bug, player (mp4client/osmo)
