### ISSUE TITLE
Crash when using utcs option in dasher with another string than 'inband'

### ISSUE THREAD

**Issue by ricardollovera** [gpac/gpac#1594] opened 2020-09-11 22:28 UTC
[crash.zip](https://github.com/gpac/gpac/files/5211706/crash.zip)
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. (version 1.1.0-DEV-rev17-gc6ca4f2-master)
- [x] I give enough information for contributors to reproduce my issue https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Hi,

I was trying to produce LL DASH.
Whenever I add the last option with some value other than 'inband' as string I have Segmentation fault. BTW, in the documentation it is not well explained an example where it can be produced the mpd with the wanted utctiming tag (my aim).

`gpac -h | grep version
gpac -r -i /var/www/html/onDemand/videos/30min_countdown.mp4#video reframer:rt=on @ -o http://localhost:8091/experiment_gpac_public/master.mpd \
 --asto=7 --buf=-1000 --cdur=1 --segdur=8 --tsb=180 \
 --cors=true --dmode=dynamic --loop=true --profile=live --rdirs=/var/www/html \
 --reqlog=GET --sreg=true --stl=false --title=ONLY-VIDEO-NO-BEEP-AUDIO --tpl=true --utcs=inband`

This is the backtrace:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f70fb5ffbf9 in gf_dm_sess_process () from /usr/local/lib/libgpac.so.10
(gdb) bt
#0  0x00007f70fb5ffbf9 in gf_dm_sess_process () from /usr/local/lib/libgpac.so.10
#1  0x00007f70fb9d840a in dasher_switch_period.constprop () from /usr/local/lib/libgpac.so.10
#2  0x00007f70fb9da94e in dasher_process () from /usr/local/lib/libgpac.so.10
#3  0x00007f70fb9bb0d8 in gf_filter_process_task () from /usr/local/lib/libgpac.so.10
#4  0x00007f70fb9ab42c in gf_fs_thread_proc () from /usr/local/lib/libgpac.so.10
#5  0x00007f70fb9aeb00 in gf_fs_run () from /usr/local/lib/libgpac.so.10
#6  0x000000000040c351 in gpac_main ()
#7  0x00007f70fb180731 in __libc_start_main (main=0x403f20 <main>, argc=24, argv=0x7ffcd31762a8, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcd3176298) at ../csu/libc-start.c:289
#8  0x0000000000403f59 in _start ()

**Segmentation fault      (core dumped and ATTACHED)**

**Comment by jeanlf** [comment] 2020-09-14 07:58
hmm I cannot reproduce here, this could be source related - could you upload your source video ?

**Comment by ricardollovera** [comment] 2020-09-28 17:17
Hi,

Here you go: https://www.mediafire.com/file/6th23z75ywvjiwz/30min_countdown.mp4/file

Hope you're doing fine. Please take a look about the question of my aim, and the syntax clarification too :) 

Br,

**Comment by jeanlf** [comment] 2020-09-29 17:55
still cannot reproduce on mac, will try on linux - does it crash right away ?

**Comment by ricardollovera** [comment] 2020-09-29 19:00
Hi,
Linux Fedora 24. No. Not right away.
Best,

**Comment by ricardollovera** [comment] 2020-09-30 11:02
Hi, I confused with another crash when answering your question. Yes, right away whenever you put other weird value than inband. I mispelled. Yes I am on linux.
Sorry If the other message distracted.

**Comment by jeanlf** [comment] 2020-09-30 14:57
now fixed, I also added in the dasher help a section on dynamic manifest offering. Thanks for the report

**Closed by jeanlf** 2020-09-30 14:57 UTC
