### ISSUE TITLE
DASH HEVC 4k Streaming

### ISSUE THREAD

**Issue by mrgilchen** [gpac/gpac#281] opened 2015-10-13 12:02 UTC
Hi,
We have Origin server supporting DASH HEVC 4k Streaming.
However the gpac client doesn't play the stream very well, the video is corrupted, sometimes there are lags, you can see some images overlay of strange frames while playing.
Not all content we go is able to play.
Is there anyway to fix those issues or debug them?

**Comment by rbouqueau** [comment] 2015-10-13 13:06
Does the stream pass the conformance checker? dashif.org/conformance.html

**Comment by mrgilchen** [comment] 2015-10-13 14:37
XLink resolving is ok.
MPD validation and Schematron validation has X
mpd error log has !

Well, it does play somehow...
What can we do with that info?

**Comment by mrgilchen** [comment] 2015-10-13 14:39
Attached is the manifest. change extension to txt.


Attached is the manifest.

![manifest](https://cloud.githubusercontent.com/assets/15105363/10457981/3f5c48d8-71d1-11e5-88f2-6b13346a6030.jpg)

**Comment by rbouqueau** [comment] 2015-10-13 16:27
I am sorry, I don't understand any of your two last messages. Could you format them properly and check your attachements?

**Comment by mrgilchen** [comment] 2015-10-13 16:29
![dash_validator](https://cloud.githubusercontent.com/assets/15105363/10461149/a8ebcca6-71e0-11e5-810c-dbe73235ed35.JPG)

**Comment by mrgilchen** [comment] 2015-10-13 16:29
I'm trying to attach the manifest but it fails.

**Comment by mrgilchen** [comment] 2015-10-13 16:30
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" type="static" mediaPresentationDuration="PT11M39S" minBufferTime="PT4S">
<Period duration="PT11M39S" start="PT0S">
<AdaptationSet id="2" group="2" segmentAlignment="true" contentType="video" mimeType="video/mp4" maxWidth="1920" maxHeight="1080" maxFrameRate="29" startWithSAP="1">
<ContentComponent contentType="video" id="2"/>
<Representation id="1" bandwidth="2457690" mimeType="video/mp4" codecs="hvc1.1.2.L120.b0" width="1920" height="1080">
<BaseURL>MissUSA_HD_AAC_2.0.ts-1436778692945.ts_2.mp4</BaseURL>
<SegmentBase indexRange="763-2474">
<Initialization range="0-762"/>
</SegmentBase>
</Representation>
</AdaptationSet>
<AdaptationSet id="1" group="1" segmentAlignment="true" contentType="audio" mimeType="audio/mp4" startWithSAP="1">
<ContentComponent contentType="audio" id="1"/>
<Representation id="2" bandwidth="192092" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000">
<BaseURL>MissUSA_HD_AAC_2.0.ts-1436778692945.ts_0.mp4</BaseURL>
<SegmentBase indexRange="620-2331">
<Initialization range="0-619"/>
</SegmentBase>
</Representation>
<Representation id="2" bandwidth="192091" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000">
<BaseURL>MissUSA_HD_AAC_2.0.ts-1436778692945.ts_1.mp4</BaseURL>
<SegmentBase indexRange="620-2331">
<Initialization range="0-619"/>
</SegmentBase>
</Representation>
<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
</AdaptationSet>
<AdaptationSet id="3" group="3" segmentAlignment="true" mimeType="video/mp4" maxWidth="1920" maxHeight="1080" maxFrameRate="29" startWithSAP="1" maxPlayoutRate="29.97" codingDependency="false">
<Role schemeIdUri="urn:mpeg:dash:role:2011" value="alternative"/>
<EssentialProperty schemeIdUri="http://dashif.org/guidelines/trickmode" value="1"/>
<Representation id="1" bandwidth="2457690" mimeType="video/mp4" codecs="hvc1.1.2.L120.b0" width="1920" height="1080">
<BaseURL>MissUSA_HD_AAC_2.0.ts-1436778692945.ts_2_I.mp4</BaseURL>
<SegmentBase indexRange="763-2474">
<Initialization range="0-762"/>
</SegmentBase>
</Representation>
</AdaptationSet>
</Period>
</MPD>

**Comment by mrgilchen** [comment] 2015-10-14 18:20
someone can help?

**Comment by rbouqueau** [comment] 2015-10-14 18:53
If the MPD is not compliant, it doesn't seem absurd that the GPAC client is not able to play it.

Have tried to read the error messages from the conformance checker? It will tell you why it failed.

**Comment by mrgilchen** [comment] 2015-10-14 18:54
Hi,
It is playing, I don't think it's dash related, but more HEVC problems.
When doing seek, the client freeze, must kill it.
Gil.

**Comment by rbouqueau** [comment] 2015-10-14 18:59
I don't understand your issue anymore. If it is HEVC related, why don't you try to remux your content into a single MP4 file and play it back? It would remove the DASH layer.

**Comment by mrgilchen** [comment] 2015-10-14 19:01
It's an Origin server packaging to DASH on the fly. The video codec is HEVC multi bitrates.
The purpose is to play the stream on mobile/STB.

**Comment by mrgilchen** [comment] 2015-10-14 19:03
We have many issues with the client.
For example, here is a URL for live dash Stream with H264 video.
It doesn't play while it does play on other clients like DASHIF, Akamai.
http://31.154.18.73:5555/sdash/LIVE%24live/5.mpd/Manifest?start=LIVE&end=END&device=DASH

Gil.

**Comment by rbouqueau** [comment] 2015-10-14 19:24
This manifest doesn't pass the DASH conformance checker. Don't you think it may be related to the issue you experiment?

**Comment by mrgilchen** [comment] 2015-10-14 19:26
No, since issues are minor. It also play well on other public clients.

**Comment by rbouqueau** [comment] 2015-10-14 19:33
> No, since issues are minor.

We don't have the same interpretation here. The DASH manifest is incorrect, there are red crosses displayed. What makes you think this is minor?

**Comment by mrgilchen** [comment] 2015-10-14 19:33
Since it play fine on other clients.
Can you please explain what is wrong with it?
Gil.

**Comment by rbouqueau** [comment] 2015-10-14 20:11
I am closing since the issue seems unrelated to GPAC. Please re-open when you have fixed your DASH compliance issues. Thanks.

**Comment by cconcolato** [comment] 2015-10-14 20:17
It seems that the validator has problems downloading the MPD (and thus cannot check it). This has something to do with & in the URL I think.
Using wget (with escaping) I could download the MPD. I then added a BaseURL and tried to play it with MP4Client. MP4Client does not play. The DASH debug logs seems to indicate a mismatch in timing.

**Comment by cconcolato** [comment] 2015-10-14 20:33
The MPD is however not valid according to ITEC's validator. Removing the publishTime and the AudioChannelConfiguration improves validation but then there are issues such as: 

> The d attribute of a SegmentTimeline shall not exceed the value give bei the MPD maxSegmentDuration attribute.

That's the case for the audio representations.

Removing the audio from the MPD does not solve the issue. It looks as if the timestamps in the file do not match the MPD. Not sure.

Anyway, the problem is more in the content than in MP4Client... closing again

**Closed by cconcolato** 2015-10-14 20:33 UTC
Labels: invalid

**Comment by mrgilchen** [comment] 2015-10-14 20:49
It's a live stream manifest, it will not play offline on your client.
The manifest is pretty fine as like I said before, it's working fine on other clients.

**Comment by mrgilchen** [comment] 2015-10-14 21:00
How do I know what are the exact issues according to validator?

**Comment by adetheprince** [comment] 2015-11-14 02:27
Thanks rbouqueau

Using dash.js is not either playing the MPD file like the demo on dash.js example html.
Is this issue on how the m3u8 translated using with dash mp4box or is something else?.
I am almost there guys.
And how do you validate the mpd? sorry total noob here.

**Comment by mrgilchen** [comment] 2015-11-30 12:45
The conformance now pass fine. HEVC is still not playable.
Anyone can help??

**Comment by mrgilchen** [comment] 2015-11-30 13:38
http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/Manifest?start=LIVE&end=END&device=DASH_6_10

This is the URL.

**Comment by rbouqueau** [comment] 2015-11-30 15:59
When I try to play, I am getting trouble with the URLs:
```
E:\Users\rbouqueau>MP4Client "http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/Manifest?start=LIVE&end
=END&device=DASH_6_10"
Using config file in E:\Users\rbouqueau\AppData\Roaming\GPAC directory
System info: 8086 MB RAM - 8 cores
Modules Found : 32
Loading GPAC Terminal
Terminal Loaded in 50 ms
Opening URL http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/Manifest?start=LIVE&end=END&device=DASH_6
_10
Service Connected
[hevc @ 0000000000553560] nb threads_frame = 7, nb threads_slice 1, thread_type = frame
[hevc @ 000000000056a660] nb threads_frame = 7, nb threads_slice 1, thread_type = frame
[HTTP] Error parsing reply: Dialog Failure with remote peer for URL http://31.154.18.73:5555/sdash/L
IVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...wGf/QualityLevels(513802)/Fragments(video=)
[DASH] FAILED to download http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...
wGf/QualityLevels(513802)/Fragments(video=) = Dialog Failure with remote peer...
[DASH] Error in downloading new segment: http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF
82XzEwEgZU.v...wGf/QualityLevels(513802)/Fragments(video=) Dialog Failure with remote peer
[HTTP] Error parsing reply: Dialog Failure with remote peer for URL http://31.154.18.73:5555/sdash/L
IVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...wGf/QualityLevels(32000)/Fragments(audio_483_und=)
[DASH] FAILED to download http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...
wGf/QualityLevels(32000)/Fragments(audio_483_und=) = Dialog Failure with remote peer...
[DASH] Error in downloading new segment: http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF
82XzEwEgZU.v...wGf/QualityLevels(32000)/Fragments(audio_483_und=) Dialog Failure with remote peer
[HTTP] Error parsing reply: Dialog Failure with remote peer for URL http://31.154.18.73:5555/sdash/L
IVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...wGf/QualityLevels(513802)/Fragments(video=)
[DASH] FAILED to download http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...
wGf/QualityLevels(513802)/Fragments(video=) = Dialog Failure with remote peer...
[DASH] Error in downloading new segment: http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF
82XzEwEgZU.v...wGf/QualityLevels(513802)/Fragments(video=) Dialog Failure with remote peer
[HTTP] Error parsing reply: Dialog Failure with remote peer for URL http://31.154.18.73:5555/sdash/L
IVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...wGf/QualityLevels(32000)/Fragments(audio_483_und=)
[DASH] FAILED to download http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...
wGf/QualityLevels(32000)/Fragments(audio_483_und=) = Dialog Failure with remote peer...
[DASH] Error in downloading new segment: http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF
82XzEwEgZU.v...wGf/QualityLevels(32000)/Fragments(audio_483_und=) Dialog Failure with remote peer
[HTTP] Error parsing reply: Dialog Failure with remote peer for URL http://31.154.18.73:5555/sdash/L
IVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...wGf/QualityLevels(513802)/Fragments(video=)
[DASH] FAILED to download http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...
wGf/QualityLevels(513802)/Fragments(video=) = Dialog Failure with remote peer...
[DASH] Error in downloading new segment: http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF
82XzEwEgZU.v...wGf/QualityLevels(513802)/Fragments(video=) Dialog Failure with remote peer
[HTTP] Error parsing reply: Dialog Failure with remote peer for URL http://31.154.18.73:5555/sdash/L
IVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...wGf/QualityLevels(32000)/Fragments(audio_483_und=)
[DASH] FAILED to download http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...
wGf/QualityLevels(32000)/Fragments(audio_483_und=) = Dialog Failure with remote peer...
[DASH] Error in downloading new segment: http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF
82XzEwEgZU.v...wGf/QualityLevels(32000)/Fragments(audio_483_und=) Dialog Failure with remote peer
[HTTP] Error parsing reply: Dialog Failure with remote peer for URL http://31.154.18.73:5555/sdash/L
IVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...wGf/QualityLevels(513802)/Fragments(video=)
[DASH] FAILED to download http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...
wGf/QualityLevels(513802)/Fragments(video=) = Dialog Failure with remote peer...
[DASH] Error in downloading new segment: http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF
82XzEwEgZU.v...wGf/QualityLevels(513802)/Fragments(video=) Dialog Failure with remote peer
[HTTP] Error parsing reply: Dialog Failure with remote peer for URL http://31.154.18.73:5555/sdash/L
IVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...wGf/QualityLevels(32000)/Fragments(audio_483_und=)
[DASH] FAILED to download http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...
wGf/QualityLevels(32000)/Fragments(audio_483_und=) = Dialog Failure with remote peer...
[DASH] Error in downloading new segment: http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF
82XzEwEgZU.v...wGf/QualityLevels(32000)/Fragments(audio_483_und=) Dialog Failure with remote peer
[HTTP] Error parsing reply: Dialog Failure with remote peer for URL http://31.154.18.73:5555/sdash/L
IVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...wGf/QualityLevels(513802)/Fragments(video=)
[DASH] FAILED to download http://31.154.18.73:5555/sdash/LIVE$HEVC/6.mpd/S!d2EJREFTSF82XzEwEgZU.v...
wGf/QualityLevels(513802)/Fragments(video=) = Dialog Failure with remote peer...
```

Could you fix this (or precise what your issue is) and come back please?

**Comment by mrgilchen** [comment] 2015-11-30 16:02
Your client ask for no segments duration:
Fragments(video=) 

It should be video=segment_time

**Comment by rbouqueau** [comment] 2015-11-30 16:41
Right. Let me check.

**Comment by rbouqueau** [comment] 2015-11-30 17:31
```availabilityStartTime="1970-01-01T00:00:00Z"``` seems wrong.

The conformance checker doesn't work for me with your URLs. Can you tell us how you did to proceed?

**Comment by mrgilchen** [comment] 2015-11-30 17:34
I download the manifest and open it in the conformance manually.

**Comment by mrgilchen** [comment] 2015-11-30 18:20
You are all off way, I don't think the problem is related to manifest at all.
I suspect this is regarding the video code itself which is H265 and the GPAC decoded doesn't work well to decode.

**Comment by jeanlf** [comment] 2015-12-01 16:32
something is wrong in the timing here. 
1- When computing live edge, local UTC is way ahead of what is listed in the segment timeline
2- when fetching the (first sample - first rep - first AS), I get a presentation time (sample DTS+CTS_offset) very close to the presentationTimeOffset (a few thousands of seconds), whereas it should be much bigger, close to EPOCH since the AST is 1970-01-01T00:00:00Z and period start is 0

I believe presentationTimeOffset in your MPD is wrong it should be 0 (and playback works fine when forcing presentationTimeOffset to 0)

**Comment by mrgilchen** [comment] 2015-12-01 16:34
Well, this URL can be working fine in other clients as VisualON, Akami test and Dash Ref Clients.

**Comment by jeanlf** [comment] 2015-12-01 16:35
still I believe it is not compliant :)
is this stream working fine in these clients if you set presentationTimeOffset to 0 ?

**Comment by mrgilchen** [comment] 2015-12-01 16:37
Not sure where to set that, but we use the same link.

**Comment by mrgilchen** [comment] 2015-12-01 16:42
Well, let us try fix this to match the first segment and try again.
Thanks,
Gil.
