### ISSUE TITLE
Convert video by ffmpeg not working in chrome

### ISSUE THREAD

**Issue by Bluesky2112** [gpac/gpac#332] opened 2015-11-25 09:33 UTC
I'm a newbie in streaming with ffmpeg and Mp4box. I tried to find solution from some website:
http://sourceforge.net/p/gpac/discussion/287547/thread/bb9a9893/?limit=50
http://stackoverflow.com/questions/33773093/convert-video-by-ffmpeg-not-working-in-chrome
http://blog.streamroot.io/encode-multi-bitrate-videos-mpeg-dash-mse-based-media-players/
but I couldn't.
What did i do wrong? Please help me. Thanks alot
My input file is downloaded from youtube (.mp4 file).

I used command to get only video with format h264 (without sound) : 
``` 
$ ffmpeg -y -i "E:\SharingVideo\src\main\webapp\resources\video\input\input.mp4" -an -c:a libfdk_aac -ac 2 -ab 128k -c:v libx264 -x264opts 'keyint=24:min-keyint=24:no-scenecut' -b:v 1500k -maxrate 1500k -bufsize 1000k -vf "scale=-1:720" "E:\SharingVideo\src\main\webapp\resources\video\input\input_an.mp4"
```
 Cmd result:
```
ffmpeg version N-76224-ga7c5005 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 5.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
  libavutil      55.  4.100 / 55.  4.100
  libavcodec     57.  9.100 / 57.  9.100
  libavformat    57. 10.101 / 57. 10.101
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 12.100 /  6. 12.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.100 /  2.  0.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:\SharingVideo\src\main\webapp\resources\video\input\input.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01 00:00:00
    encoder         : Lavf52.94.0
  Duration: 00:02:29.95, start: 0.000000, bitrate: 1787 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 1629 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 1970-01-01 00:00:00
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 151 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01 00:00:00
      handler_name    : SoundHandler
[libx264 @ 000000821f5fbe40] using SAR=1/1
[libx264 @ 000000821f5fbe40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 000000821f5fbe40] profile High, level 3.1
[libx264 @ 000000821f5fbe40] 264 - core 148 r2638 7599210 - H.264/MPEG-4 AVC codec - Copyleft 2003-2015 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=24 keyint_min=13 scenecut=0 intra_refresh=0 rc_lookahead=24 rc=cbr mbtree=1 bitrate=1500 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=1500 vbv_bufsize=1000 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'E:\SharingVideo\src\main\webapp\resources\video\input\input_an.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.10.101
    Stream #0:0(und): Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=-1--1, 1500 kb/s, 29.97 fps, 30k tbn, 29.97 tbc (default)
    Metadata:
      creation_time   : 1970-01-01 00:00:00
      handler_name    : VideoHandler
      encoder         : Lavc57.9.100 libx264
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
Press [q] to stop, [?] for help
frame= 4494 fps= 38 q=-1.0 Lsize=   25050kB time=00:02:29.88 bitrate=1369.1kbits/s
video:25003kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.188374%
[libx264 @ 000000821f5fbe40] frame I:188   Avg QP:17.73  size: 40170
[libx264 @ 000000821f5fbe40] frame P:2060  Avg QP:23.64  size:  7302
[libx264 @ 000000821f5fbe40] frame B:2246  Avg QP:24.03  size:  1339
[libx264 @ 000000821f5fbe40] consecutive B-frames: 29.6%  8.4%  8.9% 53.1%
[libx264 @ 000000821f5fbe40] mb I  I16..4: 27.8% 64.1%  8.1%
[libx264 @ 000000821f5fbe40] mb P  I16..4:  5.4% 12.4%  0.3%  P16..4: 26.4%  4.3%  2.0%  0.0%  0.0%    skip:49.3%
[libx264 @ 000000821f5fbe40] mb B  I16..4:  0.2%  0.4%  0.0%  B16..8: 17.5%  0.7%  0.1%  direct: 0.9%  skip:80.2%  L0:41.5% L1:55.9% BI: 2.7%
[libx264 @ 000000821f5fbe40] 8x8 transform intra:66.9% inter:89.7%
[libx264 @ 000000821f5fbe40] coded y,uvDC,uvAC intra: 39.1% 57.7% 20.9% inter: 4.7% 10.1% 0.3%
[libx264 @ 000000821f5fbe40] i16 v,h,dc,p: 43% 29%  8% 20%
[libx264 @ 000000821f5fbe40] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 23% 21%  4%  5%  5%  5%  5%  5%
[libx264 @ 000000821f5fbe40] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 26%  9%  4%  8%  7%  7%  5%  4%
[libx264 @ 000000821f5fbe40] i8c dc,h,v,p: 49% 24% 20%  7%
[libx264 @ 000000821f5fbe40] Weighted P-Frames: Y:9.1% UV:8.9%
[libx264 @ 000000821f5fbe40] ref P L0: 74.5% 11.1% 11.0%  3.3%  0.1%
[libx264 @ 000000821f5fbe40] ref B L0: 91.0%  7.9%  1.1%
[libx264 @ 000000821f5fbe40] ref B L1: 96.4%  3.6%
[libx264 @ 000000821f5fbe40] kb/s:1365.92
```
Then i get audio from mp4 file:
```
ffmpeg -i "E:\SharingVideo\src\main\webapp\resources\video\input\input.mp4" -vn -acodec copy "E:\SharingVideo\src\main\webapp\resources\video\input\audio.mp4"
```
Cmd result:
```
$ ffmpeg -i "E:\SharingVideo\src\main\webapp\resources\video\input\input.mp4" -vn -acodec copy "E:\SharingVideo\src\mai
n\webapp\resources\video\input\audio.mp4"
ffmpeg version N-76224-ga7c5005 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 5.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
  libavutil      55.  4.100 / 55.  4.100
  libavcodec     57.  9.100 / 57.  9.100
  libavformat    57. 10.101 / 57. 10.101
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 12.100 /  6. 12.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.100 /  2.  0.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:\SharingVideo\src\main\webapp\resources\video\input\input.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01 00:00:00
    encoder         : Lavf52.94.0
  Duration: 00:02:29.95, start: 0.000000, bitrate: 1787 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 1629 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 1970-01-01 00:00:00
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 151 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01 00:00:00
      handler_name    : SoundHandler
[mp4 @ 0000000b967e30a0] Codec for stream 0 does not use global headers but container format requires global headers
Output #0, mp4, to 'E:\SharingVideo\src\main\webapp\resources\video\input\audio.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.10.101
    Stream #0:0(und): Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 151 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01 00:00:00
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=    2806kB time=00:02:29.86 bitrate= 153.4kbits/s
video:0kB audio:2780kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.933710%
```
After that, I created .mpd file by MP4box:
```
MP4Box -dash 10000 -profile onDemand -rap -out "E:\SharingVideo\src\main\webapp\resources\video\input\input_dash.mpd" "E:\SharingVideo\src\main\webapp\resources\video\input\input_an.mp4"#video:id=video_2Mb "E:\SharingVideo\src\main\webapp\resources\video\input\audio.mp4"#audio:id=audio
```
But in chrome it doesn't working:
```
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The video playback was aborted due to a corruption problem or because the video used features your browser did not support.
Video Element Error: MEDIA_ERR_DECODE
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The video could not be loaded, either because the server or network failed or because the format is not supported.
Video Element Error: MEDIA_ERR_SRC_NOT_SUPPORTED
```

**Comment by rbouqueau** [comment] 2015-11-25 11:38
The previous link you mention has been working: http://blog.streamroot.io/encode-multi-bitrate-videos-mpeg-dash-mse-based-media-players/

What is your OS and browser?

**Comment by Bluesky2112** [comment] 2015-11-25 14:53
My OS i windows 10 64bit, Chrome version: 46.0.2490.86

**Comment by Bluesky2112** [comment] 2015-11-28 09:02
Please help me, had I got mistake in this post?

**Comment by rbouqueau** [comment] 2015-11-28 09:48
Which player do you use? Does it work with GPAC/MP4Client?

**Comment by Bluesky2112** [comment] 2015-11-28 14:18
hi @rbouqueau, my mpd and file work well with MP4Client.
I have just change somes command with ffmpeg and it can play some minutes then stop, below is my video test, .bat file (include cmd with ffmpeg and mp4box) and dash.all.js, videojs-dash.js,... which I used (sorry because it a big file):
 https://drive.google.com/file/d/0B3QfkYnX_sKqUGZSLUMzdGwyWmc/view?usp=sharing
Would you mind if you help me to find the mistake? Thanks you lots.

**Comment by jeanlf** [comment] 2015-12-02 17:10
Playback is fine with GPAC, closing the issue. Have you asked the chrome guys their opinion on that problem ?

**Closed by jeanlf** 2015-12-02 17:10 UTC

**Comment by Bluesky2112** [comment] 2015-12-03 09:03
yes, please help me.

**Comment by Bluesky2112** [comment] 2015-12-03 09:04
my problem haven't had solution :(

**Comment by rbouqueau** [comment] 2015-12-03 09:16
Did you ask the Chrome devs since there is no issue with the GPAC player?

**Comment by thebeachtoday** [comment] 2017-02-09 01:45
--enable-libfreetype gives Chrome [and Firefox] issues when playing through VideoJS via FFMPEG.  If I remove --enable-libfreetype from the FFMPEG compilation/make, and leave everything else the same, it works fine.  Kinda stinks...hope to find the root cause later.
