### ISSUE TITLE
How to convert m3u8 into mpd file

### ISSUE THREAD

**Issue by andrewmabc** [gpac/gpac#290] opened 2015-10-20 07:33 UTC
https://gpac.wp.mines-telecom.fr/2012/02/01/dash-support/

I found MP4Box supports dash in above link. But the post is too old, and below command line can't work:

MP4Box -mpd test.mpd [-url-template] [http://...]myfile.m3u8

What's correct command line in current version to convert m3u8 into mpd file?

Thanks!

**Comment by jeanlf** [comment] 2015-10-20 08:39
to convert m3u8 to mpd:
MP4Box -mpd file.m3u8

to dash MP4 files:
MP4Box -dash DURATION -out test.mpd [-url-template] myfile.mp4

you cannot mix both ...

**Comment by Classsic** [comment] 2015-10-29 04:25
This feature doesn't work to me. Here is the file for tryit https://monitor-center.com/dashtest/hlsvod/test.m3u8 and the original file https://monitor-center.com/dashtest/mp4/test.mp4. I use the lastest MP4Box compile from git.
"MP4Box -mpd https://monitor-center.com/dashtest/hlsvod/test.m3u8  -out test.mpd".
The command for generate the m3u8 is:ffmpeg -i test.mp4 -c copy -flags -global_header -bsf h264_mp4toannexb -start_number 1 -hls_list_size 0  test.m3u8.
Thanks in advance.
Classsic.

**Comment by rbouqueau** [comment] 2015-10-29 07:35
I downloaded the .m3u8 and a few segments, shortened the .m3u8, launched mp4box and got this crash:
```
Failed to parse M3U8 File, it should start with #EXTM3U, but was : <MPD type="static" xmlns="urn:mpe
g:dash:schema:mpd:2011" xmlns:hls="urn:gpac:hls:aes:mpd:2015" profiles="urn:mpeg:dash:profile:full:2
011" id="test.m3u8" mediaPresentationDuration="PT751S" minBufferTime="PT1.5S">
[M3U8] Failed to parse root playlist 'test.m3u8', error = Media Channel couldn't be found
```

MP4CLient playback of remote m3u8 is ok.

**Comment by rbouqueau** [comment] 2015-10-29 08:48
@nguyen-viet-thanh-trung or @jeanlf The translated m3u8 looks incorrect. Since you're working on m3u8, could I ask you to have a look?

```
<?xml version="1.0"?>
<MPD xmlns="(null)" type="static" ID="test.m3u8" mediaPresentationDuration="PT00H00M14.00S" minBufferTime="PT00H00M1.50S">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>test.m3u8</Title>
  <Source>Generated from URL test.m3u8</Source>
  <Copyright>Generated by GPAC 0.5.2-DEV-rev649-g361314a-master from test.m3u8</Copyright>
 </ProgramInformation>
 <Period duration="PT00H00M0.00S">
  <AdaptationSet segmentAlignment="true">
   <Representation id="test.m3u8" bandwidth="341708" width="640" height="480" audioSamplingRate="44100" mimeType="video/mp2t" codecs="avc1.42801e,mp4a.40.02">
   <SegmentList xlink:href="test.m3u8" startNumber="0"/>
   </SegmentList>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

```

**Comment by rbouqueau** [comment] 2015-10-29 10:00
Thanks. I'll make the test later today.

**Comment by Classsic** [comment] 2015-10-29 15:36
I did try, the segments now appears in the mpd file, but the codecs parameter still is empty =
<?xml version="1.0"?>
<MPD xmlns="(null)" type="static" ID="tmp_main.m3u8" mediaPresentationDuration="PT00H12M32.00S" minBufferTime="PT00H00M1.50S">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>http://10.8.0.50:7676/hlsvod/test.m3u8</Title>
  <Source>Generated from URL http://10.8.0.50:7676/hlsvod/test.m3u8</Source>
  <Copyright>Generated by GPAC 0.5.2-DEV-rev756-g200c3c1-master from http://10.8.0.50:7676/hlsvod/test.m3u8</Copyright>
 </ProgramInformation>
 <Period duration="PT00H00M0.00S">
  <AdaptationSet segmentAlignment="true">
   <Representation id="test.m3u8" bandwidth="207590" width="640" height="480" audioSamplingRate="44100" mimeType="video/mp2t" codecs="">  <-------HERE
 <BaseURL >http://10.8.0.50:7676/hlsvod/</BaseURL>
   <SegmentList duration="15000" startNumber="0"/>
   <SegmentURL media="test1.mp4"/>
/>
-------------------------------------------------------------
and the format of chunks is mp4, as you can see.
Any other information you need, tellme and I share.
Thanks.

**Comment by rbouqueau** [comment] 2015-10-29 17:33
I confirm. I have:
```
<?xml version="1.0"?>
<MPD xmlns="(null)" type="static" ID="test.m3u8" mediaPresentationDuration="PT00H00M14.00S" minBufferTime="PT00H00M1.50S">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>test.m3u8</Title>
  <Source>Generated from URL test.m3u8</Source>
  <Copyright>Generated by GPAC 0.5.2-DEV-rev649-g361314a-master from test.m3u8</Copyright>
 </ProgramInformation>
 <Period duration="PT00H00M0.00S">
  <AdaptationSet segmentAlignment="true">
   <Representation id="test.m3u8" bandwidth="341708" width="640" height="480" audioSamplingRate="44100" mimeType="video/mp2t" codecs="avc1.42801e,mp4a.40.02">
   <SegmentList duration="5000" startNumber="0"/>
   <SegmentURL media="0.ts"/>
/>
   <SegmentURL media="1.ts"/>
/>
   <SegmentURL media="2.ts"/>
/>
   </SegmentList>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

MP4Client:
```
Opening URL test.mpd
[DASH] Error - cannot connect service: MPD parsing problem Invalid node stack: closing node is SegmentList but Representation was expected - Line 18: </SegmentL
[MPD_IN] Error - cannot initialize DASH Client for test.mpd: Requested URL is not valid or cannot be
 found
 Cannot open test.mpd: Requested URL is not valid or cannot be found
```

**Comment by nguyen-viet-thanh-trung** [comment] 2015-10-29 17:58
@Classsic  You don't specify the codec in your original m3u8, so while converting to mpd codecs field is empty. And the format of segments in your m3u8 is also mp2ts (test0.ts, test1.ts, ...)
@rbouqueau This error should be fixed now, could you please test it ?

**Comment by rbouqueau** [comment] 2015-10-29 18:09
Thank you. Better, but not there yet!
1) media segments names are incorrect in the MPD (0.ts instead of test0.ts)
2) there are additional '/>':
```
   <SegmentURL media="0.ts"/>
/>
   <SegmentURL media="1.ts"/>
/>
   <SegmentURL media="2.ts"/>
```

FYI M3U8 is:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:4.801000,
test0.ts
#EXTINF:4.818000,
test1.ts
#EXTINF:4.790000,
test2.ts
#EXT-X-ENDLIST
```

**Comment by Classsic** [comment] 2015-10-29 20:39
Right, I use ffmpeg to create m3u8 from mp4 file, how I can specify the codec in the ffmpeg command? Or I have to use another tool for create it?Thanks for attend this bug so fast.

**Comment by rbouqueau** [comment] 2015-10-30 15:42
@nguyen-viet-thanh-trung I confirm it works :) Thank you!

**Comment by adetheprince** [comment] 2015-11-11 07:12
Hi there
This is my first post and I think I am late to the show, but i have installed the Gpac from thier site and i have no error on the installation, so i am assuming it was successfully installed.
Now when I entered this 

MP4Box -mpd http://mydomain.com/Videos/testm3.m3u8 -out [http://mydomain.com/Videos/] testmp.mpd 

I got this error

 [M3U8] Cannot Open m3u8 file testmp.mpd for reading
[M3U8] Failed to parse root playlist 'testmp.mpd', error = Internal Service Error
Error converting M3U8 (testmp.mpd) to MPD ([http://mydomian.com/Videos/]): Internal Service Error.
I am using ubuntu and I have installed Gpac using the tutorial on their website.
Can anyone please tell me whats wrong?
Thanks

**Comment by rbouqueau** [comment] 2015-11-11 09:28
You can make MP4Box more verbose to get more info about the issue:
```
MP4Box -logs all@debug -mpd http://mydomain.com/Videos/testm3.m3u8 -out [http://mydomain.com/Videos/] testmp.mpd
```

See also http://gpac.io/2011/08/04/recent-evolutions-in-the-gpac-log-system/ and ```MP4Box -h```

**Comment by adetheprince** [comment] 2015-11-11 16:20
Hi the
Thanks for the quick reply, I am still having probs to locate the issue.
Can it be the Gpac i am using?
And also where can i see the Logs? I am totally noob when it comes to video Trans/Encos/Convert.

**Comment by rbouqueau** [comment] 2015-11-11 17:33
Can you show the command-line you typed, and the answer you see in your terminal please?

**Comment by adetheprince** [comment] 2015-11-12 04:38
I typed:

MP4Box -mpd http://satdoc.dyndns.info/Videos/testm3.m3u8 -out [hhttp://satdoc.dyndns.info/Videos/] testmp.mpd

I get

[M3U8] Cannot Open m3u8 file testmp.mpd for reading
[M3U8] Failed to parse root playlist 'testmp.mpd', error = Internal Service Error
Error converting M3U8 (testmp.mpd) to MPD ([hhttp://satdoc.dyndns.info/Videos/]): Internal Service Error


The file 
http://satdoc.dyndns.info/Videos/testm3.m3u8
is still there and active. File or link is playable on VLC. 
By the way this file is live TV channel (m3u8) that is for testing purpose, if there is anything wrong with the file then I can test other links, so can you test it your self?
Even with the log entered like this i get the same error sir. Please accept my apology for being a noob here.

**Comment by adetheprince** [comment] 2015-11-12 04:41
Sorry not hhttp://satdoc.dyndns.info/Videos/] testmp.mpd
but http://satdoc.dyndns.info/Videos/] testmp.mpd
still no joy.lol

**Comment by rbouqueau** [comment] 2015-11-12 07:23
@adetheprince You are probably not using the latest version (which crashes anyway).

**Comment by adetheprince** [comment] 2015-11-12 07:37
Any help on to get a working version as this installed was done through this tutorial.

sudo apt-get install gpac

Should I use other or can you recommend any working one please ?
I am sure its installed properly as no error occurred during installation, and I can confirm the version if you want.

**Comment by rbouqueau** [comment] 2015-11-12 08:08
Please follow this tutorial to build the latest MP4Box: http://gpac.io/2015/07/29/gpac-build-mp4box-only-all-platforms/

Someone will fix the issue separately.

**Comment by adetheprince** [comment] 2015-11-12 08:39
Ok I have already removed the old one and installed the Gpac before i got your reply, by downloading the Iso

libgpac-dev_0.5.2-DEV-rev984-g019f08d-master_amd64.deb

and install it .
but when I entered this now

MP4Box -mpd http://satdoc.dyndns.info/Videos/testm3.m3u8 -out [http://satdoc.dyndns.info/Videos/] testmp.mpd

I Got a new error
Error - 2 input names specified, please check usage

So I thought the names here are messed up , after removing  ( [ ) from the output, as well as new folder and entered this command
( MP4Box -mpd http://satdoc.dyndns.info/Videos/testm3.m3u8 -out http://satdoc.dyndns.info/readympd/testmp.mpd )

The error is gone but now a new one 

[Core] system failure for file opening of http://satdoc.dyndns.info/readympd/testmp.mpd in mode wb: 2
Done converting M3U8 (http://satdoc.dyndns.info/Videos/testm3.m3u8) to MPD (http://satdoc.dyndns.info/readympd/testmp.mpd)
Its says done!!, but no file in there at all ( http://satdoc.dyndns.info/readympd/testmp.mpd )

and hopefully you can help or is not a version issue here.
Thanks for your help sir, Very helpful person and responsive you are!.

**Comment by adetheprince** [comment] 2015-11-13 05:47
here are the logs mate, Can you see anything wrong?


[Mutex download_manager_cache_mx] At 1 Grabbed by thread Main Process
[Mutex download_manager_cache_mx] At 1 Released by thread Main Process
[HTTP] Connecting to satdoc.dyndns.info:80
[Sock_IPV6] Solving satdoc.dyndns.info address
[Sock_IPV6] Host satdoc.dyndns.info found
[Sock_IPV6] Connecting to satdoc.dyndns.info:80
[Sock_IPV6] Connected to satdoc.dyndns.info:80
[HTTP] Connected to satdoc.dyndns.info:80
[Socket] Set socket send buffer size to 131072
[Socket] Set socket receive buffer size to 131072
[Downloader] gf_dm_configure_cache(0xa4b420), cached=yes
[Mutex download_manager_cache_mx] At 3 Grabbed by thread Main Process
[Mutex download_manager_cache_mx] At 3 Released by thread Main Process
[CACHE] gf_cache_create_entry:441, entry=0xa4e240
[Mutex download_manager_cache_mx] At 3 Grabbed by thread Main Process
[Mutex download_manager_cache_mx] At 3 Released by thread Main Process
[CACHE] Cache setup to 0xa4b420 /tmp/gpac_cache_1A6A5D9976920943A84D32D58207548CC42F9B33.m3u8
[HTTP] Sending request at UTC 1447392327117 GET /Videos/testm3.m3u8 HTTP/1.1
Host: satdoc.dyndns.info
User-Agent: GPAC/0.5.2-DEV-rev983-g1f1085b-master
Accept: */*
Connection: Keep-Alive
Icy-Metadata: 1
If-None-Match: "5642d46a-5d"
If-Modified-Since: Wed, 11 Nov 2015 05:38:50 GMT



[HTTP] HTTP/1.1 304 Not Modified
Server: nginx/1.4.6 (Ubuntu)
Date: Fri, 13 Nov 2015 05:25:27 GMT
Last-Modified: Wed, 11 Nov 2015 05:38:50 GMT
Connection: keep-alive
ETag: "5642d46a-5d"


[Downloader] gf_dm_disconnect(0xa4b420)
[HTTP] Sending data to modules from /tmp/gpac_cache_1A6A5D9976920943A84D32D58207548CC42F9B33.m3u8...
[HTTP] all data has been sent to modules from /tmp/gpac_cache_1A6A5D9976920943A84D32D58207548CC42F9B33.m3u8.
[Downloader] gf_dm_disconnect(0xa4b420)
[Downloader] gf_dm_sess_del(0xa4b420)
[Downloader] gf_dm_sess_del(0xa4b420) : DONE
[Mutex download_manager_cache_mx] At 19 Grabbed by thread Main Process
[CACHE] gf_cache_delete_entry:780, entry=0xa4e240
[Mutex download_manager_cache_mx] At 19 Released by thread Main Process
Directive at line 2: "#EXTINF:-1, TRECE", attributes= [0]='-1,' [1]='TRECE'
[M3U8] declaring media segment http://200.76.77.237/LIVE/H01/CANAL102/PROFILE03.m3u8?iptv=%2F.ts
[MPD Generator] Not downloading, programs are identical for http://satdoc.dyndns.info:80/Videos/testm3.m3u8...
[MPD Generator] Playlist will be refreshed every -1 seconds, len=23
[Core] system failure for file opening of http://satdoc.dyndns.info/readympd/testmp.mpd in mode wb: 2
Done converting M3U8 (http://satdoc.dyndns.info/Videos/testm3.m3u8) to MPD (http://satdoc.dyndns.info/readympd/testmp.mpd)

**Comment by adetheprince** [comment] 2015-11-13 06:52
Hi there
Just followed this tutorial but still same error.

 http://gpac.io/2015/07/29/gpac-build-mp4box-only-all-platforms/

Anyone knows whats this error means.

[Core] system failure for file opening of http://mydomain.com/Videos/testmp.mpd in mode wb: 2 ?
Thanks everyone for helping.

**Comment by rbouqueau** [comment] 2015-11-13 07:38
@adetheprince You cannot write remotely to your HTTP server. You need to convert locally then upload (or make the operation locally on the HTTP server).

**Comment by adetheprince** [comment] 2015-11-13 09:28
Hi rbouqueau
I really thanks you for your reply again.
I have changed the input and out put without a link address so by typing 

Videos/testmp.mpd instated of  http://mydomain.com/Videos/testmp.mpd and this worked (the error disappear) but the file is not playing using using a website like http://dash-mse-test.appspot.com/dash-player.html  (not my own hosted player) so I am snot sure why? but it could be that player is not supported.
I am almost there, so need a good testing player or else someone check whats wrong with the mpdf created .
Thanks all.

**Comment by rbouqueau** [comment] 2015-11-13 09:59
Please read this comment to add back the right file hierarchy: https://github.com/gpac/gpac/issues/281#issuecomment-148182963

Also the player you use is not common. dash-player.com or dash.js or the GPAC MP4Client are free to use and more popular.

**Comment by jeanlf** [comment] 2015-11-19 14:12
closing since m3u8->mpd is ok - open a new issue if needed

**Closed by jeanlf** 2015-11-19 14:12 UTC
