### ISSUE TITLE
ICC colour profile not supported

### ISSUE THREAD

**Issue by combucha** [gpac/gpac#396] opened 2016-02-01 13:27 UTC
I had a file encoded with wrong AR. I wanted correct it with -par command.
Mp4box from rev1110 refused any operation on this file so I grabbed the newest 1175.
No succes + crash as bonus:
`ICC colour profile not supported
Saving wrong_ar.mp4: 0.500 secs Interleaving
ICC colour profile not supportedISOBMF: Error Feature Not Supported computing box colr size
ISOBMF: Error Feature Not Supported computing box avc1 size
ISOBMF: Error Feature Not Supported computing box trak size
ICC colour profile not supportedISOBMF: Error Feature Not Supported computing box colr size
ISOBMF: Error Feature Not Supported computing box avc1 size
ISOBMF: Error Feature Not Supported computing box trak size
ICC colour profile not supportedISOBMF: Error Feature Not Supported computing box colr size
ISOBMF: Error Feature Not Supported computing box avc1 size
ISOBMF: Error Feature Not Supported computing box trak size
Error: Feature Not Supported`

I assume it's caused by colrnclc field before stts at beginning of the file, injected by HandBrake.
Old mp4box (0.5.0) is smart and skip this, allowing working on such files, while new builds can't handle this...

**Comment by jeanlf** [comment] 2016-02-01 14:25
could you upload the broken file ?

**Comment by combucha** [comment] 2016-02-01 16:26
http://www83.zippyshare.com/v/w1RPdRkm/file.html

I've uploaded only 1MB of beginning, rest of clip is pure data (It's now broken^2 with incomplete box mdat). It was binary splitted so structure is non modified.

**Comment by jeanlf** [comment] 2016-02-03 17:24
hmm strange i cannot reproduce the bug, using
`MP4Box -par 1=3:2 source.mp4 -out test.mp4`

(of course patching MP4Box to deal with the truncated file), the rewriting of the PAR works fine. 

I just patched the code to keep unrecognized colour profiles, could you see if that helps ?

If not, would you have a complete file to test this ? With the patched version you should be able to keep the colour profile and create a smaller file (e.g. -add source.mp4:dur=10  )

**Comment by combucha** [comment] 2016-02-03 18:48
Issue fixed with newest commit. Thanks.

**Comment by combucha** [comment] 2016-02-03 20:36
Reopened to ask something. It's Colr Box Atom thing.

1. Original file (also that broken^2 binary cut):

`colr nclc 00 06 00 01 00 06`

2. Original file after mp4box par correction:

`colr 00 06 00 01 00 06` <--- Color parameter 'nclc' vanished

3.  Cut from original with -add source.mp4:dur=1 http://www23.zippyshare.com/v/qMho6iN0/file.html

`colr 00 06 00 00 00 14` <--- info says [iso file] Box "colr" size 10 invalid (read 12)


Wondering why nclc gone and what happened with further values in case no.3?

**Comment by jeanlf** [comment] 2016-02-04 07:48
indeed patch was incomplete - now fixed

**Closed by jeanlf** 2016-02-04 07:48 UTC
