### ISSUE TITLE
problem demuxing pcm

### ISSUE THREAD

**Issue by stax76** [gpac/gpac#796] opened 2017-04-11 09:38 UTC
log file and sample source file: https://forum.doom9.org/showthread.php?p=1803342&highlight=staxrip#post1803342

**Comment by rbouqueau** [comment] 2017-04-11 15:23
Thanks for the sample. Much appreciated :)

Duplicate of #732 . Closing.

**Closed by rbouqueau** 2017-04-11 15:23 UTC
Labels: duplicate, feature-request, mp4box

**Comment by stax76** [comment] 2017-04-12 08:21
Sorry, I didn't remember having reported the same thing before, I though it was a bug instead of a unsupported feature.

I check the output now and if it isn't a proper audio file I call the ffmpeg demuxing function instead.

**Comment by rbouqueau** [comment] 2017-04-12 09:31
No problem. I left it open with the hope to have a look to your samples. Thanks
