### ISSUE TITLE
Mp4box aac muxing broken

### ISSUE THREAD

**Issue by Selur** [gpac/gpac#1576] opened 2020-08-17 02:46 UTC
Using:
```
MP4Box - GPAC version 1.0.0-rev188-g2aa266dfa-ab-suite
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io
```
And the following calls:
1. extract audio:
```
ffmpeg -y -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:1 -vn -sn -acodec copy -map_metadata -1 -metadata encoding_tool="Hybrid 2020.08.14.1" "E:\Output\iId_1_aid_1_DELAY_-53ms_2020-08-17@04_20_16_1410_01.mp3"
```
```
ffmpeg version N-98737-g8a31850ebf-ga72d5290c5+3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.0 (Rev1, Built by MSYS2 project)
  configuration:  --cc='ccache gcc' --cxx='ccache g++' --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --disable-debug --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libaom --enable-libopenmpt --enable-version3 --enable-libsvtav1 --enable-libkvazaar --enable-libzmq --enable-libvmaf --enable-vapoursynth --enable-librav1e --enable-mbedtls --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB
  libavutil      56. 58.100 / 56. 58.100
  libavcodec     58.100.100 / 58.100.100
  libavformat    58. 51.100 / 58. 51.100
  libavdevice    58. 11.101 / 58. 11.101
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100

  Input #0, avi, from 'F:\TestClips&Co\files\test.avi':
  Metadata:
    ISGN            : Drama
    IRTD            : Unrated
    title           : Encoding TestClip
    artist          : AutorTest
    album           : Movie
    date            : Heute
    genre           : Documentary
    ISBJ            : downfall of Hitler 
    copyright       : CopyrightTest
    IKEY            : Hitler
    comment         : Kleiner Testclip den ich zum Testen verwende
    encoder         : VirtualDub build 29393/releaseNandub v1.0rc2
  Duration: 00:00:17.16, start: 0.000000, bitrate: 860 kb/s
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 640x352 [SAR 1:1 DAR 20:11], 723 kb/s, 25 fps, 25 tbr, 25 tbn, 25 tbc
    Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 123 kb/s

  Output #0, mp3, to 'E:\Output\iId_1_aid_1_DELAY_-53ms_2020-08-17@04_20_16_1410_01.mp3':
  Metadata:
    encoding_tool   : "Hybrid 2020.08.14.1"
    TSSE            : Lavf58.51.100
    Stream #0:0: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 123 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
Press [q] to stop, [?] for help

size=     254kB time=00:00:17.13 bitrate= 121.2kbits/s speed=6.87e+03x    
video:0kB audio:253kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.183642%
finished after 00:00:00.088
created E:\Output\iId_1_aid_1_DELAY_-53ms_2020-08-17@04_20_16_1410_01.mp3 (0.247646 MB)
```
2. convert audio:
```
ffmpeg -y -threads 8 -loglevel fatal -nostdin -i "E:\Output\iId_1_aid_1_DELAY_-53ms_2020-08-17@04_18_07_5110_01.mp3" -ac 2 -ar 48000 -acodec pcm_s16le -f wav - | neroAacEnc  -br 128000 -ignorelength -if - -of "E:\Output\iId_1_aid_1_DELAY_-53ms_2020-08-17@04_18_07_5110_02.aac"
```
```
************************************************************* * * * Nero AAC Encoder * * Copyright 2009 Nero AG * * All Rights Reserved Worldwide * * * * Package build date: Feb 18 2010 * * Package version: 1.5.4.0 * * * * See -help for a complete list of available parameters. * * * ************************************************************* Processed 0 seconds... Processed 1 seconds... Processed 2 seconds... Processed 3 seconds... Processed 4 seconds... Processed 5 seconds... Processed 6 seconds... Processed 7 seconds... Processed 8 seconds... Processed 9 seconds... Processed 10 seconds... Processed 11 seconds... Processed 12 seconds... Processed 13 seconds... Processed 14 seconds... Processed 15 seconds... Processed 16 seconds... Processed 17 seconds...
finished after 00:00:00.390
created E:\Output\iId_1_aid_1_DELAY_-53ms_2020-08-17@04_20_16_1410_02.aac (0.264829 MB)
```

3. convert video:
```
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p -vsync 0  -f yuv4mpegpipe - | NVEnc --y4m -i - --fps 25.000 --codec h265 --profile main --level auto --tier high --sar 1:1 --lookahead 16 --output-depth 8 --vbrhq 0 --vbr-quality 35.00 --max-bitrate 240000 --gop-len 0 --ref 3 --bframes 0 --no-b-adapt --mv-precision Q-pel --preset quality --colormatrix bt470bg --cuda-schedule sync --output "E:\Output\test_2020-08-17@04_18_07_5110_03.265"
```
```
--------------------------------------------------------------------------------
E:\Output\test_2020-08-17@04_20_16_1410_03.265
--------------------------------------------------------------------------------
NVEncC (x64) 5.13 (r1625) by rigaya, Jul 29 2020 13:52:13 (VC 1916/Win/avx2)
OS Version     Windows 10 x64 (19041)
CPU            AMD Ryzen 7 1800X Eight-Core Processor (8C/16T)
GPU            #0: GeForce GTX 1070 Ti (2432 cores, 1683 MHz)[PCIe3x16][451.67]
NVENC / CUDA   NVENC API 10.0, CUDA 11.0, schedule mode: sync
Input Buffers  CUDA, 32 frames
Input Info     y4m(yv12)->nv12 [AVX2], 640x352, 25/1 fps
Vpp Filters    copyHtoD
Output Info    H.265/HEVC main @ Level auto
               640x352p 1:1 25.000fps (25/1fps)
Encoder Preset quality
Rate Control   VBR
Multipass      2pass-full
Bitrate        0 kbps (Max: 240000 kbps)
Target Quality 35.00
Initial QP     I:20  P:23  B:25
VBV buf size   auto
Lookahead      on, 16 frames, Adaptive I Insert
GOP length     250 frames
B frames       0 frames [ref mode: disabled]
Ref frames     3 frames
AQ             off
CU max / min   auto / auto
VUI            matrix:bt470bg
Others         mv:Q-pel 
                                                                               
encoded 429 frames, 1311.93 fps, 148.48 kbps, 0.30 MB
encode time 0:00:00, CPULoad: 9.6
frame type IDR   3
frame type I     3,  total size  0.01 MB
frame type P   426,  total size  0.29 MB
finished after 00:00:01.274
created E:\Output\test_2020-08-17@04_20_16_1410_03.265 (0.303741 MB)
```

4. rename audio:
```
E:\Output\iId_1_aid_1_DELAY_-53ms_2020-08-17@04_18_07_5110_02.aac to E:\Output\iId_1_aid_1_ms_2020-08-17@04_18_07_5110_02.aac
```
5. mux audio and video:
```
MP4Box -add "E:\Output\test_2020-08-17@04_18_07_5110_03.265"#video:fps=25:delay=53:xps_inband:name="" -brand hev1 -add "E:\Output\iId_1_aid_1_ms_2020-08-17@04_18_07_5110_02.aac"#audio:name="":lang= -mpeg4 -itags tool="Hybrid 2020.08.14.1" -tmp "E:\Output" -new "E:\Output\2020-08-17@04_18_07_5110__05.mp4"
```
```
Track Importing HEVC - Width 640 Height 352 FPS 25000/1000 SAR 1/1
Import: |                    | (01/100)
Import: |                    | (03/100)
Import: |                    | (04/100)
Import: |=                   | (06/100)
Import: |=                   | (07/100)
Import: |=                   | (09/100)
Import: |==                  | (10/100)
Import: |==                  | (12/100)
Import: |==                  | (14/100)
Import: |===                 | (15/100)
Import: |===                 | (17/100)
Import: |===                 | (18/100)
Import: |====                | (20/100)
Import: |====                | (21/100)
Import: |====                | (23/100)
Import: |=====               | (25/100)
Import: |=====               | (26/100)
Import: |=====               | (28/100)
Import: |=====               | (29/100)
Import: |======              | (31/100)
Import: |======              | (32/100)
Import: |======              | (34/100)
Import: |=======             | (36/100)
Import: |=======             | (37/100)
Import: |=======             | (39/100)
Import: |========            | (40/100)
Import: |========            | (42/100)
Import: |========            | (43/100)
Import: |=========           | (45/100)
Import: |=========           | (47/100)
Import: |=========           | (48/100)
Import: |==========          | (50/100)
Import: |==========          | (51/100)
Import: |==========          | (53/100)
Import: |==========          | (54/100)
Import: |===========         | (56/100)
Import: |===========         | (58/100)
Import: |===========         | (59/100)
Import: |============        | (61/100)
Import: |============        | (62/100)
Import: |============        | (64/100)
Import: |=============       | (65/100)
Import: |=============       | (67/100)
Import: |=============       | (69/100)
Import: |==============      | (70/100)
Import: |==============      | (72/100)
Import: |==============      | (73/100)
Import: |===============     | (75/100)
Import: |===============     | (76/100)
Import: |===============     | (78/100)
Import: |================    | (80/100)
Import: |================    | (81/100)
Import: |================    | (83/100)
Import: |================    | (84/100)
Import: |=================   | (86/100)
Import: |=================   | (87/100)
Import: |=================   | (89/100)
Import: |==================  | (91/100)
Import: |==================  | (92/100)
Import: |==================  | (94/100)
Import: |=================== | (95/100)
Import: |=================== | (97/100)
Import: |====================| (100/100)
Import: |====================| (100/100)
Import: |====================| (100/100)
Import: |====================| (100/100)
Import: |====================| (100/100)
Import: |====================| (100/100)
Import: |====================| (100/100)
Import: |====================| (100/100)

HEVC Import results: 429 samples (433 NALUs) - Slices: 3 I 426 P 0 B - 0 SEI - 3 IDR
HEVC Max NALU size is 5875 - stream could be optimized by setting nal_length=2
IsoMedia import iId_1_aid_1_ms_2020-08-17@04_20_16_1410_02.aac - track ID 1 - Audio (SR 48000 - 2 channels)
Importing ISO File: |                    | (00/100)
Importing ISO File: |                    | (01/100)
Importing ISO File: |                    | (02/100)
Importing ISO File: |                    | (03/100)
Importing ISO File: |                    | (04/100)
Importing ISO File: |=                   | (05/100)
Importing ISO File: |=                   | (06/100)
Importing ISO File: |=                   | (07/100)
Importing ISO File: |=                   | (08/100)
Importing ISO File: |=                   | (09/100)
Importing ISO File: |==                  | (10/100)
Importing ISO File: |==                  | (11/100)
Importing ISO File: |==                  | (12/100)
Importing ISO File: |==                  | (13/100)
Importing ISO File: |==                  | (14/100)
Importing ISO File: |===                 | (15/100)
Importing ISO File: |===                 | (16/100)
Importing ISO File: |===                 | (17/100)
Importing ISO File: |===                 | (18/100)
Importing ISO File: |===                 | (19/100)
Importing ISO File: |====                | (20/100)
Importing ISO File: |====                | (21/100)
Importing ISO File: |====                | (22/100)
Importing ISO File: |====                | (23/100)
Importing ISO File: |====                | (24/100)
Importing ISO File: |=====               | (25/100)
Importing ISO File: |=====               | (26/100)
Importing ISO File: |=====               | (27/100)
Importing ISO File: |=====               | (28/100)
Importing ISO File: |=====               | (29/100)
Importing ISO File: |======              | (30/100)
Importing ISO File: |======              | (31/100)
Importing ISO File: |======              | (32/100)
Importing ISO File: |======              | (33/100)
Importing ISO File: |======              | (34/100)
Importing ISO File: |=======             | (35/100)
Importing ISO File: |=======             | (36/100)
Importing ISO File: |=======             | (37/100)
Importing ISO File: |=======             | (38/100)
Importing ISO File: |=======             | (39/100)
Importing ISO File: |========            | (40/100)
importing iso file
Importing ISO File: |========            | (41/100)
Importing ISO File: |========            | (42/100)
Importing ISO File: |========            | (43/100)
Importing ISO File: |========            | (44/100)
Importing ISO File: |=========           | (45/100)
Importing ISO File: |=========           | (46/100)
Importing ISO File: |=========           | (47/100)
Importing ISO File: |=========           | (48/100)
Importing ISO File: |=========           | (49/100)
Importing ISO File: |==========          | (50/100)
Importing ISO File: |==========          | (51/100)
Importing ISO File: |==========          | (52/100)
Importing ISO File: |==========          | (53/100)
Importing ISO File: |==========          | (54/100)
Importing ISO File: |===========         | (55/100)
Importing ISO File: |===========         | (56/100)
Importing ISO File: |===========         | (57/100)
Importing ISO File: |===========         | (58/100)
Importing ISO File: |===========         | (59/100)
Importing ISO File: |============        | (60/100)
Importing ISO File: |============        | (61/100)
Importing ISO File: |============        | (62/100)
Importing ISO File: |============        | (63/100)
Importing ISO File: |============        | (64/100)
Importing ISO File: |=============       | (65/100)
Importing ISO File: |=============       | (66/100)
Importing ISO File: |=============       | (67/100)
Importing ISO File: |=============       | (68/100)
Importing ISO File: |=============       | (69/100)
Importing ISO File: |==============      | (70/100)
Importing ISO File: |==============      | (71/100)
Importing ISO File: |==============      | (72/100)
Importing ISO File: |==============      | (73/100)
Importing ISO File: |==============      | (74/100)
Importing ISO File: |===============     | (75/100)
Importing ISO File: |===============     | (76/100)
Importing ISO File: |===============     | (77/100)
Importing ISO File: |===============     | (78/100)
Importing ISO File: |===============     | (79/100)
Importing ISO File: |================    | (80/100)
Importing ISO File: |================    | (81/100)
Importing ISO File: |================    | (82/100)
Importing ISO File: |================    | (83/100)
Importing ISO File: |================    | (84/100)
Importing ISO File: |=================   | (85/100)
Importing ISO File: |=================   | (86/100)
Importing ISO File: |=================   | (87/100)
Importing ISO File: |=================   | (88/100)
Importing ISO File: |=================   | (89/100)
Importing ISO File: |==================  | (90/100)
Importing ISO File: |==================  | (91/100)
Importing ISO File: |==================  | (92/100)
Importing ISO File: |==================  | (93/100)
Importing ISO File: |==================  | (94/100)
Importing ISO File: |=================== | (95/100)
Importing ISO File: |=================== | (96/100)
Importing ISO File: |=================== | (97/100)
Importing ISO File: |=================== | (98/100)
Importing ISO File: |=================== | (99/100)
Importing ISO File: |====================| (100/100)
importing iso file
;The given code is not a valid one: , using 'und' as 3-letter code
Saving E:\Output\2020-08-17@04_20_16_1410__05.mp4: 0.500 secs Interleaving
ISO File Writing: |                    | (00/100)
ISO File Writing: |                    | (01/100)
ISO File Writing: |                    | (02/100)
ISO File Writing: |                    | (03/100)
ISO File Writing: |                    | (04/100)
ISO File Writing: |=                   | (05/100)
ISO File Writing: |=                   | (06/100)
ISO File Writing: |=                   | (07/100)
ISO File Writing: |=                   | (08/100)
ISO File Writing: |=                   | (09/100)
ISO File Writing: |==                  | (10/100)
ISO File Writing: |==                  | (11/100)
ISO File Writing: |==                  | (12/100)
ISO File Writing: |==                  | (13/100)
ISO File Writing: |==                  | (14/100)
ISO File Writing: |===                 | (15/100)
ISO File Writing: |===                 | (16/100)
ISO File Writing: |===                 | (17/100)
ISO File Writing: |===                 | (18/100)
ISO File Writing: |===                 | (19/100)
ISO File Writing: |====                | (20/100)
ISO File Writing: |====                | (21/100)
ISO File Writing: |====                | (22/100)
ISO File Writing: |====                | (23/100)
ISO File Writing: |====                | (24/100)
ISO File Writing: |=====               | (25/100)
ISO File Writing: |=====               | (26/100)
ISO File Writing: |=====               | (27/100)
ISO File Writing: |=====               | (28/100)
ISO File Writing: |=====               | (29/100)
ISO File Writing: |======              | (30/100)
ISO File Writing: |======              | (31/100)
ISO File Writing: |======              | (32/100)
ISO File Writing: |======              | (33/100)
ISO File Writing: |======              | (34/100)
ISO File Writing: |=======             | (35/100)
ISO File Writing: |=======             | (36/100)
ISO File Writing: |=======             | (37/100)
ISO File Writing: |=======             | (38/100)
ISO File Writing: |=======             | (39/100)
ISO File Writing: |========            | (40/100)
ISO File Writing: |========            | (41/100)
ISO File Writing: |========            | (42/100)
ISO File Writing: |========            | (43/100)
ISO File Writing: |========            | (44/100)
ISO File Writing: |=========           | (45/100)
ISO File Writing: |=========           | (46/100)
ISO File Writing: |=========           | (47/100)
ISO File Writing: |=========           | (48/100)
ISO File Writing: |=========           | (49/100)
ISO File Writing: |==========          | (50/100)
ISO File Writing: |==========          | (51/100)
ISO File Writing: |==========          | (52/100)
ISO File Writing: |==========          | (53/100)
ISO File Writing: |==========          | (54/100)
ISO File Writing: |===========         | (55/100)
ISO File Writing: |===========         | (56/100)
ISO File Writing: |===========         | (57/100)
ISO File Writing: |===========         | (58/100)
ISO File Writing: |===========         | (59/100)
ISO File Writing: |============        | (60/100)
ISO File Writing: |============        | (61/100)
ISO File Writing: |============        | (62/100)
ISO File Writing: |============        | (63/100)
ISO File Writing: |============        | (64/100)
ISO File Writing: |=============       | (65/100)
ISO File Writing: |=============       | (66/100)
ISO File Writing: |=============       | (67/100)
ISO File Writing: |=============       | (68/100)
ISO File Writing: |=============       | (69/100)
ISO File Writing: |==============      | (70/100)
ISO File Writing: |==============      | (71/100)
ISO File Writing: |==============      | (72/100)
ISO File Writing: |==============      | (73/100)
ISO File Writing: |==============      | (74/100)
ISO File Writing: |===============     | (75/100)
ISO File Writing: |===============     | (76/100)
ISO File Writing: |===============     | (77/100)
ISO File Writing: |===============     | (78/100)
ISO File Writing: |===============     | (79/100)
ISO File Writing: |================    | (80/100)
ISO File Writing: |================    | (81/100)
ISO File Writing: |================    | (82/100)
ISO File Writing: |================    | (83/100)
ISO File Writing: |================    | (84/100)
ISO File Writing: |=================   | (85/100)
ISO File Writing: |=================   | (86/100)
ISO File Writing: |=================   | (87/100)
ISO File Writing: |=================   | (88/100)
ISO File Writing: |=================   | (89/100)
ISO File Writing: |==================  | (90/100)
ISO File Writing: |==================  | (91/100)
ISO File Writing: |==================  | (92/100)
ISO File Writing: |==================  | (93/100)
ISO File Writing: |==================  | (94/100)
ISO File Writing: |=================== | (95/100)
ISO File Writing: |=================== | (96/100)
ISO File Writing: |=================== | (97/100)
ISO File Writing: |=================== | (98/100)
ISO File Writing: |=================== | (99/100)
ISO File Writing: |====================| (100/100)
finished after 00:00:00.163
created E:\Output\2020-08-17@04_20_16_1410__05.mp4 (0.570005 MB)
```

6. renamed E:\Output\2020-08-17@04_20_16_1410__05.mp4 to E:\Output\test_rev188.mp4

I end up with a file where the video is not playable.

I uploaded all the files to: https://drive.google.com/drive/folders/1SsA1RpBhhUYbVAS_LJ2-Yixh_f2EAQAc?usp=sharing

As a side note: just muxing the video works fine. Using ffmpeg as muxer instead of Mp4Box works fine.  All the raw files seem fine and play without a problem. Tried different players they all have the same problem. Using different aac audio and video encoders (tried NVEncC, x264, x265) all produced a broken file.

Hope this can be fixed soon.
Thanks

**Comment by Selur** [comment] 2020-08-17 14:16
Small correction: this only happens with H.265 video.

**Comment by Selur** [comment] 2020-08-17 14:23
The file plays fine in MPC-HC when using '-brand hvc1' instead of '-brand hev1'.

**Comment by Selur** [comment] 2020-08-17 18:30
correction that fixed the problem only for some other test files not the files I shared,..

**Comment by jeanlf** [comment] 2020-09-02 08:56
I cannot reproduce on OSX here, muxed files play fine in vlc / ffplay, and in QT if xps_inband is not set. I do confirm your mp4 file on the drive is broken, missing an hvcC but I cannot reproduce the mux.
- Which OS are you using ?
- can you reproduce using latest revs ?

**Comment by Selur** [comment] 2020-09-03 19:01
I'll try to reproduce it on the weekend and report back

**Comment by Selur** [comment] 2020-09-04 20:13
I did those calls on Windows. (I first stumbled over this on MacOS, but then tries on Windows since that seems to be more stable.)

Did a new MP4Box build, `MP4Box.exe -version` returns:
```
MP4Box - GPAC version 1.0.0-rev225-g4bbc29915-ab-suite
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io
GPAC Configuration: --prefix=/local64 --disable-shared --enable-static --static-mp4box
Features: GPAC_CONFIG_WIN32 GPAC_64_BITS GPAC_MINIMAL_ODF GPAC_HAS_QJS  GPAC_DISABLE_3D
```

and used the following calls:
```
"i:\Hybrid\64bit\ffmpeg.exe" -y -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:1 -vn -sn -acodec copy -map_metadata -1 "E:\Output\audio_DELAY_-53ms.mp3"
"i:\Hybrid\64bit\ffmpeg.exe" -y -threads 8 -loglevel fatal -nostdin -i "E:\Output\audio_DELAY_-53ms.mp3" -ac 2 -ar 48000 -acodec pcm_s16le -f wav - | "i:\Hybrid\32bit\neroAacEnc.exe"  -br 128000 -ignorelength -if - -of "E:\Output\audio_DELAY_-53ms.aac"
"i:\Hybrid\64bit\ffmpeg.exe" -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p -vsync 0  -f yuv4mpegpipe - | "i:\Hybrid\64bit\NVEncC.exe" --y4m -i - --fps 25.000 --codec h265 --profile main --level auto --tier high --sar 1:1 --lookahead 16 --output-depth 8 --vbrhq 0 --vbr-quality 35.00 --max-bitrate 240000 --gop-len 0 --ref 3 --bframes 0 --no-b-adapt --mv-precision Q-pel --preset quality --colormatrix bt470bg --cuda-schedule sync --output "E:\Output\test.265"
```
To create the files used for muxing.
Then I used these three calls to multiplex with different settings:
```
"i:\Hybrid\64bit\MP4Box.exe" -add "E:\Output\test.265"#video:fps=25:delay=53:xps_inband:name="" -brand hev1 -add "E:\Output\audio_DELAY_-53ms.aac"#audio:name="":lang= -mpeg4 -tmp "E:\Output" -new "E:\Output\h265_hev1_xps_inpand.mp4"
"i:\Hybrid\64bit\MP4Box.exe" -add "E:\Output\test.265"#video:fps=25:delay=53:xps_inband:name="" -brand hvc1 -add "E:\Output\audio_DELAY_-53ms.aac"#audio:name="":lang= -mpeg4 -tmp "E:\Output" -new "E:\Output\h265_hvc1_xps_inpand.mp4"
"i:\Hybrid\64bit\MP4Box.exe" -add "E:\Output\test.265"#video:fps=25:delay=53:name="" -brand hev1 -add "E:\Output\audio_DELAY_-53ms.aac"#audio:name="":lang= -mpeg4 -tmp "E:\Output" -new "E:\Output\h265_hev1.mp4"
"i:\Hybrid\64bit\MP4Box.exe" -add "E:\Output\test.265"#video:fps=25:delay=53:name="" -brand hvc1 -add "E:\Output\audio_DELAY_-53ms.aac"#audio:name="":lang= -mpeg4 -tmp "E:\Output" -new "E:\Output\h265_hvc1.mp4"
```

I uploaded all the files to my google drive (link from previous post).

Result: all files with xps_inband fail on playback, the others play fine, iirc this did work once before.

**Comment by jeanlf** [comment] 2020-09-07 10:26
ok the culprit was `-mpeg4` option triggering broken sample entry for avc and hevc in inband xPS modes. Note that you shouldn't use the `-mpeg4`option unless you require mpeg4 systems signaling.

This is now fixed on git, could you try it out ?

**Comment by Selur** [comment] 2020-09-07 15:23
Tested it, works fine here. :)
Thanks!

**Closed** 2020-09-07 15:43 UTC
