### ISSUE TITLE
Dashing TTML content in MP4

### ISSUE THREAD

**Issue by cconcolato** [gpac/gpac#76] opened 2015-03-20 14:51 UTC
This issue is to discuss strategies for DASHing TTML content in MP4. For bug reports on GPAC when dashing or playing such content, file separate issues.

Starting the discussion with a response to the comment https://github.com/gpac/gpac/issues/57#issuecomment-83944808.

@nigelmegitt noted "Note that a ```<p>``` in TTML is not necessarily the same as a subtitle, and multiple ```<p>```s in the same document are permitted with exactly the same, or overlapping, or non-overlapping timings. As @cconcolato pointed out, EBU-TT-D does permit overlapping paragraphs." 
Agreed, but for a while let's keep things simple and assume no overlap.

@nigelmegitt wrote:
"@cconcolato In your example of one sample for an hour long programme but segments of 1 minute, I wasn't aware that this is possible in DASH."
I don't think there is any restriction in DASH regarding the duration of segments vs. the duration of samples. I don't think having the segment duration shorter than the sample duration was ever considered as it does not make sense for audio and video. For subtitling, we have to tackle the question.

"Segments may contain one or more samples, right?" 
Yes

"Are you suggesting that the samples are duplicated across multiple segments?"
They could. 

 "Or that the URL for the sample in each segment is in fact the same URL?"
That could be possible too. Producing such content would be more tricky as you'd have to detect that the content is the same.

"I did not envisage that anyone would want to do that, and I don't see why they would - there's no reason not to create a single 1 hour segment for the subtitle Representation is there?"
I would agree with you in that extreme case. Now, at a finer scale, if a document is stored in a sample and you have to add a segment boundary in the middle of that sample (for instance because the segment durations are advertised in the MPD with an approximately constant duration), the sample has to be duplicated in the next segment. 

"When it comes to setting a redundant flag, I can see how your example would work @cconcolato but only if the sample content is identical."
Yes.

"I got the impression before that @rbouqueau was thinking of setting it if some part of the two samples is the same even if some other parts are not."
If that's the case, then that would be a bug in MP4Box, but I don't think it is.

Regarding your 5x18s example, I agree with your analysis on how samples/segments could be created. Note that while editing the times in the sample content should provide the same result as not editing them, in practice, the edited version would require terminating the rendering of the previous sample and loading/rendering the new one. That might introduce glitches. The redundant flag is a better option I think.

**Comment by nigelmegitt** [comment] 2015-03-20 15:17
@cconcolato We're in almost complete agreement here. A couple of finer points:

>  if a document is stored in a sample and you have to add a segment boundary in the middle of that sample (for instance because the segment durations are advertised in the MPD with an approximately constant duration), the sample has to be duplicated in the next segment.

This is a special case where a) you don't want to create multiple samples AND b) you don't want to make the segment duration in the subtitle Representation the same as the sample duration. I'm not sure why you'd want this, since the subtitle segment duration does not need to have the same segment duration as e.g. the video. So I don't get the application/use case for this scenario even if I'm sure the statement is correct.

> in practice, the edited version would require terminating the rendering of the previous sample and loading/rendering the new one. That might introduce glitches. The redundant flag is a better option I think.

In the general case it is required to terminate the rendering of the previous sample and beginning rendering the new one. It's unlikely that all samples with any kind of duplication will be able to have the redundant flag set since achieving that would be too difficult for the document author, given that he/she will not know the segment and sample boundaries that will be used at distribution time, and in any case the editorial requirement will be unrelated to those boundaries. 

It's an implementation requirement to avoid glitches on sample boundaries if the presented content in the adjacent boundary frames is the same, regardless of the redundant flag. If I were testing an implementation that glitched e.g. between any adjacent pairs of samples in my example from comment #57 then I would fail that implementation, regardless of the redundant flag or whether the content had been clipped to the sample period or left unchanged.

Going back to the idea of a single sample that is for some reason presented in multiple segments, is there any spec text missing from e.g. [Tech3381](https://tech.ebu.ch/docs/tech/tech3381.pdf), to state that in this scenario the document can remain active across segment boundaries? Just wondering because it isn't a scenario that I think we considered.

**Comment by cconcolato** [comment] 2015-03-20 17:51
@nigelmegitt I think we're in agreement. To answer your questions:

> a) you don't want to create multiple samples
Or rather, you don't want to change the TTML content, yes.

> I don't get the application/use case for this scenario
In some live cases, segments have to respect some constraints on their duration, to avoid drift in segment adresses. In multiplexed representations, you want to keep the subtitle data aligned with the media data.

> achieving that would be too difficult for the document author
I'm not sure I follow here. The document author may not have the information about the segment duration, but the segmenter has that information. I'm thinking the segmenter would create those redundant samples, as it's easier than to edit the TTML content.

> It's an implementation requirement to avoid glitches
Sure, but if the packaging can help, that's better. You can always do string comparisons, hash comparisons, or whatever ...

**Comment by nigelmegitt** [comment] 2015-03-20 20:01
What's good about this discussion is that it's clear that there are different starting assumptions, not surprisingly, from different perspectives, e.g. authors, packagers and receivers, and it's important for the whole chain to work and for interoperability to get any kinks in understanding straightened out. We both simultaneously think we're in agreement with each other, and seem to be recognising that there may be challenges from another perspective that we maybe hadn't fully considered.

I'd also add that it's quite hard to discuss all the options in a github thread. I'd be open to a telco or even a face to face meeting to go through the various scenarios and understand what all the parties want to achieve and how they think it would/could work.

In the meantime, I'll try to respond:

> Or rather, you don't want to change the TTML content, yes.

Just to understand this right, by "change the TTML content" you mean "create any new TTML documents at all"? My view so far has been that the process of extracting relevant parts of the initial document, without otherwise modifying them, and using them to synthesise new smaller documents is not a _change_ to the content in itself, but is in fact the process for creating time-restricted samples of TTML.

If you don't want to do that at all, and you have the TTML for the whole programme, then yes, you could just have that one document be the sample, and I don't see any particular problem with the redundant flag approach. It'd be bad for data rates and processing if implementations kept on fetching the same data and reprocessing it though!

> In some live cases, segments have to respect some constraints on their duration, to avoid drift in segment adresses. 

Okay, this is something I need to look into more - I thought this wasn't a problem. Is it a practical issue rather than a theoretical one? What are the attributes of the live cases that make them susceptible to this?

> In multiplexed representations, you want to keep the subtitle data aligned with the media data.

This could mean a couple of things, so can I unpack what you mean? By "multiplexed representations" are you talking about Representations containing multiple Sub-Representations, one of which contains the subtitle media content component? Or do you mean Representations that contain MPEG-2 transport stream Media Segments that contain multiplexed content? I don't think anyone has defined the carriage of TTML in MPEG-2 TS yet, so it'd be good if we can rule that out for the time being.

Assuming you mean the first one, yes, I can see that the segment boundaries are the same for all the Sub-Representations present. 

So I think I get that use case now, thanks.

> I'm thinking the segmenter would create those redundant samples, as it's easier than to edit the TTML content.

It's actually pretty easy (computationally, and in code) to pull out the TTML content that overlaps any given defined time period from a single document covering a longer period. I've seen an XSLT that can do it, for example. It's even simpler in EBU-TT-D than generic TTML because some of the time calculation complexities are reduced. MP4Box seems to have code to do this already.

But yes, doing *no* processing is always easier than doing *some* processing!

Since _some_ packagers will create temporal samples from the TTML, and it's allowed in the specs, it follows that _all_ receiver implementations need to be able to handle it. I think that's the macro point here. I'm very happy with any assistance that can be provided in packaging and any optimisations in implementations to help provide the right user experience.

So ...

> I'm not sure I follow here. The document author may not have the information about the segment duration, but the segmenter has that information.

We maybe were coming from two different starting points: I thought we were talking about a model where TTML samples matching the segment period were being extracted from the source TTML; I now see that you weren't saying that. In the model I had in mind, my point was simply that there is no and can be no fixed relationship between the begin and end times in the original (pre-sampling) TTML and the segment times, meaning that some TTML content will end up being reproduced in adjacent samples some of the time.

**Comment by rbouqueau** [comment] 2015-03-20 22:06
I'm happy to see there is more mutual understanding here.

> It's actually pretty easy (computationally, and in code) to pull out the TTML content that overlaps any given defined time period from a single document covering a longer period.

Indeed. It may be acceptable to do so at import. We have to manipulate TTML at this stage anyway.

It is not acceptable to do this while DASHing IMO. Of course this missing brick might be easy to write. But as a specification writer, one should take care to keep the "separation of concerns" and not assume the presence of this brick is mandatory. This allows a non-TTML-aware DASHer to process TTML documents (even if it consists of duplicating the full TTML document with the redundant flag) ; otherwise it forces to update the software to support new specifications.

An alternative would be to prepare the content before/when importing it (with XSLT or an MP4Box option) as both of you suggested.

**Comment by cconcolato** [comment] 2015-03-22 10:48
> Just to understand this right, by "change the TTML content" you mean "create any new TTML documents at all"? My view so far has been that the process of extracting relevant parts of the initial document, without otherwise modifying them, and using them to synthesise new smaller documents is not a change to the content in itself, but is in fact the process for creating time-restricted samples of TTML.

As you said, we come from different perspectives and don't have always the same vocabulary. For me "creating time-restricted samples of TTML" indeed means changing the TTML content, because it's unclear that the extraction of the TTML content from the resulting MP4 samples in that case can result in the same input TTML documents. 

> It'd be bad for data rates and processing if implementations kept on fetching the same data and reprocessing it though!

Sure! One has to be careful when using this flag. In my mind, it should only be used at segment boundaries when the duplication of the sample cannot be avoided.

> Okay, this is something I need to look into more - I thought this wasn't a problem. Is it a practical issue rather than a theoretical one? What are the attributes of the live cases that make them susceptible to this?

It's a complex problem, maybe a bit pathological. You can look at the latest [DASH Defect under Investigation] (http://wg11.sc29.org/doc_end_user/documents/111_Geneva/wg11/w15213.zip) where it talks a little bit about that. The problem is that since the MPD announces in advance the segment names, if those are based on a constant duration, the segment duration has to be quite constant to avoid drift and fetching the wrong segment or getting 404. 


> This could mean a couple of things, so can I unpack what you mean? By "multiplexed representations" are you talking about Representations containing multiple Sub-Representations, one of which contains the subtitle media content component? Or do you mean Representations that contain MPEG-2 transport stream Media Segments that contain multiplexed content? I don't think anyone has defined the carriage of TTML in MPEG-2 TS yet, so it'd be good if we can rule that out for the time being.
> 
> Assuming you mean the first one, yes, I can see that the segment boundaries are the same for all the Sub-Representations present.

By "multiplexed representation", I meant a representation for which media segments contain multiple media content components: eg Audio+Video+Subtitle. This does not necessarily mean using SubRepresentations. I did not mean MPEG-2 TS (although indeed that's a typical use case), but ISOBMFF. Arguably, that's not very common though.

> It's actually pretty easy (computationally, and in code) to pull out the TTML content that overlaps any given defined time period from a single document covering a longer period. I've seen an XSLT that can do it, for example. It's even simpler in EBU-TT-D than generic TTML because some of the time calculation complexities are reduced. MP4Box seems to have code to do this already.
> 
> But yes, doing no processing is always easier than doing some processing!
> 
> Since some packagers will create temporal samples from the TTML, and it's allowed in the specs, it follows that all receiver implementations need to be able to handle it. I think that's the macro point here. I'm very happy with any assistance that can be provided in packaging and any optimisations in implementations to help provide the right user experience.

As @rbouqueau said, the problem is not the difficulty/complexity of doing it. The problem is when to do it. When preparing the MP4 file, it's fine. When DASHing that's problematic. DASH processing (creating segments, MPD ...) should not require having to change the number and content of media samples (in your terms "pull out the TTML, apply XSLT, ..."). In terms of software architecture and layering, that would require some communication between the "compression"/media-aware layer and the DASH/media-unaware layer during DASHing. So far, we haven't had the need for that and we should avoid it.  

> We maybe were coming from two different starting points: I thought we were talking about a model where TTML samples matching the segment period were being extracted from the source TTML; I now see that you weren't saying that. In the model I had in mind, my point was simply that there is no and can be no fixed relationship between the begin and end times in the original (pre-sampling) TTML and the segment times, meaning that some TTML content will end up being reproduced in adjacent samples some of the time.

I fully agree with "there is no and can be no fixed relationship between the begin and end times in the original (pre-sampling) TTML and the segment times". In MP4Box model, a first phase is to create "samples" from the original TTML content. A second phase is to create segments from the samples, without touching the TTML content anymore. So the first phase has to prepare the second phase appropriately. That's where we can improve MP4Box as we currently import either unmodified TTML documents as separate samples (using NHML) or we create many samples from a given TTML document (probably too many and that fails in case of overlap).

**Comment by nigelmegitt** [comment] 2015-03-23 15:04
It feels as though we've almost reached the end of this discussion, with some useful notes for future reference. I agree with the points about where the processing should happen, and the proposed model is fine for me. 

Attempting to summarise:

* It is the role of the Encoder to take TTML input documents and create samples of TTML suitable for packaging.
* It is the role of the Packager to create DASHed output including or referencing those encoded samples.
* Encoders may create multiple samples of TTML (e.g. EBU-TT-D) that have defined sample periods in ISOBMFF but have timed (TTML) content that extends outside those periods;
* Encoders do not have to do this and could create a single long sample for the duration of the media content;
* Packagers may create multiple DASH segments that reference the same TTML sample;
* Packagers may label the redundant samples as 'redundant = true';
* Adjacent TTML samples may contain some duplicated content, e.g. a timed content element that extends across the sample boundary may be in both the samples.
* Packagers must not label non-identical samples as redundant even if they partially overlap;
* If the desired DASHed output has segments with distinct samples, e.g. for live content, then the encoder needs to be aware of the desired segment boundaries and create the TTML samples to match (or an integral number of samples that matches the segment duration
* Decoders may take advantage of the redundant flag to extend the active duration of a sample
* Decoders must ensure that zero or one TTML sample in a media component (i.e with the same `@id`) is active at any given moment on the media timeline. It is an error to permit two or more samples to be active simultaneously even if their content overlaps in time.
* On sample and segment boundaries, any presented content that is the same before and after the boundary point the implementation must not have a visible glitch in presentation.

Before we consider closing this, I just want to check if there are any remaining unresolved questions.

In particular:

* are the models for DASHing and playback clear enough?
* are there any remaining points of debate?
* are there scenarios that are under-specified by 14496-30, 23009 and/or Tech3381?

**Comment by rbouqueau** [comment] 2015-10-24 13:42
See https://github.com/rbouqueau/TTML_in_MP4_DASH_statement for further discussions.

**Closed by rbouqueau** 2015-10-24 13:42 UTC
Labels: question
