### ISSUE TITLE
two video stream create two AdaptationSet,not in one

### ISSUE THREAD

**Issue by friendtasy** [gpac/gpac#2454] opened 2023-05-02 12:12 UTC
i use command like that 

MP4Box -dash 10000 -rap -frag-rap -dash-profile dashavc264:onDemand -bs-switching no -segment-ext .m4s  11.mkv#video ED320x240.mp4#video 11.mkv#audio -out xxx.mpd

and mpd content like that,two video stream create two AdaptationSet

<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H13M38.601S" maxSubsegmentDuration="PT0H0M14.414S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011,http://dashif.org/guidelines/dash264">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>xxx.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H13M38.601S">
  <AdaptationSet segmentAlignment="true" lang="und" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="3" mimeType="audio/mp4" codecs="opus" audioSamplingRate="48000" bandwidth="120000">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>11_dash_track2_init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="915-1930">
     <Initialization range="0-802"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" maxWidth="3840" maxHeight="2160" maxFrameRate="25" par="16:9" lang="und" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="1" mimeType="video/mp4" codecs="vp09.00.00.08.00.01.01.01.00" width="3840" height="2160" frameRate="25" sar="1:1" bandwidth="13500000">
    <BaseURL>11_dash_track1_init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="986-2001">
     <Initialization range="0-873"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" maxWidth="320" maxHeight="240" maxFrameRate="60000/1001" par="4:3" lang="und" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="2" mimeType="video/mp4" codecs="hev1.1.6.L63.90" width="320" height="240" frameRate="60000/1001" sar="4:3" bandwidth="100242">
    <BaseURL>ED320x240_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="1061-2076">
     <Initialization range="0-948"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

**Comment by rbouqueau** [comment] 2023-05-02 12:28
That's because the ```par``` (picture aspect ratio)  are different: 16:9 vs 4:3. So they belong to different AdaptationSets.

**Comment by friendtasy** [comment] 2023-05-02 12:48
> That's because the `par` (picture aspect ratio) are different: 16:9 vs 4:3. So they belong to different AdaptationSets.

thank you,if i want add orgin video into dash stream,when i use ffmpeg Transcoding low quality,how can i do it can add orgin video?

**Comment by friendtasy** [comment] 2023-05-02 12:54
i have a questtion,same  AdaptationSet the decode must be same?h264 h265 video can in the same  AdaptationSet?

**Comment by friendtasy** [comment] 2023-05-02 14:04
> > if i want add orgin video into dash stream,when i use ffmpeg Transcoding low quality,how can i do it can add orgin video?
> 
> You need to be sure that the content is already ok for DASHing. You can read https://github.com/gpac/gpac/wiki/dash_transcoding.
> 
> > same AdaptationSet the decode must be same?h264 h265 video can in the same AdaptationSet?
> 
> They can be in the same AdaptationSet but you have to check if your player supports it.

i found that from youtube download orgin video code by vp9,i use mp4box add to dash,i found mpd file the video stream frameRate="25",but the video framerate is 60,at chrome can't play,but i manual operation fix it will be play at chrome

**Comment by rbouqueau** [comment] 2023-05-02 14:06
Could you share the source with us so that we have a deeper look?

**Comment by friendtasy** [comment] 2023-05-02 14:13
> Could you share the source with us so that we have a deeper look?

you can down youtube 4k or 8k to test,almost code by vp9.or download the video from

https://www.youtube.com/watch?v=yMMibCohcCk&ab_channel=Huan

**Comment by rbouqueau** [comment] 2023-05-02 19:34
I've downloaded all possible combination using youtube-dl and it works. Could you detail which files you download, what is your version of GPAC, and how you test? This way I can reproduce your issue.

**Comment by friendtasy** [comment] 2023-05-03 01:37
gpac - GPAC command line filter engine - version 2.2-rev0-gab012bbf-master
(c) 2000-2022 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io

Please cite our work in your research:
        GPAC Filters: https://doi.org/10.1145/3339825.3394929
        GPAC: https://doi.org/10.1145/1291233.1291452

the video url
https://rr4---sn-i3b7knzs.googlevideo.com/videoplayback?expire=1683098722&ei=AbhRZKmgO5PYjuMP59eViA0&ip=2400%3A6180%3A0%3Ad0%3A0%3A0%3A1001%3A7001&id=o-ALyEbnkZBLHOdh2Pe3pJTaPckKO-kn15hmNC4FnKBSiY&itag=308&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308%2C315&source=youtube&requiressl=yes&mh=2Q&mm=31%2C26&mn=sn-i3b7knzs%2Csn-un57ene6&ms=au%2Conr&mv=m&mvi=4&pl=60&initcwndbps=3608750&vprv=1&svpuc=1&mime=video%2Fwebm&ns=JL4Hz01L-g28-RkaF-55olcN&gir=yes&clen=351016617&dur=818.584&lmt=1678133894502616&mt=1683076634&fvip=4&keepalive=yes&fexp=24007246&c=WEB&txp=5432434&n=aU-o2bLa9GrUlA&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgWniebKmXH5fUUjxGD_klG9B-OVsAX5OYqZH-G-uQ4YMCIG5y6MJtDIoMrvfGOiMxr4Ix88UnQWq-XFZuzIuKlKFj&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPbB-jowEVzKWhczsv6kKnKYT5ePoPxq5qgkPrWGVylLAiAzudIkNdr9sYld14rqiDoAkFF1S5B7bMsPH9yKwKE1XQ%3D%3D

it is https://www.youtube.com/watch?v=T3-8_9CwAKo&t=602s&ab_channel=%E6%BD%AE%E7%8E%A9%E5%AE%A2 1440p qulity

use following command

MP4Box -dash 10000 -rap -frag-rap -dash-profile dashavc264:onDemand -bs-switching no 22.mkv#video 22.mkv#audio -out xxx.mpd

mpd file content
  <AdaptationSet segmentAlignment="true" maxWidth="2560" maxHeight="1440" maxFrameRate="25" par="16:9" lang="und" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="1" mimeType="video/mp4" codecs="vp09.00.00.08.00.01.01.01.00" width="2560" height="1440" frameRate="25" sar="1:1" bandwidth="3400000">

**Comment by rbouqueau** [comment] 2023-05-03 10:05
Your link doesn't work so I went to youtube-dl again. It seems that it worked: now I have a 59.94fps (60000/1001) content. I hashed it with ```MP4Box -dash 10000 -rap -frag-rap -dash-profile dashavc264:onDemand -bs-switching no 22.mkv#video 22.mkv#audio -out xxx.mpd```.

I confirm it doesn't play in firefox/chromium/chrome with the latest dash.js as they don't handle this codec+res. The GPAC player is ok (gpac -play xxx.mpd).

Which player do you try to play with?

> the mimeType="video/mp4" must fix to mimeType="video/webm"

Well if you want webm, you need to add ```:muxtype=webm``` as per https://github.com/gpac/gpac/wiki/dasher

I tried to dash and play this: it doesn't work.

> why -segment-ext .m4s not be use?on up command

Add ```-profile live``` if you need to generate segments.

**Comment by friendtasy** [comment] 2023-05-03 13:57
> 

init ext name can change?

**Comment by friendtasy** [comment] 2023-05-03 14:01
> Your link doesn't work so I went to youtube-dl again. It seems that it worked: now I have a 59.94fps (60000/1001) content. I hashed it with `MP4Box -dash 10000 -rap -frag-rap -dash-profile dashavc264:onDemand -bs-switching no 22.mkv#video 22.mkv#audio -out xxx.mpd`.
> 
> I confirm it doesn't play in firefox/chromium/chrome with the latest dash.js as they don't handle this codec+res. The GPAC player is ok (gpac -play xxx.mpd).
> 
> Which player do you try to play with?
> 
> > the mimeType="video/mp4" must fix to mimeType="video/webm"
> 
> Well if you want webm, you need to add `:muxtype=webm` as per https://github.com/gpac/gpac/wiki/dasher
> 
> I tried to dash and play this: it doesn't work.
> 
> > why -segment-ext .m4s not be use?on up command
> 
> Add `-profile live` if you need to generate segments.

i use video.js 8.3.0 windows 11 chrome 112 play

**Comment by rbouqueau** [comment] 2023-05-03 15:03
> i found mpd file the video stream frameRate="25"and mimeType="video/mp4" ,but the video framerate is 60,at chrome can't play,but i manual operation fix it will be play at chrome.the mimeType="video/mp4" must fix to mimeType="video/webm"

I am not sure to understand this sentence. I was not able to play the webm 4k@59.94fps in chrome (after dashing it). What is your expection wrt this content?

**Comment by friendtasy** [comment] 2023-05-04 00:08
> > i found mpd file the video stream frameRate="25"and mimeType="video/mp4" ,but the video framerate is 60,at chrome can't play,but i manual operation fix it will be play at chrome.the mimeType="video/mp4" must fix to mimeType="video/webm"
> 
> I am not sure to understand this sentence. I was not able to play the webm [4k@59.94fps](mailto:4k@59.94fps) in chrome (after dashing it). What is your expection wrt this content?

<img width="682" alt="1" src="https://user-images.githubusercontent.com/17196859/236076270-f59736b6-dbc3-40dd-9304-37082853feca.png">
<img width="832" alt="2" src="https://user-images.githubusercontent.com/17196859/236076286-229bf043-3c61-4a3f-8567-b870fd88a694.png">

**Comment by friendtasy** [comment] 2023-05-04 00:11
codecs="vp09.00.00.08.00.01.01.01.00"
modify
codecs="vp09.00.51.08.01.01.01.01.00"

can decode~,maybe this is key~

**Comment by rbouqueau** [comment] 2023-05-04 13:08
I confirm, nice catch and thanks for your patience.

**Comment by rbouqueau** [comment] 2023-05-04 13:27
I have extracted the raw video and the profile is set to zero in the vp9 encoding. What option do we have in this case?

**Comment by friendtasy** [comment] 2023-05-07 10:53
> I have extracted the raw video and the profile is set to zero in the vp9 encoding. What option do we have in this case?

i found av1 video have some problem like that.and video.js cant't show this quality

**Comment by jeanlf** [comment] 2023-05-10 14:03
> What option do we have in this case?

None in GPAC currently

**Comment by rbouqueau** [comment] 2023-05-10 16:14
Couldn't we 1) warn when the profile is 0 and 2) add a property to allow to set thee rfc6381 manually?

What do you think?

**Comment by jeanlf** [comment] 2023-05-11 15:53
we can add a warning yes.
Note that it is possible to override the codecs string using the `Codec` property, eg

```
gpac -i src:#Codec=foo.BAR -o dash/manifest.mpd

MP4Box -dash 1000  src:#Codec=foo.BAR -out dash/manifest.mpd

```

**Comment by rbouqueau** [comment] 2023-05-11 19:20
I checked. In VP9:
- Level 0 is legal (it means "undefined"): https://www.webmproject.org/vp9/levels/
- Profile 0 is 4:2:0 8 bits: https://www.webmproject.org/vp9/profiles/

Should we warn about level=0 in all cases? It is the first time we see this issue. And the issue is only present when DASHing (i.e. modifying the manifest suffices to fix the issue).

**Comment by jeanlf** [comment] 2023-05-12 10:37
maybe only warn when dashing ?

**Comment by jeanlf** [comment] 2023-05-22 15:50
can we close this ?

**Comment by friendtasy** [comment] 2023-05-26 04:55
> can we close this ?

ok

**Closed** 2023-05-26 09:04 UTC
