### ISSUE TITLE
Warning: gpac is too old - Using --static-mp4box then OpenGL support: no

### ISSUE THREAD

**Issue by ghost** [gpac/gpac#230] opened 2015-09-07 04:16 UTC
When trying to compile x264 against gpac, unless you build gpac as `--static-mp4box` then x264 complains that the gpac version is too old, but by doing this, then the OpenGL support is no...

How do we get OpenGL support in gpac and compile it also against x264 without it complaining?

**Comment by rbouqueau** [comment] 2015-09-07 05:32
Hi,

Can you confirm you are talking about GPAC OpenGL support? GPAC is made of several tools, including a packaging and a playback libraries. x264 can use the packager, which has almost no dependency. Only the playback library takes advantage of OpenGL. So you don't need OpenGL to link against x264.

Also when do you get the "Warning: gpac is too old" warning? There was a similar issue a year ago, we could find a way to reproduce with the latest versions of x264 and gpac. I'd like us to fix it.

**Comment by Geyup** [comment] 2015-09-07 20:44
I really don't know what OpenGL support this is, in GPAC or the System, all I know is the ```** Detected libraries **``` when you compile GPAC as ```--static-mp4box``` then it shows ```OpenGL support: no``` like below;


** Detected libraries **
zlib: system
OSS Audio: yes
ALSA Audio: yes
Jack Audio: no
PulseAudio Audio: no
DirectFB support: no
X11 Shared Memory support: yes (path: /usr/X11R6)
X11 XVideo support: yes
SDL Support: yes
```OpenGL support: no```
TinyGL support: no
OpenSSL support: no
Mozilla XUL/GECKO support: no
DVB Support: yes
XMLRPC Support: no
wxWidgets support: no

I just grabbed the latest source from git;

```git clone https://github.com/gpac/gpac.git```

These are my compile options;
```
LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
./configure \
  --prefix=/usr \
  --mandir=/usr/man \
  --disable-opt \
  --cpu=${ARCH} \
  --static-mp4box \
  --extra-cflags="$SLKCFLAGS" \
  $wx_option
```

I also grabbed the latest version of x264;
```ftp://ftp.videolan.org/pub/x264/snapshots/last_x264.tar.bz2```

If I compile gpac with ``` --static-mp4box ``` there is no warning message, if I remove it, then x264 complains.

**Comment by rbouqueau** [comment] 2015-09-08 06:31
Ok so it seems to come from the x264 detection. Have you reported the issue to their developers?

**Comment by Geyup** [comment] 2015-09-08 19:10
No, wasn't thinking about them yet.

What about this ```--static-mp4box``` and having the ```OpenGL support: no```?

**Comment by rbouqueau** [comment] 2015-09-09 16:31
> What about this --static-mp4box and having the OpenGL support: no?

Please read my previous answer. You can safely ignore this.

When you get the x264 warning, what does the config.log from x264 contains?

**Comment by Geyup** [comment] 2015-09-10 07:20
Warning: gpac is too old, update to 2007-06-21 UTC or later
platform:      X86_64
byte order:    little-endian
system:        LINUX
cli:           yes
libx264:       internal
shared:        yes
static:        no
asm:           yes
interlaced:    yes
avs:           avxsynth
lavf:          yes
ffms:          no
mp4:           no
gpl:           yes
thread:        posix
opencl:        yes
filters:       resize crop select_every
debug:         no
gprof:         no
strip:         yes
PIC:           yes
bit depth:     8
chroma format: all

**Comment by rbouqueau** [comment] 2015-09-10 07:48
Can you provide the config.log from x264 as I suggested?

**Comment by Geyup** [comment] 2015-09-10 07:59
oops sorry... brb

**Comment by Geyup** [comment] 2015-09-10 08:06
x264 configure script
Command line options: "--prefix=/usr" "--libdir=/usr/lib64" "--includedir=/usr/include" "--enable-shared" "--enable-pic" "--enable-strip" "--enable-pic" "--host=x86_64-slackware-linux"

checking whether gcc works... yes
checking whether gcc supports for( int i = 0; i < 9; i++ ); with -std=gnu99... yes
checking whether yasm supports vpmovzxwd ymm0, xmm0... yes
checking whether gcc supports __asm__("pabsw %xmm0, %xmm0");... yes
checking for -mpreferred-stack-boundary=5... yes
checking for pthread_create(0,0,0,0); in pthread.h... yes
checking for cpu_set_t p_aff; return CPU_COUNT(&p_aff); in sched.h... yes
checking for return log2f(2); in math.h... yes
checking for MADV_HUGEPAGE; in sys/mman.h... yes
checking for sws_init_context(0,0,0); in libswscale/swscale.h... yes
checking whether defined(AV_PIX_FMT_FLAG_RGB) is true... yes
checking for av_frame_free(0); in libavformat/avformat.h... yes
checking for FFMS_DestroyVideoSource(0); in ffms.h... no
Failed commandline was:
--------------------------------------------------
gcc conftest.c -m64 -O2 -fPIC -Wall -I. -I$(SRCPATH) -std=gnu99 -mpreferred-stack-boundary=5   -lffms2  -m64 -L/usr/lib64 -lm -lpthread -o conftest
conftest.c:1:18: fatal error: ffms.h: No such file or directory
 #include <ffms.h>
                  ^
compilation terminated.
--------------------------------------------------
Failed program was:
--------------------------------------------------
#include <ffms.h>
int main (void) { FFMS_DestroyVideoSource(0); return 0; }
--------------------------------------------------
checking for FFMS_DestroyVideoSource(0); in ffms.h... no
Failed commandline was:
--------------------------------------------------
gcc conftest.c -m64 -O2 -fPIC -Wall -I. -I$(SRCPATH) -std=gnu99 -mpreferred-stack-boundary=5   -lffms2 -lstdc++ -L.  -lavformat -lavcodec -lavutil -lswscale    -m64 -L/usr/lib64 -lm -lpthread -o conftest
conftest.c:1:18: fatal error: ffms.h: No such file or directory
 #include <ffms.h>
                  ^
compilation terminated.
--------------------------------------------------
Failed program was:
--------------------------------------------------
#include <ffms.h>
int main (void) { FFMS_DestroyVideoSource(0); return 0; }
--------------------------------------------------
checking for lsmash.h... no
Failed commandline was:
--------------------------------------------------
gcc conftest.c -m64 -O2 -fPIC -Wall -I. -I$(SRCPATH) -std=gnu99 -mpreferred-stack-boundary=5         -llsmash -L.  -lavformat -lavcodec -lavutil -lswscale    -lswscale -lavutil    -m64 -L/usr/lib64 -lm -lpthread -o conftest
conftest.c:1:20: fatal error: lsmash.h: No such file or directory
 #include <lsmash.h>
                    ^
compilation terminated.
--------------------------------------------------
Failed program was:
--------------------------------------------------
#include <lsmash.h>
int main (void) {  return 0; }
--------------------------------------------------
checking for -lz... yes
checking for gpac/isomedia.h... yes
checking for gf_isom_set_pixel_aspect_ratio(0,0,0,0,0); in gpac/isomedia.h... no
Failed commandline was:
--------------------------------------------------
gcc conftest.c -m64 -O2 -fPIC -Wall -I. -I$(SRCPATH) -std=gnu99 -mpreferred-stack-boundary=5        -lgpac_static -lz -L.  -lavformat -lavcodec -lavutil -lswscale    -lswscale -lavutil    -m64 -L/usr/lib64 -lm -lpthread -o conftest
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/libgpac_static.a(os_module.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../x86_64-slackware-linux/bin/ld: note: 'dlclose@@GLIBC_2.2.5' is defined in DSO /lib64/libdl.so.2 so try adding it to the linker command line
/lib64/libdl.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
--------------------------------------------------
Failed program was:
--------------------------------------------------
#include <gpac/isomedia.h>
int main (void) { gf_isom_set_pixel_aspect_ratio(0,0,0,0,0); return 0; }
--------------------------------------------------
checking for uint32_t test_vec __attribute__ ((vector_size (16))) = {0,1,2,3}; in stdint.h... yes
checking for stdio.h... yes
checking for -fno-tree-vectorize... yes
checking for fseeko(stdin,0,0); in stdio.h... yes
checking for -Wshadow... yes
checking for -Wmaybe-uninitialized... yes

platform:      X86_64
byte order:    little-endian
system:        LINUX
cli:           yes
libx264:       internal
shared:        yes
static:        no
asm:           yes
interlaced:    yes
avs:           avxsynth
lavf:          yes
ffms:          no
mp4:           no
gpl:           yes
thread:        posix
opencl:        yes
filters:       resize crop select_every 
debug:         no
gprof:         no
strip:         yes
PIC:           yes
bit depth:     8
chroma format: all

**Comment by Geyup** [comment] 2015-09-10 08:06
Here;

http://dpaste.com/1A0E14B

**Comment by rbouqueau** [comment] 2015-09-10 09:13
Ok. The faulty part of config.log is:
```
checking for gf_isom_set_pixel_aspect_ratio(0,0,0,0,0); in gpac/isomedia.h... no
Failed commandline was:
--------------------------------------------------
gcc conftest.c -m64 -O2 -fPIC -Wall -I. -I$(SRCPATH) -std=gnu99 -mpreferred-stack-boundary=5        -lgpac_static -lz -L.  -lavformat -lavcodec -lavutil -lswscale    -lswscale -lavutil    -m64 -L/usr/lib64 -lm -lpthread -o conftest
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/libgpac_static.a(os_module.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../x86_64-slackware-linux/bin/ld: note: 'dlclose@@GLIBC_2.2.5' is defined in DSO /lib64/libdl.so.2 so try adding it to the linker command line
/lib64/libdl.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
--------------------------------------------------
Failed program was:
--------------------------------------------------
#include <gpac/isomedia.h>
int main (void) { gf_isom_set_pixel_aspect_ratio(0,0,0,0,0); return 0; }
```

I have to check the x264 configure, but this may be due to #5

**Comment by Geyup** [comment] 2015-09-10 09:58
ok

**Comment by rbouqueau** [comment] 2015-09-10 12:11
I have checked: https://github.com/mirror/x264/blob/master/configure#L1065

It seems that x264 configure is incorrect. But to be correct it would have to use pkg-config from gpac and it has a limitation described in #5 .

Do you know if there is a good place where we can tell people to build gpac using ```--static-mp4box``` to ease everybody's pain? :)

**Comment by Geyup** [comment] 2015-09-10 20:17
Tell people... hmm

I guess on the website, github and the docs :)

**Comment by rbouqueau** [comment] 2015-09-15 11:30
See also deprecated https://sourceforge.net/p/gpac/bugs/341/

**Comment by Geyup** [comment] 2016-04-12 02:30
@rbouqueau have you submitted something to x264 team if their configure is incorrect, to correct this?

0.6.1 seems to still be working this same way, needing ```--static-mp4box```. One thing that concerns me about this, is when it's compiled like this, then there is no OpenGL support; ```OpenGL support: no```.

**Comment by rbouqueau** [comment] 2016-04-12 06:27
Hi,

Thanks for touching base on this. I'd like it fixed for our next release (likely end of summer). Time is scarse.

> @rbouqueau have you submitted something to x264 team if their configure is incorrect, to correct this?

I'd like to suggest them to use pkg-config. The issue is that the GPAC pkgconfig is broken with some static configurations, see #5. I'd probably make a PR to x264 when GPAC is ok. Apparently the problem has been here for years but nobody ever reported us so I think it can wait for a little longer.

> But I'd like to have OpenGL support for playback...

I can only suggest to have two builds of GPAC. GPAC supports out of tree builds: https://msteveb.github.io/autosetup/user/outoftree/

**Comment by Geyup** [comment] 2016-04-12 07:15
Sounds good, keep up the great work!

**Comment by rbouqueau** [comment] 2016-04-27 10:02
I've spent some time but:
- pkg-config doesn't handle static libs having different name as dyn lib (why?)
- pkg-config from the system doesn't behave like the one from the toolchain even on simple .pc files on MSYS2

**Comment by Geyup** [comment] 2016-04-30 01:31
Sorry can't help... :(

**Comment by jeanlf** [comment] 2019-06-28 15:02
can we close this ?

**Comment by jeanlf** [comment] 2020-07-31 14:18
see #1528

**Closed by jeanlf** 2020-07-31 14:18 UTC
Labels: build
