### ISSUE TITLE
Incorrect debian depends

### ISSUE THREAD

**Issue by ivan1986** [gpac/gpac#1131] opened 2018-09-05 18:37 UTC
can not build in last debian and ubuntu

Depends: xulrunner-dev but it is not installable
Depends: libpng12-dev but it is not installable
Depends: libopenjpeg-dev but it is not installable

libpng12-dev to libpng-dev (it's 1.16 now)
libopenjpeg-dev to libopenjp2-7-dev
xulrunner looks removed

any plans to update or sync with debian or ubuntu (0.5.2 current in ubuntu)?

**Comment by rbouqueau** [comment] 2018-09-06 09:03
> can not build in last debian and ubuntu

Could you detail the step you followed to build GPAC? We need the info to reproduce your issue to be able to fix it.

> any plans to update or sync with debian or ubuntu (0.5.2 current in ubuntu)?

It is up to the distribution package maintainer to update it. You can contact them, that would be helpful for us.

**Comment by ivan1986** [comment] 2018-09-06 11:37
i using debocker for this repository:

1) clone repository
2) create file debian/source/format with "3.0 (native)"
3) dobocker build

i try build with you debian directory and it has old depends

**Comment by aureliendavid** [comment] 2018-09-06 13:31
some notes on this point: 

* our `deb` packages (available on https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/) are built for ubuntu 16.04 LTS and should install / build without issue there

* there are issues with ubuntu 18.04 LTS mostly with `libopenjpeg` and `libmozjs185` which have been removed in ubuntu >= 18.04 (this will need to be fixed soon-ish)

* however, the `./configure` script should disable the features used by the missing libraries and still build properly (tested on ubuntu 18.04: `make` and `make deb` both work - the big thing missing in this case is the interactive part of the `MP4Client` gui, the rest looks more or less ok)

* I don't use or know `debocker` so I don't know if this can be supported

* however the problem you described looks like it comes from `dpkg-checkbuilddeps` which reads its dependencies from `debian/control`

* you can edit `debian/control` and remove the dependencies that bother you - I was able to pass the `dpkg-checkbuilddeps` with this content in `debian/control` on ubuntu 18.10: 

``
Build-Depends: debhelper (>= 6), libc6, libc6-dev, libx11-dev (>= 1.3), zlib1g-dev (>= 1), libfreetype6-dev, libjpeg62-dev, libpng-dev, libmad0-dev, libfaad-dev, libogg-dev, libvorbis-dev, libtheora-dev, liba52-dev, libavcodec-dev, libavformat-dev, libswscale-dev, libxv-dev, x11proto-video-dev, libgl1-mesa-dev, x11proto-gl-dev, linux-sound-base (>= 1.0), libxvidcore-dev, libssl-dev (>= 0.9.8), libjack-dev (>= 0.118), libasound2-dev (>= 1.0), libpulse-dev (>= 0.9), libsdl-dev (>= 1.2) | libsdl2-dev, ccache
``

(this needs to be updated too)

hope this helps

**Comment by jeanlf** [comment] 2019-06-28 23:20
can we close this?

**Comment by aureliendavid** [comment] 2019-06-29 14:41
with the last commit + https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux, we can

**Closed by aureliendavid** 2019-06-29 14:41 UTC
