### ISSUE TITLE
Live Tiled Dash Streaming, No Segment Increment  :: MP4Box and Kvazaar

### ISSUE THREAD

**Issue by franciscomfcmaia** [gpac/gpac#1648] opened 2020-11-26 12:44 UTC
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Hello,

I am trying to create live dash streaming of tiled HEVC. I have been doing extensive reading, and I believe I might be on the right path, but I cannot correctly dash this.

I am doing the following every X seconds (loop) => **[ffmpeg records video from /dev/videox] -> [kvazaar tiles] -> [MP4Box packages it]**

```
rm -R dash_output/*
i=0
while true;
do
ffmpeg -f v4l2 -framerate 30 -video_size 3840x2160 -i /dev/video0 -an -f rawvideo -pix_fmt yuvj420p -t 00:00:02 - | kvazaar -i - --input-res 3840x2160 -o videos/hevc_live_output.hevc --tiles 3x3 --slices tiles --mv-constraint frametilemargin --bitrate 128000 --period 30 --input-fps 30
MP4Box -add videos/hevc_live_output.hevc:split_tiles -fps 30 -new videos/live_video_tiled.mp4
done
```
By the end of this, I have a new MP4 file I want to dash:

```
MP4Box -dash-ctx dash_output/dash-live.txt -dash-live 2000 -run-for 2000 -profile live \
-mpd-title "DASH-LIVE stream" -ast-offset 12 -no-frags-default -rap -frag-rap \
-insert-utc -mpd-refresh 2000 -time-shift 1200 -min-buffer 2000 -bs-switching no \
-out dash_output/dash.mpd -subsegs-per-sidx -1 videos/live_video_tiled.mp4:role=main
```

_I am running this on a loop for video recordings of **2 seconds each**._

**At the output of each dash run I get:**

```
[Dasher] No template assigned, using $File$_dash$FS$$Number$
[Dasher] First CTS 204000 in segment 35 drifting by -61.2 (more than half a segment duration) from segment time, consider reencoding or using segment timeline
[Dasher] Segment 35 duration 0.2 less than half DASH duration, consider reencoding or using segment timeline
[Dasher] AS-1 Rep 1_2 segment 35 done TOO LATE by 29695 ms
[Dasher] updated period DID3 duration 7000 MPD time 7000
[Dasher] updated period DID3 duration 7000 MPD time 7000
[MPD] Generating MPD at time 2020-11-26T12:20:20.700Z

Done running, computing static MPD(DASH time 7000 ms)
```

Finally, when I try to play this MPD back on gpac I always get the same error:

```
[DASH] File /media/psf/Home/Projects/linux_shell/dash_output/live_video_tiled_dash_trackX_Y.m4s not found on disk
[DASH] File /media/psf/Home/Projects/linux_shell/dash_output/live_video_tiled_dash_trackX_(Y+1).m4s not found on disk
[DASH] File /media/psf/Home/Projects/linux_shell/dash_output/live_video_tiled_dash_trackX_(Y+2).m4s not found on disk
.
.
.
[DASH] File /media/psf/Home/Projects/linux_shell/dash_output/live_video_tiled_dash_trackX_(Y+N).m4s not found on disk
```

Is this the correct way of doing this? Is this simply not supported? 

**Thank you for your great work!**

**GPAC**: version 1.1.0-DEV-rev276-g8f79ec5ab-master
**Kvazaar** v2.0.0-43-g4d41f417 2020-11-03

**Comment by jeanlf** [comment] 2020-11-30 08:17
Are you sure all the generated files have a 2s duration ? Could you upload samples ?

**Comment by franciscomfcmaia** [comment] 2020-11-30 09:56
Hello,

Thank you so much for your reply. I have uploaded them. I have also probed these files myself. 

These were the durations I was able to probe:

-  **FFMpeg Output : 2s**

- **MP4Box Output : 0.2s**

So my first instincts were to check if I was tiling the video correctly because **0.2 = 2 / (3x3 +1 )**.

I have uploaded them through the link provided at the top of the issue. Furthermore, I uploaded them here:

**http://www.mediafire.com/folder/qc6x5jlx2saei/github_upload_gpac**

Once again, thank you!

**Comment by a23232390** [comment] 2020-11-30 14:23
@franciscomfcmaia 
What server is applicable?
are you use Nginx?

**Comment by franciscomfcmaia** [comment] 2020-11-30 14:25
Hi @a23232390, I am not serving this. I am testing it locally.

**Comment by jeanlf** [comment] 2020-12-01 14:45
your raw hevc file is only 0.2 sec (I checked reimport with MP4Box and ffmpeg, same result)

**Comment by franciscomfcmaia** [comment] 2020-12-01 14:49
Hi @jeanlf thank you for your help. I will move this issue over to Kvazaar as this seems to be an issue with my tiling commands. 

**Before I close this issue**; Is this the correct usage of MP4Box Dash "-dash-live"? Calling it constantly at a given interval X like how I am doing above? _(Assuming my HEVC is actually of a correct interval)_

Thank you!

**Comment by jeanlf** [comment] 2020-12-01 15:07
For MP4Box yes.

You could use piping, using `stdin` source file (or any other named pipes):
`MP4Box -dash 1000 [...] -out live/live.mpd stdin"

This however won't work with tile spliting at the current time since it is not filter-based.

I'll look at kvazaar support (either directly or through libavcodec) to optimize this workflow, ultimately what I would like to have is a live tiled encoder with no temporary disk IOs, e.g. `gpac -i video:// enc:c=hevc:[kvazaar_opts] tilesplit @ -o live.mpd:dmode=dynamic`.
We could also make it work through piping using `gpac -i stdin tilesplit @ -o live.mpd:dmode=dynamic` 

But in either case, we need to have a tile spliter filter in place...

Let's keep this open for the time being

**Comment by franciscomfcmaia** [comment] 2020-12-01 15:13
@jeanlf, that would be beyond perfect! gpac has great pipe support, having a tile split filter would be perfect.

I will keep this open.

Once again, thank you for the great work!

**Comment by franciscomfcmaia** [comment] 2020-12-01 19:40
Hello again @jeanlf, I have corrected my capture above. 

I am now able to capture exactly 2s videos. I had to tweak some of the pixel formats to achieve this, but I can now dash them with no errors!

With this command : 

`MP4Box -dash-ctx dash_output/dash-live.txt -dash-live 2000 -run-for 1000 -no-frags-default -rap -frag-rap -insert-utc -mpd-refresh 1 -time-shift 2 -min-buffer 2 -bs-switching no -out dash_output/dash.mpd videos/live_video_tiled.mp4`

```
[Dasher] No template assigned, using $File$_dash$FS$$Number$
[Dasher] AS-1 Rep 1_2 segment 7 done 1831 ms before UTC due time
[Dasher] removing segment live_video_tiled_dash5.m4s
[Dasher] updated period DID3 duration 14000 MPD time 14000
[MPD] Generating MPD at time 2020-12-01T19:26:24.489Z
[Dasher] updated period DID3 duration 14000 MPD time 14000
[MPD] Generating MPD at time 2020-12-01T19:26:24.492Z

Done running, computing static MPDms (DASH time 14000 ms)

```

The issue is the same as the initial post now. Once a successful dash is completed I can see that the m4s file is incremented but not the tracks!

So, once a dash has completed this file is incremented.

**[Run 1] => "live_video_tiled_dash1.m4s"
[Run 2] => "live_video_tiled_dash2.m4s"
[Run 3] => "live_video_tiled_dash3.m4s"
[Run N] => "live_video_tiled_dashN.m4s"**

But the tracks remain the same across all "Dash".

[Run 1] => "live_video_tiled_dash_trackX_1.m4s"
[Run 2] => "live_video_tiled_dash_trackX_2.m4s"
[Run 3] => "live_video_tiled_dash_trackX_2.m4s"
[Run N] => "live_video_tiled_dash_trackX_2.m4s"

When I try to play this output with gpac I get this error: 

```
[DASH] File /media/psf/Home/Projects/linux_shell/dash_output/live_video_tiled_dash_trackX_Y.m4s not found on disk
[DASH] File /media/psf/Home/Projects/linux_shell/dash_output/live_video_tiled_dash_trackX_(Y+1).m4s not found on disk
[DASH] File /media/psf/Home/Projects/linux_shell/dash_output/live_video_tiled_dash_trackX_(Y+2).m4s not found on disk
.
.
.
[DASH] File /media/psf/Home/Projects/linux_shell/dash_output/live_video_tiled_dash_trackX_(Y+N).m4s not found on disk
```

It seems as though the gpac player is trying to seek tracks with no respect for the segment duration?

This is the MPD and the CTX after my successful dash: [https://app.mediafire.com/jfcygtysx40e7](https://app.mediafire.com/jfcygtysx40e7)

**Comment by jeanlf** [comment] 2020-12-01 21:32
I'll have a look at that.

Meanwhile (since that was fun to do) I added a `tilesplit`filter and [tests](https://github.com/gpac/testsuite/blob/filters/scripts/tilesplit.sh) here, so now you can pipe the output of kvazaar as input to a live  DASH session. Feedback more than welcome on this new feature ...

**Comment by franciscomfcmaia** [comment] 2020-12-01 22:07
@jeanlf, you definitely beat me to it! This is definitely the way forward! I am excited about this :) 

I will bring any feedback back to this issue!

**Comment by franciscomfcmaia** [comment] 2020-12-02 11:18
Hi @jeanlf, I have been following the past to commits on gpac master. Both have been working perfectly with the **"tilesplit".**

**stdin** - Had some issues due to some data coming in late.
**named pipes** - Works perfectly!!!

I have one final question; this is wishful thinking, but **is it possible to pipe in multiple representations?**

Awesome work!

**Comment by jeanlf** [comment] 2020-12-02 15:19
Getting there, here's my setup:

- ffmpeg compiled with Kvazaar support (--enable-libkvazaar in ffmpeg configure), check GPAC support using `gpac -h ffenc:libkvazaar`
- latest GPAC git (fixed a few issues with tile spliter and ffenc)

et voila ! :

```
gpac -i video:// enc:c=libkvazaar:b=1m:fintra=1:rc::kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin @ tilesplit @ -o live.mpd:dmode=dynamic
```
It also works by dropping some tiles on the fly using `tiledrop`option :)

I had some issues forcing Kvazaar to generate an IDR when using `fintra`, so I added `rc` option to ffenc to force codec destroy/recreate. It works well but is a bit resource heavy (especially when threads are used in the encoder), this will need more investigations...


Regarding your question on piping multiple representation, each input to the dasher can be a pipe or anything so yes it should work but it's not very elegant when your source is a camera (you need N processes to read from the video pipe).

Now that this can be integrated as filters, you could do multi-quality: 

```
gpac -+::kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin -i video:// enc:c=libkvazaar:b=1m:fintra=1:rc @ tilesplit:FID=1 enc:c=libkvazaar:b=1m:fintra=1:rc @ tilesplit:FID=2 -o live.mpd:dmode=dynamic:SID=1,2
```

Unfortunately (at least on my mac) opening a second instance of Kvazaar is not supported: error `Internal bug, should not have happened`). So maybe piping will be needed ...

**Comment by jeanlf** [comment] 2020-12-02 17:43
With multirate working- there is a small issue in the libavcodec wrapper triggering this error due to bitrate selection. The workaround is to pass the bitrate option as kvazaar opt:


```
gpac  -i video:// 
 enc:c=libkvazaar:fintra=1:rc::kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,bitrate=1000000 @ tilesplit:FID=1
 enc:c=libkvazaar:fintra=1:rc::kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,bitrate=200000 @ tilesplit:FID=2
 -o live.mpd:dmode=dynamic:SID=1,2

``` 

I'll ping our kvazaar friends on these identified issues.

**Comment by franciscomfcmaia** [comment] 2020-12-02 18:20
Hi @jeanlf!

I am amazed at the speed and quality of your work!!

I have done some testing on these last three commits. I am having an issue though. 

I have rebuilt FFmpeg from source and have enabled libKvazaar. 

When I try running any of the examples you kindly provided with I get this error printed out repeatedly on my shell.

```
Error Feature Not Supported while instantiating filter ffenc
```

Do I need to silence this error? Is this expected behavior?

Thank you once again :)

**Comment by jeanlf** [comment] 2020-12-02 18:29
Hmm no there should not be any error if you have the latest git recompiled.
What do `gpac -h ffenc` and `gpac -h ffenc:libkvazaar` report ?

**Comment by jeanlf** [comment] 2020-12-02 20:36
Found a nicer workaround which is to specify the rate control used in global options:

```
gpac  -i video://
 -+kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,rc-algorithm=lambda 
 enc:c=libkvazaar:fintra=1:rc:b=1m @ tilesplit:FID=1
 enc:c=libkvazaar:fintra=1:rc:b=200k @ tilesplit:FID=2
 -o live.mpd:dmode=dynamic:SID=1,2
```

Updated [guide](https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide#kvazaar-as-a-gpac-filter) based on this thread.

**Comment by franciscomfcmaia** [comment] 2020-12-02 20:55
Hi @jeanlf,

I did not want to start a new issue as having everything in one thread might help people in the future.

Quick question about the new **ffenc:libkvazaar**. Do we need to configure gpac with any special flags?

It seems as though gpac is not being able to find Kvazaar from ffmpeg.

 _**I can confirm that has been built with "--enable-libkvazaa". It can also be found by running `ffmpeg -encoders`**_

Thank you!

**Comment by jeanlf** [comment] 2020-12-02 21:31
no options needed for configure, but you should rerun configure / make for gpac (or edit ffmpeg ldflags in config.mak).

This is really strange, are you using a recent version of ffmpeg ?
You should have something like:

>% gpac -h ffenc:libkvazaar
>Description: libkvazaar H.265 / HEVC
>Version: Lavc58.81.100
>
>Options (basic):
>
>kvazaar-params (str):          Set kvazaar parameters as a comma-separated list of key=value pairs.


I'll have a look on an ubuntu vm to see if I can reproduce your problem.

**Comment by franciscomfcmaia** [comment] 2020-12-02 22:50
Indeed, @jeanlf it is most likely an issue with the ldflags.  I will keep trying to build it. Excited to try `enc:c=libkvazaar`!

Thank you for your awesome work!

**Comment by franciscomfcmaia** [comment] 2020-12-03 12:00
Hi @jeanlf,

I managed to fix the issue I had. It was rather simple. _As usual, the issue was with linking the libraries._

I have rebuilt FFmpeg and gpac on **Ubuntu 20.04** with no issues now! **For anyone in the future, don't follow FFMpeg's guide**.

Two aspects for anyone wanting to build GPAC and FFMpeg on Ubuntu 20.04:

1. For **GPAC** _(with unix_deps from [3.12.2020])_ you must modify your **scons** to use Python2.7. Just modify the head so instead of `/usr/bin/python3` -> `/usr/bin/python2`.

2. For FFMpeg do not follow the official guide. Libraries have to be shared in order to work. I made this scrip that **HELPED ME BUT MIGHT NOT HELP YOU**  [franciscomfcmaia/ffmpeg_build_libkvazaar_ubuntu_20.04/main/install.sh](https://raw.githubusercontent.com/franciscomfcmaia/ffmpeg_build_libkvazaar_ubuntu_20.04/main/install.sh).

I do not recommend using this script but you can use it as a reference. Hopefully, it helps!

**Now, for the fun part. On with the testing  of `enc:c=libkvazaar` :)**

**Comment by jeanlf** [comment] 2020-12-03 12:07
Good to hear 👍 
I made some cleanup on the HEVC tiled generated MPD in the process, old versions were half-baked in terms of dependency and init segments.
I have not yet tested dashing with multi-res tiled hevc though...

**Comment by franciscomfcmaia** [comment] 2020-12-04 13:27
Hi @jeanlf,

I have been following the past commits. I must say it works perfectly. I am trying to test this on multiple systems and here are my initial questions:

- **Single Bit-rate** 👍 

I have been able to test with the following commands:

``` 
ffmpeg -f v4l2 -input_format yuyv422 -framerate 10 -video_size 640x480 -i /dev/video0 -an -f rawvideo -pix_fmt yuv420p pipe: > ffmpeg1
```

```

**Comment by franciscomfcmaia** [comment] 2020-12-04 13:38
Hi @jeanlf,

I have been following the past commits. I must say it works perfectly. I am trying to test this on multiple systems and here are my initial questions:

- **Single Bitrate** 👍 

I have been able to test with the following commands:

``` 
ffmpeg -f v4l2 -input_format yuyv422 -framerate 10 -video_size 640x480 -i /dev/video0 -an -f rawvideo -pix_fmt yuv420p pipe: > ffmpeg1
```
```
kvazaar -i ffmpeg1 --input-res 640x480 --input-format P420 -o tiled1 --tiles 3x3 --slices tiles --mv-constraint frametilemargin --bitrate 10000 --period 10 --input-fps 10
```
```
gpac -i pipe://tiled1:#Bitrate=1m @ tilesplit:FID=1 -o dash_out/live.mpd:SID=1:dmode=dynamic
```
**Works flawlessly!**

- **Multi Bitrate** [Not fully tested]
 
With the latest **kvazaar** no errors are produced.  There is one issue. The dasher complains about the segments **coming late on some slower systems**.

```
gpac  -i video://
 -+kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,rc-algorithm=lambda 
 enc:c=libkvazaar:fintra=1:rc:b=1m @ tilesplit:FID=1
 enc:c=libkvazaar:fintra=1:rc:b=200k @ tilesplit:FID=2
 -o live.mpd:dmode=dynamic:SID=1,2
```

**Final questions **

- For debugging, is there a way we can control the capture resolution and fps to make sure that streams come slow enough for us to dash them? _(using `enc:c=libkvazaa`)_

- For debugging, is there any way we can run something like `gpac -i pipe://tiled1:#Bitrate=1m @ tilesplit:FID=1 @ -i pipe://tiled2:#Bitrate=10k @ tilesplit:FID=2 @ -o dash_out/live.mpd:SID=1:dmode=dynamic` so we have full control of both pipes?

I can see how some issues in regards to **segments coming late** will be created by people running on slower systems. **It would be interesting if people could test the capabilities of their own systems to ensure that multi-bitrate tiled dashing is feasible.**

Once again, fantastic work @jeanlf. No words! :)

**Comment by jeanlf** [comment] 2020-12-04 18:34
> For debugging, is there a way we can control the capture resolution and fps to make sure that streams come slow enough for us to dash them? (using enc:c=libkvazaa)

Yes. You can rescale the source by either:
-   changing the video settings - see [gpac -hx ffavin](https://github.com/gpac/gpac/wiki/ffavin)
- insert a rescaler filter [ffsws](https://github.com/gpac/gpac/wiki/ffsws) before your encoder, eg:

```
gpac  -i video:// ffsws:FID=S:osize=640x360 enc:SID=S:c=libkvazaar ...
```

> For debugging, is there any way we can run something like gpac -i pipe://tiled1:#Bitrate=1m @ tilesplit:FID=1 @ -i pipe://tiled2:#Bitrate=10k @ tilesplit:FID=2 @ -o dash_out/live.mpd:SID=1:dmode=dynamic so we have full control of both pipes?
 
Yes there is no limit on the number of pipes:

```
gpac 
 -i pipe://tiled1:#Bitrate=1m @ tilesplit:FID=1
 -i pipe://tiled2:#Bitrate=10k @ tilesplit:FID=2
 -o dash_out/live.mpd:SID=1,2:dmode=dynamic
```

I'm closing but don't hesitate to keep sending feedback/tips here as the issue is referenced in the guide.

**Closed by jeanlf** 2020-12-04 18:34 UTC
