### ISSUE TITLE
MP4Box generates not valid MP4 for DASH starting v.0.7.0

### ISSUE THREAD

**Issue by askoretskiy** [gpac/gpac#824] opened 2017-05-05 12:08 UTC
Starting  0.7.0 MP4Box no longer producing MP4 files that could be played using reference dash.js player.

I see the same error when generating DASH with gpac 0.7.0, 0.7.1 and master (as of 05.05.2017):

    # In javascript console
    Video Element Error: MEDIA_ERR_SRC_NOT_SUPPORTED (0x80004005: IsInitSegmentPresent: Invalid Top-Level Box:tfra)

Command:

    MP4Box -dash 4000 -rap -frag 4000 -frag-rap -profile dashavc264:onDemand -out my.mpd <list of 7 different MP4 files>

The same command produces working DASH playout using MP4Box from gpac version 0.6.1.

**Comment by boris-petrov** [comment] 2017-06-01 14:27
We have a similar problem. We use `MP4Box -dash 10000 -profile onDemand -out something.mpd` which doesn't work anymore on `Firefox` with `dash.js` and `video.js`. It used to work before.

**Comment by rbouqueau** [comment] 2017-06-02 12:03
Thanks for reporting.

I can't reproduce. It works in Chrome 58, Edge and Firefox 53 on W10 using dash.js 2.5.0. I use our DASH sequences as a source.

I also checked about the following message and couldn't see the according box:
> Video Element Error: MEDIA_ERR_SRC_NOT_SUPPORTED (0x80004005: IsInitSegmentPresent: Invalid Top-Level Box:tfra)

Could you please provide a sample input that triggers the issue?

**Comment by boris-petrov** [comment] 2017-06-02 14:00
Hi @rbouqueau,

These are the exact commands we use:

```
ffmpeg -i lego.mp4 -f mp4 -ar 44100 -ab 96k -pix_fmt yuv420p -filter:a aformat=s16:44100:stereo -vcodec libx264 -crf 25 -g 250 -coder 1 -flags +loop -filter:v scale=min(640\,iw):trunc(ow/a/2)*2 -strict -2 transcoded.mp4

ffmpeg -y -i transcoded.mp4 -map_metadata -1 -an -f mp4 -c copy audio-stream.mp4

MP4Box -crypt drm.key audio-stream.mp4 -out encrypted-video-stream.mp4

ffmpeg -y -i transcoded.mp4 -vn -f mp4 -acodec copy dash-audio-stream.mp4

MP4Box -dash 10000 -profile onDemand -out drm.mpd encrypted-video-stream.mp4 dash-audio-stream.mp4
```

[lego.zip](https://github.com/gpac/gpac/files/1047849/lego.zip)

The first command transcodes the video to a web-preview-friendly type. The second we extract the audio stream which we use in the encryption command. The fourth again to extract audio (we actually extract more stuff but I've removed them as they are irrelevant) and in the fifth command we generate the `mpd` file.

The resulting `mpd`:

```xml
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.7.1-revrelease  at 2017-06-02T13:44:21.646Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M5.570S" maxSegmentDuration="PT0H0M5.570S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>drm.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M5.570S">
  <AdaptationSet segmentAlignment="true" maxWidth="560" maxHeight="320" maxFrameRate="15360/515" par="560:320" lang="und" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="77fc8529-5f9e-4583-a0a6-7668d1f35bf2" />
   <Representation id="1" mimeType="video/mp4" codecs="avc1.64001E" width="560" height="320" frameRate="30" sar="1:1" startWithSAP="1" bandwidth="166411">
    <BaseURL>url-for-video-stream</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="1107-1150">
      <Initialization range="0-1106" />
    </SegmentBase>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" lang="eng" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="2" mimeType="audio/mp4" codecs="mp4a.40.2" startWithSAP="1" bandwidth="100254">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2" />
    <BaseURL>url-for-audio-stream</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="835-878">
      <Initialization range="0-834" />
    </SegmentBase>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

The result is that this is playable in `Chrome` but not in `Firefox`. Also, in FF, there is an error (which was also there before with `0.6.1` but didn't seem to matter):

```
XML Parsing Error: syntax error
Location: url-where-we-show-the-video-player-which-actually-returns-index.html
Line Number 1, Column 1:
```

If you need any more information, please just ask. :)

**Comment by rbouqueau** [comment] 2017-06-06 17:32
Ok thanks, I tried and couldn't reproduce. Since it involves encryption, it would be easier if you could upload some content on our confidential dropbox (https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95):
 - The DASH package that used to work, with the files prior to DASHing.
 - The DASH package that do not work anymore, with the files prior to DASHing.

I aim to check at 1) reproducing your issue and 2) check the ISOBMF structure of the files to catch the difference that causes the issue.

**Comment by askoretskiy** [comment] 2017-06-07 12:55
I have uploaded 2 sets of files:

old* -- source MP4 and resulting MPD and MP4 produced by GPAC 0.6.1
new* -- source MP4 and resulting MPD and MP4 produced by GPAC 0.7.1

**Comment by askoretskiy** [comment] 2017-06-07 12:56
Also I've included mp4box_try.sh that you could use to reproduce all the files.

**Comment by boris-petrov** [comment] 2017-06-07 14:15
Ok, I spent a horrible amount of time creating a reproducible version. I've attached the `zip` here.

[test.zip](https://github.com/gpac/gpac/files/1058259/test.zip)

It uses the same `lego` file from my previous comment. In this zip are:

`code.js` - my JS code for the video player.
`drm.key` - the key used to encrypt the video.
`drm.mpd` - the `mpd` file.
`index.html` - open this in Chrome to see it working and in FF to see it not working (be sure to use `localhost:3000/index.html`)
`server.js` - a Node.js server that serves the static files and returns all the correct headers/status codes needed for DRM to work.
The rest of the files are the minified libraries.

I hope this is enough to reproduce the problem.

**Comment by rbouqueau** [comment] 2017-06-13 17:13
@boris-petrov I've just spent one hour with your package, thanks for taking the time. It works in Chrome, not in FF which doesn't complain at all. I couldn't find why. Also I was not able to generate a package that would work with an older version of MP4Box ; by any chance, would you have the same package with the mpd&mp4s that work?

Comparing something that works with something that doesn't gives us precise clues thank you.

Now looking at the other package.

**Comment by rbouqueau** [comment] 2017-06-13 17:27
@askoretskiy Thanks for your script. The 'tfra' box is generated by the FFmpeg fragmentation with your options (probably a legacy from HSS). Why do you need FFmpeg to fragment the files?

I am going to have a look at why we're keeping them. Note that we generally try to keep the info from the primary muxing (such as metadata, encryption data, etc.).

**Comment by boris-petrov** [comment] 2017-06-14 09:39
@rbouqueau - I have a version of `gpac` which works with Firefox. Version 0.6.1. I've attached a zip file (because GitHub requires it) which inside has a `.tar.xz`. This is an installation package for Arch Linux.
 
[gpac.zip](https://github.com/gpac/gpac/files/1074154/gpac.zip)

With it and the same process the video file plays in FF. This is the resulting `mpd`:

```xml
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.6.2-DEV-rev61-gf48c7e4af-HEAD  at 2017-06-14T09:29:44.971Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M5.570S" maxSegmentDuration="PT0H0M5.570S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>something.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M5.570S">
  <AdaptationSet segmentAlignment="true" maxWidth="560" maxHeight="320" maxFrameRate="30" par="560:320" lang="und" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="c886ea10-ab87-40f0-af64-efc4f3787c3f" />
   <Representation id="1" mimeType="video/mp4" codecs="avc1.64001e" width="560" height="320" frameRate="30" sar="1:1" startWithSAP="1" bandwidth="163558">
    <BaseURL>lego-videoStream.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="1106-1149">
      <Initialization range="0-1105" />
    </SegmentBase>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" lang="eng" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="2" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="44100" startWithSAP="1" bandwidth="100218">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2" />
    <BaseURL>lego-audioStream.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="850-893">
      <Initialization range="0-849" />
    </SegmentBase>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

Do you need any more help with reproducing it?

**Comment by rbouqueau** [comment] 2017-06-14 14:00
@boris-petrov I could reproduce your issue

**Comment by boris-petrov** [comment] 2017-06-14 14:19
@rbouqueau - great, glad to hear it! I hope you can fix it as this is a rather big issue. Do you suggest we use v0.6.1 until you've figured it out? And you owe me a beer for the reproductions. :)

**Comment by rbouqueau** [comment] 2017-06-14 14:31
@boris-petrov I can only advise to stay on a working version. I sent an email to the appropriate contributors to make the fix, it may take quite some time. With pleasure for the beer :)

**Comment by jeanlf** [comment] 2017-06-15 11:43
This should now be fixed could you check it works fine for you?

**Comment by askoretskiy** [comment] 2017-06-16 08:23
@jeanlf What branch / tag we should try?

**Comment by jeanlf** [comment] 2017-06-16 11:08
master as of  15/06/2017

**Comment by askoretskiy** [comment] 2017-06-17 13:42
@rbouqueau Do you want to say that I don't need to fragment MP4 with ffmpeg before giving it to MP4Box? I.e. it would fragment itself?

BTW, would there ever be an option to produce fragmented DASH with ffmpeg? At the moment it produces only "normal" DASH with dozens of .TS files.

**Comment by askoretskiy** [comment] 2017-06-17 14:31
@rbouqueau Do you want to say that I don't need to fragment MP4 with ffmpeg before giving it to MP4Box? I.e. it would fragment itself?

BTW, would there ever be an option to produce fragmented DASH with ffmpeg? At the moment it produces only "normal" DASH with dozens of .TS files.

**Comment by askoretskiy** [comment] 2017-06-17 14:33
Version from master branch does not resolve the problem.

Video is still not playable, shows an error:

> Video Element Error: MEDIA_ERR_SRC_NOT_SUPPORTED (NS_ERROR_FAILURE (0x80004005) - virtual mozilla::MediaResult mozilla::MP4ContainerParser::IsInitSegmentPresent(mozilla::MediaByteBuffer *): Invalid Top-Level Box:tfra)

**Comment by askoretskiy** [comment] 2017-06-17 14:43
I have extended the script to include reproduce steps. See attachment (sorry, GitHub does not allow SH files).
[mp4box_try.zip](https://github.com/gpac/gpac/files/1082583/mp4box_try.zip)

**Comment by rbouqueau** [comment] 2017-06-17 14:50
> @rbouqueau Do you want to say that I don't need to fragment MP4 with ffmpeg before giving it to MP4Box? I.e. it would fragment itself?

Yes, that's the reason why it doesn't work for you. MP4Box tries to respect the metadata that you provide, and the one from FFmpeg isn't compatible with browsers.

**Comment by askoretskiy** [comment] 2017-06-17 14:52
I've just tried with no fragmentation from ffmpeg -- with the same result. Trying without explicit MOOV flags...

**Comment by askoretskiy** [comment] 2017-06-17 15:08
Just confirmed -- it works both on v0.7.1 and master branch.

**Comment by rbouqueau** [comment] 2017-06-18 13:40
@askoretskiy Thanks for the quick feedback.

@boris-petrov Please close the issue if it is also ok for you.

**Comment by boris-petrov** [comment] 2017-06-19 09:15
Yes, `master` seems to work for me also. I cannot close the issue as I'm not the author. Do you intend to release a new version soon?

**Comment by jeanlf** [comment] 2017-06-19 11:14
yes we will release a new version very soon as this is a nasty bug. Closing the issue.

**Closed by jeanlf** 2017-06-19 11:14 UTC
Labels: bug, mp4box
