### ISSUE TITLE
Remove cover art

### ISSUE THREAD

**Issue by svnpenn** [gpac/gpac#990] opened 2018-02-19 04:42 UTC
You can set cover art like this

~~~
mp4box -itags cover=1.jpg 1.m4a
~~~

However none of these remove it

~~~
mp4box -itags cover= 1.m4a
mp4box -itags cover=0 1.m4a
mp4box -itags cover=NULL 1.m4a
~~~

this works, but it removes all tags

~~~
mp4box -itags all=NULL 1.m4a
~~~

**Comment by aureliendavid** [comment] 2018-02-19 09:34
you're right that 

`mp4box -itags cover=NULL 1.m4a`

should work but didn't. 

should be fixed now, please reopen if the problem is still present

**Comment by svnpenn** [comment] 2018-02-19 12:34
@aureliendavid no, its worse now

~~~
$ mp4box -version
MP4Box - GPAC version 0.7.2-DEV-rev417-g31185cbf-master
(c) Telecom ParisTech 2000-2018 - Licence LGPL v2
GPAC Configuration: (static configuration file)
Features: GPAC_64_BITS GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY
GPAC_HAS_JPEG GPAC_HAS_PNG

$ mp4box -itags cover=NULL 1.m4a
Setting up iTunes/iPod file...
Segmentation fault

$ mp4box -itags cover= 1.m4a
Setting up iTunes/iPod file...
Segmentation fault
~~~

**Comment by aureliendavid** [comment] 2018-02-19 12:46
hm, for me it used to segfault before the fix and now it doesn't

can I see your 1.m4a file maybe it has something special?

**Comment by svnpenn** [comment] 2018-02-19 12:50
@aureliendavid here is a full example:

~~~
$ youtube-dl --write-thumbnail --format m4a --output 1.m4a Aio_UkAJtoI
[youtube] Aio_UkAJtoI: Downloading webpage
[youtube] Aio_UkAJtoI: Downloading video info webpage
[youtube] Aio_UkAJtoI: Extracting video information
[youtube] Aio_UkAJtoI: Downloading thumbnail ...
[youtube] Aio_UkAJtoI: Writing thumbnail to: 1.jpg
[download] Destination: 1.m4a
[download] 100% of 4.61MiB in 00:00
[ffmpeg] Correcting container in "1.m4a"

$ mp4box -itags cover=1.jpg 1.m4a
Setting up iTunes/iPod file...
Saving 1.m4a: 0.500 secs Interleaving

$ mp4box -itags cover=NULL 1.m4a
Setting up iTunes/iPod file...
Segmentation fault
~~~

**Comment by aureliendavid** [comment] 2018-02-19 13:04
well it does work properly for me on both windows and linux (apart from the fact that can't download the `Aio_UkAJtoI` youtube vid for some reason so I test with the similar `ZKfEzadyrO0`) 

are you sure you rebuilded the latest revision properly?

**Comment by svnpenn** [comment] 2018-02-19 13:11
@aureliendavid its only segfaulting with the 64-bit version of Mp4Box - the 32-bit version works

**Comment by aureliendavid** [comment] 2018-02-19 13:14
this is very weird since I'm only testing with 64bits versions..

are you using installers from https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/ or building from git?

**Comment by svnpenn** [comment] 2018-02-19 13:17
works

http://download.tsi.telecom-paristech.fr/gpac/new_builds/win32/gpac-0.7.2-DEV-rev418-gef47f60e-master-win32.exe

dont work

http://download.tsi.telecom-paristech.fr/gpac/new_builds/win64/gpac-0.7.2-DEV-rev418-gef47f60e-master-x64.exe

**Comment by svnpenn** [comment] 2018-02-19 13:19
works

http://download.tsi.telecom-paristech.fr/gpac/new_builds/win32/gpac-0.7.2-DEV-rev418-gef47f60e-master-win32.exe

dont work

http://download.tsi.telecom-paristech.fr/gpac/new_builds/win64/gpac-0.7.2-DEV-rev418-gef47f60e-master-x64.exe

maybe it has something to do with Visual C++?

**Comment by aureliendavid** [comment] 2018-02-19 13:21
wow you're right

it has to do with the different VS version to build the installers and the one I'm using for testing

hang on, i'll check on the build machine

**Comment by aureliendavid** [comment] 2018-02-19 14:10
argh this is so dumb.. 

VS2010 is less forgiving with uninitialized pointers compared to 2017 or gcc. 

I pushed a fix (7a0fe4e1fec6bd2ed10eb32159e2b2b25f51aa34), you can try : http://download.tsi.telecom-paristech.fr/gpac/new_builds/win64/gpac-0.7.2-DEV-rev419-g7a0fe4e1-master-x64.exe

sorry for the confusion and thanks for the report

**Comment by svnpenn** [comment] 2018-02-19 14:28
@aureliendavid I will try it on lunch - thanks

in regards to the VS issue - cant you just start requiring the newer version?

**Comment by svnpenn** [comment] 2018-02-20 05:00
@aureliendavid confirmed fixed - using either of these - thanks

~~~
$ mp4box -itags cover=NULL 1.m4a
Setting up iTunes/iPod file...
Saving 1.m4a: 0.500 secs Interleaving
~~~

~~~
$ mp4box -itags cover= 1.m4a
Setting up iTunes/iPod file...
Saving 1.m4a: 0.500 secs Interleaving
~~~

**Closed** 2018-02-20 07:59 UTC
