### ISSUE TITLE
TTML muxing should be able to merge timed elements

### ISSUE THREAD

**Issue by sdroege** [gpac/gpac#654] opened 2016-10-04 10:36 UTC
Currently each timed element is put into its own sample, with the whole XML boilerplate around it. That's repetitive, wasteful and usually not required.

It would be good to at least have an parameter to override this, and e.g. write the whole TTML stream into a single sample, or all timed elements for a single MP4 fragment into a single sample inside that fragment, or e.g. make samples of 1 minute duration.

**Comment by rbouqueau** [comment] 2016-10-09 22:14
I am not sure to understand the issue. Could you detail the use-case?

> write the whole TTML stream into a single sample

That's the default behaviour for all TTML profiles in GPAC (except EBU-TTD, which is indeed imported). See http://gpac.io/2014/08/23/ebu-ttd-support-in-gpac/ for more information.

> That's repetitive, wasteful and usually not required.

We agree this is widely suboptimal. But that's doubly required:
 1) by the spec MPEG4 part 30 ;
 2) by the DASH-ing process, which does not reencode the content (hence having the full TTML document in one sample would lead to the duplication if the full TTML in all DASH segments).

Please make sure you read http://www.gpac-licensing.com/2016/03/21/guidelines-on-how-to-embed-ttml-in-mp4-and-dash/ . It is possible to open issues on the github tracker to discuss these subjects with more than the GPAC team :)

**Comment by sandersaares** [comment] 2016-10-10 08:11
I believe a useful interpretation here would be "Merge the whole TTML stream **of one segment** into a single sample". This would provide some gains (though, in the big picture, the size of text streams is so trivial that I wonder if it is worth the effort).

**Comment by rbouqueau** [comment] 2016-10-10 08:56
@sandersaares I am still not sure to get it. Do you mean trying to merge the samples within a segment? When would this merging occur according to you (authoring, import/packaging, dashing, ...)?

**Comment by sandersaares** [comment] 2016-10-10 10:33
Yes, exactly. If there are multiple TTML samples within a segment, they can be merged to save some trivial amount of bytes and to avoid duplication of some XML.

I would envision this to be a part of the packaging (dashing) process.

**Comment by rbouqueau** [comment] 2016-10-10 10:43
Thank you. To know more about the workflow of subtitles, please read: https://github.com/rbouqueau/TTML_in_MP4_DASH_statement/blob/master/README.md

The packager can either:
 1) Isolate each timing inside a sample (EBU-TTD) (which forces us to change the syntax without changing the semantics).
 2) Take the full TTML (all other TTML profiles) within one sample.
 3) Use NHML to provide MP4Box with preprocessed content (see https://concolato.wp.mines-telecom.fr/2014/01/27/first-attempt-at-storing-ttml-in-mp4/).

The packager could use 1) to group some samples (the syntax could be ugly if we put a time argument on the top of this but why not). Or the author could pre-process the content and use 3).

The segmenter won't re-encode the content (same as for any other codec). It will just put the appropriate signalling at the MP4 level. So the TTML content needs to be prepared (either at 1) or 3)).

IMO the issue is that we have no "TTML preprocesor" that would be able to merge or split TTML documents. Given the complexity of TTML and all its profiles, we would need an external contribution or a sponsorship to make it work in an easy and reliable way. Any idea or comment welcome.

**Comment by nigelmegitt** [comment] 2016-10-10 15:54
@sandersaares you may be interested to know that we are working on an EBU-TT Live to EBU-TT-D converter as part of http://ebu.github.io/ebu-tt-live-toolkit/ at the moment, which puts incoming EBU-TT Live documents onto a timeline and then extracts arbitrarily timed content from that timeline prior to converting it into EBU-TT-D. That would constitute such a TTML pre-processor. I'm hoping that we can merge the pull request for that in the next couple of days. 

The incremental work to do that for a set of EBU-TT-D samples would be small but is not on our roadmap - and I do not expect it to be. Just a hint...

**Comment by jeanlf** [comment] 2019-06-28 17:14
seems using  http://ebu.github.io/ebu-tt-live-toolkit/  will do the trick, closing for now

**Closed by jeanlf** 2019-06-28 17:14 UTC
Labels: bug, mp4box, subtitle

**Comment by nigelmegitt** [comment] 2019-07-01 08:24
@jeanlf have you done any testing or any other work to establish that the whole workflow will work using the EBU-TT LIT as you suggest? I don't believe it can generically manipulate EBU-TT-D documents, though it can do a large amount of the functionality if they are converted to EBU-TT Part 3 documents first.

**Comment by jeanlf** [comment] 2019-07-01 08:42
No we haven't (I should have said "could do the trick" rather than "will").
Since we won't integrate any TTML preprocessor in the importer (at least not in the near future) and we don't have a bug here, I'm closing for now.
