### ISSUE TITLE
GPAC 0.9  Illegal instruction: 4

### ISSUE THREAD

**Issue by grylem** [gpac/gpac#1286] opened 2019-07-24 10:48 UTC
Hi
MP4Box - GPAC version 0.9.0-DEV-rev2612-g3df065da-filters  macOS

$ MP4Box -raw 1 -raw 2 test.mov
[iso file] Unknown box type load in parent trak
[iso file] Unknown box type stps in parent stbl
Illegal instruction: 4

$ MP4Box -add test.mov test.m4v
$ MP4Box -raw 1 -raw 2 test.m4v
[iso file] Unknown box type load in parent trak
Illegal instruction: 4

Regards.

**Comment by jeanlf** [comment] 2019-07-24 11:06
could you upload a sample file ?

**Comment by grylem** [comment] 2019-07-24 12:03
but you can try this file with similar errors from MP4Box
$ MP4Box -raw 1 -raw 2 test.mov
[iso file] Unknown box type mp4a in parent wave
Illegal instruction: 4

$ MP4Box -add test.mov test.mp4
$ MP4Box -raw 1 -raw 2 test.mp4
Illegal instruction: 4
[test.mov.zip](https://github.com/gpac/gpac/files/3426683/test.mov.zip)
P.S.
$ MP4Box -raw 1 -raw 2 test.mp4
makes mp4 with ftyp isom only.

**Comment by jeanlf** [comment] 2019-07-24 13:20
now fixed, thanks for the report. 
Not sure what you mean by "makes mp4 with ftyp isom only", that's the normal behaviour when using -add

**Closed by jeanlf** 2019-07-24 13:20 UTC

**Comment by grylem** [comment] 2019-07-24 14:14
@jeanlf
sorry but MP4Box - GPAC version 0.9.0-DEV-rev2620-ge12d1c31-filters
[iso file] Unknown box type load in parent trak
[iso file] Unknown box type stps in parent stbl
Illegal instruction: 4
[test.mov.zip](https://github.com/gpac/gpac/files/3427212/test.mov.zip)

About
ftyp for mp4 also can contain mp41 etc not only isom

**Comment by jeanlf** [comment] 2019-07-24 15:54
what is your command line ? I cannot reproduce here with any of the files you posted.

ftyp can indeed contain whatever you want, the importer only sets the default `isom` brand and some other brands when required by the tools used in the file. Use `-brand`, `-ab` `-rb` to adjust.

**Comment by grylem** [comment] 2019-07-24 19:24
ftyp doesn't care much for me

for the second uploaded file
MP4Box - GPAC version 0.9.0-DEV-rev2620-ge12d1c31-filters
$ MP4Box -raw 1 -raw 2 test.mov
[iso file] Unknown box type load in parent trak
[iso file] Unknown box type stps in parent stbl
Illegal instruction: 4

**Comment by jeanlf** [comment] 2019-07-25 07:42
nope, still working fine here (mac OS). Maybe something is wrong with your build, can you make clean and make ?

**Comment by grylem** [comment] 2019-07-25 12:04
I used version from https://gpac.wp.imt.fr/downloads/gpac-filters-branch/
but anyway now GPAC version 0.9.0-DEV-rev2633-ga9b2677d-filters work fine.
$ MP4Box -raw 1 -raw 2 test.mov
[iso file] Unknown box type load in parent trak
[iso file] Unknown box type stps in parent stbl
Exporting MPEG-4 AAC Audio - SampleRate 48000 2 channels 16 bits per sample
Exporting MPEG-4 AVC|H264 Video - Size 960x540 

Thanks.
