### ISSUE TITLE
Audio gradually goes out of sync when playing files repackaged with MP4Box

### ISSUE THREAD

**Issue by jocooza** [gpac/gpac#287] opened 2015-10-18 23:45 UTC
I use MP4Box on Ubuntu 12.04 64-bits to repackage TS files into MP4 files like this:

`$ MP4Box -add in.ts out.mp4`

A problem occurs with files obtained from a specific source. After being repackaged, the audio gradually goes out of sync. At the beginning audio is in sync, but after 5-10 minutes it's out of sync by one second. The problem is present when files are played in smart TV media players, but not VLC, MPlayer etc. I have tried TV's from multiple different vendors, and the problem occurs on all of them.

The problem does not occur if I use ffmpeg (0.8.17-4:0.8.17-0ubuntu0.12.04.1) from Ubuntu 12.04 repository, and repackage the files like this:

`$ ffmpeg -i in.ts -vcodec copy -acodec copy out.mp4`

    $ MP4Box -version
    MP4Box - GPAC version 0.5.2-DEV-rev719-g867374d-master
    GPAC Copyright (c) Telecom ParisTech 2000-2012
    GPAC Configuration: --static-mp4box --use-zlib=no
    Features: GPAC_64_BITS GPAC_DISABLE_3D GPAC_DISABLE_SWF_IMPORT

**Comment by rbouqueau** [comment] 2015-10-19 08:03
I am investigating. First the stream has similar issues as #211. Did you have the opportunity to run it through an analyzer? My assumption is that an incorrect input somehow could lead to an incorrect output.

Thanks for the sample. As you report I cannot reproduce your issue with VLC or the GPAC MP4Client player:
```MP4Box -add mp4box_issue_287.ts -new mp4box_issue_287.mp4```

Is there a way we can reproduce on a PC?

**Comment by jocooza** [comment] 2015-10-19 13:44
I have not tried to run the file through an analyzer. Can you recommend any specific?

So far all my efforts to reproduce on a PC has failed.

As ffmpeg produces a file that will play without sync problems and MP4Box does not, could we then somehow compare the output files and find out what ffmpeg does different from MP4Box?

**Comment by rbouqueau** [comment] 2015-10-19 18:04
Yes. ```MP4Box -diso file.mp4``` outputs a XML description of the MP4 file. It would really help if you could compare between FFmpeg and MP4Box.

**Comment by cconcolato** [comment] 2015-10-20 08:03
Please use another file upload service. This one is full of spam links. You can use:
https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95
adding the issue number in the title

**Comment by jocooza** [comment] 2015-10-20 16:33
> Please use another file upload service. This one is full of spam links.

Sorry, I wasn't aware of that.

All files should be uploaded to the dropbox within an hour.

**Comment by jeanlf** [comment] 2015-10-21 15:53
the ffmpeg file is not compliant for audio: the samples contains AAC frames encapsulated in ADTS which is not defined anywhere in the spec - can be fixed through (nhml export + aac re-import) 

playing source ffmpeg, fixed ffmpeg or source mp4box with ffplay give me the same bad sync output, hard to see (hear) what is wrong here ...

**Comment by jocooza** [comment] 2015-10-25 23:31
I have now written a program that can read a TS, change `adaptation_field_control` value to 0x02 if `adaptation_field_control` value is 0x03 and `adaptation_field_length` is 183 or discard the packet completely. I have tried both methods on issue_287.ts and although MP4Box no longer generates warnings like this:

`[MPEG-2 TS] TS Packet 530977 Detected wrong adaption field size 183 when control value is 3`

it has not changed anything regarding the sync issue.

**Comment by rbouqueau** [comment] 2016-10-09 22:16
I still get the assert on the latest file I downloaded + no news for a year => closing.

**Closed by rbouqueau** 2016-10-09 22:16 UTC
Labels: help wanted, mp4box

**Comment by seiya-git** [comment] 2018-01-12 16:09
I have same issue with `audio_issue_287.ts`, it's lost some audio fragments.
I get many errors like this:

`[MPEG-2 TS] TS Packet 121965 Detected wrong adaption field size 183 when control value is 3`
