### ISSUE TITLE
Dasher Time Server Uri with Params

### ISSUE THREAD

**Issue by jhlopezp** [gpac/gpac#2401] opened 2023-02-16 21:15 UTC
We are trying to specify a time server for a dasher filter using the `utcs` parameter, like this: `[opts]::utcs="xsd@https://time.akamai.com/?iso&ms"`, but that last `&ms` part of the uri causes the manifest to not include the AdaptationSet for the video track:

![image (1)](https://user-images.githubusercontent.com/125606672/219486725-7bfd7dbc-59cb-4b73-b20a-193cd87ac85e.png)

The full command is this:
`gpac -i [some_rtmp_input] -o [some_playlist.mpd]:gpac:dual:segdur=2.0:buf=-100:hlsc=1:cmaf=cmfc:profile=live:dmode=dynamic:template=segment_$$(openssl rand -hex 5):hmode=push:rdirs=gmem::utcs="xsd@https://time.akamai.com/?iso&ms"`

We see that it works if we just use `[opts]::utcs=xsd@https://time.akamai.com/?iso`, but shouldn't it work with the `&ms` part?

**Comment by rbouqueau** [comment] 2023-02-17 09:12
I tried and it work here (Linux). I think that may be related to your terminal. Can you tell me more about your environment?

**Comment by jeanlf** [comment] 2023-03-13 08:59
Cannot reproduce on OSX or linux, closing. Please provide a reproducible setup (gpac info, os info ...)

**Closed by jeanlf** 2023-03-13 08:59 UTC
