### ISSUE TITLE
First CTS causes DASH streaming video delay

### ISSUE THREAD

**Issue by JuanMorenoS** [gpac/gpac#2367] opened 2022-12-23 21:46 UTC
Hello! 
I'm trying to generate a stream from ll-dash but when I do it gpac throws this : `[Dasher] First CTS 17160 in segment 9 drifting by 1.16 (more than half a segment duration) from segment time, consider reencoding or using segment timeline` or `[Dasher] Segment 34 duration 0.88 less than half DASH duration, consider reencoding or using segment timeline` which generates latency and the video is out of sync with the audio.  

I tried to put the `stl` option but the video does not look smooth and has enough latency. 

I thought it was due to CPU resources but everything is fine, I also tried to increase the gpac threads but I don't see any change in performance.

`gpac -i rtmp://<rtmp-server>/live -o http://<origin-server>:8080/live/public/playlist.mpd:gpac:segdur=2:cdur=0.2:asto=1.8:cmaf=cmfc:profile=dashif.ll:dmode=dynamic:template=segment_dash:rdirs=gmem:hmode=push:max_cache_segs=14 -threads=4`

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by rbouqueau** [comment] 2022-12-25 19:34
First could you confirm your GPAC version and OS?

Then is there a way to replicate or access your RTMP input?

**Comment by JuanMorenoS** [comment] 2022-12-25 19:41
Yes, I'm sorry I forgot to put that information. 

Version: version 2.3-DEV-rev2-gb0ad64301-master also I tried with 2.2 stable version 
OS: Mac and Linux 

And no.... the stream is not under my control.  sorry.

**Comment by rbouqueau** [comment] 2022-12-26 11:05
Would you be able to make a capture (e.g. a flv file) that we can replay to reproduce the issue? You can upload it anonymously to [our dropbox](https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95) (just make sure to mention the issue number).

**Comment by JuanMorenoS** [comment] 2022-12-26 16:31
Uploaded! 
let me know if you need anything

**Comment by rbouqueau** [comment] 2023-01-03 10:27
I was able to make some tests (when the stream is available), but I could not reproduce any issue. Could you let me know:
1. When the stream is up, and
2. How much time it takes for you to reproduce the issue?

All the errors I got were from disconnections from the RTMP server.

**Comment by rbouqueau** [comment] 2023-05-25 10:15
Is this issue still relevant?

**Comment by jeanlf** [comment] 2023-05-26 12:56
no follow-up, closing - will reopen if enough details to reproduce are give.

**Closed by jeanlf** 2023-05-26 12:56 UTC
