### ISSUE TITLE
Checking the actual data link rate of dash connection

### ISSUE THREAD

**Issue by hamodisaif17** [gpac/gpac#1763] opened 2021-04-28 19:05 UTC
We are trying to check what is the data link rate between the client and the server over the dash connection, not the estimated which is related to the representations given via the mpd file but the actual rate related to the actual BW of the service.

any ideas how to do that or if it is possible given the current implementation?

**Comment by rbouqueau** [comment] 2021-04-28 19:34
Stats are available when writing a custom adaptation algorithm (cf https://github.com/gpac/gpac/wiki/jsdash). I haven't found other ways to get access to it.

You could also compute it based on the logs: ```-logs=http@info``` seems to be the most useful.

**Comment by jeanlf** [comment] 2021-04-29 10:14
Could you describe a bit more what you are trying to do ?

If you define your own algo (JS or Python), the data rate is available in the API callbacks.

If you want to analyze the session, use `-logs=dash@info`

If you're just fiddling with the code, the data rate at the end of the segment transfer is stored in the DASH client [here](https://github.com/gpac/gpac/blob/master/src/media_tools/dash_client.c#L3493) .

Closing as this is not a bug, but feel free to continue the discussion here.

**Closed by jeanlf** 2021-04-29 10:14 UTC
