### ISSUE TITLE
1.0.0 build fails

### ISSUE THREAD

**Issue by lgbaldoni** [gpac/gpac#1508] opened 2020-06-16 08:38 UTC
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

Local developer path in distributed tree:
```
make[1]: *** No rule to make target '/Users/lefeuvre/code/gpac/include/gpac/filters.h', needed by '../modules/dektec_out/dektec_video_decl.o'.  Stop.
```
Building gpac 1.0.0 on openSUSE Tumbleweed linux. More details available if needed.

**Comment by jeanlf** [comment] 2020-06-16 08:40
did you do a complete reinstall `make uninstall && ./configure && make`?

**Comment by aureliendavid** [comment] 2020-06-16 08:57
I would also add a `make distclean` before the configure for good measure.

**Comment by ricardollovera** [comment] 2020-06-16 11:53
Hi, I also had the same issue. 
And I did your suggestions of cleaning the make, uninstall etc, I suppressed all the existing installations and I rebooted the pc to restart all over.
Making the jeanlf suggestion I think was the one that helped most.
**Anyway, the documentation for Build needs IMPROVEMENT,** since it is very confusing, this suggestion that really works, the actual doc (that doesnt) and the Build old doc. I think it has to be more visible.
My setup: 
#uname -a
Linux pc-01 4.11.12-100.fc24.x86_64 #1 SMP Fri Jul 21 17:35:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

#cat /etc/fedora-release
Generic release 24 (Generic)

My best regards,

**Comment by aureliendavid** [comment] 2020-06-16 12:22
I added these instructions in the doc

https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux#upgrading-from-a-previous-version

**Comment by jeanlf** [comment] 2020-06-16 12:33
and general intro on the topic added [here](https://github.com/gpac/gpac/wiki/Upgrading)

**Comment by rbouqueau** [comment] 2020-06-16 14:39
Isn't the confusion about putting the system folders, in particular /usr/local/include, before the local folder?

**Comment by jeanlf** [comment] 2020-06-16 15:32
indeed... now fixed - will re-tag 1.0.1 for tarballs

**Closed by jeanlf** 2020-06-16 15:32 UTC

**Comment by ricardollovera** [comment] 2020-06-16 18:07
Hi,

I tried now, build it all, but the ticket was closed too soon.

I get this error when I do "make install":



*dh_link /usr/local/share/gpac/res/gpac.png
/usr/local/share/pixmaps/gpac.pngmake: dh_link: Command not
foundMakefile:114: recipe for target 'install' failedmake: *** [install]
Error 127*
Always


As said, I had a Fedora, details in the other message before, and
particularly I had to restart procedure all over because for a dash chunked
generation I had this message while performing it (another problem)
*Adaptation sets in period are of unequal duration min 545.994 max 937.96
seconds (in loop and of course varying the quantity of the the min/max)*
So a regression against MP4Box - GPAC version 0.8.0-rev267-gd9d3533-master
but I have to be more sure Install is good with all extra dep for linux.


I am trying a correct full install also because if I didn't, then the old
0.62 or something like that in the system was taking over. (TY very much
for the change of the Upgrading Versions Documentation)



BTW,  you could improve DOCUMENTATION adding this optional command:
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/gpac_public/bin/gcc

And Deleting this web page or section:
https://github.com/gpac/gpac/wiki/GPAC-build-MP4Box-only-all-platforms
Or specify which version deserves it.


  Regards,

**Comment by rbouqueau** [comment] 2020-06-16 19:43
> And Deleting this web page or section:
https://github.com/gpac/gpac/wiki/GPAC-build-MP4Box-only-all-platforms
Or specify which version deserves it.

Hi, thanks for taking the time to report the issues. Very valuable for the community.

I've tried the instructions and the static mp4box build seems to work. Please do not hesitate to give more information if you have any additional issue.

**Comment by aureliendavid** [comment] 2020-06-16 19:49
> I get this error when I do "make install": *dh_link /usr/local/share/gpac/res/gpac.png /usr/local/share/pixmaps/gpac.pngmake: dh_link: Command not foundMakefile:114: recipe for target 'install' failedmake: *** [install] Error 127* Always

see https://github.com/gpac/gpac/issues/1510#issuecomment-644954731 for reference

**Comment by rbouqueau** [comment] 2020-06-17 10:22
I put a prefix in my local folder (```./configure --static-mp4box --use-zlib=no --prefix=/home/rbouqueau/works/gpac/tmp && make -j && make install```). I went into this error:

```
ln -sf /home/rbouqueau/works/gpac/tmp/share/gpac/res/gpac.png /usr/share/pixmaps/gpac.png
ln: impossible de créer le lien symbolique '/usr/share/pixmaps/gpac.png': Permission non accordée
make: *** [Makefile:141: install] Error 1
```

Looks similar to me but I had missed the fact that we try to write in /usr/share while giving a local prefix. Let me know if I should open a separate issue.

**Comment by aureliendavid** [comment] 2020-06-17 10:57
you are correct, that's my bad

should be fixed now
