### ISSUE TITLE
First Letter of -name Sometimes Gets Cut Off

### ISSUE THREAD

**Issue by LeeThompson** [gpac/gpac#1416] opened 2020-02-19 22:25 UTC
I haven't yet found a reliable way to reproduce this issue, and for that I deeply apologize.

I rip my DVD collections for personal use as mp4 with HEVC compression is much less cumbersome than watching directly from the discs.    Although most of the playback software does not pay any attention to the name of the audio tracks, for commentaries and other features I name the track for reference purposes.

Sometimes, something odd happens (I've changed the names here to be generic ones) when doing `mp4box _file_ -name _tracknumber_ "Commentary with the Writer & Producer"`, the C in "Commentary" will be cut off.    Oddly, if I use lowercase "commentary" it works fine - well other than having commentary be lower case.    This happens fairly rarely (I've had this happen maybe... 4 times in the past year)  and I have no idea what any of the affected files have had in common.  

```
Audio #4
ID                                       : 5
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 22 min 21 s
Source duration                          : 22 min 21 s
Bit rate mode                            : Constant
Bit rate                                 : 160 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 25.6 MiB (9%)
Source stream size                       : 25.6 MiB (9%)
Title                                    : ommentary with the Writer & Producer
```

Builds Tested:
```
GPAC version 0.8.0-rev177-g51a8ef87-master
GPAC version 0.8.0-rev95-g00dfc9336-ab-suite
```

**Comment by jeanlf** [comment] 2020-03-02 15:41
I cannot reproduce here, could you share a sample faulty file?

**Comment by LeeThompson** [comment] 2020-03-03 07:59
@jeanlf I will try, unfortunately it's only happened on my own personal backups of commercial media.  If I'm ever able to find out what makes it happen; I should be able to submit a public domain sample with the issue.   (I would've waited before submitting this but maybe someone else will have better luck.)

**Comment by jeanlf** [comment] 2020-09-03 15:04
Now that I think of it, this reminds me of this [related fix](https://github.com/gpac/gpac/commit/97fdd03749b8de29b6ebae1ecfd62bc0715eaeca) - here's my insight:
- QTFF uses length-counted strings for handler name, eg `bit(8) len + bit(8)string[len]`
- ISOBMFF uses null-terminated strings for handler name

So mp4 softwares usually try to guess the format used, and they could be confused when the first character of the string matches the amount of bytes left in the box (eg chars in the string). 
My 2c is that we are not truncating the string (I carefully just checked so), but that your visualization software has this issue. Next time you encounter this:
- do an hex check on the file to see that all chars are indeed present
- backup your file  

As I don't think this comes from our side, I'm closing this.

**Closed by jeanlf** 2020-09-03 15:04 UTC

**Comment by LeeThompson** [comment] 2020-09-03 21:16
That is a possibility, the tool I use is mediainfo (unfortunately I don't know of any good alternatives).    And while I've never seen it happen with MKV, MP4 is a completely different container structure so... a possibility.

**Comment by LeeThompson** [comment] 2020-09-21 20:40
I believe you are correct, I finally had it happen again and looked at the file in hex mode and the full text is there.

```
000ABA30  00 00 00 00 00 00 00 00 00 00 04 7B 8C 6D 64 69    ...........{mdi
000ABA40  61 00 00 00 20 6D 64 68 64 00 00 00 00 DB 8E AB    a... mdhd....Û«
000ABA50  8B DB 8E AB 8C 00 00 BB 80 03 EE 44 00 15 C7 00    Û«..».îD..Ç.
000ABA60  00 00 00 00 65 68 64 6C 72 00 00 00 00 00 00 00    ....ehdlr.......
000ABA70  00 73 6F 75 6E 00 00 00 00 00 00 00 00 00 00 00    .soun...........
000ABA80  00 43 6F 6D 6D 65 6E 74 61 72 79 20 77 69 74 68    .Commentary with
000ABA90  20 4A 61 63 6B 73 6F 6E 20 50 75 62 6C 69 63 6B     Jackson Publick
000ABAA0  2C 20 44 6F 63 20 48 61 6D 6D 65 72 20 61 6E 64    , Doc Hammer and
000ABAB0  20 41 63 74 6F 72 20 4A 61 6D 65 73 20 55 72 62     Actor James Urb
000ABAC0  61 6E 69 61 6B 00 00 04 7A FF 6D 69 6E 66 00 00    aniak...zÿminf..
```

Mediainfo:
```
Audio #3
ID                                       : 4
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 22 min 53 s
Bit rate mode                            : Variable
Bit rate                                 : 160 kb/s
Maximum bit rate                         : 165 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 26.2 MiB (10%)
Title                                    : ommentary with Jackson Publick, Doc Hammer and Actor James Urbaniak
Language                                 : English
Encoded date                             : UTC 2020-09-21 19:12:11
Tagged date                              : UTC 2020-09-21 20:31:49
```

So this appears to be a mediainfo bug.
