### ISSUE TITLE
Invalid IsoMedia Error in Drone Recording

### ISSUE THREAD

**Issue by thealphadollar** [gpac/gpac#1030] opened 2018-04-10 07:13 UTC
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**ISSUE CONTENT**

This issue originates at https://github.com/CCExtractor/ccextractor/issues/961

**Video file:** *https://drive.google.com/file/d/1MyABc8cByEWcW9wQkl_Y_JIUYGC-Kd_5/view?usp=sharing*

MP4 recorded from a drone (specifically: "Zenmuse camera on a DJI Inspire 2 Drone"). The telemetry data is saved as subtitles and in fact VLC can display it.

Using MP4Box from libGPAC to extract information from the MP4 file fails with the following error,

![screenshot from 2018-04-09 01-19-34](https://user-images.githubusercontent.com/32812320/38541071-9237f37e-3cbb-11e8-8932-de1b2d9d74db.png)

**Background:** 
At CCExtractor we use libGPAC to process MP4 files and extract subtitles from them and we have failed at this file. The problem seems that libGPAC is not able to process the file and thus throws an error.

**To reproduce:**
- Download the video file
- Install MP4Box
- Use the following command from the video file's directory
```
MP4Box -info DJI_0019.MP4
```

**Comment by cconcolato** [comment] 2018-04-13 23:51
Thank you for the report. I can indeed reproduce the problem. The file is called MP4 (and even declares the ISO brands) when in fact it looks like a QuickTime file (use of the 'wide' box, 'text' handler, 'text' sample entry ...). According to the QT specification, the 'text' sample entry should be at least 51 bytes long. In your case it isn't that long, so MP4Box considers the box invalid.

**Comment by jeanlf** [comment] 2018-04-16 14:31
This should now be fixed on git, thanks for the file

**Closed by jeanlf** 2018-04-16 14:31 UTC
