### ISSUE TITLE
Filters branch mp4box fails to mux .eac3 -file into .mp4 container

### ISSUE THREAD

**Issue by ndwhyy** [gpac/gpac#1394] opened 2020-01-19 16:34 UTC
When trying to mux E-AC-3 file into mp4 with version "gpac-0.9.0-DEV-rev3136-g7b1805e3-filters-x64", I'm getting the following loop of errors on 64-bit Windows 10 v1909. 

I'm not sure in which build was this broken, but the same command works on version "gpac-0.9.0-DEV-rev2882-g045c7de1-filters-x64" which I still have.

The loop just goes on and on unless I terminate the process manually.

```
C:\gpac-0.9.0-DEV-rev3136-g7b1805e3-filters-x64>mp4box -add "audio_ddp.eac3" "audio.mp4"
[AC3Dmx] 3071 bytes unrecovered before sync word
[AC3Dmx] 3070 bytes unrecovered before sync word
[AC3Dmx] 3069 bytes unrecovered before sync word
[AC3Dmx] 3068 bytes unrecovered before sync word
...
...
[AC3Dmx] 18 bytes unrecovered before sync word
[AC3Dmx] 17 bytes unrecovered before sync word
[AC3Dmx] 16 bytes unrecovered before sync word
[AC3Dmx] 15 bytes unrecovered before sync word
[AC3Dmx] 14 bytes unrecovered before sync word
[AC3Dmx] 13 bytes unrecovered before sync word
[AC3Dmx] 12 bytes unrecovered before sync word
[AC3Dmx] 11 bytes unrecovered before sync word
[AC3Dmx] 10 bytes unrecovered before sync word
[AC3Dmx] 9 bytes unrecovered before sync word
[AC3Dmx] 8 bytes unrecovered before sync word
[AC3Dmx] 7 bytes unrecovered before sync word
[AC3Dmx] 6 bytes unrecovered before sync word
[AC3Dmx] 5 bytes unrecovered before sync word
[AC3Dmx] 4 bytes unrecovered before sync word
[AC3Dmx] 3 bytes unrecovered before sync word
[AC3Dmx] 2 bytes unrecovered before sync word
[AC3Dmx] 1 bytes unrecovered before sync word
[AC3Dmx] 3071 bytes unrecovered before sync word
[AC3Dmx] 3070 bytes unrecovered before sync word
[AC3Dmx] 3069 bytes unrecovered before sync word
[AC3Dmx] 3068 bytes unrecovered before sync word
[AC3Dmx] 3067 bytes unrecovered before sync word
[AC3Dmx] 3066 bytes unrecovered before sync word
...
...
```

**Comment by jeanlf** [comment] 2020-01-20 07:42
could you upload a sample file?

**Comment by anddilolz** [comment] 2020-01-20 09:20
> 
> 
> could you upload a sample file?

Sure! I just tried with [any .eac3 -file from ffmpeg samples, will these do](https://samples.ffmpeg.org/A-codecs/AC3/eac3/)? They all give they same error. I can upload a sample as well if needed!

**Comment by jeanlf** [comment] 2020-01-21 13:52
indeed, the EC-3 parsing was pretty broken! this should now be fixed, thanks for the report. Could you check and close?

This was not visible before since EC-3 was parsed by FFMPEG demux, and we moved it back to GPAC demux not long ago. 
Note that you can still use FFMPEG demux for your inputs by specifying `gfref=ffdmx` for your input - using MP4Box you will need to add `:sopt:gfreg=ffdmx`

**Comment by anddilolz** [comment] 2020-01-21 21:23
> indeed, the EC-3 parsing was pretty broken! this should now be fixed, thanks for the report. Could you check and close?
> 
> This was not visible before since EC-3 was parsed by FFMPEG demux, and we moved it back to GPAC demux not long ago.
> Note that you can still use FFMPEG demux for your inputs by specifying `gfref=ffdmx` for your input - using MP4Box you will need to add `:sopt:gfreg=ffdmx`

I can indeed confirm the latest filters build now muxes E-AC-3 files into mp4 without a hitch!

My pleasure, thanks for fixing it so quickly and the explanation for why it was broken.

**Comment by gacopl** [comment] 2022-02-26 10:16
@anddilolz sorry to reopen but when i use this flag it indeed helps but then the :lang setting stops to work is there anyway to workaround it ?

**Comment by gacopl** [comment] 2022-02-26 11:28
seems like using -lang $trackid=eng switch is only option as rest of the input filter is ignored with ffdmx

**Comment by jeanlf** [comment] 2022-03-07 09:34
could you please post a sample file and your command line ?

**Comment by gacopl** [comment] 2022-03-07 09:46
this is with 1.0.1 as with 2.0 that :sopt:gfreg=ffdmx doesnt seem to work at all
regarding sample file this happens with any file when ffdmx is engaged :lang filter does not work the resulting file doest not have lang set

**Comment by jeanlf** [comment] 2022-03-07 13:12
> this is with 1.0.1 as with 2.0 that :sopt:gfreg=ffdmx doesnt seem to work at all

It's working here, you can check the import graph using `-graph`.  We however had a bug forcing ffdmx for eac3 parsing (now fixed).

The language tagging is independent from the media import filters used, so you should not need to use the global '-lang' switch:

```
MP4Box -add bitstream.ec3:lang=fr -new dst.mp4
MP4Box -add bitstream.ec3:lang=fr:sopt:gfreg=ffdmx -new dst.mp4
```

> regarding sample file this happens with any file when ffdmx is engaged :lang filter does not work the resulting file doest not have lang set

Sorry but I can't reproduce (tested with ac3, eac3, aac+adts), the language tag is present. Maybe an issue with your command line?

**Comment by ndwhyy** [comment] 2022-12-28 13:29
Hello again! It's been a while, but I think EC-3 parsing is broken (or just not supported?) with certain files ( 7.1 EAC-3 ). I'm on version 2.2-rev0-gab012bbf-master. 

Sample files from a Dolby demo, encoded from TrueHD 7.1 to E-AC3 7.1 one with DEE and one with EAE: [https://we.tl/t-nF6XUT5KSM](https://we.tl/t-nF6XUT5KSM)

```
C:\GPAC>mp4box -add Dolby_Universe_4K_SDR_71-Atmos-thedigitaltheater-DEE.eac3 DEE.mp4
Track Importing EAC-3 - SampleRate 48000 Num Channels 6
[AC3Dmx] Trashing 10424 garbage bytes0)
[AC3Dmx] Trashing 10600 garbage bytes
[AC3Dmx] Trashing 11024 garbage bytes
[AC3Dmx] Trashing 12128 garbage bytes
[AC3Dmx] Trashing 10264 garbage bytes
...
...
[AC3Dmx] Trashing 11200 garbage bytes
[AC3Dmx] Trashing 11624 garbage bytes0)
[AC3Dmx] Trashing 12048 garbage bytes
[AC3Dmx] Trashing 10184 garbage bytes
[AC3Dmx] Trashing 10608 garbage bytes
[AC3Dmx] Trashing 11032 garbage bytes
..
```

Clearly it parses the channel count incorrectly, as it says above. If I mux to mp4 first with ffmpeg and then mux again with mp4box, everything works just fine! Also the `:sopt:gfreg=ffdmx` switch didn't work for me at all.

**Comment by jeanlf** [comment] 2023-01-04 11:25
Indeed these configurations were not properly supported, this should now be fixed.

Using `MP4Box -add source.eac3:sopt:gfreg=ffdmx -new test.mp4` works fine here, maybe you have an install without ffmpeg support - check `gpac -h ffdmx`

**Closed by jeanlf** 2023-01-04 11:25 UTC
