### ISSUE TITLE
Compiling on recent debian/Ubuntu versions

### ISSUE THREAD

**Issue by s0m30n3** [gpac/gpac#1210] opened 2019-02-24 15:25 UTC
Hi,

I'd like to use the gpac library for a project of my own.
Packages provided by Debian (buster) and Ubuntu (18.10) are too old for me so I have to compile it from source.

The first issue is that https://gpac.wp.imt.fr/2011/04/20/compiling-gpac-on-ubuntu/ guide is old and there are some packages that are gone now. OpenJPEG development library is not detected even if I install libopenjp2-7-dev which seems the right packet.
Anyway, this not blocking for me.

Another issue is that [/usr/local/]include/gpac/configuration.h file produces "error: #error "Unknown target platform used with static configuration file" when used. I manually replaced it with config.h generated file from the source directory and now it works. Maybe install script must be adjusted.

I use gpac to rewrap an elementary stream into a standard MP4 file but for that, I'm including an internal header: <gpac/internal/isomedia_dev.h>. The word "internal" means it's not intended to be used but headers are installed, functions exported and I don't want to spawn an mp4box process for that. Do you plan to make them public or to keep them exported in the foreseeable future?

Thanks!

**Comment by rbouqueau** [comment] 2019-02-24 17:23
If you're trying to build MP4Box only, we have updated instructions at http://gpac.io/2015/07/29/gpac-build-mp4box-only-all-platforms/

**Comment by s0m30n3** [comment] 2019-02-24 17:55
Thanks for the link.
I want to use the library so a static mp4box build is not what I'm looking for.
I gave zenbuild a try (from https://github.com/gpac/zenbuild) but "./zenbuild.sh ~/gpacbuild gpac \`gcc -dumpmachine\`" fails building fontconfig:
```
  CC       fcmatch.lo
../../../src/fcmatch.c:323:63: error: ‘PRI_CHAR_WIDTH_STRONG’ undeclared here (not in a function); did you mean ‘PRI_WIDTH_STRONG’?
 #define FC_OBJECT(NAME, Type, Cmp) { FC_##NAME##_OBJECT, Cmp, PRI_##NAME##_STRONG, PRI_##NAME##_WEAK },
                                                               ^~~~
../../../src/fcobjs.h:54:1: note: in expansion of macro ‘FC_OBJECT’
 FC_OBJECT (CHAR_WIDTH,  FcTypeInteger, NULL)
 ^~~~~~~~~
../../../src/fcmatch.c:323:84: error: ‘PRI_CHAR_WIDTH_WEAK’ undeclared here (not in a function); did you mean ‘PRI_WIDTH_WEAK’?
 CT(NAME, Type, Cmp) { FC_##NAME##_OBJECT, Cmp, PRI_##NAME##_STRONG, PRI_##NAME##_WEAK },
                                                                     ^~~~

../../../src/fcobjs.h:54:1: note: in expansion of macro ‘FC_OBJECT’
 FC_OBJECT (CHAR_WIDTH,  FcTypeInteger, NULL)
 ^~~~~~~~~
make[3]: *** [Makefile:644: fcmatch.lo] Error 1
```

**Comment by rbouqueau** [comment] 2019-02-24 19:28
Which features of GPAC are you interested in?

**Comment by s0m30n3** [comment] 2019-02-24 19:57
I have files whose format is proprietary and my tool convert them back to standard format (MP4 H.264).
The first step is to build an index of frames (offset, length, associated timecode).
Then (step 2) I concatenate each data block to a new file (this is an elementary stream, extension is .264) based on the index I built in the first step.
In the third step, I use mp4box to rewrap this .264 to a new .mp4 file.
Finally, I open the generated the .mp4, read each frame + its display time (DTS) and create for each frame a text frame containing a string (the timecode of my index). The goal is to add a subtitle track with a text displayed at the frame level.

Step 3 uses : gf_sys_init, gf_isom_open, gf_isom_probe_file, gf_media_import, gf_isom_get_track_by_id, gf_isom_set_handler_name, gf_isom_set_composition_offset_mode, gf_isom_rewrite_track_dependencies, gf_isom_make_interleave, gf_free, gf_isom_close, gf_sys_close and gf_delete_file.
FYI, I'm using GF_IMPORT_KEEP_REFS and GF_IMPORT_NO_FRAME_DROP import flags hence the need for a recent version.

Last step uses : gf_isom_get_track_count, gf_isom_get_sample_count, gf_isom_get_media_timescale, gf_isom_new_track, gf_isom_set_track_enabled, gf_isom_set_track_layout_info, gf_odf_desc_new(GF_ODF_TX3G_TAG), gf_malloc, gf_isom_new_text_description, gf_isom_new_text_sample, gf_isom_get_sample, gf_isom_text_reset, gf_isom_text_add_text, gf_isom_text_to_sample, gf_isom_add_sample, gf_isom_set_final_name, gf_odf_desc_del, gf_isom_delete_text_sample, gf_isom_sample_del and gf_move_file.

**Comment by rbouqueau** [comment] 2019-02-24 20:35
Ok so you only use MP4Box.

If you simply do ```./configure && make```, does it work?

Which distribution do you use? (You mentioned Debian xxx and Ubuntu 18.10 - I have some Debian 8, 9, 10 (testing) ready to help you).

**Comment by s0m30n3** [comment] 2019-02-24 20:56
I guess my first post was not clear enough.

Yes I can successfully compile mp4box from source (./configure && make works).
I was just informing you that instructions was old and you should update + retest it for Ubuntu 18.10.
I adapted the apt-get install step but some libraries (like OpenJPEG) still remain as not detected.
If you update the guide, I can build a full-featured mp4box but I as said, it's not blocking for me.

The "real" issue is the error I get when compiling my program:
```
In file included from /usr/local/include/gpac/setup.h:54,
                 from /usr/local/include/gpac/tools.h:33,
                 from /usr/local/include/gpac/isomedia.h:50,
                 from /usr/local/include/gpac/internal/isomedia_dev.h:33,
                 from ../../CFLibrary/src/ConverterHelper/ConverterHelper_MP4.cpp:5:
/usr/local/include/gpac/configuration.h:163:2: error: #error "Unknown target platform used with static configuration file"
 #error "Unknown target platform used with static configuration file"
```

I "fixed" the error by doing `sudo cp gpacsrc/config.h /usr/local/include/gpac/configure.h`.
So I guessed `make install` was missing something.

The last point was about using internal header.
I just commented the isomedia_dev.h include and it still compiles so you can ignore that point.

**Comment by aureliendavid** [comment] 2019-02-25 08:48
> I was just informing you that instructions was old and you should update + retest it for Ubuntu 18.10. 

Yes, we are currently working on refreshing the documentation, which includes renewing the build instructions. 

I'm glad you were still able to build it. I'll look at why the `configure` script didn't detect the newer openjpeg

> I "fixed" the error by doing `sudo cp gpacsrc/config.h /usr/local/include/gpac/configure.h`.
> So I guessed `make install` was missing something.

It looks like the `make install-lib` target does that:

`$(INSTALL) $(INSTFLAGS) -m 644 config.h "$(DESTDIR)$(prefix)/include/gpac/configuration.h"`

https://github.com/gpac/gpac/blob/master/Makefile#L254

I'm not sure whether the `make install` should do it too, or if we should add to the instructions something about using `install-lib` if you intend to use it for development.

**Comment by s0m30n3** [comment] 2019-02-26 20:16
I just re-tested with a fresh Ubuntu 18.10 setup + gpac git.
`./run_configure && make && sudo make install-lib` does install everything needed and has a correct configure.h as expected.

For some reason, `gf_isom_new_text_description` and other functions are not exported.
It seems GPAC_DISABLE_ISOM_WRITE or GPAC_DISABLE_ISOM is defined at some point.
I didn't specified any --disable-xXx but I'll wait for the complete guide as I may be missing some prerequisites.

Anyway, thanks for the quick response !

**Comment by s0m30n3** [comment] 2019-03-04 21:29
GPAC_DISABLE_* defines are only used for "Win32&MSVC" builds as noted in export.c header.
`mp4box -version` confirmed I had no GPAC_DISABLE_* in my build.

The following functions (I use in my program) are missing a GF_EXPORT attribute: `gf_isom_new_text_description`, `gf_isom_new_text_sample`, `gf_isom_new_text_reset`, `gf_isom_new_text_add_text` and `gf_isom_new_text_to_sample`.
Adding it fixes the issue on my side.

I guess it would be a good idea to use that mechanism for all platforms.

I know I'm asking many things but to sum them up, please:
- update compiling guide for recent Ubuntu/Debian versions
- add a note about `make install-lib` target
- support pkg-config
- replicate export-fn-if-DISABLEXXX-macro-is-not-set logic for *nix builds.

**Comment by aureliendavid** [comment] 2019-03-05 15:27
> * replicate export-fn-if-DISABLEXXX-macro-is-not-set logic for *nix builds.

Hi @s0m30n3,

The problem is not really with the `DISABLE_` mechanism, this should work properly on all platforms. 

The problem is that, for historic reasons, we don't export symbols the same way on unix and windows. And of course, with time, the two different lists of exported symbols have diverged. 

This is admittedly not a great system. We're working to get rid of it in future version. 

In the meantime, I've "re-synced" the exported symbols lists so that the functions you needed (and a bunch of others) now have the right `GF_EXPORT`.

**Comment by aureliendavid** [comment] 2019-04-12 09:11
> I know I'm asking many things but to sum them up, please:
>     * update compiling guide for recent Ubuntu/Debian versions
>     * add a note about `make install-lib` target
>     * support pkg-config

The updated build instructions for linux can be found here: https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux

It was tested on recent ubuntu and debian versions and includes building replacements for missing libraries (libopenjp2-7-dev for example is too recent and not supported by gpac that's why your configure didn't see it).

It also includes a paragraph on make install-lib and pkg-config : https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux#install-for-developers

>     * replicate export-fn-if-DISABLEXXX-macro-is-not-set logic for *nix builds.

this was fixed previously


I'm closing this issue, please reopen if needed.

**Closed by aureliendavid** 2019-04-12 09:11 UTC
Labels: build, help wanted, mp4box

**Comment by lihow** [comment] 2020-03-21 10:18
I copy **gpac_build/gpac_public/config.h** to **include/gpac/** solved the problem #error "Unknown target platform used with static configuration file"
and make makefile has **CXXFLAGS=-g -DGPAC_HAVE_CONFIG_H**
