### ISSUE TITLE
mp4box bug when creating DASH files containing aacplus/sbr audio

### ISSUE THREAD

**Issue by richardbushell** [gpac/gpac#62] opened 2015-03-11 02:14 UTC
mp4box seems to have a BUG when creating DASH files containing aacplus/sbr audio.

You can download my source file from this link:
http//living.tv/mob/ibeani_i4.mp4

This is an MP4 video containing aacplus/sbr (HEAAC+1) file. It is strict 4 second keyframes. We have been successfully streaming a copy of this file via Akamai, using in-the-network segmentation to HDS, HLS, etc... We are sure the file is fine!

But through mp4box:-

- if we process the file directly we get an audio codec reported incorrectly in the MPD file as codec 'mp4a.40.2' (which is LC-AAC). The dash file still plays fine in IE11 Win8.1 through dash.js and through the Dash Reference Player, but it does not play in Chrome 41.0.2272.76 (desktop). Chrome does nothing. But interestingly, if I manually amend the MPD with a text editor to audio codec 'mp4a.40.5' (which is HE-AAC v1) then it now plays in Chrome too. BUT I also note that mediainfo reports the audio_init.mp4 file as LC-AAC (where I note it reports other AAC+1 files correctly). So, I fear I'm getting a loss in quality here.

- I have then tried (both native and raw methods) of using the mp4box -sbr flag  to force AAC+1 handling. It then correctly reports the 'mp4a.40.5' codec in the MPD file, but the DASHed audio segments are split into twice as many segments as the video segments and playback at half/double the rate of the video. I suspect mp4box is not handling the sampling rate correctly, and not sure why it's creating twice as many files as expected. I also recall a similar post a few weeks ago relating to incorrect mp4box audio sample rate for android.

I have tried everything, but cannot find a solution. I am sure this is a BUG. I would happily talk through my attempts and methods, but wonder if you can confirm and replicate this error.

**Comment by jeanlf** [comment] 2015-03-11 19:06
Hmm something is indeed wrong, at least in our playback. I will have a look

**Comment by richardbushell** [comment] 2015-03-11 19:36
Thanks, really appreciate it as we need to segment our current assets soon and they are all HEAAC+1.

 

Keep me posted…


Kind regards

Richard

 

  _____  

 


Richard Bushell
Managing Director
Living.TV

Freephone
Freefax

0800 377 77 25
0800 098 88 76

Email
Web

 <mailto:rb@living.tv> rb@living.tv
 <http://www.living.tv> www.living.tv 

 

  _____  


  _____  


	

 <http://www.living.tv/> 

		

Living.TV produce stunning corporate videos to utilise on your website, email and other marketing. Then, our 100,000 streaming servers provide the highest quality video-streaming on the planet. Viewers enjoy glorious high-definition playback of your video, without buffering. View examples at   <http://www.living.tv/> www.living.tv

	
	

  _____  

  _____  


 <http://living.tv/video> 

 <http://living.tv/livingtvmediapack> 

 <http://facebook.com/livingtv1>    <http://twitter.com/livingtv1>    <http://linkedin.com/company/living.tv>    <http://google.com/+livingtv1> 

Watch our Video,
Read our Media Pack,
and Please Follow Us...

**Comment by jeanlf** [comment] 2015-03-12 10:42
I think the issue was a bug in our SBRX import, now fixed on GIT. Could you check if that solves your issue ?

**Comment by richardbushell** [comment] 2015-03-12 11:09
Hi Jean

 

OK, would it make a difference if we use –sbr or –sbrx on the command line, or does the same fix implemented apply to both? We did try both previously when trying to get it to work.

 

Also, sorry for being a bit naïve when it comes to GIT, but would we now require a Windows compilation/build before we can test it? This is something we are not geared up to do. 

 

Please advise on both.


Kind regards

Richard

 

  _____  

 


Richard Bushell
Managing Director
Living.TV

Freephone
Freefax

0800 377 77 25
0800 098 88 76

Email
Web

 <mailto:rb@living.tv> rb@living.tv
 <http://www.living.tv> www.living.tv 

 

  _____  


  _____  


	

 <http://www.living.tv/> 

		

Living.TV produce stunning corporate videos to utilise on your website, email and other marketing. Then, our 100,000 streaming servers provide the highest quality video-streaming on the planet. Viewers enjoy glorious high-definition playback of your video, without buffering. View examples at   <http://www.living.tv/> www.living.tv

	
	

  _____  

  _____  


 <http://living.tv/video> 

 <http://living.tv/livingtvmediapack> 

 <http://facebook.com/livingtv1>    <http://twitter.com/livingtv1>    <http://linkedin.com/company/living.tv>    <http://google.com/+livingtv1> 

Watch our Video,
Read our Media Pack,
and Please Follow Us...

**Comment by jeanlf** [comment] 2015-03-12 11:54
The fix only applies to SBR explicit mode, not sure why chrome only accepts the SBR signaling.

You will need to re-import the aac (eg, MP4Box -raw then MP4Box -add with sbrx flag set)

rev 115 (96823b5) is now available on our download page

**Comment by richardbushell** [comment] 2015-03-12 15:39
Hi Jean

 

That seems to have sorted some things but not others.

 

The MPD file generated after your fix is here:  <http://living.tv/mob/ibeani_i4.mpd> http://living.tv/mob/ibeani_i4.mpd

It now reports correctly as: (audio) codecs="mp4a.40.5"

Video codec reported as: codecs="avc1.42001e"

 

In Google Chrome Desktop (Win8.1) version:------

 

Here is our test page for this MPD playback.

 <http://living.tv/mob/test_ibeani_i4.html> http://living.tv/mob/test_ibeani_i4.html

(does not play)

 

AND again in Chrome Desktop (Win8.1):

 

http://dashif.org/reference/players/javascript/1.0.0/index.html

Stream:  http://living.tv/mob/ibeani_i4.mpd

The page at dashif.org says:

Codec (video/mp4; codecs=”avc1.42001e”) is not supported.

(does not play)

 

In IE11 (Win8.1) both the above still play fine.

 

The video was playing the other day in Chrome when I manually edited the MPD file to 40.5 on the audio codec, but now it reports a problem with the video codec!

 

Any ideas?


Kind regards

Richard

 

  _____  

 


Richard Bushell
Managing Director
Living.TV

Freephone
Freefax

0800 377 77 25
0800 098 88 76

Email
Web

 <mailto:rb@living.tv> rb@living.tv
 <http://www.living.tv> www.living.tv 

 

  _____  


  _____  


	

 <http://www.living.tv/> 

		

Living.TV produce stunning corporate videos to utilise on your website, email and other marketing. Then, our 100,000 streaming servers provide the highest quality video-streaming on the planet. Viewers enjoy glorious high-definition playback of your video, without buffering. View examples at   <http://www.living.tv/> www.living.tv

	
	

  _____  

  _____  


 <http://living.tv/video> 

 <http://living.tv/livingtvmediapack> 

 <http://facebook.com/livingtv1>    <http://twitter.com/livingtv1>    <http://linkedin.com/company/living.tv>    <http://google.com/+livingtv1> 

Watch our Video,
Read our Media Pack,
and Please Follow Us...

**Comment by richardbushell** [comment] 2015-03-12 16:17
For completeness, these were my steps from the original MP4:

 

MP4Box -raw 2 "ibeani_i4.mp4"

MP4Box -add "ibeani_i4_track2.aac" -sbrx -lang eng -mpeg4 "ibeani_i4.m4a"

MP4Box -dash 4000 -rap -no-frags-default -profile live -segment-name %%s -url-template -out "\out\ibeani_i4.mpd" ibeani_i4.mp4#video ibeani_i4.m4a


Kind regards

Richard

 

  _____  

 


Richard Bushell
Managing Director
Living.TV

Freephone
Freefax

0800 377 77 25
0800 098 88 76

Email
Web

 <mailto:rb@living.tv> rb@living.tv
 <http://www.living.tv> www.living.tv 

 

  _____  


  _____  


	

 <http://www.living.tv/> 

		

Living.TV produce stunning corporate videos to utilise on your website, email and other marketing. Then, our 100,000 streaming servers provide the highest quality video-streaming on the planet. Viewers enjoy glorious high-definition playback of your video, without buffering. View examples at   <http://www.living.tv/> www.living.tv

	
	

  _____  

  _____  


 <http://living.tv/video> 

 <http://living.tv/livingtvmediapack> 

 <http://facebook.com/livingtv1>    <http://twitter.com/livingtv1>    <http://linkedin.com/company/living.tv>    <http://google.com/+livingtv1> 

Watch our Video,
Read our Media Pack,
and Please Follow Us...

**Comment by jeanlf** [comment] 2015-03-18 07:24
hmm strange. Does the video plays if you comment the audio adaptation set ? And vice versa ?

**Comment by richardbushell** [comment] 2015-03-19 19:32
Hi Jean, Sorry... I have overwritten that file since in continued attempts to get a working solution. All my best efforts have failed. I can get a dashed file to play on the DASH-IF reference player, but the timing seems wrong. Video playback is finishing about 1.5 seconds early. Any chance that someone in your team (or even another poster) can try and figure out what is wrong please? This is driving me crazy!

The original source file is still available to download from this link:
http://living.tv/mob/ibeani_i4.mp4
(this version is AACHE+1 i.e. SBR)

My latest attempt to get it to play is available under this mpd file:
http://living.tv/mob/test_800k.mpd
(This file was actually created when I was trying to get an AACHE+2 file version to work instead)
(you can put this directly into the DASH_IF reference player: http://dashif.org/reference/players/javascript/1.3.0/samples/dash-if-reference-player/index.html )

I have been trying AAC, AACHE+1, AACHE+2 alternatives of the original, and I always get this timing problem, playback is finishing with 1.5 seconds of the video and audio streams showing as buffered.

Nor does the mpd file validate on: http://dashif.org/conformance.html
(the validator just continues to run forever, and never completes the test)

These were my latest steps:

MP4Box -raw 1 ibeani_i4.mp4
MP4Box -raw 2 ibeani_i4.mp4
MP4Box -add ibeani_i4_track1.h264 -fps 25 ibeani_i4_video.m4v
MP4Box -add ibeani_i4_track2.aac ibeani_i4_audio.m4a
MP4Box -dash 4000 -frag 4000 -rap -frag-rap -profile dashavc264:live -segment-name %%s -url-template -out "test_800k.mpd" ibeani_i4_video.m4v ibeani_i4_audio.m4a

Anyway, I thought if you had the original source file (link above), that you (or anyone else) might be able to get a working solution, or else isolate the problem...

Frustrated!

Richard

**Comment by richardbushell** [comment] 2015-03-19 21:49
p.s. Have just checked the segments generated in MediaInfo and the Audio Segments show as duration 3.968 seconds, whereas the Video Segments report as 4 seconds (which is correct). Why would this not be 4 second for audio too?

**Comment by richardbushell** [comment] 2015-03-20 02:04
OK, this is clearly something to do with Audio Frame length at 1024 samples for AAC. The audio is stereo at Sample Rate 48000. When I set the dash segments to 16 seconds (an exact multiple of Audio Frame length) it plays OK right to the end of the file.

Is this a bug in MP4Box or does DASH only work if your segments are exact multiples of your audio frame length?

**Comment by richardbushell** [comment] 2015-03-20 18:48
NO, sorry, jumped the gun, not solved it.
There just seems to be a timing issue between the Audio and Video components and this causes the problems. For basic testing, until the problem is isolated, I am just trying to get this working using AAC-LC. The original file to download for reference is here:
http://living.tv/mob/ibeani_i4_mcqtlow.mp4
This mp4 shows as 54.76 seconds. This is the same as the original AVI master shows.
If I extract the RAW data to an aac file in MP4box, then -add this to create a new m4a file then this file shows a duration of 54.783 seconds. I am sure that it is this anomaly that causes the timing issues. I have tried everything, but the resulting file playback either has an issue with video and audio not starting concurrently OR completes playback with over a second reporting as left in the video and audio buffers (and you can still drag the playback cursor a further second to the end of playback) in the DASH-IF Reference Player.
Something is wrong, I cannot think of anything in my methodology, so it is either a bug, or there may be something that you or your team can replicate and offer a solution, or fix if it's a bug???
Anyway, from the file link above could you please download this, replicate this your end, and try and offer a solution asap. I would really appreciate it, we are desperate to proceed but are stuck!
Thanks, Richard.

**Comment by richardbushell** [comment] 2015-03-22 23:11
SOLVED IT!
OK, I was testing 8 second segments.
Changed Video Segment Duration in MPD manually to 200000 (i.e. 8 seconds x 25000 timescale = 200000). (MP4Box had wrongly generated this figure as 195571)
Changed Audio Segment Duration in MPD manually to 384000 (i.e. 8 seconds x 48000 timescale = 384000). (MP4Box had wrongly generated this figure as 375661)
I used the amended MPD file and it works!!!!!!!!!!!!!!!!!!!!! The playback and timing is now correct. 
I can therefore officially report this as a BUG. The Segment Duration that MP4Box is generating in the MPD file is WRONG for both the video and audio segments.
Please can you advise of a fix for this asap.
Thanks, Richard.

**Comment by rbouqueau** [comment] 2015-03-23 07:46
@richardbushell Have you checked the generated MPD in another player? Like GPAC/MP4Client for example?

As you imagine, MP4box doesn't write values like '195571' or '375661' by chance. Have you tried again to check what the conformance checker says? (Try several times if it blocks, it happens sometimes)

We need to check here. But it could also be a limitation in dash.js forcing the alignment of segments. It would not be the first time a player requires so.

What do you think?

**Comment by richardbushell** [comment] 2015-03-23 08:16
HI Romain

 

It conforms OK.

 

The original file had strict 4 sec keyframes. It was DASHed with MP4Box at DASH -8000. And I have also checked both the Video and Audio SEGMENT files generated by MP4Box and they are all correct at exactly 8 seconds.

 

I cannot think where or how MP4Box got the figures it wrote to the MPD file? Changing them manually sorts the problem instantly.

 

Obviously, it is an important case to track through internally as it seems like a very strange error to be producing when everything else, including the DASHed segment files are all actually OK.

 

Please advise asap.


Kind regards

Richard

 

  _____  

 


Richard Bushell
Managing Director
Living.TV

Freephone
Freefax

0800 377 77 25
0800 098 88 76

Email
Web

 <mailto:rb@living.tv> rb@living.tv
 <http://www.living.tv> www.living.tv 

 

  _____  


  _____  


	

 <http://www.living.tv/> 

		

Living.TV produce stunning corporate videos to utilise on your website, email and other marketing. Then, our 100,000 streaming servers provide the highest quality video-streaming on the planet. Viewers enjoy glorious high-definition playback of your video, without buffering. View examples at   <http://www.living.tv/> www.living.tv

	
	

  _____  

  _____  


 <http://living.tv/video> 

 <http://living.tv/livingtvmediapack> 

 <http://facebook.com/livingtv1>    <http://twitter.com/livingtv1>    <http://linkedin.com/company/living.tv>    <http://google.com/+livingtv1> 

Watch our Video,
Read our Media Pack,
and Please Follow Us...

**Comment by rbouqueau** [comment] 2015-03-23 11:41
Richard,

I've jut checked. The content you provided is ok. But it ends up with a shorter segment. @Duration's definition in the DASH spec:
```
If present, specifies the constant approximate Segment duration.

All Segments within this Representation element have the same duration unless it is the last Segment within the Period, which could be significantly shorter.

The value of the duration in seconds is the division of the value of this attribute and the value of the @timescale attribute associated to the containing Representation.
```

So I don't see anything wrong in what we do.

@jeanlf We could ignore the last segment duration, what do you think? (I thought we did actually)

@richardbushell You can prepare your content so that you end up with same duration segments (e.g. MP4Box -splitx 0:48 ibeani_i4_mcqtlow.mp4). You could also report a bug to dash.js so that they don't rely too strictly on this 'approximative' duration for the playback.

**Comment by richardbushell** [comment] 2015-03-23 12:05
Romain

 

I am confused.

 

I had checked, all Segments generated by MP4Box are exactly 8 seconds. Both audio and video segments are exactly 8 seconds throughout. Obviously the last segment is shorter which is correct as it it just the remaining number of seconds in the video.

 

MP4Box iscorrectly  generating the segments correctly at 8 seconds, but writing a completely different Segment Duration in the MPD file.

 

The bug is definitely in mis-writing the segment duration in the MPD file in MP4Box. Manually changing the duration in a text editor fixes it instantly, but you need to track down the bug as to why it writes the wrong info.


Kind regards

Richard

 

  _____  

 


Richard Bushell
Managing Director
Living.TV

Freephone
Freefax

0800 377 77 25
0800 098 88 76

Email
Web

 <mailto:rb@living.tv> rb@living.tv
 <http://www.living.tv> www.living.tv 

 

  _____  


  _____  


	

 <http://www.living.tv/> 

		

Living.TV produce stunning corporate videos to utilise on your website, email and other marketing. Then, our 100,000 streaming servers provide the highest quality video-streaming on the planet. Viewers enjoy glorious high-definition playback of your video, without buffering. View examples at   <http://www.living.tv/> www.living.tv

	
	

  _____  

  _____  


 <http://living.tv/video> 

 <http://living.tv/livingtvmediapack> 

 <http://facebook.com/livingtv1>    <http://twitter.com/livingtv1>    <http://linkedin.com/company/living.tv>    <http://google.com/+livingtv1> 

Watch our Video,
Read our Media Pack,
and Please Follow Us...

**Comment by rbouqueau** [comment] 2015-03-23 12:21
> The bug is definitely in mis-writing the segment duration in the MPD file in MP4Box.

As I write above, we can certainly improve on this. I'd also prefer MP4Box to write 4s here.

However what MP4Box writes is not incorrect. This is not a bug. The value written is the real average duration and one could imagine it is the segmenter target duration.

> Manually changing the duration in a text editor fixes it instantly

You use a general phrasing, but it only fixes dash.js behaviour. Other players such as the GPAC one can play this content flawlessly.

dash.js seems to rely strongly on this value which is said as 'approximate' by the standard. In our case we write 7.82s instead of 8.00s (e.g. a 2% approximation across 54s). I would expect dash.js to be more robust againt this value.

I'll keep you updated about our thoughts here.

**Comment by jeanlf** [comment] 2015-03-23 12:41
Could you give a try at the last commit (0c0efac) ?

**Comment by richardbushell** [comment] 2015-03-23 13:59
Hi Jean,

I have just downloaded and tried: gpac-0.5.2-DEV-rev163-ge23a154-master-x64.exe

Does this include the latest commit/changes?

It still reports the original segment duration error.

Richard

**Comment by cconcolato** [comment] 2015-03-23 15:37
Our Windows buildbot has some problems at the moment. rev165 should include the fix. If you can, download/update the source code and build the exe.

**Comment by richardbushell** [comment] 2015-03-23 16:04
OK, thanks for letting us know. Self-build is beyond us, but I will keep checking for the updated Windows builds to be posted and then check…
Richard

**Comment by richardbushell** [comment] 2015-03-24 12:37
Any ETA on when the Windows Builds will be available?

Richard

**Comment by mraulet** [comment] 2015-03-24 12:58
I saw it yersterday.

----- Mail original -----
De: "richardbushell" <notifications@github.com>
À: "gpac/gpac" <gpac@noreply.github.com>
Envoyé: Mardi 24 Mars 2015 13:37:49
Objet: Re: [gpac] mp4box bug when creating DASH files containing aacplus/sbr audio (#62)

Any ETA on when the Windows Builds will be available? 

Richard

**Comment by richardbushell** [comment] 2015-03-24 19:04
THANKS, THE NEW SEGMENT DURATIONS ARE NOW CORRECT, AND WORK PERFECTLY!!!

Just one request please. Could you please add an extra decimal place (so, 3 decimal places) to the MPD figures shown for:
mediaPresentationDuration="PT0H0M54.78S"
maxSegmentDuration="PT0H0M8.00S"
<Period duration="PT0H0M54.78S">

Note, you seem to include 6 decimal places i.e. minBufferTime="PT1.500000S"

mp4Box obviously requests its SEGMENT times in Milliseconds (so it would be much better to record 3 decimal places in the Duration times recorded in the MPD. And Milliseconds seems fairly standard across the industry.

The regulations for the format actually allow for any number of Decimal Places. See:-
http://en.wikipedia.org/wiki/ISO_8601#Durations
which states:
There is no limit on the number of decimal places for the decimal fraction.
Would that be OK, could these figures be recorded as 3 decimal places please?
I have pre-checked and 3 decimal places plays and conforms just fine too.
Richard.

**Comment by richardbushell** [comment] 2015-03-24 19:05
Sorry, and:
Period duration="PT0H0M54.784S"
as well.

**Comment by richardbushell** [comment] 2015-03-25 00:06
Hi Romain

Our emails crossed and so are now out of sync.

Jean’s code amends today (24th March) have fixed the segment reporting.

It is now working perfectly.

There is one subsequent request that durations elsewhere within the MPD file generated are stated with a minimum of 3 decimal places for the seconds rather than two, as this is fine in the guidelines, and all other units are generally in milliseconds as a unit for mp4box and dash settings. This would be ideal.
Richard

**Closed** 2015-03-26 10:49 UTC
Labels: bug
