### ISSUE TITLE
AV1 parser doesn't read enough to get correct size for ispe element

### ISSUE THREAD

**Issue by tdaede** [gpac/gpac#1747] opened 2021-04-16 03:50 UTC
The AV1 parser doesn't read enough bytes for the ispe element - getting the correct values requires looping over every OBU_FRAME or OBU_FRAME_HEADER in the source bitstream and finding the maximum size, but currently it only reads one block (currently 5000 bytes). There are a couple of solutions for this, but I'd like to know which one is appropriate for gpac.

1. Configure the AV1 parser to read an arbitrary number of bytes.
2. Use a function like av1_get_layer_size added by my a1lx PR specifically for the ispe element to determine sizes (it could in fact be the exact same function).

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by jeanlf** [comment] 2021-04-16 17:20
I'm not sure I get the problem here, the parser dispatches one TU at a time, so that you have one complete image (with all layers) in one packet. The ispe element is not related to the parser, it should be setup at the creation of the item. Could you please elaborate ?

Also FYI we have now merged #1744 and added a sample scalable av1 streams [here](http://download.tsi.telecom-paristech.fr/gpac/gpac_test_suite/resources/media/import/the_beacon_short.obu) in order to add tests in the testsuite

**Comment by tdaede** [comment] 2021-04-16 21:21
The reason that the parser (specifically the "probe" step in ffmpeg parlance) is relevant for ispe is because image_props in iff.c is filled out during the probe step. Specifically it uses gf_isom_get_visual_info(fsrc, imported_track, sample_desc_index, &w, &h) which through a long chain eventually gets width and height from the probe step.

The probing gives the parser a GF_Bitstream limited to 5000 bytes, which is enough for most AV1 streams to get to the first OBU_FRAME, but not enough for scalable images. I don't know if this is an intentional limit to make probing faster, or a bug in probing.

**Comment by jeanlf** [comment] 2021-04-19 08:35
Sorry I still don't get it: probers in GPAC do not define any PID properties (eg width, height), they only try to detect underlying media type. PID creation and properties assignment are done in the parsing routines.

Would you have a sample file and command line to reproduce your problem ?

**Comment by rbouqueau** [comment] 2021-04-19 09:34
@jeanlf IIUC 5000 bytes may not be enough to encounter the layer with the maximum size. Thus we fill the wrong dimensions in the ispe box.

Maybe when we see the ```bu_extension_flagobu_extension_flag``` at true we should parse more (until coming back to a know set of temporal_id/spatial_id? )

**Comment by jeanlf** [comment] 2021-04-22 08:47
Again this has nothing to do with probing.

I suspect the issue is that the av1dmx_parse_av1 does not properly handle the case where aom_av1_parse_temporal_unit_from_ ZZZ return a BUFFER_TOO_SMALL 
If you can't provide a bitstream for that I'll try to generate one.

**Comment by jeanlf** [comment] 2021-04-22 10:23
Here's what I tried:
- use [this multilayer test sequence](http://download.tsi.telecom-paristech.fr/gpac/gpac_test_suite/resources/media/import/the_beacon_short.obu)
- import image specifying input block size `MP4Box --block_size=X -add-image src.obu -new test.avif`

Even with very small input blocks (X=10), I still have ispe indicating 640x480

Please provide a test sequence reproducing your issue.

**Comment by tdaede** [comment] 2021-04-22 23:42
Here is another multilayer obu that reproduces:
```
MP4Box -add-image tiger.obu_2.av1 -ab miaf -ab mif1 -brand avif -set-primary 1 -new test.avif
Track Importing AOM AV1 Video - Width 304 Height 208 FPS 25000/1000 SAR 0/0
Adding sample at time 0.000 as item 1         
Saving test.avif: 0.500 secs Interleaving
```
```
MP4Box --block_size=500000 -add-image tiger.obu_2.av1 -ab miaf -ab mif1 -brand avif -set-primary 1 -new test.avif
Track Importing AOM AV1 Video - Width 608 Height 416 FPS 25000/1000 SAR 0/0
Adding sample at time 0.000 as item 1         
Saving test.avif: 0.500 secs Interleaving
```

Neither of these are correct. With the block size manually patched to a very high value we get the correct result:
```
$ ~/sandbox/gpac/bin/gcc/MP4Box --block_size=5000000 -add-image tiger.obu_2.av1 -ab miaf -ab mif1 -brand avif -set-primary 1 -new test.avif
Track Importing AOM AV1 Video - Width 1216 Height 832 FPS 25000/1000
Adding sample at time 0.000 as item 1
```

(the printed width and height match what is written into ispe)
[tiger.obu_2.zip](https://github.com/gpac/gpac/files/6361808/tiger.obu_2.zip)

**Comment by jeanlf** [comment] 2021-04-23 07:48
Thanks for the file, the av1 parser was indeed declaring the size of the last frame seen instead of the sequence size, now fixed.
- Could you cross-check ? 
- Is it OK if we use this sequence in our test suite ?

**Comment by jeanlf** [comment] 2021-05-07 06:47
ping

**Comment by tdaede** [comment] 2021-05-07 16:11
Yes, it's fixed. The sequences in https://github.com/AOMediaCodec/av1-avif/pull/134 have been created using the fix as well as the additional patches.

The image can be added to the test set. The source and license is here (it's compatible with gpac's license)

https://commons.wikimedia.org/wiki/File:08-2011._Panthera_tigris_tigris_-_Texas_Park_-_Lanzarote_-TP04.jpg

**Comment by jeanlf** [comment] 2021-05-10 10:24
added to [testsuite](https://github.com/gpac/testsuite/blob/master/scripts/iff-misc.sh)

**Closed by jeanlf** 2021-05-10 10:24 UTC
