### ISSUE TITLE
Missing </font> tag after import srt subtitle

### ISSUE THREAD

**Issue by magiciannew** [gpac/gpac#2267] opened 2022-09-23 02:59 UTC
Hi, I just start to use MP4box few days ago. this is fantastic, thank you all.
Could you please check the problem I met below:

Product: gpac/mp4box 2.0 for win-x64 (the latest stable) issued on 2022/02/22
Problem: part of font tag in srt could be miss after importing
Enviroment: Win10 command prompt
Command: mp4box -add vediofile.mp4 -add  subtitle.srt targetfile.mp4

SRT sample in input file:
1
00:00:01,200 --> 00:00:04,000
\<font color=#FFFF70>The first language\</font>
The second language (english) line
(File encoding: Win CRLF UTF-8)

Text in MP4 file, same as the exported to STR file:
1
00:00:01,200 --> 00:00:04,000
\<font color=#FFFF70>The first language
The second language (english) line

The \</font> at the end of the first language line is missing.
When I open a new command prompt, and tried to export to a text-only MP4, seems the outfile is correct, but later I repeat the same command, I always got problems.
I tried with an older version (MP4box 0.5), didn't see this problem

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by magiciannew** [comment] 2022-09-27 01:22
I tried MP4box 0.8.1, </font> is missed between multi-line subtitles as well.

**Comment by jeanlf** [comment] 2022-09-28 13:21
indeed, now fixed. Thanks for the feedback!

**Closed** 2022-09-28 13:20 UTC

**Comment by magiciannew** [comment] 2022-09-30 09:27
Hi JeanIf, I tried the new build 2.1-DEV-rev346-gb23408b1-master. All the (font) tags in SRT are removed  :-(

**Comment by jeanlf** [comment] 2022-09-30 11:52
could you share a sample SRT ? I cannot reproduce with our base [test file](https://github.com/gpac/testsuite/blob/master/media/auxiliary_files/subtitle.srt)

**Comment by magiciannew** [comment] 2022-09-30 17:30
Hi jeanlf,
I tried your "test file" with: _mp4box -add "F:\path\input.mp4" -add "F:\path\test.srt" -new F:\path\output.mp4_
The subtitle contained in the output.mp4 are all in "plain text style".

Enviroment: Microsoft Windows [Ver 10.0.19044.2006]
Video player: Potplay x64

MP4Box - GPAC version 2.1-DEV-rev346-gb23408b1-master
(c) 2000-2022 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io
I am not sure which dll file should I check?
gm_timedtext.dll - last modified: 2021/02/06 1:27

**Comment by magiciannew** [comment] 2022-09-30 17:56
I only used: 

1
00:00:01,262 --> 00:00:02,787
\<font color=#F0F0F0>text\</font>
plain text without colors

**Comment by magiciannew** [comment] 2022-10-02 03:45
Now I have a workaround, generate SRT steams to .mp4 by ver0.5.0, and then import text steam from the test only MP4, uses the newest MP4box.
only problem is, 0.5.0 is not happy when the number of lines under 1 timestamp is more than 3 .
Don' worry, more powerful, more bugs ...

**Comment by jeanlf** [comment] 2022-10-03 09:35
With master, using your example with `color=#FF0000` and `MP4Box -add video.mp4#video -add s.srt:hdlr=sbtl -new test.mp4` shows first line in red in QT.

Have you tested your samples with other players ?
