### ISSUE TITLE
Gpac with kvazaar not working

### ISSUE THREAD

**Issue by jakc-1** [gpac/gpac#1759] opened 2021-04-24 09:28 UTC
Hello, 
I am trying to use Kvazaar as a GPAC filter, but I cannot make it work. 
I've compiled ffmpeg with following commands:

sudo apt-get update
sudo apt-get install ffmpeg
moved to ffmpeg folder 
./configure --enable-libkvazaar
make 
make install

I've installed gpac:

downloaded source code
moved to gpac folder
./configure --use-ffmpeg=local
make
make install

I used following command: 
gpac -i rtmp://MyURL/live enc:c=libkvazaar:b=1m::kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,rc-algorithm=1 @ tilesplit @ -o dest

and the response I got was:
Unrecognized codec identifier in "enc" definition: c=libkvazaar
Failed to find filter "enc:c=libkvazaar:b=1m::kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,rc-algorithm=1"
No filter with similar name found, see gpac -h filters

When I type gpac -h filters I get this:
Listing 104 supported filters:
inspect: Inspect packets
probe: Probe source
compositor: Compositor
mp4dmx: ISOBMFF/QT demuxer
bifsdec: MPEG-4 BIFS decoder
odfdec: MPEG-4 OD decoder
fin: File input
btplay: BT/XMT/X3D loader
httpin: HTTP input
svgplay: SVG loader
rfimg: JPG/J2K/PNG/BMP reframer
imgdec: PNG/JPG decoder
rfadts: ADTS reframer
rflatm: LATM reframer
rfmp3: MP3 reframer
faad: FAAD decoder
maddec: MAD decoder
xviddec: XVid decoder
rfac3: AC3 reframer
a52dec: A52 decoder
rfamr: AMR/EVRC reframer
oggdmx: OGG demuxer
vorbisdec: Vorbis decoder
theoradec: Theora decoder
m2tsdmx: MPEG-2 TS demuxer
sockin: UDP/TCP input
dvbin: DVB for Linux
mcdec: MediaCodec decoder
lsrdec: MPEG-4 LASeR decoder
safdmx: SAF demuxer
dashin: MPEG-DASH and HLS client
cdcrypt: CENC decryptor
cecrypt: CENC  encryptor
mp4mx: ISOBMFF/QT muxer
rfqcp: QCP reframer
rfh263: H263 reframer
rfmpgvid: M1V/M2V/M4V reframer
nhntr: NHNT reader
nhmlr: NHML parser
rfnalu: AVC/HEVC reframer
m2psdmx: MPEG PS demuxer
avidmx: AVI demuxer
txtin: Subtitle loader
ttxtdec: TTXT/TX3G decoder
vttdec: WebVTT decoder
ttmldec: TTML decoder
rtpin: RTP/RTSP/SDP input
fout: File output
uflatm: Raw AAC to LATM writer
ufadts: ADTS writer
ufmhas: MHAS writer
reframer: Media Reframer
writegen: Stream to file
ufnalu: AVC/HEVC to AnnexB writer
writeqcp: QCP writer
writevtt: WebVTT writer
nhntw: NHNT writer
nhmlw: NHML writer
vobsubdmx: VobSub demuxer
avimx: AVI muxer
aout: Audio output
ufm4v: M4V writer
resample: Audio resampler
vout: Video output
vcrop: Video crop
vflip: Video flip
rfrawvid: RAW video reframer
rfpcm: PCM reframer
jpgenc: JPG encoder
pngenc: PNG encoder
rewind: Audio/Video rewinder
flist: Sources concatenator
m2tsmx: MPEG-2 TS muxer
dasher: DASH and HLS segmenter
tileagg: HEVC tile aggregator
pin: pipe input
pout: pipe output
gsfmx: GSF Muxer
gsfdmx: GSF Demuxer
sockout: UDP/TCP output
rfav1: AV1/IVF/VP9 reframer
ufobu: IVF/OBU/annexB writer
nvdec: NVidia decoder
routein: ROUTE input
rtpout: RTP Streamer
rtspout: RTSP Server
httpout: HTTP Server
hevcsplit: HEVC tile spliter
hevcmerge: HEVC Tile merger
rfflac: FLAC reframer
rfmhas: MPEH-H Audio Stream reframer
rfprores: ProRes reframer
tssplit: MPEG Transport Stream splitter
bsrw: Compressed bitstream rewriter
ffdmx: FFMPEG demuxer
ffdec: FFMPEG decoder
ffavin: FFMPEG AV Capture
ffsws: FFMPEG video rescaler
ffenc: FFMPEG encoder
ffmx: FFMPEG muxer
ffavf: FFMPEG AVFilter
jsf: JavaScript filter
routeout: ROUTE output
dtout: DekTec SDIOut
avgen: AV Counter Generator

Does the error mean that something is not installed correctly? If so, how do I check if ffmpeg and gpac are compiled correctly?

Thanks

**Comment by jeanlf** [comment] 2021-04-26 13:20
Your syntax is correct (`enc:c=libkvazaar` ).
I guess you still use a different ffmpeg build, check the output of `gpac -h ffenc:libkvazaar`.

You can also check your ffmpeg version using `gpac -h ffenc | grep Version`, but it does not give you the compilation flags used (I'll look into that).

**Comment by jeanlf** [comment] 2021-04-26 14:34
With latest version, `gpac -h ffenc` will show the ffmpeg configuration info

**Comment by jakc-1** [comment] 2021-04-27 11:22
Thanks, I just recompiled gpac and now it looks like it's working, but now when I tried to execute following:

gpac -i rtmp://myURL/live ffsws:FID=S -+kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,rc-algorithm=lambda enc:SID=S:c=libkvazaar:b=1m:fintra=1:rc @ tilesplit:FID=1 enc:SID=S:c=libkvazaar:b=200k:fintra=1:rc @ tilesplit:FID=2 -o /home/path/live.mpd:SID=1,2

I get this:
No filter chain found for PID audio1 in filter ffdmx to any loaded filters - NOT CONNECTED
Disabling TMVP because tiles are used.
Disabling WPP because tiles were enabled.
Compiled: INTEL, flags:
Detected: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42
Available: sse2(2) sse41(4) 
In use: sse2(1) sse41(4) 
--owf=auto value set to 2.
--threads=auto value set to 4.
Disabling TMVP because tiles are used.
Disabling WPP because tiles were enabled.
Compiled: INTEL, flags:
Detected: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42
Available: sse2(4) sse41(8) 
In use: sse2(2) sse41(8) 
--owf=auto value set to 2.
--threads=auto value set to 4.
[Filter] ffsws not responding properly: 100000 consecutive process with no packet discarded or sent, but 4 packets pending
	discarding all inputs and notifying end of stream on all outputs

or sometimes this:
No filter chain found for PID audio1 in filter ffdmx to any loaded filters - NOT CONNECTED
Filters not connected:
ffsws (FID=S) (ID=S)
ffenc (SID=S:c=libkvazaar:b=1m:fintra=1:rc) (ID=_0x90708f0_)
tilesplit (FID=1) (ID=1)
ffenc (SID=S:c=libkvazaar:b=200k:fintra=1:rc) (ID=_0x9070d10_)
tilesplit (FID=2) (ID=2)
fout (dst=/home/path/live.mpd:SID=1,2) (ptr=0x9071130)

I am trying to split live video to tiles and encode it to different qualities and if I am not wrong this example (https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide#kvazaar-as-a-gpac-filter) is doing exactly that?

**Comment by jeanlf** [comment] 2021-04-28 10:16
Have you tried first with a local file ? Your command line works fine here using a 720p source avc.

**Comment by jakc-1** [comment] 2021-05-02 08:33
I have tried, but I am still getting this:
![image](https://user-images.githubusercontent.com/82051773/116807118-98c92b80-ab31-11eb-97a8-d0d9eb15543b.png)

What does this error mean?

**Comment by jeanlf** [comment] 2021-05-02 09:33
I tried this command line with a few sources (1080, 720), but I could not reproduce the issue. 
- Could you upload your source ?
- Could you post the resulting filter graph (add `-graph`to the command line) ?

**Comment by rbouqueau** [comment] 2021-05-02 09:34
The ```gpac``` graph resolver fails to build a proper graph. You can display the graph (and report it here) using the ```-graph``` option.

The difference between your command-line and the one in [the guide](https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide) is that your input is compressed (and requires a decoder).

You can guide the ```gpac``` graph resolver to connect an input with an output using the ```@``` symbol. In your case I added 2 ```@```:
```
gpac -i rtmp://myURL/live @ ffsws:FID=S -+kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,rc-algorithm=lambda @ enc:SID=S:c=libkvazaar:b=1m:fintra=1:rc @ tilesplit:FID=1 enc:SID=S:c=libkvazaar:b=200k:fintra=1:rc @ tilesplit:FID=2 -o /home/path/live.mpd:SID=1,2
```

Let us know if it helps.

**Comment by jakc-1** [comment] 2021-05-02 10:53
Still not working :( 
I tried command twice and got those resutls:

![img](https://user-images.githubusercontent.com/82051773/116810568-c8356380-ab44-11eb-9900-025c513fef9e.png)

I am streaming to rtmp from OBS webcam source, that plays in VLC correctly. The source I used locally was this: 

https://user-images.githubusercontent.com/82051773/116810609-fc108900-ab44-11eb-9aaf-89362ef6f5b8.mp4

**Comment by jakc-1** [comment] 2021-05-05 19:06
I tried with local file and graph and got this: 
![gpac_1](https://user-images.githubusercontent.com/82051773/117195034-149ece80-ade5-11eb-9371-16620d5b2437.png)

I assume that because ffsws is not responding properly, there is a Unknown argument error. But why is ffsws not responding properly? Is it because of the warning in third line? test.mp4 file is the same I provided in previous comment.

**Comment by jeanlf** [comment] 2021-05-06 09:25
I still can't reproduce here...

Can you try without explictly using ffsws :
`gpac -i test.mp4:FID=S -+kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,rc-algorithm=lambda enc:SID=S:c=libkvazaar:b=1m:fintra=1:rc @ tilesplit:FID=1 enc:SID=S:c=libkvazaar:b=200k:fintra=1:rc @ tilesplit:FID=2 -o dash/live.mpd:SID=1,2 -graph`

Also make sure a simple encoding without tiling works:
`gpac  -+kvazaar-params=rc-algorithm=lambda  -i test.mp4 @ enc:c=libkvazaar:b=1m:fintra=1:rc @ -o dash/live.mpd -graph`

**Comment by jakc-1** [comment] 2021-05-06 15:38
Looks like it is working without using ffsws, even though there is still an error **Unknown argument "-+kvazaar-params" set but not used by any filter - no matching argument found**. I got live.mpd file, test_dash_track1_init.mp4 file and a lot of m4s files, and when I play mpd, the tiles are slightly visible. Now I want to use live stream from rtmp instead of test.mp4. When I put rtmp://... @:FID=S instead of test.mp4:FID=S it starts executing, but I do not get the output files. What do I have to do, to eventually get the playable mpd file? I assume that because of live stream the mpd file has to be updating?

**Comment by jeanlf** [comment] 2021-05-07 06:46
> Looks like it is working without using ffsws, even though there is still an error Unknown argument "-+kvazaar-params" set but not used by any filter - no matching argument found.

Hmm that's definitely wrong. Could you give more info:
- OS version
- FFmpeg version

Also could you post the result of `gpac -hx ffenc:libkvazaar` ? 

> What do I have to do, to eventually get the playable mpd file? I assume that because of live stream the mpd file has to be updating?

You should get output files with this command line too. One way to check what is going on is to use the inspect filter instead of the dasher:

```
gpac -i test.mp4:FID=S -+kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,rc-algorithm=lambda enc:SID=S:c=libkvazaar:b=1m:fintra=1:rc @ tilesplit:FID=1 enc:SID=S:c=libkvazaar:b=200k:fintra=1:rc @ tilesplit:FID=2 inspect:deep:SID=1,2 -graph
```
This will print all packets and PID configuration coming out of the two `tilesplit` filters.


If your source is live, you should use DASH dynamic mode:
```
-o dash/live.mpd:dmode=dynamic
```

**Comment by jakc-1** [comment] 2021-05-07 15:10
This is the OS and configuration I use.
![gpac_2](https://user-images.githubusercontent.com/82051773/117470426-14bedb80-af57-11eb-8886-00a2cdb3067b.png)

**Comment by jeanlf** [comment] 2021-05-12 15:33
I patched both ffsws explicit loading bug and wrong report of ffmpeg options being unused, closing this.

If you still have issue with using rtmp as source, could you please open a new issue ?

**Closed by jeanlf** 2021-05-12 15:33 UTC
