### ISSUE TITLE
2fac884 onward fails to build MP4Box.exe with MinGW

### ISSUE THREAD

**Issue by wiiaboo** [gpac/gpac#344] opened 2015-12-02 03:17 UTC
8cccf166d13521d5a866d3cccfb877cae1e96bd2 (previous commit) works.
Using mingw-w64-crt 5.0.0.4592.90b8472
Configure: `--static-mp4box --extra-libs="-lz"`

Error:
```
make -C applications all
make[1]: Entering directory '/build/gpac-git/applications'
set -e; for i in  mp4box  ; do make -C $i all; done
make[2]: Entering directory '/build/gpac-git/applications/mp4box'
  CC main.c
  CC filedump.c
main.c: In function 'wmain':
main.c:4995:44: warning: passing argument 3 of 'gf_utf8_wcstombs' from incompatible pointer type [-Wincompatible-pointer-types]
   res_len = gf_utf8_wcstombs(argv[i], len, &src_str);
                                            ^
In file included from main.c:29:0:
E:/ab-full/build/gpac-git/include/gpac/utf.h:60:8: note: expected 'const short unsigned int **' but argument is of type 'wchar_t ** {aka short unsigned int **}'
 size_t gf_utf8_wcstombs(char* dst, size_t dst_len, const unsigned short** srcp);
        ^
  CC fileimport.c
fileimport.c: In function 'import_file':
fileimport.c:786:13: warning: variable 'read' set but not used [-Wunused-but-set-variable]
      size_t read;
             ^
  CC live.c
E:/ab-full/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.2.0/../../../../i686-w64-mingw32/lib/../lib/libmingw32.a(lib32_libmingw32_a-crt0_c.o): In function `main':
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status
Makefile:74: recipe for target 'MP4Box.exe' failed
make[2]: *** [MP4Box.exe] Error 1
make[2]: Leaving directory '/build/gpac-git/applications/mp4box'
Makefile:55: recipe for target 'apps' failed
make[1]: *** [apps] Error 2
```

**Comment by wiiaboo** [comment] 2015-12-02 03:46
Adding `-municode` seems to fix linking.
Source: http://sourceforge.net/p/mingw-w64/wiki2/Unicode%20apps/

**Comment by jeanlf** [comment] 2015-12-02 12:42
indeed, now fixed thanks for the report

**Closed by jeanlf** 2015-12-02 12:42 UTC

**Comment by rdp** [comment] 2016-07-05 20:23
I still get this failure when cross compiling, FWIW, --extra-ldflags=-municode is the workaround <sigh>

**Comment by rbouqueau** [comment] 2016-07-05 21:01
@rdp what's your exact toolchain so that I can reproduce?

**Comment by wiiaboo** [comment] 2016-07-05 21:57
It's probably because it's mingw but not in windows. Cross-compiling needs --target-os=mingw64 since it relies on uname.

**Comment by rbouqueau** [comment] 2016-07-06 06:35
Thanks. What does ```uname -s```gives on this? We could add it for automatic detection if the value is meaningful.

**Comment by rdp** [comment] 2016-09-26 16:41
Yeah it's cross compiling so possibly not useful since it can vary [?] `$ uname -s Darwin`
