### ISSUE TITLE
mp4box inconsistently outputs broken file

### ISSUE THREAD

**Issue by dansmithcode** [gpac/gpac#1455] opened 2020-04-06 15:00 UTC
About half of the time when I run mp4box to edit metadata, the output file is garbage.

Here's an invocation:

```
$ -> mp4box 01\ Points\ of\ Departure.m4v -itags cover= -out 01\ Points\ of\ Departure.1.m4v
[iso file] Unknown box type cios in parent dref
[iso file] Unknown box type pinf in parent mp4a
[iso file] extra box UNKN found in mp4a, deleting
[iso file] Unknown box type cios in parent dref
[iso file] Unknown box type uuid in parent avc1
[iso file] Unknown box type pinf in parent avc1
[iso file] Unknown box type cios in parent dref
[iso file] Box "----" (start 965444) has 69 extra bytes
Setting up iTunes/iPod file...
Saving to 01 Points of Departure.1.m4v: 0.500 secs Interleaving
```

This succeeds, removing the cover image and outputting a 547 MB file.

Here's another:

```
$ -> mp4box 01\ Points\ of\ Departure.m4v -itags cover= -out 01\ Points\ of\ Departure.3.m4v
[iso file] Unknown box type cios in parent dref
[iso file] Unknown box type pinf in parent mp4a
[iso file] extra box UNKN found in mp4a, deleting
[iso file] Unknown box type cios in parent dref
[iso file] Unknown box type uuid in parent avc1
[iso file] Unknown box type pinf in parent avc1
[iso file] Unknown box type cios in parent dref
[iso file] Box "----" (start 965444) has 69 extra bytes
Setting up iTunes/iPod file...
Saving to 01 Points of Departure.3.m4v: 0.500 secs Interleaving
```

This outputs a 2 MB file.

Running 10 times, here's my directory:

$ -> ls -l
total 5454008
-rw-r--r--  1 family  staff  547074871 Apr  6 08:50 01 Points of Departure.0.m4v
-rw-r--r--  1 family  staff  547074871 Apr  6 08:50 01 Points of Departure.1.m4v
-rw-r--r--  1 family  staff    1966153 Apr  6 08:50 01 Points of Departure.2.m4v
-rw-r--r--  1 family  staff  547074871 Apr  6 08:50 01 Points of Departure.3.m4v
-rw-r--r--  1 family  staff    1966153 Apr  6 08:50 01 Points of Departure.4.m4v
-rw-r--r--  1 family  staff  547074871 Apr  6 08:50 01 Points of Departure.5.m4v
-rw-r--r--  1 family  staff    1966153 Apr  6 08:50 01 Points of Departure.6.m4v
-rw-r--r--  1 family  staff    1966153 Apr  6 08:50 01 Points of Departure.7.m4v
-rw-r--r--  1 family  staff    1966153 Apr  6 08:50 01 Points of Departure.8.m4v
-rw-r--r--  1 family  staff    1966153 Apr  6 08:50 01 Points of Departure.9.m4v
-rwxr--r--  1 family  staff  547361292 Apr  6 08:16 01 Points of Departure.m4v

4 good runs, 6 garbage runs.

One way I can tell the garbage output is coming is that the command finishes immediately, rather than showing a progress bar that takes a few seconds to complete.

I tried `-v`, didn't see anything notable.

I've seen the same behavior on multiple files.

My system: macOS 10.15.3, GPAC 0.8.0-rev224-g656aca0e-master

Am I missing something obvious? Any suggestions on how to further diagnose?

**Comment by jeanlf** [comment] 2020-04-06 15:09
strange indeed - could you upload a sample file?

**Comment by jeanlf** [comment] 2020-11-22 16:17
I could not reproduce, and there's been a few cleanups in itunes tags since 0.8 so I'm closing this for now. Please check with latest git and reopen if needed (and post a test file)

**Closed by jeanlf** 2020-11-22 16:17 UTC
