### ISSUE TITLE
Insert TEMI timeline into non-video PID

### ISSUE THREAD

**Issue by angusbell** [gpac/gpac#283] opened 2015-10-14 15:59 UTC
We're using `MP42TS` to create transport streams with a TEMI timeline embedded in the video pid.

However, we have two additional requirements that do not appear to be supported:
1. Insert TEMI timeline into a PID carrying audio
2. Insert TEMI timeline into a PID carrying private PES data with no payload

In both cases we want the TEMI descriptors to be inserted into the adaptation field of the TS packet header, as is done with the video case.

Is this a feature that can be added?

**Comment by jeanlf** [comment] 2015-10-15 07:08
could you be more precise:
- do you want one TEMI stream per component ?
- one TEMI stream on audio when the program has both audio and video ?
- one TEMI stream on audio when the program has only audio ?
  
for private data, we don't mux them (appart from ac3 which is considered as audio)

**Comment by angusbell** [comment] 2015-10-16 09:01
It would be clearer if I just list our specific requirements:

1. A TS carrying a service with a TEMI timeline on the video pid and a separate TEMI timeline with a different id, on the audio pid.
2. A TS carrying an audio-only service (it has to be MPEG-1L2 audio) with a TEMI timeline on the audio pid.
3. A TS carrying a service with video, audio and DVB subtitles, and a TEMI timeline on the video.
4. A TS carrying a service with video and DVB subtitles with a TEMI timeline on a separate PES stream with no payload.

It sounds like you don't have capability to do requirement #4.

Requirement #3 may be easy to do, but I haven't investigated how to add DVB subtitles using `MP42TS`. Any help on this would be appreciated.

I hope this makes more sense.

**Comment by jeanlf** [comment] 2015-11-16 12:12
1 and 2 should now be working on GIT, could you check if it works as expected ?
 For 3 this shouldn't be very hard but we would need a sample MP4 file with DVB subs stored in it to check what needs to be done. For 4, do you want the TEMI to be carried inside the AF descriptor loop of the empty PES, or as a PES stream (the TS spec allows for both) ?

**Comment by beltsonata** [comment] 2015-11-17 14:51
>1 and 2 should now be working on GIT, could you check if it works as expected ?

When I do
-temi 129 -temi2 130

The TEMI timeline_id is the same (129) on both the video and audio pid. I was expecting the audio pid to have a TEMI timeline_id of 130.

**Comment by jeanlf** [comment] 2015-11-17 15:09
hmm strange I just tried on a file with one video and one audio track:
`MP42TS -src av.mp4 -dst-file test.ts -temi 129 -temi2 130`

and at playback side I can see both timelines 129 and 130, each one on the desired PIDs. Are you using a specific input file ?

**Comment by angusbell** [comment] 2015-11-17 15:28
I think the difference is that we're specifying two -src options, one with video and the second with audio, whereas you're specifying a single MP4 src with audio and video tracks on it. Would that explain the discrepancy?

**Comment by beltsonata** [comment] 2015-11-17 15:31
For the avoidance of doubt, the command used looks like:

MP42TS -src <audio.mp4> -src <video.mp4> -temi 129 -temi2 130 -pcr-init 0 -pcr-ms 40 -pcr-offset 25000 -rate 8000 -single-au -sdt-rate 1000 -dst-file <outfile.ts>

**Comment by jeanlf** [comment] 2015-11-17 15:34
yes using of two sources might be the issue, I'll check that asap

**Comment by jeanlf** [comment] 2015-11-17 16:15
should now be fixed on git

**Comment by beltsonata** [comment] 2015-11-17 16:25
Thanks, that has fixed the differing timelien_ids.

**Comment by angusbell** [comment] 2015-11-18 10:43
Hi Jean

**Comment by angusbell** [comment] 2015-11-18 10:46
Hi Jean - in relation to your request for an MP4 containing DVB subtitles, we're not sure how to create this. DVB subtitles are bitmaps in a bespoke encoding. How would we encapsulate this in an MP4 container?

**Comment by beltsonata** [comment] 2015-11-19 15:24
I think this commit (9f09b137027ee25d4435fa947b293c265b8c867e) has changed the way PIDs are assigned to elementary streams in the resulting MPEG-2 TS.

i.e. with this command line

MP42TS -src video.mp4 -src audio.mp4 -temi 128 -pcr-init 0 -pcr-ms 40 -pcr-offset 25000 -rate 8000 -single-au -sdt-rate 1000 -dst-file outfile.ts

Previously, this was assigning the video to PID 111 (along with the TEMI timline) and the audio to PID 101. Now the PIDs appear to have been swapped over, and the TEMI timeline is on the audio PID 101, regardless of the order of the '-src' switches I use.

We really need our scripts using MP42TS to reliably reproduce the same transport streams each time they run, and for new additions to MP42TS not to break or change existing functionality (ideally, we would be able to specify the PIDs assigned to each elementary streams directly via the CLI, and also which PID the TEMI descriptor is assigned to).

**Comment by beltsonata** [comment] 2015-11-23 12:33
I have done some more analysis.

1) 

MP42TS -src audio.mp4 -src video.mp4 -temi -temi2 129 -pcr-init 0 -pcr-ms 40 -pcr-offset 25000 -rate 8000 -single-au -sdt-rate 1000 -dst-file outfile.ts

This assigns the audio to PID 101 (with TEMI timeline_id 150) and the video to PID 111 (with TEMI timeline_id 129).

2) Swapped -src order

MP42TS -src video.mp4 -src audio.mp4 -temi -temi2 129 -pcr-init 0 -pcr-ms 40 -pcr-offset 25000 -rate 8000 -single-au -sdt-rate 1000 -dst-file outfile.ts

This assigns the video to PID 101 (with TEMI timeline_id 150) and the audio to PID 111 (with TEMI timeline_id 129)

3) As per 1, but with -temi and -temi2 swapped

MP42TS -src audio.mp4 -src video.mp4 -temi2 129 -temi -pcr-init 0 -pcr-ms 40 -pcr-offset 25000 -rate 8000 -single-au -sdt-rate 1000 -dst-file outfile.ts

This assigns the video to PID 101 (with TEMI timeline_id 150) and the audio to PID 111 (with TEMI timeline_id 129)

4) As per 3, but with the -src order swapped

MP42TS -src video.mp4 -src audio.mp4 -temi2 129 -temi -pcr-init 0 -pcr-ms 40 -pcr-offset 25000 -rate 8000 -single-au -sdt-rate 1000 -dst-file outfile.ts

This assigns the video to PID 101 (with TEMI timeline_id 150) and the audio to PID 111 (with TEMI timeline_id 129), i.e. the same as 3.

The result is that the order of the -src switches matters, but so do the order of the -temi and -temi2 switches.

**Comment by cconcolato** [comment] 2015-12-04 13:56
Hi @angusbell 

> Hi Jean - in relation to your request for an MP4 containing DVB subtitles, we're not sure how to create this. DVB subtitles are bitmaps in a bespoke encoding. How would we encapsulate this in an MP4 container?

There is no official carriage of DVB subtitles in MP4. There is a code point for PNG image streams (see http://mp4ra.org/codecs.html), so you could probably transcode your DVB subtitle images to PNG images, and store them as a PNG stream in an MP4. The problem is to signal that this is a subtitle stream. I don't know if we could use a 'text' or 'subt' track handler for that. We should probably raise that question within MPEG, possibly to extend MPEG-4 Part 30.

In GPAC, we also have some support for vobsub files. You could export your DVB Subtitles in that format and then import then vobsub file into an MP4 file with MP4Box. It uses a code point (stream type 0x38 and object type 0xe0) in the user-space, not officially registered, that some old Nero Digital streams. Unfortunately, there seems to be a regression in the player as we don't play them (some ffmpeg errors). Anyway, this would need to be clarified from a standard point of view.

**Comment by angusbell** [comment] 2015-12-24 12:01
Hi @jeanlf 

We're happy to drop our requests for adding DVB subtitles, as we have devised an alterntaive solution to this. However, we're still concerned about the change to the meaning of the command line options as commented on 19 Nov.

This change means that earlier invocations of MP42TS, when re-run now, result in a transport stream that is different in ways that are materially important to us: specifically on which pid(s) the TEMI timeline(s) are carried, and on which pid the PCR is carried.

We want to be in the situation where we can run the same command line one year from now and reproduce the same transport stream: that is to say, the same transport stream in terms of structure and composition, not necessarily the same bitwise transport stream.

I believe that the code contains the functionality that we need in this area; it's just that the command line options don't give us the control we need.

What we need is to be able to specify, on the command line:-
(a) which pid carries the first TEMI timeline, and what its TEMI timeline_id is;
(b) which pid carries the second TEMI timeline, and what its TEMI timeline_id is;
(c) which pid carries the PCR.

If we could achieve this deterministically, rather than by trial and error, it would greatly help our ability to continue to use the tool moving forward.

Thanks.

**Comment by angusbell** [comment] 2016-02-01 15:01
Hi @jeanlf 

You may not have noticed my last comment, as it was immediately before Christmas. To summarise, we are happy with the functionality provided, and all we need now are some modifications to the command line options to make them more user-friendly and deterministic.

If you could make such small modifications, that would be great.

Thanks.

**Comment by jeanlf** [comment] 2019-06-28 15:28
MP42TS is now deprecated, use GPAC 0.9.0 to do this

**Closed by jeanlf** 2019-06-28 15:28 UTC
Labels: feature-request, mp42ts
