### ISSUE TITLE
PAR and SAR calculation errors in DASH MPD file. 

### ISSUE THREAD

**Issue by Buster223** [gpac/gpac#556] opened 2016-06-14 21:44 UTC
Using GPAC version 0.6.2-DEV-rev576

I am packaging multiple mp4 files to DASH. All of the files are 16:9 aspect ratio but are being broken up into 2 different adaptation sets. I need to keep in one adaptation set. 

For the 1920x1080 rendition (and others), PAR is being set to 16:9 and SAR is being set to 1:1. This is correct. 

For the 412x236 rendition, the PAR is being set to 412:236 and the SAR is being set to 1:1. However, the PAR should be 16:9 and the SAR should be (412 \* 9) : (236 \* 16). 

I believe this is what is causing the generation of the 2 different adaptation sets. It appears that there is a calculation error in mp4box. 

Can you confirm?

**Comment by sandersaares** [comment] 2016-06-15 06:01
Can you provide steps to reproduce? I have done quite a bit of testing with aspect ratio calculations for my own use of mp4box and am not aware of any remaining issues.

NB! Despite the name, the `par` field in the DASH manifest is actually DAR.

**Comment by Buster223** [comment] 2016-06-15 11:14
Thank you for your response. I will post the command line once I get from the developer. In the meantime, can you help me confirm my understanding?

PAR in the DASH manifest refers to the Display Aspect Ratio. I assume that mp4box should simply pull this information directly from the Display Aspect Ratio in mp4 file. This is correct?

The SAR is the Pixel Aspect Ratio and mp4box should be calculating this from the Display Aspect Ratio and the video dimensions of the file. Is this correct?

**Comment by sandersaares** [comment] 2016-06-15 11:58
> PAR in the DASH manifest refers to the Display Aspect Ratio.
> The SAR is the Pixel Aspect Ratio

I have the same understanding, yes, although I lack sufficient knowledge to comment on where mp4box takes the data from.

Can you provide the video files that can be used to reproduce the unexpected behavior you encountered?

**Comment by rbouqueau** [comment] 2016-09-13 08:38
For all readers, there is a patch available at https://github.com/gpac/gpac/compare/dash_relax_ar_in_as

This is not approved by the other GPAC contributors because it can lead to image distortion. However I could make it available as an option that would display a warning. Would it make sense for you?

**Comment by rbouqueau** [comment] 2016-10-10 12:56
No answer = no. Closing for now.

**Comment by ssanthos** [comment] 2016-11-18 08:34
@rbouqueau I was facing the same problem. Thanks for the patch. Would love to have it available as an option.

**Closed** 2017-07-28 13:33 UTC
Labels: dash, mp4box, question
