### ISSUE TITLE
error compiling gpac

### ISSUE THREAD

**Issue by Catskan** [gpac/gpac#418] opened 2016-02-17 16:15 UTC
Hi,

When I compiling gpac, I have this error message 

`make
make -C src all
make[1] : on entre dans le répertoire « /home/phraseanet/Phraseanet/gpac/src »
make[1]: Rien à faire pour « all ».
make[1] : on quitte le répertoire « /home/phraseanet/Phraseanet/gpac/src »
make -C applications all
make[1] : on entre dans le répertoire « /home/phraseanet/Phraseanet/gpac/applications »
set -e; for i in  mp4client  mp4box  mp42ts  dashcast ; do make -C $i all; done 
make[2] : on entre dans le répertoire « /home/phraseanet/Phraseanet/gpac/applications/mp4client »
make[2] : on quitte le répertoire « /home/phraseanet/Phraseanet/gpac/applications/mp4client »
make[2] : on entre dans le répertoire « /home/phraseanet/Phraseanet/gpac/applications/mp4box »
make[2] : on quitte le répertoire « /home/phraseanet/Phraseanet/gpac/applications/mp4box »
make[2] : on entre dans le répertoire « /home/phraseanet/Phraseanet/gpac/applications/mp42ts »
make[2] : on quitte le répertoire « /home/phraseanet/Phraseanet/gpac/applications/mp42ts »
make[2] : on entre dans le répertoire « /home/phraseanet/Phraseanet/gpac/applications/dashcast »
/usr/bin/ld: /usr/local/lib/libavcodec.a(aacps_float.o): référence au symbole non défini «hypot@@GLIBC_2.2.5»
/usr/bin/ld: note: «hypot@@GLIBC_2.2.5» est défini dans le DSO /lib64/libm.so.6 donc essayez de l'ajouter à la ligne de commande du lieur
/lib64/libm.so.6: could not read symbols: Opération invalide
collect2: erreur: ld a retourné 1 code d'état d'exécution
make[2]: *** [DashCast] Erreur 1
make[2] : on quitte le répertoire « /home/phraseanet/Phraseanet/gpac/applications/dashcast »
make[1]: *** [apps] Erreur 2
make[1] : on quitte le répertoire « /home/phraseanet/Phraseanet/gpac/applications »
make: *** [all] Erreur 2
[phraseanet@Phraseanet gpac]$ 
`

How can I solve this ?

Thanks you

**Comment by rbouqueau** [comment] 2016-02-17 16:18
Thanks fro reporting. Could you give us info about your GPAC version, OS, build system etc.? See http://gpac.io//2013/07/16/how-to-file-a-bug-properly/ for guidelines.

**Comment by Catskan** [comment] 2016-02-17 16:21
Oh sorry I missing.

OS - CentOS 7 x64
GPAC Version - 0.5 (git clone https://github.com/gpac/gpac)
./configure - Ok, no errors
build system - gcc I think

**Comment by rbouqueau** [comment] 2016-02-17 16:28
> /usr/local/lib/libavcodec.a

Why is it in /usr/local? Did you build it your self?

If you want me to help you, you need to give me enough information so that I can reproduce your issue.  Even if that implies to install a VM.

**Comment by Catskan** [comment] 2016-02-17 16:39
No, I didn't build any lib.

I installed just ffmpeg-3 (compile last release on official website) after tried compile gpac. That's it.

`git clone https://github.com/gpac/gpac
cd /home/user/gpac
./configure
make


./configure result :
`** System Configuration
Install prefix: /usr/local
Source path: /home/phraseanet/gpac
C   compiler: gcc
C++ compiler: g++
make: make
CPU: x86_64
Big Endian: no

** GPAC 0.5.2-DEV rev1198-g8a9b9bc-master Core Configuration **
debug version: no
GProf enabled: no
Static build enabled: no
Memory tracking enabled: no
Fixed-Point Version: no
IPV6 Support: yes
Static Modules: no

** Detected libraries **
zlib: system
OSS Audio: yes
ALSA Audio: yes
Jack Audio: no
PulseAudio Audio: no
DirectFB support: no
X11 Shared Memory support: yes (path: /usr/X11R6)
X11 XVideo support: no
SDL Support: yes
OpenGL support: yes
TinyGL support: no
OpenSSL support: no
Mozilla XUL/GECKO support: no
DVB Support: yes
XMLRPC Support: no
wxWidgets support: no

** Extra Libraries used **
SpiderMonkey: no
FreeType: system
JPEG: no
OpenJPEG: no
PNG: system
MAD: no
FAAD: no
XVID: no
FFMPEG: system
Xiph OGG: no
Platinum UPnP: no
AVCap: no
A52 (AC3): no
OpenSVCDecoder: no
OpenHEVCDecoder: no
Freenect: no

Creating config.mak
Check config.log for detection failures
Done - type 'make help' for make info, 'make' to build`
`

make result :
`CC dashcast.c
  CC audio_data.c
  CC audio_decoder.c
audio_decoder.c: In function ‘dc_audio_decoder_read’:
audio_decoder.c:251:5: attention : ‘av_free_packet’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
     av_free_packet(&packet);
     ^
audio_decoder.c:368:3: attention : ‘av_free_packet’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
   av_free_packet(&packet);
   ^
audio_decoder.c: In function ‘dc_audio_decoder_close’:
audio_decoder.c:386:4: attention : ‘av_free_packet’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
    av_free_packet(pkt);
    ^
  CC audio_encoder.c
audio_encoder.c: In function ‘dc_audio_encoder_encode’:
audio_encoder.c:320:3: attention : ‘av_free_packet’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
   av_free_packet(&audio_output_file->packet);
   ^
  CC audio_muxer.c
audio_muxer.c: In function ‘dc_ffmpeg_audio_muxer_write’:
audio_muxer.c:323:3: attention : ‘av_free_packet’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
   av_free_packet(&audio_output_file->packet);
   ^
audio_muxer.c:327:2: attention : ‘av_free_packet’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
  av_free_packet(&audio_output_file->packet);
  ^
audio_muxer.c: In function ‘dc_ffmpeg_audio_muxer_open’:
audio_muxer.c:297:23: attention : ignoring return value of ‘avformat_write_header’, declared with attribute warn_unused_result [-Wunused-result]
  avformat_write_header(audio_output_file->av_fmt_ctx, NULL);
                       ^
  CC circular_buffer.c
  CC cmd_data.c
  CC controler.c
controler.c: In function ‘video_encoder_thread’:
controler.c:884:5: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
     if ((loss_state==1) && out_file.codec_ctx->coded_frame->key_frame) {
     ^
  CC message_queue.c
  CC register.c
  CC video_data.c
  CC video_decoder.c
video_decoder.c: In function ‘dc_video_decoder_read’:
video_decoder.c:256:5: attention : ‘av_free_packet’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
     av_free_packet(&packet);
     ^
video_decoder.c:318:5: attention : ‘av_free_packet’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
     av_free_packet(&packet);
     ^
video_decoder.c:403:6: attention : ‘av_free_packet’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
      av_free_packet(&packet);
      ^
video_decoder.c:411:3: attention : ‘av_free_packet’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
   av_free_packet(&packet);
   ^
  CC video_encoder.c
video_encoder.c: In function ‘dc_video_encoder_encode’:
video_encoder.c:226:5: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
     video_codec_ctx->coded_frame->pts = video_codec_ctx->coded_frame->pkt_pts = pkt.pts;
     ^
video_encoder.c:226:5: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
video_encoder.c:227:5: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
     video_codec_ctx->coded_frame->pkt_dts = pkt.dts;
     ^
video_encoder.c:228:5: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
     video_codec_ctx->coded_frame->key_frame = (pkt.flags & AV_PKT_FLAG_KEY) ? 1 : 0;
     ^
  CC video_muxer.c
video_muxer.c: In function ‘dc_gpac_video_isom_write’:
video_muxer.c:538:2: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
  video_output_file->sample->DTS = video_codec_ctx->coded_frame->pkt_dts;
  ^
video_muxer.c:539:2: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
  video_output_file->sample->CTS_Offset = (s32) (video_codec_ctx->coded_frame->pts - video_output_file->sample->DTS);
  ^
video_muxer.c:540:2: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
  video_output_file->sample->IsRAP = video_codec_ctx->coded_frame->key_frame;
  ^
video_muxer.c: In function ‘dc_ffmpeg_video_muxer_write’:
video_muxer.c:689:2: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
  if (video_codec_ctx->coded_frame->pts != AV_NOPTS_VALUE) {
  ^
video_muxer.c:690:3: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
   pkt.pts = av_rescale_q(video_codec_ctx->coded_frame->pts, video_codec_ctx->time_base, video_stream->time_base);
   ^
video_muxer.c:693:2: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
  if (video_codec_ctx->coded_frame->key_frame)
  ^
video_muxer.c:706:2: attention : ‘av_free_packet’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
  av_free_packet(&pkt);
  ^
video_muxer.c: In function ‘dc_video_muxer_write’:
video_muxer.c:834:6: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
      gf_isom_set_fragment_reference_time(video_output_file->isof, video_output_file->trackID, ntp_timestamp, video_output_file->codec_ctx->coded_frame->pts);
      ^
video_muxer.c:837:5: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
     video_output_file->first_dts_in_fragment = video_output_file->codec_ctx->coded_frame->pkt_dts;
     ^
video_muxer.c:839:6: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
      video_output_file->pts_at_segment_start = video_output_file->codec_ctx->coded_frame->pts;
      ^
video_muxer.c:851:8: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
        s32 ts_diff = (s32) ( 1000 * (video_output_file->codec_ctx->coded_frame->pts - video_output_file->pts_at_first_segment) / video_output_file->timescale );
        ^
video_muxer.c:865:4: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
    video_output_file->last_pts = video_output_file->codec_ctx->coded_frame->pts;
    ^
video_muxer.c:866:4: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
    video_output_file->last_dts = video_output_file->codec_ctx->coded_frame->pkt_dts;
    ^
video_muxer.c:885:5: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
     GF_LOG(GF_LOG_INFO, GF_LOG_DASH, ("[DashCast] Flushed fragment at UTC "LLU" ms - First DTS "LLU" last PTS "LLU" - First Segment PTS "LLU" timescale %d\n", gf_net_get_utc(), video_output_file->first_dts_in_fragment, video_output_file->codec_ctx->coded_frame->pts, video_output_file->pts_at_segment_start, video_output_file->timescale));
     ^
video_muxer.c:898:5: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
     video_output_file->pts_at_segment_start = video_output_file->codec_ctx->coded_frame->pts;
     ^
video_muxer.c:915:4: attention : ‘coded_frame’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:2945) [-Wdeprecated-declarations]
    GF_LOG(GF_LOG_INFO, GF_LOG_DASH, ("[DashCast] Flushed fragment to disk at UTC "LLU" ms - last coded frame PTS "LLU"\n", gf_net_get_utc(), video_output_file->codec_ctx->coded_frame->pts));
    ^
video_muxer.c: In function ‘dc_ffmpeg_video_muxer_open’:
video_muxer.c:673:23: attention : ignoring return value of ‘avformat_write_header’, declared with attribute warn_unused_result [-Wunused-result]
  avformat_write_header(video_output_file->av_fmt_ctx, NULL);
                       ^
video_muxer.c: In function ‘hevc_import_ffextradata’:
video_muxer.c:327:12: attention : ‘idx’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    slc->id = idx;
            ^
  CC video_scaler.c
video_scaler.c: In function ‘dc_video_scaler_node_create’:
video_scaler.c:53:2: attention : ‘avpicture_alloc’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4871) [-Wdeprecated-declarations]
  avpicture_alloc((AVPicture*)video_scaled_data_node->v_frame, pix_fmt, width, height);
  ^
video_scaler.c:55:3: attention : ‘avpicture_alloc’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4871) [-Wdeprecated-declarations]
   avpicture_alloc((AVPicture*)video_scaled_data_node->cropped_frame, pix_fmt, width-crop_x, height-crop_y);
   ^
video_scaler.c: In function ‘dc_video_scaler_scale’:
video_scaler.c:201:3: attention : ‘av_picture_crop’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4911) [-Wdeprecated-declarations]
   if (av_picture_crop((AVPicture*)video_scaled_data_node->cropped_frame, (AVPicture*)video_data_node->vframe, PIX_FMT_YUV420P, video_input_data->vprop[index].crop_y, video_input_data->vprop[index].crop_x) < 0) {
   ^
video_scaler.c:230:4: attention : ‘av_free_packet’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4040) [-Wdeprecated-declarations]
    av_free_packet(&video_data_node->raw_packet);
    ^
  CC task.c
/usr/bin/ld: /usr/local/lib/libavcodec.a(aacps_float.o): référence au symbole non défini «hypot@@GLIBC_2.2.5»
/usr/bin/ld: note: «hypot@@GLIBC_2.2.5» est défini dans le DSO /lib64/libm.so.6 donc essayez de l'ajouter à la ligne de commande du lieur
/lib64/libm.so.6: could not read symbols: Opération invalide
collect2: erreur: ld a retourné 1 code d'état d'exécution
make[2]: *** [DashCast] Erreur 1
make[2] : on quitte le répertoire « /home/phraseanet/gpac/applications/dashcast »
make[1]: *** [apps] Erreur 2
make[1] : on quitte le répertoire « /home/phraseanet/gpac/applications »
make: *** [all] Erreur 2
[phraseanet@Phraseanet gpac]$ 
`

**Comment by rbouqueau** [comment] 2016-02-17 16:48
> I installed just ffmpeg-3 (compile last release on official website) after tried compile gpac. That's it.

Two steps:
1) Could you please make './configure --verbose && make' and print the output here?
2) If you build ffmpeg as a dynamic lib, do you get the error?

Your error is probably due to a wrong order in the inclusion of libm at link time. I'd like to know why yet.

**Comment by Catskan** [comment] 2016-02-18 10:00
I builded ffmpeg with ./configure --enable-shared and I had no error.

The output of ./configure --verbose && make : 
[http://pastebin.com/eYGvnqdd](url)

**Comment by rbouqueau** [comment] 2016-02-18 10:07
Ok. I close it. Re-open if necessary.

**Closed by rbouqueau** 2016-02-18 10:07 UTC
Labels: build

**Comment by akrv** [comment] 2019-01-28 00:35
Got the same error using the svn repo.
Cloned the git repo and it works fine for me.
