### ISSUE TITLE
PNG images not displayed in Android 5.1.1

### ISSUE THREAD

**Issue by traianlavric** [gpac/gpac#305] opened 2015-10-30 10:57 UTC
I installed the last nightly build (osmo4-0.5.2-DEV-latest-master-stagefright.apk) on Android 5.1.1 and the PNG images are not being displayed. I simply start Osmo4 and open a png image. There is no error in the logs except a "Invalid qct format (611)". I also compiled the sources and generate the APK and I got the same behaviour. I have tried it on some other device and got the same issue.

**Comment by rbouqueau** [comment] 2015-10-30 15:34
I al really unsure, but could it be related to http://gpac.io/2011/09/01/jpeg-support-for-android-resolving-libjpeg-so-conflicts/?

**Comment by fcsteagu** [comment] 2015-10-30 15:44
I think it's not related to that. Libpng is loaded and moreover the JPEG images are rendered, only PNG images are not.
I have installed osmo4-0.5.2-DEV-rev930-g8c38743-master.apk and I get this in the console:

_I/GF_LOG_COMPOSE(24823): [Compositor] GLES Vertex shader not found, disabling shaders
I/GF_LOG_COMPOSE(24823): [Compositor] GLES Fragment shader not found, disabling shaders_

I don't know if this is related to PNG images not being shown..

**Comment by nguyen-viet-thanh-trung** [comment] 2015-11-03 08:58
@fcsteagu  Could you please try the latest version ?

**Comment by fcsteagu** [comment] 2015-11-03 09:03
You mean the last nigthly build without stagefright? (osmo4-0.5.2-DEV-latest-master.apk)
thanks!

**Comment by nguyen-viet-thanh-trung** [comment] 2015-11-03 09:12
This is osmo4-0.5.2-DEV-rev943-g805fefa-master.apk (for the build without stagefright) or osmo4-0.5.2-DEV-rev943-g805fefa-master-stagefright.apk (with support stagefright).

**Comment by nguyen-viet-thanh-trung** [comment] 2015-11-03 09:27
@fcsteagu sorry there was a problem with our buildbot so this is not the latest version, I'll tell you asap I fix it !

**Comment by fcsteagu** [comment] 2015-11-03 09:55
ok, I'm waiting then :)

**Comment by nguyen-viet-thanh-trung** [comment] 2015-11-03 12:56
It should be ok now. Could you please test osmo4-0.5.2-DEV-latest-master.apk (or osmo4-0.5.2-DEV-rev955-g4c659b5-master.apk, they are identical) ?

**Comment by fcsteagu** [comment] 2015-11-03 13:22
I have tested it and the PNG images are rendered but there is another problem it seems.
I have attached screenshots with the errors. As you can see, they keep showing even if I leave the application. I have to force close Osmo4 in order to get rid of them.

![screenshot_2015-11-03-14-03-26](https://cloud.githubusercontent.com/assets/2527837/10909015/27a0e260-8236-11e5-9cb5-c6013b18b2df.png)
![screenshot_2015-11-03-14-17-21](https://cloud.githubusercontent.com/assets/2527837/10909023/303dec9c-8236-11e5-83f7-1bb50b70a189.png)
![screenshot_2015-11-03-14-17-48](https://cloud.githubusercontent.com/assets/2527837/10909031/4164ecdc-8236-11e5-8370-6f67a634d781.png)
![screenshot_2015-11-03-14-17-23](https://cloud.githubusercontent.com/assets/2527837/10909032/4165ad16-8236-11e5-8cfd-7f221e846070.png)
![screenshot_2015-11-03-14-17-25](https://cloud.githubusercontent.com/assets/2527837/10909035/41676cdc-8236-11e5-8822-6190fd4a8363.png)
![screenshot_2015-11-03-14-17-27](https://cloud.githubusercontent.com/assets/2527837/10909030/4164e5d4-8236-11e5-935e-98596ab613ab.png)
![screenshot_2015-11-03-14-17-29](https://cloud.githubusercontent.com/assets/2527837/10909033/416645c8-8236-11e5-9026-758245cfc782.png)
![screenshot_2015-11-03-14-17-31](https://cloud.githubusercontent.com/assets/2527837/10909034/416753c8-8236-11e5-9454-db131bfd9484.png)
![screenshot_2015-11-03-14-17-33](https://cloud.githubusercontent.com/assets/2527837/10909037/418423ae-8236-11e5-9176-8212502ea33c.png)
![screenshot_2015-11-03-14-17-39](https://cloud.githubusercontent.com/assets/2527837/10909036/41838462-8236-11e5-82b4-32cce5c1bc70.png)
![screenshot_2015-11-03-14-17-41](https://cloud.githubusercontent.com/assets/2527837/10909038/418ac68c-8236-11e5-95c2-8cd77e6d6755.png)

**Comment by fcsteagu** [comment] 2015-11-03 16:30
Hmm it seems that the PNG images are still not rendered on Android 5. I was also trying to play a video and it is very slow. Could you tell me where is now the config file stored?

**Comment by nguyen-viet-thanh-trung** [comment] 2015-11-03 16:36
The problem of error message should be fixed now. Could you please retry ? GPAC.cfg is stored in application data dir (normally /data/data/com.gpac.Osmo4)

**Comment by fcsteagu** [comment] 2015-11-03 16:43
Indeed the error messages are gone now but the PNG images are still not displayed. 

Hmm I think data/data/ is only accessible if the phone is rooted so there is no access to the GPAC.cfg file which is not very convenient :(

One more question: how can I get rid of the default menu, the one at the bottom of the screen?
Thanks

**Comment by nguyen-viet-thanh-trung** [comment] 2015-11-03 16:55
Could you share somewhere your PNG images ? I tested in my device (Nexus 5, Android 5.1) and it worked.

**Comment by fcsteagu** [comment] 2015-11-03 16:58
yes of course. These are some of them...
![ancient_scroll](https://cloud.githubusercontent.com/assets/2527837/10914846/7cdf3f06-8254-11e5-8ca5-a1373a0099d7.png)
![actions-games-hint-icon](https://cloud.githubusercontent.com/assets/2527837/10914851/80437e5a-8254-11e5-96c1-e10e435a5943.png)
![help_tab_on](https://cloud.githubusercontent.com/assets/2527837/10914855/83c064bc-8254-11e5-9ca6-e207f18fdf4a.png)

**Comment by nguyen-viet-thanh-trung** [comment] 2015-11-03 17:12
Seem that it work with me.
![screenshot_20151103-180838](https://cloud.githubusercontent.com/assets/10617871/10915301/6eff9a0a-8256-11e5-8ac5-00b219e9162f.png)
![screenshot_20151103-180846](https://cloud.githubusercontent.com/assets/10617871/10915303/6f01a7e6-8256-11e5-9036-a47068079215.png)
![screenshot_20151103-180850](https://cloud.githubusercontent.com/assets/10617871/10915302/6f018fc2-8256-11e5-94d9-5003d8576932.png)

**Comment by fcsteagu** [comment] 2015-11-03 18:03
hmm that's really weird!!
I get this in the logs:
I/Adreno  ( 9206): GetNativeFormatFromQctPixelFormat: Invalid qct format (611)
I/Adreno  ( 9206): GetNativeFormatFromQctPixelFormat: Invalid qct format (611)
I/Adreno  ( 9206): GetNativeFormatFromQctPixelFormat: Invalid qct format (611)
I/Adreno  ( 9206): GetNativeFormatFromQctPixelFormat: Invalid qct format (611)
I/Adreno  ( 9206): GetNativeFormatFromQctPixelFormat: Invalid qct format (612)
I/Adreno  ( 9206): GetNativeFormatFromQctPixelFormat: Invalid qct format (612)
I/Adreno  ( 9206): GetNativeFormatFromQctPixelFormat: Invalid qct format (612)
I/Adreno  ( 9206): GetNativeFormatFromQctPixelFormat: Invalid qct format (612)

How can I debug because there is no other message that I can see...

**Comment by fcsteagu** [comment] 2015-11-04 15:16
Hi again,

I managed to put Android 5.1 on my Nexus 5 and I can confirm the PNG images are not displayed. There is no error in the logcat. Screenshots attached below: in the first one the device and softare info are shown and the other one is how the PNG image is displayed.

![screenshot_2015-11-04-16-13-41](https://cloud.githubusercontent.com/assets/2527837/10942208/4fbfcff2-830f-11e5-9b4f-30b8d92000fe.png)
![screenshot_2015-11-04-16-13-21](https://cloud.githubusercontent.com/assets/2527837/10942213/51b2899e-830f-11e5-810a-f41af226fefb.png)

**Comment by nguyen-viet-thanh-trung** [comment] 2015-11-04 17:31
Hi,
Did you have anymore these messages ?
I/GF_LOG_COMPOSE(24823): [Compositor] GLES Vertex shader not found, disabling shaders
I/GF_LOG_COMPOSE(24823): [Compositor] GLES Fragment shader not found, disabling shaders

If yes, please reset the config file (Option button > More > Reset GPAC config) then reopen it.
Btw, have you got in osmo/log any debug.txt files ?

**Comment by fcsteagu** [comment] 2015-11-04 19:54
No, I don't get those errors in logcat. Maybe I have to specify the log level in the config file to see them?
I already reseted the config file from the menu.
There is nothing in osmo/log directory. :(

**Comment by nguyen-viet-thanh-trung** [comment] 2015-11-05 14:17
Could you please checkout osmo4-0.5.2-DEV-rev974-g2c01d16-master.apk ? FYI there are some changes for debugging:
- use GPAC.cfg in your /sdcard/osmo if it exists
- you can enable debug mode (Option button > More > Quick setting then check Enable Debug)

**Comment by fcsteagu** [comment] 2015-11-06 04:20
hi,
I will not be able to do tests one week from now but I will let you know as soon as I can.
What I can tell you is that there was no GPAC.cfg in /sdcard/osmo when I was using the latest build.
Enabling the debug mode would give me a lot of text in the logcat (really a lot) and I could not see any error message there..

**Comment by nguyen-viet-thanh-trung** [comment] 2015-11-06 09:00
@fcsteagu if there is no GPAC.cfg in /sdcard/osmo then Osmo try to create and use the default config in  /data/data/com.gpac.Osmo4. If you want to debug (by changing sth in GPAC.cfg for example) you can create your own GPAC.cfg in /sdcard/osmo. For the problem ò PNG, it is really weird. I'll try also to reproduce it and let you know. Thank you for your feedback

**Comment by fcsteagu** [comment] 2015-11-13 12:08
hi there again!

So I managed to test the last master version and I get the following (errors) in the console. The PNG images are still not displayed..

_W/linker  (16170): libswscale.so: unused DT entry: type 0x6ffffffe arg 0xcec
W/linker  (16170): libswscale.so: unused DT entry: type 0x6fffffff arg 0x1
I/LibrariesLoader(16170): Loading library swresample...
W/linker  (16170): libswresample.so: unused DT entry: type 0x6ffffffe arg 0xb68
W/linker  (16170): libswresample.so: unused DT entry: type 0x6fffffff arg 0x1
I/LibrariesLoader(16170): Loading library avcodec...
W/linker  (16170): libavcodec.so: unused DT entry: type 0x6ffffffe arg 0x5228
W/linker  (16170): libavcodec.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker  (16170): libavcodec.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
I/LibrariesLoader(16170): Loading library avformat...
W/linker  (16170): libavformat.so: unused DT entry: type 0x6ffffffe arg 0x53e4
W/linker  (16170): libavformat.so: unused DT entry: type 0x6fffffff arg 0x2
I/LibrariesLoader(16170): Loading library avfilter...
W/linker  (16170): libavfilter.so: unused DT entry: type 0x6ffffffe arg 0x3e20
W/linker  (16170): libavfilter.so: unused DT entry: type 0x6fffffff arg 0x5_

and maybe this is also somehow important:

_I/Adreno  (16170): QUALCOMM build                   : d809d99, Ie081474390
I/Adreno  (16170): Build Date                       : 04/28/15
I/Adreno  (16170): OpenGL ES Shader Compiler Version: E031.25.03.07
I/Adreno  (16170): Local Branch                     : LA.BF64.1.2.1_RB2.05.01.00.081.009
I/Adreno  (16170): Remote Branch                    :
I/Adreno  (16170): Remote Branch                    :
I/Adreno  (16170): Reconstruct Branch               :
I/Adreno  (16170): GetNativeFormatFromQctPixelFormat: Invalid qct format (611)
I/Adreno  (16170): GetNativeFormatFromQctPixelFormat: Invalid qct format (611)
I/Adreno  (16170): GetNativeFormatFromQctPixelFormat: Invalid qct format (611)
I/Adreno  (16170): GetNativeFormatFromQctPixelFormat: Invalid qct format (611)
I/Adreno  (16170): GetNativeFormatFromQctPixelFormat: Invalid qct format (612)
I/Adreno  (16170): GetNativeFormatFromQctPixelFormat: Invalid qct format (612)
I/Adreno  (16170): GetNativeFormatFromQctPixelFormat: Invalid qct format (612)
I/Adreno  (16170): GetNativeFormatFromQctPixelFormat: Invalid qct format (612)_

**Comment by rbouqueau** [comment] 2015-11-13 12:40
Naive idea: FFmpeg has some support for PNG. So if we remove libpng and reset GPAC.cfg, we should fallback to FFmpeg PNG decoding. What does that give? (If it doesn't work please post your GPAC.cfg here)

**Comment by fcsteagu** [comment] 2015-11-13 12:55
it is not possible to root the phone that I'm using right now (yet) and I am not able to access the package folder of the application. Moreover, the APK is not generated with the debugging flag. Is there any way that I can remove the libpng and get the GPAC config file from there without having to root the phone?
Thank you

**Comment by nguyen-viet-thanh-trung** [comment] 2015-11-13 13:19
Hi,
You can get your GPAC.cfg by these commands: (suppose you use linux and you have adb tool)
adb backup  com.gpac.Osmo4
dd if=backup.ab bs=1 skip=24 | python -c "import zlib,sys;sys.stdout.write(zlib.decompress(sys.stdin.read()))" | tar -xvf -

Then you can copy GPAC.cfg to /sdcard/osmo and make some changes if you want, Osmo4 will use it as your config

**Comment by fcsteagu** [comment] 2015-11-13 14:53
Thank you!
ok I managed to get the config file. Now, in order to remove libpng is it enough to delete it from the _lib_ directory, as the application is already installed on the device?

**Comment by jeanlf** [comment] 2015-11-19 09:20
no you cannot remove libpng, it's statically linked in the binary
You have to:
- get last version (I just fixed FFMPEG PNG support in GPAC)
- edit/add in the config file:
`[Systems] 
codec_04_6D=FFMPEG decoder`

restart the player, with the config file still in /sdcard/osmo/ and let us know

**Comment by fcsteagu** [comment] 2015-11-19 15:54
thanks jeanlf, it works!

Could you please tell me what was the problem? I want to compile the code by myself and I would like to know what am I supposed to do in order to fix this issue.
Related to the config file, how is it possible to automatically add that line in _[Systems]_? Moreover, what _codec_04_6D_ means? 

Thanks again!

**Comment by jeanlf** [comment] 2015-11-19 16:32
we'll look at how to change that at run-time, although it would be better to understand what is wrong with libpng on this version...
codec_04_6D is some obscure naming of PNG in MPEG-4 systems (streamtype 4 is visual, ObectTypeIndication 0x6D is PNG)

**Comment by fcsteagu** [comment] 2015-11-19 22:22
Ah that was MPEG-4 Systems naming. Thanks for the clarification!
Related to the PNG issue, the player tries to decode the image by using __libpng__ and if it fails, it falls back to __ffmpeg__? I see there is also a module __img_in__ which also handles image decoding in my understanding. If this is the case, where is the priority of the libraries doing the same thing decided? E.g. 1.libpng, 2.ffmpeg, 3.img_in, 4.other_module, etc..
Thank you!

**Comment by fcsteagu** [comment] 2016-07-08 13:06
unfortunately I come back with the same problem.
On some Android versions (e.g. 5.1.1) I still have the same problem. I must manually add the line indicated by jeanlf in the config file.
The problem is the decoding of PNG iamges. It works if "codec_04_6D" is "FFMPEG Decoder" but by default the value of "codec_04_6D" is set to "GPAC Image Decoder". It seems that the library is not able to decode PNG images..

**Comment by fcsteagu** [comment] 2016-07-21 11:05
So, I come back with the same issue.
Is it possible for you to investigate the problem? Manually setting the parameter in the config file is not an option for us anymore..
Thanks!

**Comment by rbouqueau** [comment] 2016-07-21 11:10
Note: @rauf should add improvements on Android so that you can edit the config file from the Android app. That should ease the experiments :)

**Comment by fcsteagu** [comment] 2016-07-21 11:32
@rbouqueau thanks!
Would it be a solution to programatically choose the right library that is able to decode the images? Because we cannot ask people to change technical things while testing the application..

**Comment by rbouqueau** [comment] 2016-07-21 13:49
Could we have a summary on this bug? Is it on specific devices? Specific Android versions?

**Comment by fcsteagu** [comment] 2016-07-21 14:04
I only get it on Android 5 (the device is LG Flex 2).
On android 4 and 6 it works (Samsung Galaxy S3 and Nexus 5).
The easiest test is to open a PNG file. The result is a black screen...

If I put "codec_04_6D" is "FFMPEG Decoder" in the config file it works on Android 5 but not on the others.

**Comment by jeanlf** [comment] 2020-07-31 14:08
should be fixed in 1.0, reopen if needed

**Closed by jeanlf** 2020-07-31 14:08 UTC
Labels: android, player (mp4client/osmo)
