### ISSUE TITLE
Build from Source  - build_all.sh linux gives Scons/Python Errors

### ISSUE THREAD

**Issue by hickhub** [gpac/gpac#2468] opened 2023-05-14 22:46 UTC
Following the build from source instructions, on Ubuntu.
` ./configure --disable-X11` `results` in:

`! Unrecognized option disable-X11, ignoring !`

Same happens trying to pass any of the options shown in help configure.

Any dieas please?
Many thanks

**Comment by rbouqueau** [comment] 2023-05-15 01:07
Can you tell us more about what you are doing exactly? In particular how did you checkout the source code? Can you detail the instructions? Which Ubuntu and which shell do you use?

**Comment by hickhub** [comment] 2023-05-15 01:31
> Can you tell us more about what you are doing exactly? In particular how did you checkout the source code? Can you detail the instructions? Which Ubuntu and which shell do you use?

I followed the build guide for linux: 
```

1. https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux
2. https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-ull GPAC build (advanced users)
3. 
4. $ sudo apt-get install build-essential pkg-config g++ git scons cmake yasm
5. $ git clone https://github.com/gpac/gpac.git
6. 
7. <GPAC_ROOT_DIR>$ git clone https://github.com/gpac/gpac.git gpac_public
8. 
9. <GPAC_ROOT_DIR>$ git clone https://github.com/gpac/deps_unix
10. <GPAC_ROOT_DIR>$ cd deps_unix
11. <GPAC_ROOT_DIR>/deps_unix$ git submodule update --init --recursive --force --checkout
12. <GPAC_ROOT_DIR>/deps_unix$ ./build_all.sh linux
13. <GPAC_ROOT_DIR>/gpac_public$ ./configure
14. <GPAC_ROOT_DIR>/gpac_public$ emconfigure ./configure --prefix=/home/s/webassembly/gpac-wasm --enable-depth disable-wx disable-x11 extra-cflags=-O3 extra-cxxflags=-O3

```

Another problem I encountered was the ` ./build_all.sh linux` in line 12, was nor working until I ran 2to3 (Python 2 to Python 3) converter on the PlatinumSDK directory.  A Scons file has old style code, I think.  I thought I would make a different post about to let the GPAC people know.  Switching environments between Python2 and Python3 did no resolve the error.

Thank you!

I am running Ubuntu on Windows WSL.

**Comment by aureliendavid** [comment] 2023-05-15 10:41
Hi, 

> Another problem I encountered was the ` ./build_all.sh linux` in line 12, was nor working until I ran 2to3 (Python 2 to Python 3 converter) on the PlatinumSDK directory. A Scons file has old style code, I think. I thought I would make a different post about to let the GPAC people know. Switching environments between Python2 and Python3 did not resolve the error.

I'll look into updating the platinum build, thanks for reporting



> Following the build from source instructions, on Ubuntu. ` ./configure --disable-X11` `results` in:
> 
> `! Unrecognized option disable-X11, ignoring !`
> 

I think the option is `disable-x11` (lowercase x)


> Same happens trying to pass any of the options shown in help configure.

all of them? for example `--disable-remotery` gives an error/warning?

does it happen when running `./configure` directly or with `emconfigure`?

have you tried running `./configure --emscripten` instead of using `emconfigure`? it should set up things properly for wasm build

**Comment by aureliendavid** [comment] 2023-05-15 11:08
Note: if you are trying to do a wasm build, there is a [deps_wasm](https://github.com/gpac/deps_wasm) repo for gpac that might help

since the feature is still a bit experimental, there is not a build guide on the wiki for it yet (we'll write one soon)

in the meantime, you can see an example of how we do our wasm build in our buildbot logs: https://buildbot.gpac.io/#/builders/27/builds/96

**Comment by hickhub** [comment] 2023-05-15 11:36
> I think the option is `disable-x11` (lowercase x)
>
> > Same happens trying to pass any of the options shown in help configure.
> 
> all of them? for example `--disable-remotery` gives an error/warning?

I tried all kinds of options, they all give the same warning. 
 
> does it happen when running `./configure` directly or with `emconfigure`?
Directly running `./configure` gives the errors.  I tried with emconfigure and the result is the same.

> have you tried running `./configure --emscripten` instead of using `emconfigure`? it should set up things properly for wasm build

No, I have not tried that as I would have run emconfigure directly later in the process (presumably after `make install-lib`), and I want to be know exactly what is happening, whereas I think `./configure --emscripten` sets some options.

Thank you.

**Comment by hickhub** [comment] 2023-05-15 12:23
> it's very weird because if it says `! Unrecognized option` and not `Unknown feature` it means it didn't even recognize the `--disable-` part
> ...

Very helpful.  I will first try installing a fresh Fedora and try from there as it seems like some kind of shell issue, as you noted.   I was planning on trying a different linux, but asked the original question in case someone has already encountered the same issue.

Many thanks!

**Comment by rbouqueau** [comment] 2023-05-15 13:11
I am trying to install WSL on a computer to try to reproduce also.

**Comment by hickhub** [comment] 2023-05-20 19:29
Apologies for delay.

Tried on a different machince with WSL-2, ubuntu.  Following the build guide (as above), I get the Python issue, resolved by running 2to3 on PlatinumSDK directory files.  I get as fas as `<GPAC_ROOT_DIR>/deps_unix$ ./build_all.sh linux` which gives errors:

```
(base) s@DESKTOP-51EORGD:~/webassembly/gpac/deps_unix$ ./build_all.sh linux
scons: Reading SConscript files ...
KeyError: 'target':
  File "/home/s/webassembly/gpac/deps_unix/PlatinumSDK/Platinum/SConstruct", line 1:
    SConscript('Build/Boot.scons')
  File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 661:
    return method(*args, **kw)
  File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/python3/dist-packages/SCons/Script/SConscript.py", line 287:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/s/webassembly/gpac/deps_unix/PlatinumSDK/Platinum/Build/Boot.scons", line 50:
    if env['target'] == 'x86-microsoft-win32':
  File "/usr/lib/python3/dist-packages/SCons/Environment.py", line 405:
    return self._dict[key]
cp: cannot stat 'Build/Targets/x86-unknown-linux/Debug/*.a': No such file or directory
```

Many thanks!

**Comment by hickhub** [comment] 2023-05-20 20:00
Seems to be Python related to the build system.  I tried installing Conda to clean any Python environment issues, without difference.

Running 2to3 on the deps_unix directory gives errors:

```
RefactoringTool: Can't parse ./PlatinumSDK/Neptune/Extras/Scripts/CodeScanner.py: ParseError: bad input: type=22, value='=', context=('', (98, 67))
RefactoringTool: Can't parse ./gpac3/Neptune/Extras/Scripts/CodeScanner.py: ParseError: bad input: type=22, value='=', context=('', (98, 67))
```

**Comment by hickhub** [comment] 2023-05-20 20:28
Apologies for delay.

Tried a fresh WSL-2 Ubuntu build, all packages updates, Conda Python installed and updated. 
```

$ conda update python

$ sudo apt-get install build-essential pkg-config g++ git scons cmake yasm

$ git clone https://github.com/gpac/gpac.git

$ cd gpac

~/webassembly/gpac$ ./configure --prefix=/home/s/webassembly/gpac-wasm --enable-depth --disable-wx --disable-x11 --extra-cflags=-O3 --extra-cxxflags=-O3

~/webassembly/gpac$ ./configure --prefix=/home/s/webassembly/gpac-wasm --enable-depth --disable
-x11 --extra-cflags=-O3

~/webassembly/gpac$ sudo apt-get install zlib1g-dev libfreetype6-dev libjpeg62-dev libpng-dev libmad0-dev libfaad-dev libogg-dev libvorbis-dev libtheora-dev liba52-0.7.4-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavdevice-dev libxv-dev x11proto-video-dev libgl1-mesa-dev x11proto-gl-dev libxvidcore-dev libssl-dev libjack-dev libasound2-dev libpulse-dev libsdl2-dev dvb-apps mesa-utils

~/webassembly/gpac$ git clone https://github.com/gpac/gpac.git gpac_public

~/webassembly/gpac$ git clone https://github.com/gpac/deps_unix

~/webassembly/gpac$ cd deps_unix

~/webassembly/gpac/deps_unix$ git submodule update --init --recursive --force --checkout

~/webassembly/gpac/deps_unix$  ./build_all.sh linux
```

Gives:

```
scons: Reading SConscript files ...
  File "/home/s/webassembly/gpac/deps_unix/PlatinumSDK/Platinum/Build/Boot.scons", line 55

    print '********** Configuring Build Target =', env['target'], '/', build_config, '********'

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

cp: cannot stat 'Build/Targets/x86-unknown-linux/Debug/*.a': No such file or directory
checking for a BSD-compatible install... /usr/bin/install -c
```

**Comment by hickhub** [comment] 2023-05-20 20:55
Apologies for delay.   I tried on a fresh WSL-2 Ubuntu install.
```

$ conda update python

$ sudo apt-get install build-essential pkg-config g++ git scons cmake yasm

$ git clone https://github.com/gpac/gpac.git

$ cd gpac

~/webassembly/gpac$ ./configure --prefix=/home/s/webassembly/gpac-wasm --enable-depth --disable-wx --disable-x11 --extra-cflags=-O3 --extra-cxxflags=-O3

~/webassembly/gpac$ ./configure --prefix=/home/s/webassembly/gpac-wasm --enable-depth --disable
-x11 --extra-cflags=-O3

~/webassembly/gpac$ sudo apt-get install zlib1g-dev libfreetype6-dev libjpeg62-dev libpng-dev libmad0-dev libfaad-dev libogg-dev libvorbis-dev libtheora-dev liba52-0.7.4-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavdevice-dev libxv-dev x11proto-video-dev libgl1-mesa-dev x11proto-gl-dev libxvidcore-dev libssl-dev libjack-dev libasound2-dev libpulse-dev libsdl2-dev dvb-apps mesa-utils

~/webassembly/gpac$ git clone https://github.com/gpac/gpac.git gpac_public

~/webassembly/gpac$ git clone https://github.com/gpac/deps_unix

~/webassembly/gpac$ cd deps_unix

~/webassembly/gpac/deps_unix$ git submodule update --init --recursive --force --checkout

~/webassembly/gpac/deps_unix$  ./build_all.sh linux
```

Gives:
```

scons: Reading SConscript files ...
  File "/home/s/webassembly/gpac/deps_unix/PlatinumSDK/Platinum/Build/Boot.scons", line 55

    print '********** Configuring Build Target =', env['target'], '/', build_config, '********'

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

cp: cannot stat 'Build/Targets/x86-unknown-linux/Debug/*.a': No such file or directory
checking for a BSD-compatible install... /usr/bin/install -c
```

Many thanks!

**Comment by hickhub** [comment] 2023-05-21 03:46
> I use multiple wsl distros on different machines (and don't have this issue) so I'm pretty sure this isn't a wsl issue
> 
> The only issue I've had with wsl before are end-of-lines issues when you use the windows git command to clone a repo you then use in wsl (you can get shell scripts with CRLFs that won't run).

Did `./build_all.sh linux `work on WSL?

Many thanks

**Comment by hickhub** [comment] 2023-05-21 23:09
I might be jumping into the wrong rabbit hole but I got a little further by a quick and dirty Python2 to Python3 refactoring of the deps_unix directory with a BASH script (attached) before running  ` ./build_all.sh linux ` which gives errors:

```scons: Reading SConscript files ...
KeyError: 'target':
  File "/home/s/webassembly/gpac/deps_unix/PlatinumSDK/Platinum/SConstruct", line 1:
    SConscript('Build/Boot.scons')
```
Is SConscript a command?  I cannot find any files called SConscript in the repo.

Many thanks

[3.sh.txt](https://github.com/gpac/gpac/files/11525741/3.sh.txt)

**Comment by aureliendavid** [comment] 2023-05-22 06:27
Hi, 

My advice would be to simply ignore this dependency as it is an optional one and it's probable you don't need it. 

I'm working on updating the dependency to a newer version that builds better on newer systems, I'll report on my progress.

In the meantime I have pushed a patch in deps_unix to skip it (if you explicitly need it I can probably send you binaries versions to try)


Please report if your original configure issue is ok otherwise, thanks.

**Comment by hickhub** [comment] 2023-05-22 08:02
> Hi,
> 
> My advice would be to simply ignore this dependency as it is an optional one and it's probable you don't need it.
> 
> I'm working on updating the dependency to a newer version that builds better on newer systems, I'll report on my progress.
> 
> In the meantime I have pushed a patch in deps_unix to skip it (if you explicitly need it I can probably send you binaries versions to try)
> 
> Please report if your original configure issue is ok otherwise, thanks.

Most helpful.

Thank you very much.

**Comment by aureliendavid** [comment] 2023-05-22 14:08
in fact support for Platinum has been deprecated in gpac so the dependency is really not needed

so I'm not going to bother updating to a newer version for now, I'll do it if we try to port the old platinum module to the new filter arch at some point 

I assume your original shell issue with configure options has been resolved so I'm closing the issue, feel free to reopen if needed

thanks

**Closed by aureliendavid** 2023-05-22 14:08 UTC
