### ISSUE TITLE
can gpac transcode one rtmp input to several streams with different resolution and output them with one ll-hls? 

### ISSUE THREAD

**Issue by GlassyYang** [gpac/gpac#2129] opened 2022-02-28 17:19 UTC
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [X] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I use `gpac` reading `RTMP` input and serve them with ll-hls, the command is like:
```
gpac -i 'rtmp://:1935/live/abc:gpac:rtmp_listen=1' reframer:rt=on -o http://127.0.0.1:8080/ll-hls/live.m3u8:gpac:segdur=4:cdur=1:profile=live:dmode=dynamic:hmode=push:llhls=sf
``` 
Now I want to add some arguments which can transcode rtmp to different resolution streams and use ll-hls provide these streams so web player can choose one of them by estimated bandwidth, which is so called adaptive stream media. I have read documents and found nothing. I want to know whether `gpac` support this operation and how to change above command. 
Thank you.

**Comment by jeanlf** [comment] 2022-03-07 09:49
You will need to setup encoders in your chain. Using GPAC 2.0, this transcodes video but not audio:

```
gpac -i URL  reframer:rt=on @ c=avc:b=1m @1 c=avc:b=500k @ @1 @@1#audio -o dash/live.m3u8:segdur=2 -graph

```

See [this howto](https://github.com/gpac/gpac/wiki/dash_low_latency#dash-low-latency-live-encoding) - I'll add a howto on generic dash transcoding without low latency.

**Comment by GlassyYang** [comment] 2022-03-11 09:40
I tried this command with `gpac` version `2.1-DEV-rev28-gea1eca00f-master`, which is built from newest source on branch `master`  and it wasn't working. The only thing I did was adding a rtmp source:
```shell
gpac -i 'rtmp://:1935/live/abc:gpac:rtmp_listen=1' reframer:rt=on @ c=avc:b=1m @1 c=avc:b=500k @ @1 @@1#audio -o dash/live.m3u8:segdur=2 -graph
```
the error was:
```shell
[DASHDmx] Error - cannot initialize DASH Client for dash/live.m3u8: Requested URL is not valid or cannot be found
Failed to connect filter dasher PID manifest_m3u8 to filter dashin: Requested URL is not valid or cannot be found
```
I also tried example command on [HowTO](https://github.com/gpac/gpac/wiki/dash_low_latency#dash-low-latency-live-encoding) with a small modify which just changed source and target addr like this:
```shell
gpac -i 'rtmp://:1935/live/abc:gpac:rtmp_listen=1' ... -o http://127.0.0.1:8080/live.mpd...
```
all other parts of command is the same except listed above.
there also were other problems:
```
[rtmp] Unexpected stream test, expecting abc
[rtmp] Unexpected stream test, expecting abc
No filter chain found for PID audio1 in filter ffdmx to any loaded filters - NOT CONNECTED
No filter chain found for PID video1 in filter ffdmx to any loaded filters - NOT CONNECTED
Unknown argument "--profile" set but not used by any filter - no matching argument found
Argument "--segdur" was set but not used by any filter
Argument "--cdur" was set but not used by any filter
Argument "--asto" was set but not used by any filter
Filters not connected:
ffsws (osize=1280x720:SID=1) (idx=2)
ffenc (c=avc:fintra=1:FID=EV1:b=1m) (idx=3)
ffsws (osize=854x480:SID=1) (idx=4)
ffenc (c=avc:fintra=1:FID=EV2:b=500k) (idx=5)
ffenc (ffc=aac:SID=1:FID=EA:b=128k) (idx=6)
httpout (dst=http://127.0.0.1:8080/live.mpd:gpac:SID=EV1,EV2,EA) (idx=7)
```
I also tried to build gpac from source on tag `v2.0.0` it didn't work on all above commands.

**Comment by jeanlf** [comment] 2022-03-11 16:46
I just tested both ways:

Source as server:

```
gpac -i src.mp4 -o rtmp://127.0.0.1:8888/live:gpac:ffmt=flv:rtmp_listen=1
gpac -i 'rtmp://127.0.0.1:8888/live' reframer:rt=on @ c=avc:b=1m @1 c=avc:b=200k @ @1 @@1#audio -o dash/live.m3u8:segdur=2 -graph
```

or Dasher as server:

```
gpac -i 'rtmp://127.0.0.1:8888/live:gpac:rtmp_listen=1' reframer:rt=on @ c=avc:b=1m @1 c=avc:b=200k @ @1 @@1#audio -o dash/live.m3u8:segdur=2 -graph
gpac -i src.mp4 -o rtmp://127.0.0.1:8888/live:gpac:ffmt=flv
```

Both are working ok (tested on OSX).
Isn't the problem coming from the source RTMP feed ? Can you play (`gpac -play URL`) or inspect (`gpac -info URL`, `gpac -info URL --deep`) it ?

**Comment by GlassyYang** [comment] 2022-03-14 02:34
I use `gpac` generating rtmp stream and use `gpac` play it, everything is normal. when I test the given two command, the same error was happened:
```
[DASHDmx] Error - cannot initialize DASH Client for dash/live.m3u8: Requested URL is not valid or cannot be found
Failed to connect filter dasher PID manifest_m3u8 to filter dashin: Requested URL is not valid or cannot be found
Blacklisting dashin as output from dasher and retrying connections
No filter chain found for PID manifest_m3u8 in filter dasher to any loaded filters - NOT CONNECTED

Filters connected:
ffdmx (src=rtmp://127.0.0.1:8888/live/test) (idx=1)
-(PID video1)\
-(PID audio1)-> reframer (rt=on) (idx=2)
--(PID video1) osvcdec (dyn_idx=6)
---(PID video1) ffenc "ffenc:libx264" (c=avc:b=1m) (idx=3)
----(PID video1) rfnalu (dyn_idx=8)
-----(PID video1) dasher (dyn_idx=7)
------(PID manifest_m3u8) fout (dst=dash/live.m3u8:segdur=2) (idx=5)
---(PID video1) ffenc "ffenc:libx264" (c=avc:b=200k) (idx=4)
----(PID video1) rfnalu (dyn_idx=9)
-----(PID video1) dasher (dyn_idx=7)
--(PID audio1) dasher (dyn_idx=7)
```
the command `gpac -info rtmp://127.0.0.1:8888/live/test` generate next output:
```
PID 1 video timescale 1000 1920x1080 fps 25 SAR 1/1 2470 kbps codec AVC|H264 PL High@5 YUV 4:2:0 8 bpp
PID 2 audio timescale 1000 48000 Hz 2 channels 129 kbps codec AAC LC (aot=2 implicit)
```
BY the way, I use linux x64, the `uname -a` output is:
```
Linux glassyyang 5.10.102-1-MANJARO #1 SMP PREEMPT Wed Feb 23 14:44:40 UTC 2022 x86_64 GNU/Linux
```
the gcc version is: `11.2.0`, gpac version is: `2.1-DEV-rev42-g9f61a4cfc-master`. I also try the command with `root`, and I'm sure that My computer has enough memory and disk space.

**Comment by GlassyYang** [comment] 2022-03-14 02:52
If I do not use multi streams, it can play normally:
```
gpac -i rtmp://127.0.0.1:1935/test:gpac:rtmp_listen=1 -o http://127.0.0.1:8080/ll-hls/playlist.m3u8:gpac:segdur=4:cdur=1:profile=live:dmode=dynamic:llhls=sf
```

**Comment by GlassyYang** [comment] 2022-03-14 12:48
These commands are useful. 
When I use `gpac` push `ll-hls` file into my HTTP server, streams can be played. When I use `gpac` as HTTP server, something just wrong and output following error:
```
[1]    131516 floating point exception (core dumped)  gpac -i 'rtmp://127.0.0.1:1935/live:gpac:rtmp_listen=1' @ c=avc:b=1m @1  @ @1
```
when I use `gpac` on all above commands, `gpac` generate two kinds of warning:
```
[libx264] non-strictly-monotonic PTS
[MP4Mux] PID video1 ID 1 Sample 1015 with DTS 33733 less than previous sample DTS 33733, adjusting prev sample duration
```
It's seems like bugs. I also don't see these outputs When I transform RTMP to single ll-hls stream.
By the way, I use OBS generating RTMP stream.

**Comment by jeanlf** [comment] 2022-03-14 13:47
Could you grab the source to gsf and upload it ?

```
gpac -i rtmp://127.0.0.1:1935/live -o dump.gsf
```

(press ctr+c to stop recording if live source)

**Comment by jeanlf** [comment] 2022-03-14 16:13
yes perfect. There was a bug in ffenc timescale setup resulting in these warnings, now fixed. 

Could you provide the complete command line for the observed crash ?

**Comment by GlassyYang** [comment] 2022-03-15 01:50
```
gpac -i 'rtmp://127.0.0.1:1935/live:gpac:rtmp_listen=1' @ c=avc:b=1m @1 c=avc:b=200k @ @1 @@#audio reframer:rt=on @ -o http://127.0.0.1:8080/ll-hls/playlist.m3u8:gpac:segdur=4:cdur=1:profile=live:dmode=dynamic:llhls=sf:rdirs=/tmp/gpac -graph
```
The error message is:
```
[1]    148447 floating point exception (core dumped)  gpac -i 'rtmp://127.0.0.1:1935/live:gpac:rtmp_listen=1' @ c=avc:b=1m @1  @ @1
```
When I use `gpac` play `ll-hls` stream video playback is not very smooth, there will be stuttering.

**Comment by jeanlf** [comment] 2022-03-15 08:38
I tried using your captured GSF as source and the provided command line, I cannot reproduce the crash (tested on osx and ubuntu 20.04), playback works fine with safari and gpac.

Can you try to do a capture that reproduces your crash ?

**Comment by GlassyYang** [comment] 2022-03-15 14:13
It's seems like the same bug lead to two actions: crash and warning generate. After I upgrade my `gpac` to newest version, The crash just disappear even if the same GSF file was used. I think the crash was fixed.

**Comment by jeanlf** [comment] 2022-03-21 13:51
Try setting `cmaf=cmfc` option on output, some implementations don't deal properly with fragments not having a tfdt.

**Closed by jeanlf** 2022-03-21 13:51 UTC
